-- S288 (SkyZ) checkpoint write, 2026-09-25. Rule 9 step 10 (Rule 8 ingest). Three rows, their log and the verify as
-- THREE statements in ONE execute_sql call (Sam's SQL budget ruling, 2026-09-24). INSERT-only, idempotent on slug.
-- Row 1 is Sam's own words, so it is verified with him named in verified_by; it refines cip-load-do-not-gate (a
-- human-sourced row) rather than superseding it (Rule 8). Rows 2 and 3 are this session's findings, proposed.
-- Rollback: delete from cpl_memory_log where actor = 'SkyZ-s288' and action = 'create';
--           delete from cpl_memory where author = 'SkyZ-s288';
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, verified_at, event_date, author)
values
 ('top-is-unchecked-program-cip-is-reliable-sam-2026-09-25', 'decision', 'Sam: TOP is unchecked; program CIPs are almost fully reliable', 'Sam, 2026-09-25: TOP codes are unreliable because colleges enter them with no effective checks, the new CIP system will be better, course CIPs are only partially set, and program CIPs are almost 100% reliable.', 'Verbatim, unprompted, after #1692 corrected TOP_Code_Lookup.xlsx column D: ''TOP is not reliable since it is entered by the colleges with no effective checks. The new CIP system will be better. The course CIPs are only partially set now the the program CIPs are almost 100% reliable''. It refines cip-load-do-not-gate (2026-09-17), which measured CIP coverage (blank on 29.1% of programs and 14.1% of active ones) rather than the reliability of the values that are set; both stand. Applied the same day: Rule 7''s CIP line and methodology-top-is-a-last-in-line-signal carry it, and the session withdrew its ask for MAP''s TOP table. Its limit, measured the same day: a program CIP labels the program, not the courses it lists (row a-program-cip-labels-the-program-not-its-courses). Vault capture: 03-professional/braindumps/braindump-2026-09-25-1315-program-cip-is-the-reliable-anchor.md.', 'Sam says the older TOP program codes cannot be trusted, because colleges enter them without real checks. The newer CIP codes are better: the ones on programs are almost always right, while the ones on individual courses are only partly filled in so far.', array['cip','top-code','data-quality','doctrine','eacr']::text[], 'Sam, 2026-09-25 (S288 SkyZ session)', array['cip-load-do-not-gate','observed-cip-beats-the-published-crosswalk-3x-2026-09-21','a-program-cip-labels-the-program-not-its-courses']::text[], 'verified', 'general', 'Sam Lee (2026-09-25), recorded by SkyZ S288', now(), '2026-09-25'::date, 'SkyZ-s288'),
 ('top-code-lookup-column-d-disagreed-with-its-titles-on-81-rows', 'fact', 'TOP_Code_Lookup.xlsx column D was wrong on 81 of 198 rows', 'Measured 2026-09-25: TOP_Code_Lookup.xlsx column D, the CCC 4-digit TOP that routes MAP''s TOP id to a CIP family, disagreed with its own program title on 81 of 198 rows until #1692 set it from the TOP manual, which cut the EACR''s unsectored matrix rows from 890 to 379.', 'Nothing read column D before #1681 (2026-09-24), which measured that 163 of 198 ids resolved and shipped; 46 of those 163 resolved to the wrong program, so a join rate is not a correctness rate. The 81: 35 codes that are no TOP code (Fire Technology 2130, Drafting 0909, Welding 0941) and 46 real codes naming another program (History 2203, which is Ethnic Studies; Political Science 2205, History; Nursing (RN) 1211, Polysomnography; Construction Crafts 0946, HVAC). kb/_correct_top_lookup_code4.py sets column D to the category of the TOP title column E names (kb/reference/top_categories.json, then the published crosswalk), settles 15 non-exact titles by hand and keeps row 144; receipt kb/receipts/top_code_lookup_code4_2026-09-25_s288.json; guard tests/top_code_lookup_code4_test.py (13 checks, in js-tests.yml beside tests/eacr_matrix_payload_test.py). Live since the 2026-09-25 13:16 UTC build, confirmed in Chromium: 890 to 379 unsectored rows (dropdown 449 cards), 328 cards re-sectored. 37 MAP TOP ids still have no row (100 cards) and stay that way while the course CIP route is pursued.', 'A lookup table that turns MAP''s program codes into career sectors had wrong codes on 81 of its 198 rows, because nobody had used that column before. Fixing it from the official code manual put 328 credentials in the right sector and cut the unsorted rows from 890 to 379.', array['eacr','cip','top-code','data-quality','lookup']::text[], 'CPL-Initiative/cpl-project-tracker#1692', array['top-is-unchecked-program-cip-is-reliable-sam-2026-09-25','eacr-ten-tweaks-sam-2026-09-24']::text[], 'proposed', 'workstream-specific', 'SkyZ S288', null, '2026-09-25'::date, 'SkyZ-s288'),
 ('a-program-cip-labels-the-program-not-its-courses', 'pitfall', 'A program CIP labels the program, not its courses', 'Measured 2026-09-25: voting a course''s CIP family from the COCI programs that list it misfiles service courses, because a course takes the field of every program that requires it; on a random 30 of the 682 EACR rows it would have moved, 8 read better, 15 worse and 7 the same, so it was not shipped.', 'Built on kb/program_course_graph.json (colleges joined on the MIS code through kb/college_identity/<date>/crosswalk.json, course numbers compared without leading zeros, umbrella families 24 and 30 voting only when alone). It sectored 2,244 of 3,000 matrix rows against 2,621 for the TOP route, and its largest disagreement groups favored it (culinary 19 to 12, FAA pilot 47 to 49, water treatment 03 to 15, welding and ironworkers 15 to 48): those groups are career-technical, whose courses live in their own programs. The random sample told the other half: Elementary Italian to 12 Culinary, Beginning Chinese and AP Japanese to 05 Area Studies, Calculus 1 to 40 Physical Sciences, AP US Government to 22 Legal, Microsoft Word Expert to 51 Health. Read the course''s own CIP (no file or table we hold carries it; Supabase has CIP only on coci_college_programs; open-asks card 15 asks Sam for a source), and use program membership to corroborate. Note: docs/kb-notes/methodology-a-program-cip-labels-the-program-not-its-courses.md.', 'It seemed natural to guess a course''s career field from the programs that include it. That goes wrong for courses many programs borrow: a language course inside a cooking program would be filed as cooking. So the field has to come from the course''s own code, and the programs only help confirm it.', array['cip','program-course-graph','methodology','eacr','data-quality']::text[], 'docs/kb-notes/methodology-a-program-cip-labels-the-program-not-its-courses.md', array['top-is-unchecked-program-cip-is-reliable-sam-2026-09-25','observed-cip-beats-the-published-crosswalk-3x-2026-09-21']::text[], 'proposed', 'general', 'SkyZ S288', null, '2026-09-25'::date, 'SkyZ-s288')
on conflict (slug) do nothing;
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyZ-s288', 'create', 'S288 SkyZ checkpoint auto-write (Rule 9 step 10); rows, log and verify in one call (kb/receipts/cpl_memory_2026-09-25_s288.sql)', to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyZ-s288'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
select m.slug, m.status, count(l.id) filter (where l.action = 'create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyZ-s288'
group by m.slug, m.status order by m.slug;
