-- S338 SkyLantern, 2026-10-06: the Noncredit Summit deck's draft 2 and the Library filer's first sign-in.
-- Sam's rulings are verified (verified_by Sam); session findings are proposed. INSERT-only;
-- rollback: supersede each row by slug.
insert into public.cpl_memory (slug, title, kind, summary, detail, plain, tags, affects, source, author, event_date, status, verified_by, verified_at)
values
('sam-summit-mtsac-plans-to-2026-10-06',
 'Sam: the Summit deck says Mt. San Antonio College plans to document its health ladder in MAP',
 'decision',
 'Sam, 2026-10-06, on slide 2''s dashed Mt. SAC step (MAP showed no LVN, CNA, medical assistant or surgical tech exhibit there): "Soften to ''plans to''". Slides 2, 4 and 5 and their notes say Mt. SAC plans to document its ladder; Carla''s CPL step keeps its dashed outline.',
 'Deck draft 2, CPLBrain 04-projects/cpl-initiative/20261005_Noncredit_Summit_CPL_Slides_2.md (samueltlee/CPLBrain#247). The film still says "documenting now" until it is re-cut.',
 'The Summit slides now say Mt. San Antonio College plans to put its health ladder in MAP.',
 array['noncredit','summit','deck','mt-sac'], array['CPLBrain/04-projects/cpl-initiative/20261005_Noncredit_Summit_CPL_Slides_2_build.py'],
 'Sam, in session (AskUserQuestion), 2026-10-06', 's338-2026-10-06', '2026-10-06', 'verified', 'Sam', now()),
('sam-summit-drop-noce-claim-2026-10-06',
 'Sam: drop the NOCE claim from the Summit deck',
 'decision',
 'Sam, 2026-10-06: "Drop the NOCE claim." NOCE''s MAP exhibits are QuickBooks, the 22-unit LVN license and the police academy, with no CompTIA or IT exhibit. Nadia''s path no longer says North Orange is building it, and slide 5 names only San Diego College of Continuing Education among those who have begun posting certificates.',
 'Nadia''s CPL step became CompTIA A+, Network+ and Security+, 9 units as at Saddleback College (Sam''s follow-up ask the same hour: "If there are any other potential CompTia options to bundle in for Nadia, check that").',
 'The Summit slides no longer say North Orange Continuing Education is building Nadia''s path.',
 array['noncredit','summit','deck','noce'], array['CPLBrain/04-projects/cpl-initiative/20261005_Noncredit_Summit_CPL_Slides_2_build.py'],
 'Sam, in session (AskUserQuestion), 2026-10-06', 's338-2026-10-06', '2026-10-06', 'verified', 'Sam', now()),
('sam-calbright-one-of-116-2026-10-06',
 'Sam: Calbright counts among the 116; the $50,000 grants card keeps its three noncredit programs',
 'decision',
 'Sam, 2026-10-06, asked whether slide 4''s last-year card should add Calbright (the funding tab''s grant list names it as a fourth noncredit recipient beside NOCE, SDCCE and Mt. SAC Noncredit): "I included Calbright as 1 of the 116 so we can leave it as is."',
 null,
 'Sam counts Calbright among the 116 colleges, so the grant card names only the three noncredit programs.',
 array['noncredit','summit','calbright','funding'], array[]::text[],
 'Sam, in session (AskUserQuestion), 2026-10-06', 's338-2026-10-06', '2026-10-06', 'verified', 'Sam', now()),
('sam-summit-film-new-voice-2026-10-06',
 'Sam: change the Noncredit Summit film''s narrator voice and make a small edit, in a new session',
 'decision',
 'Sam, 2026-10-06: "I want to change the narrator voice and make a small edit to the video explainer. Should that be in next session?" Agreed: a new session, which also applies the deck''s draft 2 changes and files both cuts with the Library filer.',
 'This revisits sam-ladypatty1-narrates-noncredit-film-2026-10-05 (left verified, not superseded: the new voice is not named yet). The film handoff lists the draft 2 changes: CPLBrain 04-projects/cpl-initiative/20261005_Noncredit_Summit_Video_handoff.md.',
 'Sam wants a different narrator voice for the Summit film, done in the next session.',
 array['noncredit','summit','film','narration'], array['prototype/noncredit_video/'],
 'Sam, in session, 2026-10-06', 's338-2026-10-06', '2026-10-06', 'verified', 'Sam', now()),
('funding-noncredit-total-1812403-2026-10-06',
 'The published allocation''s noncredit total is $1,812,403; $1,783,399 is a stale Scenario 3 sheet figure',
 'fact',
 'cpl_funding.js over the live configuration (md5 764fd264, rebuilt from the e21658f9 fixture plus the two 2026-10-02 plans), Scenario 2: $1,812,403 noncredit = $1,326,601 in college awards'' noncredit subtotals + $485,802 to the three noncredit-only institutions; $25,240,308 to 118 institutions; 85,444 noncredit FTES on the Statewide row.',
 '$1,783,399 came from kb/_build_funding_scenario3_decision_sheet.py and reached the Summit deck''s draft 1 notes and prototype/noncredit_video/build.py''s comment. _effective().pool and _csv() answer it.',
 'Noncredit funding totals about $1.81 million under the published scenario.',
 array['implementation-funding','noncredit','summit'], array['cpl_funding.js','prototype/noncredit_video/build.py'],
 'model run, S338, 2026-10-06', 's338-2026-10-06', '2026-10-06', 'proposed', null, null),
('potential-colleges-are-non-adopters-2026-10-06',
 'credential_reference_data.js potential_colleges lists colleges that have NOT adopted a credential',
 'pitfall',
 'Adopters live in articulations[].local[].colleges (kb/_sync_credential_catalog.adopters_of). Read as adopters, CompTIA A+ showed 24 colleges and none of the deck''s 21.',
 'Measured 2026-10-06 (credential reference generated 16:09Z): CompTIA A+ 21 adopters, Network+ 21, Security+ 17, all three at 12 (Chaffey, Clovis, College of the Desert, Copper Mountain, Lake Tahoe, Las Positas, LA Mission, Modesto, Reedley, Saddleback, San Diego City, Santa Ana); none in the North Orange district. Saddleback 9 units, Santa Ana 12.',
 'The list called potential colleges is the colleges that have not yet adopted the credential.',
 array['credential-reference','comptia','pitfall'], array['credential_reference_data.js','kb/_sync_credential_catalog.py'],
 'S338 measurement, 2026-10-06', 's338-2026-10-06', '2026-10-06', 'proposed', null, null),
('library-filer-signin-set-2026-10-06',
 'The Library filer''s Google sign-in is set; publishing needed a privacy page; check a secret''s shape, never its value',
 'milestone',
 'Sam, 2026-10-06: OAuth app CPL Library filer In production (Branding needed the home page, privacy.html (#1887) and the authorized domain cpl-initiative.github.io before Publish lit), three environment variables saved. The first save held the template placeholders (invalid_client; lengths 11/15/15). The first --check runs in a session started after ~18:45Z.',
 'The guide carries every snag: docs/reference/library_filer.md (#1888). A session checks the values'' shape (length, .apps.googleusercontent.com, GOCSPX-, 1//) without printing them.',
 'The filer can now sign in to Google Drive; a new session runs its first check.',
 array['library','filer','drive','oauth'], array['scripts/library_file.py','docs/reference/library_filer.md','privacy.html'],
 'PRs #1887, #1888', 's338-2026-10-06', '2026-10-06', 'proposed', null, null),
('apply-migration-stall-sql-editor-fallback-2026-10-06',
 'When apply_migration stalls, Sam runs the receipt in the Supabase SQL editor; the execute_sql guard refuses row changes by design',
 'pitfall',
 'S338, 2026-10-06: four apply_migration calls for the Summit deck''s Library receipt timed out at 60 s with no row changed and no migration recorded (pg_stat_activity idle; no approval prompt reached Sam). execute_sql was blocked by the repo''s Supabase guard. Sam ran the receipt in the SQL editor ("Success. No rows returned" is normal for a row change); the read-back confirmed it.',
 'Keep an unapplied receipt out of the repo, so a committed receipt always means a write that happened. Receipt: kb/receipts/library_filed/2026-10-06_noncredit-summit-cpl-slides__20261005_Noncredit_Summit_CPL_Slides_2.sql (#1889).',
 'If the database tool stalls, Sam can paste the prepared change into Supabase himself.',
 array['supabase','receipts','library'], array['kb/receipts/library_filed/'],
 'S338, 2026-10-06', 's338-2026-10-06', '2026-10-06', 'proposed', null, null)
on conflict (slug) do nothing;

insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 's338-2026-10-06', 'create', 'S338 checkpoint, 2026-10-06', to_jsonb(m)
from public.cpl_memory m where m.author = 's338-2026-10-06'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
