-- S335 (SkyKeel), checkpoint 2026-10-05: Miramar's AUTO 156G traced, drafts for the college, Sierra's gap labels.
-- Rollback: supersede each row by slug under actor 'SkyKeel-s335-rollback'.
insert into public.cpl_memory (slug, title, kind, summary, detail, plain, tags, affects, source, author, event_date, status)
values
('miramar-auto-156g-is-mapview-not-student-credit-2026-10-05', 'Miramar''s AUTO 156G link is in MAP''s articulated-exhibit view only; students received the credit on EMGM 106 and FIPT 321P', 'fact', 'MAP''s 0.3-hour EMT Certification and Driver Operator 1B rows at Miramar list AUTO 156G Engine and Related Systems beside EMGM 106 and FIPT 321P. map_college_cr_unit shows both credits awarded at 0.25 hours on EMGM-106 and FIPT-321P only. The college-facing draft says exactly that.', 'Eight handoffs (S327-S334) carried ''raise Miramar''s AUTO 156G articulations''. kb/_seed_coci_articulations.py reads one course per MAP view row, so the link is MAP''s. Build 1cb75672ba6c adds the two drafts on Miramar Entrepreneurship 35030 (sheet 42 card 2). KB note methodology-trace-a-finding-to-what-students-received.', 'Miramar''s records list an auto engine course beside the right fire and EMS courses on two recommendations, but every student who got that credit got it on the right course. We tell the college to tidy the record; there were no wrong awards.', array['program-requirements-harvest', 'cleanup', 'map-data', 'miramar']::text[], array['kb/_build_roep_display.py', 'program_requirements.js']::text[], 'docs/kb-notes/methodology-trace-a-finding-to-what-students-received.md', 'SkyKeel-s335', '2026-10-05', 'proposed'),
('harvest-tab-drafts-for-the-college-2026-10-05', 'Drafts for the college on the Program Requirements tab: sheet 32 card 2''s harvest-tab half is built', 'milestone', 'Program records gathers each college''s college-owned gaps under its heading as Drafts for the college, with a draft to copy; Catalogs counts and filters them; record notes list only what the procedure owns. 26 live at five colleges, 28 after sheet 42 card 2. The My College half waits on sheet 42 card 3.', 'program_requirements.js collegeDrafts/draftText; tests/program_requirements.test.js block 6c; PR #1874. My College is the college''s own page, so a draft there would reach the college before the MAP team sends; proposed: list an item once sent.', 'The tab now collects, per college, the places where its catalog, the state''s course file or MAP disagree, as a ready-to-edit note the MAP team sends when it chooses.', array['program-requirements-harvest', 'decision-sheet', 'college-facing']::text[], array['program_requirements.js']::text[], 'docs/program_requirements_harvest_lessons.md', 'SkyKeel-s335', '2026-10-05', 'proposed'),
('sierra-labeled-every-college-gap-a-catalog-difference-2026-10-05', 'Sierra labeled every college-owned display gap ''Catalog and state file differ''; a new gap kind needs her deploy first', 'pitfall', 'cpl-chat displayLines wrote every gap with owner college as a catalog-and-state-file difference. S335 labels each by its kind (in the repo, tests/sierra_program_courses.test.js). Deploy cpl-chat before writing a display build that adds a new college-owned kind.', 'display.gaps has three readers: the harvest tab, CPL Pathways and Sierra. grep the field across *.js and *.ts before adding a kind. Sheet 42 card 2 orders the deploy before the 1cb75672ba6c write.', 'Our chat assistant would have described a mismatched MAP record as a catalog difference. The fix names each problem by its own kind, and it goes live before the new data does.', array['sierra', 'program-requirements-harvest', 'deploy-order']::text[], array['chatbox/supabase/functions/cpl-chat/index.ts']::text[], 'docs/program_requirements_harvest_lessons.md', 'SkyKeel-s335', '2026-10-05', 'proposed')
on conflict (slug) do nothing;

insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyKeel-s335', 'create', 'checkpoint auto-write (S335)', to_jsonb(m)
from public.cpl_memory m where m.author = 'SkyKeel-s335'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');

select m.slug, m.status, count(l.id) filter (where l.action='create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyKeel-s335' group by m.slug, m.status order by m.slug;
