-- WRITTEN 2026-09-24 00:3x UTC by S285 (SkyGrant) through kb/receipts/cpl_memory_2026-09-24_s285.sql, which
-- re-read every row against the state that day and restructured each into a one-sentence summary plus detail
-- (the table holds summary to 400 characters). This file stays as staged; the changes are listed in that receipt.
-- S283 (SkyFund) checkpoint memory rows. Rule 8 ingest; status='proposed' (own writes are not
-- self-verified). INSERT-only, idempotent on slug: rerunning writes nothing.
-- STAGED, NOT WRITTEN: the repo's execute_sql guard refuses session writes (same as S281's file).
-- Rollback: delete from cpl_memory where verified_by like '%SkyFund S283%';
insert into cpl_memory (slug, kind, title, summary, tags, status, source, verified_by, event_date)
values
 ('baseline-counts-run-over-116-colleges-including-calbright', 'decision', 'The funding baseline counts run over 116 colleges, Calbright included', 'Sam, 2026-09-22, on the Implementation Funding baseline block that read ''48 of 115'': ''should be 116 college, including Calbright''. The credit colleges (base().colleges, 115) plus Calbright are the colleges; NOCE and SD Cont. Ed are institutions in the 118-row roster but not colleges, so they stay out of this count. cpl_funding.js eligColleges() is the one list. MAP spells Calbright ''Calbright College Credit'' and ''Calbright College Non-Credit''; both now match the Calbright row in the coordinator join. Live 2026-09-22: 48 colleges have a coordinator on file (map_coordinator_summary, 123 rows).', array['implementation-funding','college-identity','calbright','baseline'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1660', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date),
 ('career-attainment-measured-by-the-co-from-edd-wage-data', 'decision', 'Goal (C) career attainment is measurable: the CO measures it from EDD wage data', 'Sam, 2026-09-22: ''On Career Attainment, I had been thinking we wouldn''t be able to measure it, but after speaking with CO research team, we can use EDD wage data to measure this... This would not be reported by the colleges but instead measured by the CO and reflected on our funding model with periodic updates (imports) of the data. The Opportunities section would stay as is.'' Retires the ''funded with no campus measure'' posture for (C) once the first import lands. How it enters the model is on the funding review sheet (https://claude.ai/artifact/9MfbN6jqio8as9mY4LwPB2): proposed show-first-fund-after-an-import, because srcDelivered() reads an undelivered measure as $0 and would strand a pinned share.', array['implementation-funding','career-attainment','edd','co-research','goal-c'], 'proposed', 'CPLBrain/03-professional/braindumps/braindump-2026-09-22-2030-career-attainment-measured-by-edd-wage-data.md', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date),
 ('funding-prose-leads-positive-with-no-restatement', 'decision', 'Funding prose leads with the positive and never restates itself', 'Sam, 2026-09-22, opening the leadership-review edits: ''start with positive and avoid statements like this, not that or follow on restatements in other words'', and on the allocation explainer: ''avoiding mannerly language, using active voice where possible, avoiding adjectives in preference for action verbs... Try and simplify and use academic rather than commercial language throughout.'' Extends the 2026-09-16 no-this-not-that ruling with a second ban: a follow-on sentence that says the same thing in other words. Applied across the Summary, the Baseline block, the Funding Breakdown and How an allocation is computed in #1660.', array['implementation-funding','house-voice','writing'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1660', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date),
 ('funding-statewide-lines-and-project-partners', 'decision', 'Statewide ledger lines read in black; many CPL projects are carried out with college partners', 'Sam, 2026-09-22, on the Funding Breakdown: ''change red font to black and revise deducted to something positive. Many of the projects involve college partners (e.g., Twentynine Palm and Copper Mt. Demo Project and AI Apprenticeship Tools with SCC and American River College (was Norco College, but changed)''. Red stays for a state the reader must act on. FACT for the register: project 1.1.2 AI Apprenticeship CPL Tools partners are Santiago Canyon College and American River College; the projects table team field still read ''Santiago Canyon College, Norco College, Trade Partners'' on 2026-09-22 and awaits Sam''s edit in Activities.', array['implementation-funding','budget','projects','register'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1660', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date),
 ('decision-sheet-replies-are-keyed-to-card-position', 'pitfall', 'A decision sheet whose cards renumber must not republish onto its live store', 'The replies collection keys each verdict to the card NUMBER. Measured 2026-09-22: the standing open-asks sheet was published with 21 cards and fully answered (Complete, through 18); #1659 then dropped the executed cards and the builder emits 15. A republish would pin every stored reply on the wrong card with nothing erroring (card 11, the phone width, would inherit the old card 11, the light tints). Before republishing a sheet whose card set changed, start a fresh SHEET_ID and artifact or migrate the store by title. Recorded in docs/reference/decision_sheets.md and methodology-key-a-side-table-by-the-write-key-not-by-position.', array['decision-sheets','artifacts','data-shape'], 'proposed', 'docs/kb-notes/methodology-key-a-side-table-by-the-write-key-not-by-position.md', 'SkyFund S283', '2026-09-22'::date),
 ('funding-demonstrated-counts-reserved-funding', 'fact', 'The funding Summary counts reserved funding as demonstrated', 'In cpl_funding.js earnAgg(), winEarned excludes funding a gated (unconfirmed) institution has demonstrated; that sits in winHeld. With 0 of 118 confirmed, Sam''s Summary read ''$0 demonstrated so far'' beside a $2,174,757 reserve line. Since #1660 the allocation bullet counts winEarned + winHeld as demonstrated and ends: ''Each institution receives its demonstrated funding once it confirms local participation.'' The separate reserve bullet is retired.', array['implementation-funding','earn-diagnostic','summary'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1660', 'SkyFund S283', '2026-09-22'::date)
on conflict (slug) do nothing
returning slug, kind, status;
