-- S284 (SkyWage) checkpoint, 2026-09-23. Rule 8 ingest; status='proposed' (own writes are not
-- self-verified). INSERT-only, idempotent on slug: rerunning writes nothing.
-- Written 2026-09-23 after #1670 merged. Until then the guard read this file's ON CONFLICT DO NOTHING as
-- a DO block and let an apostrophe in these comments swallow the INSERT, so it refused the write.
-- The rows describe the state at 19:44 UTC, after Sam published Scenario 1. author names the session
-- so the playbook's log check can find them. The first send (20:48 UTC) failed on cpl_memory_summary_check,
-- which holds summary to one sentence of 1-400 characters: the long text now sits in detail.
-- Rollback: delete from cpl_memory where verified_by like '%SkyWage S284%' and event_date = '2026-09-23';
insert into cpl_memory (slug, kind, title, summary, detail, tags, status, source, verified_by, event_date, author)
values
 ('scenario-3-thirty-three-percent-into-career-attainment', 'decision', 'Sam: in Scenario 3 the deleted completion priority''s 33% goes to Career attainment', 'Sam moved the deleted completion priority''s 33% share into Career attainment and published the result as Scenario 1 on 2026-09-23, so the model now funds Access 33%, Completion 34% and Career attainment 33%.', 'Sam, 2026-09-23, verbatim: ''I want to put the 33% into Career Attainment''. Scenario 3 deletes Completion with Transcription (slot 1) and moves its 33% share to Career attainment (ca_u), not into Completion. This reverses his same-day funding-review ruling to hold the career priority at 0% until the first EDD import. Done 2026-09-23 19:44 UTC in Scenario 1, which he then published (''Deleted on Scenario 1 and published''): Access ppa_u 33, Completion ptc_u 34, Career attainment 33, Completion with Transcription deleted (prioRemoved [1]). Measured through the model, the 115 maximum awards total the $24,757,639 allocation. Career attainment''s factor was still the baked 1.0 against his 0.5 ruling.', array['implementation-funding','scenario-3','career-attainment','shares'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1664', 'Sam Lee (2026-09-23), recorded by SkyWage S284', '2026-09-23'::date, 'SkyWage-s284'),
 ('a-new-scenario-was-not-wired-to-the-public', 'fact', 'A new funding scenario never reached the public page; a published scenario now decides', 'Until #1664 the public explainer and the college briefing showed each viewer''s own selected scenario, so a new scenario never reached colleges; a published scenario per project now decides what they see.', 'Measured 2026-09-23: cpl_funding.js read the scenario the VIEWER''s browser had selected, so a college (no selection) saw Scenario 1 on the explainer while the curator''s browser showed his working scenario there, and college_briefing.js named ''Scenario 1'' in code. #1664 adds projects.<pid>.published: the explainer, the college briefing and any browser that never chose a scenario read it; Publish on the strip moves it; unset keeps Scenario 1.', array['implementation-funding','scenarios','public-view','college-briefing'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1664', 'SkyWage S284', '2026-09-23'::date, 'SkyWage-s284'),
 ('the-149k-at-base-was-a-label-on-the-share', 'pitfall', 'Colleges at the base read ~$149k because the table showed only the credit share beside ''(at base)''', 'Colleges at the $150,000 base appeared to receive about $149,000 because the table showed only the credit share beside the words at base; the Max award column now shows the full figure.', 'All 51 institutions at the $150,000 base receive exactly $150,000 (solveBounded holds them there). The table showed the CR/NC pair only, so Clovis read $149,321 (at base) plus $679. #1664 adds a Max award column carrying the bound word and the qualifying line; it reverses part of the 2026-08-31 R6/R7 ruling and is item 4 on Sam''s Scenario 3 sheet. KB note: methodology-label-a-bound-where-it-binds.', array['implementation-funding','base','presentation'], 'proposed', 'docs/kb-notes/methodology-label-a-bound-where-it-binds.md', 'SkyWage S284', '2026-09-23'::date, 'SkyWage-s284'),
 ('nc-base-cap-proportional-is-the-live-model', 'fact', 'Per-lane NC base/cap by each institution''s NC FTES share is exactly the live one-pool model', 'Giving noncredit its own base and cap in proportion to each institution''s noncredit FTES reproduces the live one-pool model to the cent, so noncredit already receives its share of the funding.', 'Sam, 2026-09-23, asked whether NC should get a base/cap proportional to its NC FTES share with the NC base taken from the CR base. Run against the live dials it reproduces every award to $0.00. NC gets parity: 7.12% of statewide FTES, 7.07% of the funding ($1,783,399). The combined $400K cap trims the two largest NC programs on credit campuses (Mt. SAC $115,102 against $237,441 proportional; Santa Ana $131,052 against $171,409). A noncredit weight is the clean lever (x1.25 gives $2,106,330); capping the credit share alone gives $1,880,823 and six institutions over $400K.', array['implementation-funding','noncredit','one-pool','base','cap'], 'proposed', 'docs/visuals/2026-09-23-funding-scenario-3.html', 'SkyWage S284', '2026-09-23'::date, 'SkyWage-s284'),
 ('supabase-new-public-tables-need-explicit-grants-2026-10-30', 'risk', 'From 2026-10-30 a new table in public gets no automatic Data API grant', 'From 2026-10-30 Supabase stops granting API access to new tables in the public schema, so every table the repo creates or rebuilds must grant its own access; the five nightly rebuilds were fixed and applied live on 2026-09-23.', 'Supabase notice forwarded by Sam, 2026-09-23: from October 30 existing projects stop auto-granting Data API access to NEW tables in public; existing tables keep their grants. Every migration that creates a table must grant select to anon and select/insert/update/delete to authenticated and service_role as its RLS intends, or the table is unreachable through PostgREST. Done 2026-09-23 (#1665): the five nightly rebuild functions that drop and re-create their tables grant them, tests/supabase_table_grants_test.py fails any created table without grants (49 live tables baselined), and the five functions were re-created live on Sam''s verdict (receipt kb/receipts/supabase_rebuild_grants_2026-09-23.sql). Verify after the 2026-09-24 promotion.', array['supabase','grants','rls','migrations'], 'proposed', 'Supabase email to slee@cccco.edu, 2026-09-23', 'Sam Lee (2026-09-23), recorded by SkyWage S284', '2026-09-23'::date, 'SkyWage-s284'),
 ('a-redraw-during-a-press-swallows-the-click', 'pitfall', 'A redraw between a press and its release swallows the click', 'A button pressed right after typing in a field did nothing, because the field saved on the way out and the tab redrew under the pressed button; the funding tab now waits for the press to finish before redrawing.', 'Sam, 2026-09-23: ''I tried to delete the P3 ... but the Delete button doesn''t fire.'' Reproduced in Chromium: he had just typed a share. Pressing Delete moved focus off the field, the field committed on blur (a change, and a save), and the commit redrew the tab while the mouse button was still down. The release reached a new button, and a browser sends click only to the element the press began on, so the handler never ran and a second press worked. Any tab that redraws on a committed edit has the trap. cpl_funding.js render() now waits while a press begun in the mount is open (selects exempt, 1.5 s fallback), #1667, guard tests/cpl_funding_press_hold.test.js. jsdom cannot see it: ask whether the pressed element is still in the document at release.', array['cobi','ui','events','implementation-funding'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1667', 'SkyWage S284', '2026-09-23'::date, 'SkyWage-s284'),
 ('a-fixture-sets-the-feed-state-it-assumes', 'pitfall', 'A test that reads a generated feed as its before state fails the day the feed gains the key', 'A test that treated the live daily feed as the state before a new measure arrived broke the day the feed gained that measure; a test must set the data state it depends on.', '2026-09-23: the first daily run after #1664 published ptc/ptc_u, and tests/cpl_funding_counselor_measure.test.js had taken the live cpl_funding_performance.js as the feed without that key. Checks 7h and 7k went red on main and on every PR merge ref. #1666 strips the key for before and writes it for after inside the fixture. A pinned absence is a pinned figure: set the state the assertion needs, never read it off a file the cron regenerates.', array['tests','generated-artifacts','implementation-funding','ci'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1666', 'SkyWage S284', '2026-09-23'::date, 'SkyWage-s284'),
 ('sql-guard-read-a-quote-in-a-comment-as-a-string', 'pitfall', 'The Supabase SQL guard read an apostrophe in a comment as a string, and ON CONFLICT DO NOTHING as a DO block', 'The SQL guard misread an apostrophe inside a comment and let a hidden delete pass as a read, and it refused every memory write made the documented way; reading the statement once, left to right, fixed both on 2026-09-23.', 'Measured 2026-09-23: scripts/supabase_sql_guard.py stripped literals before comments in separate regex passes, so an apostrophe inside a -- comment opened a phantom string that ran to the next quote. select 1; -- the curator''s list + newline + delete from kb_curation ...; -- end'' came back allow, and E''it\''s'' shifted the reading the same way. Separately, the do of ON CONFLICT (slug) DO NOTHING matched the DO-block verb, so every memory receipt written the documented INSERT-only way was refused while a bare insert passed: 20 rows from S281, S283 and S284 sat staged from 2026-09-21. The fix reads comments and literals in one left-to-right pass as Postgres does, asks on anything unterminated, and reads ON CONFLICT ... DO NOTHING as a clause; tests/supabase_sql_guard_test.py 47 cases, 8 of them failing on the old guard.', array['supabase','guard','rule-10','cpl-memory'], 'proposed', 'scripts/supabase_sql_guard.py', 'SkyWage S284', '2026-09-23'::date, 'SkyWage-s284')
on conflict (slug) do nothing;

-- ── The playbook's step 6 log for the eight rows above ──
-- The rows above were written 2026-09-23 20:56 UTC through execute_sql. This log insert was refused then:
-- the guard allowed a session to write cpl_memory alone. Sam said yes to letting a session append to the
-- log (evening sheet item 3, accepted in session about 21:15 UTC). The session ran this at 21:57:35 UTC,
-- after that guard change merged (#1671); the verify query read creates = 1 for all eight. Idempotent.
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyWage-s284', 'create', 'S284 checkpoint auto-write, logged late: the guard refused the log insert until Sam said yes', to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyWage-s284'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
-- Verify (every slug should read creates = 1):
-- select m.slug, count(l.id) filter (where l.action = 'create') as creates from public.cpl_memory m
--   left join public.cpl_memory_log l on l.memory_id = m.id where m.author = 'SkyWage-s284'
--   group by m.slug order by m.slug;
-- Rollback of this block alone: delete from public.cpl_memory_log where actor = 'SkyWage-s284' and action = 'create';
