-- S284 (SkyWage) checkpoint, 2026-09-23. Rule 8 ingest; status='proposed' (own writes are not
-- self-verified). INSERT-only, idempotent on slug: rerunning writes nothing.
-- STAGED, NOT WRITTEN: the repo's execute_sql guard refuses session writes (as with the S283 files).
-- Rollback: delete from cpl_memory where verified_by like '%SkyWage S284%' and event_date = '2026-09-23';
insert into cpl_memory (slug, kind, title, summary, tags, status, source, verified_by, event_date)
values
 ('scenario-3-thirty-three-percent-into-career-attainment', 'decision', 'Sam: in Scenario 3 the deleted completion priority''s 33% goes to Career attainment', 'Sam, 2026-09-23, verbatim: ''I want to put the 33% into Career Attainment''. Scenario 3 deletes Completion with Transcription (slot 1) and moves its 33% share to Career attainment (ca_u), not into Completion. This reverses, for Scenario 3, his same-day funding-review ruling to hold Priority 4 at 0% until the first EDD import. Measured on Scenario 3: statewide Current Total $2,613,990 today, $1,354,241 after the move, until the import lands. The sheet proposes factor 0.5 with the share and keeping Scenario 1 published until the import.', array['implementation-funding','scenario-3','career-attainment','shares'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1664', 'Sam Lee (2026-09-23), recorded by SkyWage S284', '2026-09-23'::date),
 ('a-new-scenario-was-not-wired-to-the-public', 'fact', 'A new funding scenario never reached the public page; a published scenario now decides', 'Measured 2026-09-23: cpl_funding.js read the scenario the VIEWER''s browser had selected, so a college (no selection) saw Scenario 1 on the explainer while the curator''s browser showed his working scenario there, and college_briefing.js named ''Scenario 1'' in code. #1664 adds projects.<pid>.published: the explainer, the college briefing and any browser that never chose a scenario read it; Publish on the strip moves it; unset keeps Scenario 1.', array['implementation-funding','scenarios','public-view','college-briefing'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1664', 'SkyWage S284', '2026-09-23'::date),
 ('the-149k-at-base-was-a-label-on-the-share', 'pitfall', 'Colleges at the base read ~$149k because the table showed only the credit share beside ''(at base)''', 'All 51 institutions at the $150,000 base receive exactly $150,000 (solveBounded holds them there). The table showed the CR/NC pair only, so Clovis read $149,321 (at base) plus $679. #1664 adds a Max award column carrying the bound word and the qualifying line; it reverses part of the 2026-08-31 R6/R7 ruling and is item 4 on Sam''s Scenario 3 sheet. KB note: methodology-label-a-bound-where-it-binds.', array['implementation-funding','base','presentation'], 'proposed', 'docs/kb-notes/methodology-label-a-bound-where-it-binds.md', 'SkyWage S284', '2026-09-23'::date),
 ('nc-base-cap-proportional-is-the-live-model', 'fact', 'Per-lane NC base/cap by each institution''s NC FTES share is exactly the live one-pool model', 'Sam, 2026-09-23, asked whether NC should get a base/cap proportional to its NC FTES share with the NC base taken from the CR base. Run against the live dials it reproduces every award to $0.00. NC gets parity: 7.12% of statewide FTES, 7.07% of the funding ($1,783,399). The combined $400K cap trims the two largest NC programs on credit campuses (Mt. SAC $115,102 against $237,441 proportional; Santa Ana $131,052 against $171,409). A noncredit weight is the clean lever (x1.25 gives $2,106,330); capping the credit share alone gives $1,880,823 and six institutions over $400K.', array['implementation-funding','noncredit','one-pool','base','cap'], 'proposed', 'docs/visuals/2026-09-23-funding-scenario-3.html', 'SkyWage S284', '2026-09-23'::date),
 ('supabase-new-public-tables-need-explicit-grants-2026-10-30', 'risk', 'From 2026-10-30 a new table in public gets no automatic Data API grant', 'Supabase notice forwarded by Sam, 2026-09-23: from October 30 existing projects stop auto-granting Data API access to NEW tables in public; existing tables keep their grants. Every migration that creates a table must grant select to anon and select/insert/update/delete to authenticated and service_role as its RLS intends, or the table is unreachable through PostgREST. Action queued for S285: add grants to the table-creating SQL files and a lint beside tests/supabase_function_grants_test.py.', array['supabase','grants','rls','migrations'], 'proposed', 'Supabase email to slee@cccco.edu, 2026-09-23', 'Sam Lee (2026-09-23), recorded by SkyWage S284', '2026-09-23'::date)
on conflict (slug) do nothing;
