-- S288 (SkyZ) checkpoint write, 2026-09-25. Rule 9 step 10 (Rule 8 ingest). Three rows, their log and the verify as
-- THREE statements in ONE execute_sql call (Sam's SQL budget ruling, 2026-09-24). INSERT-only, idempotent on slug.
-- Row 1 is Sam's own words, so it is verified with him named in verified_by; it refines cip-load-do-not-gate (a
-- human-sourced row) rather than superseding it (Rule 8). Rows 2 and 3 are this session's findings, proposed.
-- Rollback: delete from cpl_memory_log where actor = 'SkyZ-s288' and action = 'create';
--           delete from cpl_memory where author = 'SkyZ-s288';
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, verified_at, event_date, author)
values
 ('top-is-unchecked-program-cip-is-reliable-sam-2026-09-25', 'decision', 'Sam: TOP is unchecked; program CIPs are almost fully reliable', 'Sam, 2026-09-25: TOP codes are unreliable because colleges enter them with no effective checks, the new CIP system will be better, course CIPs are only partially set, and program CIPs are almost 100% reliable.', 'Verbatim, unprompted, after #1692 corrected TOP_Code_Lookup.xlsx column D: ''TOP is not reliable since it is entered by the colleges with no effective checks. The new CIP system will be better. The course CIPs are only partially set now the the program CIPs are almost 100% reliable''. It refines cip-load-do-not-gate (2026-09-17), which measured CIP coverage (blank on 29.1% of programs and 14.1% of active ones) rather than the reliability of the values that are set; both stand. Applied the same day: Rule 7''s CIP line and methodology-top-is-a-last-in-line-signal carry it, and the session withdrew its ask for MAP''s TOP table. Its limit, measured the same day: a program CIP labels the program, not the courses it lists (row a-program-cip-labels-the-program-not-its-courses). Vault capture: 03-professional/braindumps/braindump-2026-09-25-1315-program-cip-is-the-reliable-anchor.md.', 'Sam says the older TOP program codes cannot be trusted, because colleges enter them without real checks. The newer CIP codes are better: the ones on programs are almost always right, while the ones on individual courses are only partly filled in so far.', array['cip','top-code','data-quality','doctrine','eacr']::text[], 'Sam, 2026-09-25 (S288 SkyZ session)', array['cip-load-do-not-gate','observed-cip-beats-the-published-crosswalk-3x-2026-09-21','a-program-cip-labels-the-program-not-its-courses']::text[], 'verified', 'general', 'Sam Lee (2026-09-25), recorded by SkyZ S288', now(), '2026-09-25'::date, 'SkyZ-s288'),
 ('top-code-lookup-column-d-disagreed-with-its-titles-on-81-rows', 'fact', 'TOP_Code_Lookup.xlsx column D was wrong on 81 of 198 rows', 'Measured 2026-09-25: TOP_Code_Lookup.xlsx column D, the CCC 4-digit TOP that routes MAP''s TOP id to a CIP family, disagreed with its own program title on 81 of 198 rows until #1692 set it from the TOP manual, which cut the EACR''s unsectored matrix rows from 890 to 379.', 'Nothing read column D before #1681 (2026-09-24), which measured that 163 of 198 ids resolved and shipped; 46 of those 163 resolved to the wrong program, so a join rate is not a correctness rate. The 81: 35 codes that are no TOP code (Fire Technology 2130, Drafting 0909, Welding 0941) and 46 real codes naming another program (History 2203, which is Ethnic Studies; Political Science 2205, History; Nursing (RN) 1211, Polysomnography; Construction Crafts 0946, HVAC). kb/_correct_top_lookup_code4.py sets column D to the category of the TOP title column E names (kb/reference/top_categories.json, then the published crosswalk), settles 15 non-exact titles by hand and keeps row 144; receipt kb/receipts/top_code_lookup_code4_2026-09-25_s288.json; guard tests/top_code_lookup_code4_test.py (13 checks, in js-tests.yml beside tests/eacr_matrix_payload_test.py). Live since the 2026-09-25 13:16 UTC build, confirmed in Chromium: 890 to 379 unsectored rows (dropdown 449 cards), 328 cards re-sectored. 37 MAP TOP ids still have no row (100 cards) and stay that way while the course CIP route is pursued.', 'A lookup table that turns MAP''s program codes into career sectors had wrong codes on 81 of its 198 rows, because nobody had used that column before. Fixing it from the official code manual put 328 credentials in the right sector and cut the unsorted rows from 890 to 379.', array['eacr','cip','top-code','data-quality','lookup']::text[], 'CPL-Initiative/cpl-project-tracker#1692', array['top-is-unchecked-program-cip-is-reliable-sam-2026-09-25','eacr-ten-tweaks-sam-2026-09-24']::text[], 'proposed', 'workstream-specific', 'SkyZ S288', null, '2026-09-25'::date, 'SkyZ-s288'),
 ('a-program-cip-labels-the-program-not-its-courses', 'pitfall', 'A program CIP labels the program, not its courses', 'Measured 2026-09-25: voting a course''s CIP family from the COCI programs that list it misfiles service courses, because a course takes the field of every program that requires it; on a random 30 of the 682 EACR rows it would have moved, 8 read better, 15 worse and 7 the same, so it was not shipped.', 'Built on kb/program_course_graph.json (colleges joined on the MIS code through kb/college_identity/<date>/crosswalk.json, course numbers compared without leading zeros, umbrella families 24 and 30 voting only when alone). It sectored 2,244 of 3,000 matrix rows against 2,621 for the TOP route, and its largest disagreement groups favored it (culinary 19 to 12, FAA pilot 47 to 49, water treatment 03 to 15, welding and ironworkers 15 to 48): those groups are career-technical, whose courses live in their own programs. The random sample told the other half: Elementary Italian to 12 Culinary, Beginning Chinese and AP Japanese to 05 Area Studies, Calculus 1 to 40 Physical Sciences, AP US Government to 22 Legal, Microsoft Word Expert to 51 Health. Read the course''s own CIP (no file or table we hold carries it; Supabase has CIP only on coci_college_programs; open-asks card 15 asks Sam for a source), and use program membership to corroborate. Note: docs/kb-notes/methodology-a-program-cip-labels-the-program-not-its-courses.md.', 'It seemed natural to guess a course''s career field from the programs that include it. That goes wrong for courses many programs borrow: a language course inside a cooking program would be filed as cooking. So the field has to come from the course''s own code, and the programs only help confirm it.', array['cip','program-course-graph','methodology','eacr','data-quality']::text[], 'docs/kb-notes/methodology-a-program-cip-labels-the-program-not-its-courses.md', array['top-is-unchecked-program-cip-is-reliable-sam-2026-09-25','observed-cip-beats-the-published-crosswalk-3x-2026-09-21']::text[], 'proposed', 'general', 'SkyZ S288', null, '2026-09-25'::date, 'SkyZ-s288')
on conflict (slug) do nothing;
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyZ-s288', 'create', 'S288 SkyZ checkpoint auto-write (Rule 9 step 10); rows, log and verify in one call (kb/receipts/cpl_memory_2026-09-25_s288.sql)', to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyZ-s288'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
select m.slug, m.status, count(l.id) filter (where l.action = 'create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyZ-s288'
group by m.slug, m.status order by m.slug;

-- ── Later the same day (SkyZ S288): Sam's scoping ruling, one new row, and two in-place corrections to rows this
-- session wrote an hour earlier (their before-values are the INSERT above; each UPDATE restates the detail with one sentence changed). Rows,
-- log and verify in ONE execute_sql call. Rollback: delete the new row by slug; write the first block's detail back to the two.
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, verified_at, event_date, author)
values
 ('eacr-cip-sector-is-a-filter-aid-sam-2026-09-25', 'decision', 'Sam: the EACR''s CIP sector is a filter aid; sector it from your own analysis', 'Sam, 2026-09-25: the Exhibit Adoption view needs the CIP sector only for filtering and quick categorization, so the session may assign sectors from its own analysis rather than open the TOP/CIP question, which is its own project.', 'Verbatim, answering the session''s question of where to get course CIPs: ''CIP sector is best ... I don''t want this to be a big deal. We only need the CIP sector on this tab for filter and quick categorization. I would be just as happy if you used your own analysis from your knowledge to create the sectors yourself. I don''t want to get sucked into the top/CIP black hole, which is it''s own project.'' Applied the same day: the course-CIP ask (open-asks card 15) was withdrawn before it was published, and kb/reference/eacr_cip_title_rules.json (37 ordered title patterns plus an exact-title table) now sectors Standardized Assessment cards from their titles first and fills every card the TOP route leaves empty; cards without a sector 449 to 3, 84 exams moved to their subject, a random 25 all read right. Guard: tests/eacr_matrix_payload_test.py section 8c. Course and program CIPs stay with the TOP to CIP lane.', 'Sam decided the career-sector labels on the exhibit adoption page only need to be good enough to filter and group by, so the session sorted each exam into a sector by reading its title instead of chasing the official coding system, which Sam treats as its own project.', array['eacr','cip','scope','decision']::text[], 'Sam, 2026-09-25 (S288 SkyZ session)', array['top-is-unchecked-program-cip-is-reliable-sam-2026-09-25','a-program-cip-labels-the-program-not-its-courses','top-code-lookup-column-d-disagreed-with-its-titles-on-81-rows']::text[], 'verified', 'workstream-specific', 'Sam Lee (2026-09-25), recorded by SkyZ S288', now(), '2026-09-25'::date, 'SkyZ-s288')
on conflict (slug) do nothing;
update public.cpl_memory set detail = 'Built on kb/program_course_graph.json (colleges joined on the MIS code through kb/college_identity/<date>/crosswalk.json, course numbers compared without leading zeros, umbrella families 24 and 30 voting only when alone). It sectored 2,244 of 3,000 matrix rows against 2,621 for the TOP route, and its largest disagreement groups favored it (culinary 19 to 12, FAA pilot 47 to 49, water treatment 03 to 15, welding and ironworkers 15 to 48): those groups are career-technical, whose courses live in their own programs. The random sample told the other half: Elementary Italian to 12 Culinary, Beginning Chinese and AP Japanese to 05 Area Studies, Calculus 1 to 40 Physical Sciences, AP US Government to 22 Legal, Microsoft Word Expert to 51 Health. Read the course''s own CIP where one is set (no file or table we hold carries course CIPs; Supabase has CIP only on coci_college_programs), and use program membership to corroborate. For the EACR, Sam scoped the sector to a filter aid and the session sectored exams from their titles instead (row eacr-cip-sector-is-a-filter-aid-sam-2026-09-25). Note: docs/kb-notes/methodology-a-program-cip-labels-the-program-not-its-courses.md.'
 where slug = 'a-program-cip-labels-the-program-not-its-courses' and author = 'SkyZ-s288';
update public.cpl_memory set detail = 'Nothing read column D before #1681 (2026-09-24), which measured that 163 of 198 ids resolved and shipped; 46 of those 163 resolved to the wrong program, so a join rate is not a correctness rate. The 81: 35 codes that are no TOP code (Fire Technology 2130, Drafting 0909, Welding 0941) and 46 real codes naming another program (History 2203, which is Ethnic Studies; Political Science 2205, History; Nursing (RN) 1211, Polysomnography; Construction Crafts 0946, HVAC). kb/_correct_top_lookup_code4.py sets column D to the category of the TOP title column E names (kb/reference/top_categories.json, then the published crosswalk), settles 15 non-exact titles by hand and keeps row 144; receipt kb/receipts/top_code_lookup_code4_2026-09-25_s288.json; guard tests/top_code_lookup_code4_test.py (13 checks, in js-tests.yml beside tests/eacr_matrix_payload_test.py). Live since the 2026-09-25 13:16 UTC build, confirmed in Chromium: 890 to 379 unsectored rows (dropdown 449 cards), 328 cards re-sectored. 37 MAP TOP ids still have no row (100 cards); since 2026-09-25 the EACR sectors those cards from their titles instead (row eacr-cip-sector-is-a-filter-aid-sam-2026-09-25).'
 where slug = 'top-code-lookup-column-d-disagreed-with-its-titles-on-81-rows' and author = 'SkyZ-s288';
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyZ-s288', case when m.slug = 'eacr-cip-sector-is-a-filter-aid-sam-2026-09-25' then 'create' else 'update' end,
       case when m.slug = 'eacr-cip-sector-is-a-filter-aid-sam-2026-09-25' then 'S288 SkyZ: Sam''s scoping ruling (kb/receipts/cpl_memory_2026-09-25_s288.sql, second block)'
            else 'S288 SkyZ: one sentence replaced after Sam''s scoping ruling withdrew card 15; before-value is the first block of kb/receipts/cpl_memory_2026-09-25_s288.sql' end,
       to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyZ-s288'
  and m.slug in ('eacr-cip-sector-is-a-filter-aid-sam-2026-09-25', 'a-program-cip-labels-the-program-not-its-courses', 'top-code-lookup-column-d-disagreed-with-its-titles-on-81-rows')
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.note like 'S288 SkyZ: %');
select m.slug, m.status, (m.detail like '%card 15%') as mentions_card_15,
       count(l.id) filter (where l.action = 'create') as creates, count(l.id) filter (where l.action = 'update') as updates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyZ-s288'
group by m.slug, m.status, m.detail order by m.slug;

-- ── Checkpoint, end of the day (SkyZ S288): one row, its log and the verify in ONE execute_sql call.
-- Rollback: delete the log row (actor SkyZ-s288, this slug), then the row by slug.
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, event_date, author)
values
 ('three-repo-sessions-never-ran-the-stop-hook-patch', 'pitfall', 'Three-repo sessions never ran the stop-hook patch', 'The tracker''s SessionStart hook applies scripts/patch_stop_hook.py, and a three-repo session never loads the repo''s settings, so the Stop hook''s unpushed-commit false positive returned on 2026-09-25; since then scripts/check_hooks_live.py --fix, the first command of every session, applies the patch itself.', 'Seen in S288 (SkyZ): after #1693 squash-merged and GitHub deleted the branch, the local branch was reset to origin/main and the Stop hook reported ''There are 2 unpushed commit(s)'' (9bc5a30 and ed7247a, both on main) because the harness copy of ~/.claude/stop-hook-git-check.sh still counted $upstream..HEAD against a stale refs/remotes/origin/<branch>. git rev-list HEAD --not --remotes --count read 0. Pushing would have recreated a branch identical to main that a session cannot delete (the token 403s). Fix shipped: check_hooks_live.py runs patch_stop_hook.py when --fix is passed and prints a STOP HOOK: line when it patched anything; tested end to end on an unpatched copy (the patched result is byte-identical to a patched backup, exec bit kept) and pinned in tests/install_prompt_guards_test.py. docs/reference/troubleshooting.md carries the case.', 'At the end of a turn, an automatic check sometimes says there is unsaved work to upload when everything is already on the main branch. It was wrong because a repair meant to run when each session starts never ran in sessions that open all three repositories. The start-of-session check Sam pastes now applies the repair itself.', array['claude-code','stop-hook','session-practice','three-repo']::text[], 'docs/reference/troubleshooting.md; scripts/check_hooks_live.py', '{}'::text[], 'proposed', 'general', 'SkyZ S288', '2026-09-25'::date, 'SkyZ-s288')
on conflict (slug) do nothing;
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyZ-s288', 'create', 'S288 SkyZ end-of-day checkpoint (kb/receipts/cpl_memory_2026-09-25_s288.sql, third block)', to_jsonb(m)
from public.cpl_memory m
where m.slug = 'three-repo-sessions-never-ran-the-stop-hook-patch' and m.author = 'SkyZ-s288'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
select m.slug, m.status, count(l.id) as log_rows
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyZ-s288'
group by m.slug, m.status order by m.slug;
