-- S333 (SkyHarbor), checkpoint 2026-10-05: sheet 39 rulings, the additive-sync pitfall, the display delta write.
-- Rollback: supersede each row by slug under actor 'SkyHarbor-s333-rollback'.
insert into public.cpl_memory (slug, title, kind, summary, detail, plain, tags, affects, source, author, event_date, status)
values
('sam-sheet39-rulings-2026-10-05', 'Sam, sheet 39: the display build goes, and OSHA takes one name as issuer with CTCNC its trainer', 'decision', 'Sam, open-asks sheet 39 (2026-10-05 15:52Z, both his own call): card 1 "go" on display build 799bfb9a7dbf (the Ext & Review label on IWAP 41.09); card 2 "name": OSHA is named U.S. Occupational Safety and Health Administration (OSHA) as issuer across the CER, and on OSHA 10-hour Construction Training Course OSHA issues and CTCNC trains.', 'Applied the same day: the display as a two-path guarded update (all 20 rows match the build''s md5s, #1866); kb/credentials.json edited for five entries and five of Sam''s kb_curation rows replaced by guarded update (two Agriculture issuing_agency_override rows of 2026-07-08, three _UNCLASSIFIED triage assignments of 2026-07-07 that set U.S. Department of Labor), plan kb/cer_decisions_out/2026-10-05-2, #1868. The card had named two of his rows and an override-only route; the correction went to him in the sheet''s thread before any write. No hold came back.', 'Sam approved the page update for the ironworker course and asked that the federal safety agency appear under one name everywhere, with the training committee listed as trainer rather than as the issuer.', array['decision-sheet','cer','issuing-agency','osha','roep-display','program-requirements'], array['kb/credentials.json','kb_curation','program_requirement_records'], 'Sam, open-asks sheet 39 replies store (2026-10-05)', 'SkyHarbor-s333', '2026-10-05', 'verified'),
('cer-issuer-sync-is-additive-only-2026-10-05', 'The CER''s issuer syncs only add: an override row cannot rename or replace an issuer in credentials.json', 'pitfall', 'kb/_apply_credential_review.py and kb/_fold_unclassified.py fill an empty issuer and append one no record names (exact, acronym or 8-character containment), and never overwrite. An override row alone appends beside the old issuer or does nothing. A correction edits the file and replaces every source row the syncs read (override and _UNCLASSIFIED triage), in one window.', 'Found S333 planning sheet 39 card 2: the OSHA cards'' U.S. Department of Labor came from three triage assignments the card never named. KB note methodology-an-additive-sync-cannot-carry-a-correction; the applier''s guarded replace (replaces: {value, reviewer_email}) carries the source-row half, #1868.', 'Fixing a credential''s issuer name takes two changes at once, the list itself and every place the nightly update copies issuers from; otherwise the old name comes back the next morning.', array['cer','issuing-agency','kb-curation','sync','pitfall'], array['kb/_apply_credential_review.py','kb/_fold_unclassified.py','kb/_cer_decision_apply.py'], 'S333 code read; KB note methodology-an-additive-sync-cannot-carry-a-correction', 'SkyHarbor-s333', '2026-10-05', 'proposed'),
('roep-display-delta-write-proven-by-md5-2026-10-05', 'A display build that changes two paths is written as a guarded two-path update and proven by the full build''s md5s', 'procedure', 'Build 799bfb9a7dbf differed from 81691460ba18 in two JSON paths (build on 20 rows, one IWAP 41.09 label). S333 wrote it as two jsonb_set updates conditioned on the before-values, in place of the 159 KB upsert, then proved all 20 rows against kb/_build_roep_display.py --verify-sql. Diff the two receipts first.', 'Before the write, all 20 rows matched md5s built from the old receipt with the builder''s jsonb_text; a verify retyped from a truncated listing gave four false differs, so build verify queries from files. Receipt kb/receipts/program_requirement_records_display_2026-10-05_799bfb9a7dbf_delta.sql; rollback is the old build''s receipt.', 'When the program pages'' stored facts change in only a couple of places, the session updates just those places and then checks every row against the full expected result.', array['program-requirements','roep-display','supabase','receipt','procedure'], array['program_requirement_records','kb/_build_roep_display.py'], 'S333 apply (#1866)', 'SkyHarbor-s333', '2026-10-05', 'proposed')
on conflict (slug) do nothing;

insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyHarbor-s333', 'create', case when m.slug = 'sam-osha-issues-the-card-not-the-teaching-college-2026-10-05' then 'session write (S333; log entry late, written at the checkpoint)' else 'checkpoint auto-write (S333)' end, to_jsonb(m)
from public.cpl_memory m where m.author = 'SkyHarbor-s333'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');

select m.slug, m.status, count(l.id) filter (where l.action='create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyHarbor-s333' group by m.slug, m.status order by m.slug;
