-- WRITTEN 2026-09-24 00:3x UTC by S285 (SkyGrant) through kb/receipts/cpl_memory_2026-09-24_s285.sql, which
-- re-read every row against the state that day and restructured each into a one-sentence summary plus detail
-- (the table holds summary to 400 characters). This file stays as staged; the changes are listed in that receipt.
-- S283 (SkyFund) second checkpoint, 2026-09-23. Rule 8 ingest; status='proposed' (own writes are not
-- self-verified). INSERT-only, idempotent on slug: rerunning writes nothing.
-- STAGED, NOT WRITTEN: the repo's execute_sql guard refuses session writes (as with the 2026-09-22 file).
-- Rollback: delete from cpl_memory where verified_by like '%SkyFund S283%' and event_date = '2026-09-23';
--           update cpl_memory set status = 'proposed'
--             where slug = 'counselor-step-is-the-only-campus-measure-for-goal-c';   -- its value before the supersede below
insert into cpl_memory (slug, kind, title, summary, tags, status, source, verified_by, event_date)
values
 ('priority-2-serves-b-alone-career-attainment-is-priority-4', 'decision', 'Priority 2 serves (B) alone, and career attainment is Priority 4', 'Sam, 2026-09-22, verbatim: ''1. Change P2 B&C Completion to B Completion with Counseling (read from live tab--also designated where the metric is derived) 2. Change P3 to Completion with Transcription (read from live tab) 3. Add P4 with the same ability to edit as other P cards.'' The counselor step (milestone accepted, pac_u) now derives goal (B) only, superseding his 2026-09-01 ruling that it served (B) and (C). Goal (C) is carried by Priority 4, pinned to ca_u (milestone career, origin co). Card headers read each priority''s live title. Shipped in #1662.', array['implementation-funding','goal-c','counselor','priorities'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1662', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-23'::date),
 ('priority-4-career-attainment-zero-share-ca-u', 'fact', 'Priority 4 ships at a 0% share and factor 1.0, measured in CPL units by the CO', 'As of #1662 (2026-09-23): Priority 4, Career attainment, is baked into both years with share 0, factor 1.0, metric_src ca_u (CPL units in FTES for students who reach a career outcome in EDD wage records; noncredit twin nc_ca_u). Units, because Sam ruled headcount is not a metric in this tab. The live config has no entry for slot 3, so P4 inherits the bake until Sam edits it; P1-P3 run at 0.5. srcDelivered() reads ca_u as $0 until the Chancellor''s Office import lands, so a share set earlier sits at $0. Stored order [0,2,1] extends to [0,2,1,3].', array['implementation-funding','career-attainment','edd','priorities'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1662', 'SkyFund S283', '2026-09-23'::date),
 ('a-control-that-does-nothing-read-the-request-log-first', 'pitfall', 'When a curator says a button does nothing, read the request log before the handler', 'Sam reported the (D) card''s Designate button did nothing (2026-09-22). jsdom and Chromium replays worked. The Supabase edge logs showed nine 200 PATCHes on cpl_funding_config from 23:37 to 23:39 UTC, the last four his releases, and none after: the click never reached saveShared(). The handler''s reachable early return was an empty selection, which returned silently; #1662 makes it say what it needs. No request means the client stopped; a 4xx means the server refused; a 200 with the change missing means a later whole-config save overwrote it. docs/kb-notes/methodology-a-control-that-does-nothing-read-the-request-log-first.md.', array['debugging','supabase','curation-ui','implementation-funding'], 'proposed', 'docs/kb-notes/methodology-a-control-that-does-nothing-read-the-request-log-first.md', 'SkyFund S283', '2026-09-23'::date),
 ('stored-order-predating-a-priority-is-extended-not-reset', 'pitfall', 'A stored display order written before a priority existed must be extended, never reset', 'priorityOrder() fell back to the natural order whenever the stored permutation''s length differed from the priority count. The day Priority 4 arrived, Sam''s live [0,2,1] would have swapped his P2 and P3 with nothing on screen saying why. Both cpl_funding.js priorityOrder() and college_briefing.js applyPriorityOrder() now keep a shorter valid permutation and append the newcomers. The two copies of the rule must stay in step. Guard: tests/cpl_funding_career_attainment.test.js 2a and cpl_funding_reorder.test.js C.', array['implementation-funding','college-briefing','priority-order'], 'proposed', 'CPL-Initiative/cpl-project-tracker#1662', 'SkyFund S283', '2026-09-23'::date)
,
 ('funding-review-rulings-2026-09-23', 'decision', 'Sam ruled the funding review sheet: hold P4 at 0%, CO research defines the outcome, consolidate the drill-in', 'Sam, 2026-09-23 ("Decisions done"; high-water mark 3 of 3 on https://claude.ai/artifact/9MfbN6jqio8as9mY4LwPB2). (1) Hold: Priority 4 stays at a 0% share until the first Chancellor''s Office import lands; its share and a funding factor of 0.5 are then set together. (2) CO research defines the career outcome; the import carries, per college, the CPL units of students awarded CPL who reach it, counts under 10 masked before the file is committed; the receiver is funding/career_attainment_import.json read by funding/_build_funding_performance.py (docs/kb-notes/reference-career-attainment-import.md). (3) Each institution''s drill-in is one Baseline line with the CO''s control, then the priority table captioned Current Total and Total Possible.', array['implementation-funding','career-attainment','edd','decision-sheets','drill-in'], 'proposed', 'https://claude.ai/artifact/9MfbN6jqio8as9mY4LwPB2', 'Sam Lee (2026-09-23), recorded by SkyFund S283', '2026-09-23'::date)
on conflict (slug) do nothing
returning slug, kind, status;

-- Superseded explicitly by Sam's 2026-09-22 ruling above (a session-sourced row, verified_by = 'session').
update cpl_memory set status = 'superseded'
 where slug = 'counselor-step-is-the-only-campus-measure-for-goal-c' and status = 'proposed'
returning slug, status;
