-- S285 (SkyGrant) write of the 15 rows S281 and S283 staged and never landed, 2026-09-24. Rule 8 ingest.
-- The staged receipts: kb/receipts/cpl_memory_2026-09-21_s281.sql (4 rows), cpl_memory_2026-09-22_s283.sql (6),
-- cpl_memory_2026-09-23_s283.sql (5). None reached cpl_memory: the guard refused ON CONFLICT DO NOTHING as a DO
-- block until #1670 (S284 measured it 2026-09-23 20:00 UTC; all 15 absent again at 2026-09-24 00:0x UTC).
-- Every row was re-read against the state on 2026-09-24 before it was written; verified_by keeps the original
-- attribution and author names this session so the log check and the rollback can find the cohort.
-- Changes from the staged text, all noted inside detail:
--   opt-out-sheets-need-verdict-provenance   the calibration consequence now follows the 09-22 high-water mark
--   jev-magic-half-one-module-for-every-reference   the CCR was wired on 2026-09-22 (#1648)
--   priority-2-serves-b-alone-career-attainment-is-priority-4   Career attainment is P3 in the published scenario since 09-23
--   priority-4-career-attainment-zero-share-ca-u   false since 09-23 19:44 UTC; written status superseded, superseded_by set
--   funding-review-rulings-2026-09-23   ruling (1) reversed by Sam the same evening
--   funding-statewide-lines-and-project-partners   the 1.1.2 team field re-read live 2026-09-24 (still unedited)
-- Summary is one sentence of at most 400 characters (cpl_memory_summary_check); the long text sits in detail;
-- plain is present on every row (playbook rule 5). INSERT-only, idempotent on slug: rerunning writes nothing.
-- Rollback: delete from cpl_memory where author = 'SkyGrant-s285' and event_date <= '2026-09-23';
--           then delete from cpl_memory_log where actor = 'SkyGrant-s285' and action = 'create';
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, superseded_by, scope, verified_by, event_date, author)
values
 ('sendtoclaude-cannot-reach-a-claude-code-session', 'pitfall', 'Complete button cannot reach the session', 'Measured 2026-09-21 (S281): an artifact''s sendToClaude() reports no_session from a remote-container Claude Code session even with a live, confirmed artifact watch, so a decision sheet''s Complete press never wakes the session that published it.', 'The watch was re-registered and listed at 13:42:11Z, Sam pressed Complete at 13:43:24Z, the page still reported ''no session is listening'' and replies/done carried sent:false. A lapsed watch was a real condition and was not the cause; do not re-diagnose consent or permissions. It works from a claude.ai chat session. The reliable path: replies/done is a durable record needing nothing alive at press time, so arm a send_later that reads it and compares its at. Still the case on 2026-09-23: S284''s evening sheet was answered in session, not through the button. Staged by SkyAnvil S281 on 2026-09-21; written by SkyGrant S285 on 2026-09-24 after re-reading against the current state.', 'When Sam presses the finish button on a decision sheet, the page tries to tell the working session that he is done. From a cloud-run coding session that message never arrives, even when everything is set up correctly. The sheet still records his answers, so the session schedules its own reminder to go read them instead of waiting for the button.', array['decision-sheets','artifacts','notification','claude-code']::text[], 'docs/kb-notes/methodology-the-record-is-the-mechanism-the-notification-is-a-bonus.md', '{}'::text[], 'proposed', null, 'general', 'SkyAnvil S281', '2026-09-21'::date, 'SkyGrant-s285'),
 ('a-second-look-shown-the-verdict-rubber-stamps-it', 'procedure', 'Skeptic pass never sees the verdict', 'An adjudication''s second look must not be shown the verdict it checks, because a model handed its own conclusion tends to agree and the failure is silent, so kb/_jev_adjudicate.py asks the negative question in a separate call with the first answer withheld.', 'The Trail Crew playbook requires an adversarial skeptic on every merge proposal, and its working version re-derived the numbers rather than re-reading the claim. A rubber-stamping skeptic produces a clean report with a high confirmation rate, indistinguishable from a pass that worked. A refuted proposal routes to the curator however confident the first look was; the gate is symmetric so a 0.5 hedge is not a refutation; the second call is spent only above the gate. tests/jev_adjudicate_test.py asserts the skeptic call does not contain the first verdict. Staged by SkyAnvil S281 (2026-09-21); written by SkyGrant S285 (2026-09-24).', 'When we ask the AI to double-check one of its own merge suggestions, the checker must not be told what the first answer was. If it is, it usually just agrees, and the report looks clean either way. So the second check is asked the opposite question from the same evidence, with the first answer hidden.', array['adjudication','ai','jev','trail-crew','verification']::text[], 'docs/kb-notes/methodology-a-second-look-shown-the-verdict-rubber-stamps-it.md', '{}'::text[], 'proposed', null, 'general', 'SkyAnvil S281', '2026-09-21'::date, 'SkyGrant-s285'),
 ('opt-out-sheets-need-verdict-provenance', 'decision', 'Opt-out sheets record who ruled', 'Sam, 2026-09-21: an opt-out decision sheet pre-selects the recommended verdict and he changes only what he disagrees with, so the store records who ruled (by sam) and which items rode the proposal (by default), and the high-water mark he added on 2026-09-22 says how far he read.', 'Sam, 2026-09-21: ''set the decision button for each item to your recommended and I will change only if needed -- opt-out approach''. A pre-selected chip is indistinguishable from an answered one, so a sheet abandoned at item 30 hands over verdicts for 31-51 nobody read. They are still handed over, since that is what opt-out is, but never as his: no stored reply means the item carries the proposal, a stored reply is always by sam, and Complete commits the rest by default. REFINED 2026-09-22 (Sam''s high-water mark): the last item carrying any input marks how far he read; everything at or below it counts as his judgment, everything above it has no verdict. So calibration scores everything at or below the mark, which supersedes S281''s narrower rule of scoring against by-sam rows only. Mechanics in docs/reference/decision_sheets.md. Staged by SkyAnvil S281 (2026-09-21); written by SkyGrant S285 (2026-09-24) with the 09-22 refinement.', 'Sam asked that decision sheets come pre-filled with our recommendation so he only changes what he disagrees with. Because a pre-filled answer looks the same as one he chose, the sheet keeps track of which items he actually touched, and the last item he touched shows how far down the sheet he read. Items below that point count as his decisions; items above it were never reviewed.', array['decision-sheets','cr-reference','calibration']::text[], 'docs/reference/decision_sheets.md', '{}'::text[], 'proposed', null, 'general', 'Sam Lee (2026-09-21), recorded by SkyAnvil S281', '2026-09-21'::date, 'SkyGrant-s285'),
 ('jev-magic-half-one-module-for-every-reference', 'fact', 'One Jev module for every reference', 'kb/_jev_adjudicate.py is the single Jev magic half for the CSR, CER, CCRR and, since 2026-09-22 (#1648), the CCR through a Trust Card adapter on the six-rung ladder; it suggests and writes nothing, and runs through typesafe-smoke.yml because typesafe.ai is egress-blocked from the sandbox.', 'The method+magic pattern is the repo''s own (playbook-trail-crew-method-magic-audit, run twice 2026-07-10 on CER then CSR); every reference owns a METHOD half and what differs is the magic one. CCRR blocking is imported from _typesafe_cr_trial.build_pairs(), never reimplemented. Triage measured 2026-09-21: CER 239 findings -> 59 worth a call (180 mechanical), CSR 185 -> 143, CCRR 55 anchored pairs; the 2026-09-20 receipt''s 51 pairs all still present, the 4 new pairs under the community relations anchor. S281 recorded the CCR as deliberately unwired (its method half emits Trust Cards rather than findings); S282 wired it on 2026-09-22 (#1648: the ladder sheet plus the CCR Trust Card adapter), on Sam''s ruling that the CCR gets the next sitting at 40-60 findings on a six-rung ladder (receipt kb/receipts/jev_ccr_title_rung_2026-09-22_s282.json). Staged by SkyAnvil S281 (2026-09-21); written by SkyGrant S285 (2026-09-24) with the 09-22 change.', 'We have one shared routine that asks the AI reviewer, Jev, to look at proposed merges across all four of our reference lists, instead of a separate routine per list. It only suggests; a person decides. The common-course list was the last to join, on 2026-09-22.', array['cr-reference','jev','adjudication','csr','cer','ccr']::text[], 'kb/_jev_adjudicate.py', array['sam-ccr-next-sitting-and-the-six-rung-ladder-2026-09-21']::text[], 'proposed', null, 'workstream-specific', 'SkyAnvil S281', '2026-09-21'::date, 'SkyGrant-s285'),
 ('baseline-counts-run-over-116-colleges-including-calbright', 'decision', 'Baseline counts 116 colleges with Calbright', 'Sam, 2026-09-22, on the Implementation Funding baseline block that read ''48 of 115'': ''should be 116 college, including Calbright'', so the baseline counts run over the 115 credit colleges plus Calbright, with NOCE and SD Continuing Education in the 118-row roster as institutions, not colleges.', 'cpl_funding.js eligColleges() is the one list (#1660). MAP spells Calbright ''Calbright College Credit'' and ''Calbright College Non-Credit''; both match the Calbright row in the coordinator join. Live 2026-09-22: 48 colleges had a coordinator on file (map_coordinator_summary, 123 rows). Staged by SkyFund S283 (2026-09-22); written by SkyGrant S285 (2026-09-24).', 'When the funding page says how many colleges have met a baseline requirement, the total is 116: the 115 credit colleges plus Calbright, the online college. The two stand-alone adult schools in the funding roster are counted as institutions but not as colleges.', array['implementation-funding','college-identity','calbright','baseline']::text[], 'CPL-Initiative/cpl-project-tracker#1660', '{}'::text[], 'proposed', null, 'workstream-specific', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date, 'SkyGrant-s285'),
 ('career-attainment-measured-by-the-co-from-edd-wage-data', 'decision', 'CO measures career attainment from EDD', 'Sam, 2026-09-22: goal (C) career attainment is measurable after all, because the Chancellor''s Office can measure it from EDD wage data and import the result into the funding model periodically, so colleges report nothing for it.', 'Verbatim: ''On Career Attainment, I had been thinking we wouldn''t be able to measure it, but after speaking with CO research team, we can use EDD wage data to measure this... This would not be reported by the colleges but instead measured by the CO and reflected on our funding model with periodic updates (imports) of the data. The Opportunities section would stay as is.'' Retires the funded-with-no-campus-measure posture for (C). How it enters the model: the receiver is funding/career_attainment_import.json read by funding/_build_funding_performance.py into ca_u and nc_ca_u (units only; an unmasked count under 10 stops the import; reference-career-attainment-import). S283 proposed showing the priority first and funding it after the first import, because srcDelivered() reads an undelivered measure as $0; Sam instead funded it at 33% with factor 0.5 on 2026-09-23 (scenario-3-thirty-three-percent-into-career-attainment), so its share qualifies nothing until CO research sends the first file. His method note the same day: CPL FTES per student record that demonstrates a career attainment improvement, from CO analysis. Staged by SkyFund S283 (2026-09-22); written by SkyGrant S285 (2026-09-24).', 'We had assumed the career attainment goal in the law could not be measured. Sam learned from the Chancellor''s Office research team that state wage records can measure it, so the Chancellor''s Office will compute it and load the results into the funding model from time to time. Colleges do not have to report anything for it. Until the first load arrives, the share of funding tied to this goal pays out nothing.', array['implementation-funding','career-attainment','edd','co-research','goal-c']::text[], 'CPLBrain/03-professional/braindumps/braindump-2026-09-22-2030-career-attainment-measured-by-edd-wage-data.md', array['scenario-3-thirty-three-percent-into-career-attainment']::text[], 'proposed', null, 'workstream-specific', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date, 'SkyGrant-s285'),
 ('funding-prose-leads-positive-with-no-restatement', 'decision', 'Funding prose leads positive, no restatement', 'Sam, 2026-09-22: funding prose starts with the positive, avoids this-not-that framing and any follow-on sentence that restates the point in other words, uses active voice and academic rather than commercial language, and prefers action verbs to adjectives.', 'Verbatim, opening the leadership-review edits: ''start with positive and avoid statements like this, not that or follow on restatements in other words''; on the allocation explainer: ''avoiding mannerly language, using active voice where possible, avoiding adjectives in preference for action verbs... Try and simplify and use academic rather than commercial language throughout.'' Extends the 2026-09-16 no-this-not-that ruling with a second ban: a follow-on sentence that says the same thing in other words. Applied across the Summary, the Baseline block, the Funding Breakdown and How an allocation is computed in #1660. Staged by SkyFund S283 (2026-09-22); written by SkyGrant S285 (2026-09-24).', 'When we write about the funding model, Sam wants each point stated once, positively and directly: say what something is, in plain academic language, and do not follow it with a second sentence that says the same thing another way.', array['implementation-funding','house-voice','writing']::text[], 'CPL-Initiative/cpl-project-tracker#1660', '{}'::text[], 'proposed', null, 'workstream-specific', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date, 'SkyGrant-s285'),
 ('funding-statewide-lines-and-project-partners', 'decision', 'Ledger lines in black; project partners', 'Sam, 2026-09-22, on the Funding Breakdown: the statewide ledger lines read in black rather than red, the word deducted gives way to a positive one, and many CPL projects are carried out with college partners, so project 1.1.2''s partners are Santiago Canyon College and American River College.', 'Verbatim: ''change red font to black and revise deducted to something positive. Many of the projects involve college partners (e.g., Twentynine Palm and Copper Mt. Demo Project and AI Apprenticeship Tools with SCC and American River College (was Norco College, but changed)''. Red stays for a state the reader must act on. FACT for the register: project 1.1.2 AI Apprenticeship CPL Tools partners are Santiago Canyon College and American River College; the projects table team field still read ''Santiago Canyon College, Norco College, Trade Partners'' on 2026-09-24 (last updated 2026-07-22) and awaits Sam''s edit in Activities, which the To-Do feed carries; sessions do not write that table. Staged by SkyFund S283 (2026-09-22); written by SkyGrant S285 (2026-09-24), team field re-read live.', 'On the funding breakdown, the statewide lines are shown in ordinary black text, since red is kept for things a reader must act on, and the word deducted was replaced with a positive one. Sam also noted that many of the funded projects are run with partner colleges; the AI apprenticeship project''s partners are Santiago Canyon College and American River College, and the project list still names Norco College until Sam edits it.', array['implementation-funding','budget','projects','register']::text[], 'CPL-Initiative/cpl-project-tracker#1660', '{}'::text[], 'proposed', null, 'workstream-specific', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-22'::date, 'SkyGrant-s285'),
 ('decision-sheet-replies-are-keyed-to-card-position', 'pitfall', 'Reply store keyed to card number', 'A decision sheet''s replies collection keys each verdict to the card number, so a sheet whose card set changed must never be republished onto its live store, or every stored reply lands on the wrong card with nothing erroring.', 'Measured 2026-09-22: the standing open-asks sheet was published with 21 cards and fully answered (Complete, through 18); #1659 then removed the executed cards and the builder emits 15. A republish would pin every stored reply on the wrong card (card 11, the phone width, would inherit the old card 11, the light tints). Before republishing a sheet whose card set changed, start a fresh SHEET_ID and artifact or migrate the store by title. Still standing 2026-09-24: CLAUDE.md section 11 says the open-asks sheet is not to be republished as it stands. Recorded in docs/reference/decision_sheets.md and methodology-key-a-side-table-by-the-write-key-not-by-position. Staged by SkyFund S283 (2026-09-22); written by SkyGrant S285 (2026-09-24).', 'A decision sheet remembers Sam''s answers by the item''s position: item 1, item 2 and so on. If we remove or reorder items and publish the sheet again at the same address, his old answers attach to the wrong items without any warning. A changed sheet gets a new address instead.', array['decision-sheets','artifacts','data-shape']::text[], 'docs/kb-notes/methodology-key-a-side-table-by-the-write-key-not-by-position.md', '{}'::text[], 'proposed', null, 'general', 'SkyFund S283', '2026-09-22'::date, 'SkyGrant-s285'),
 ('funding-demonstrated-counts-reserved-funding', 'fact', 'Summary counts reserved funding as demonstrated', 'Since #1660 the funding Summary counts the funding an unconfirmed institution has demonstrated (winHeld) together with winEarned as demonstrated and ends with each institution receiving its demonstrated funding once it confirms local participation, so it no longer reads $0 demonstrated beside a large reserve line.', 'In cpl_funding.js earnAgg(), winEarned excludes funding a gated (unconfirmed) institution has demonstrated; that sits in winHeld. With 0 of 118 confirmed on 2026-09-22, Sam''s Summary read ''$0 demonstrated so far'' beside a $2,174,757 reserve line. The separate reserve bullet is retired. Staged by SkyFund S283 (2026-09-22); written by SkyGrant S285 (2026-09-24).', 'Before a college confirms it is taking part, the funding it has already demonstrated through its CPL results is held in reserve. The summary at the top of the funding page used to show that as zero demonstrated, which read as if nothing had been achieved; now it counts the held funding too and explains that each college receives it once it confirms participation.', array['implementation-funding','earn-diagnostic','summary']::text[], 'CPL-Initiative/cpl-project-tracker#1660', '{}'::text[], 'proposed', null, 'workstream-specific', 'SkyFund S283', '2026-09-22'::date, 'SkyGrant-s285'),
 ('priority-2-serves-b-alone-career-attainment-is-priority-4', 'decision', 'Priority 2 serves (B) alone', 'Sam, 2026-09-22: Priority 2 becomes Completion with Counseling serving goal (B) alone, the counselor step no longer derives goal (C), and career attainment gets its own priority card pinned to the CO-measured ca_u, superseding his 2026-09-01 ruling that the counselor step served (B) and (C).', 'Verbatim: ''1. Change P2 B&C Completion to B Completion with Counseling (read from live tab--also designated where the metric is derived) 2. Change P3 to Completion with Transcription (read from live tab) 3. Add P4 with the same ability to edit as other P cards.'' Shipped in #1662 with career attainment as Priority 4 (ca_u, milestone career, origin co); card headers read each priority''s live title. Numbering moved on 2026-09-23: Sam deleted Completion with Transcription in Scenario 1 and moved its 33% to Career attainment, so the published scenario reads Access P1 (ppa_u), Completion P2 (ptc_u, outcome B), Career attainment P3 (ca_u, factor 0.5) and Innovation Projects as the reported P4 (#1664). The durable part is the goal wiring: (B) from the counselor-checked measure, (C) from the CO import. Staged by SkyFund S283 (2026-09-23); written by SkyGrant S285 (2026-09-24) with the numbering change.', 'Sam split two goals from the law onto separate funding priorities. The priority tied to students who met with a counselor now counts only toward the completion goal, and career attainment has a priority of its own, measured by the Chancellor''s Office rather than by colleges. The card numbers shifted a day later when Sam removed a duplicate completion priority, but the split itself stands.', array['implementation-funding','goal-c','counselor','priorities']::text[], 'CPL-Initiative/cpl-project-tracker#1662', array['scenario-3-thirty-three-percent-into-career-attainment']::text[], 'proposed', null, 'workstream-specific', 'Sam Lee (2026-09-22), recorded by SkyFund S283', '2026-09-23'::date, 'SkyGrant-s285'),
 ('priority-4-career-attainment-zero-share-ca-u', 'fact', 'Priority 4 shipped at zero share', 'As shipped in #1662 on 2026-09-23, Priority 4 Career attainment was baked into both years at share 0 and factor 1.0 on metric ca_u, a state Sam replaced the same day by funding Career attainment at 33% with factor 0.5 in Scenario 1.', 'The bake: share 0, factor 1.0, metric_src ca_u (CPL units in FTES for students who reach a career outcome in EDD wage records; noncredit twin nc_ca_u), units because Sam ruled headcount is not a metric in this tab; the live config had no entry for slot 3, so P4 inherited the bake while P1-P3 ran at 0.5; srcDelivered() reads ca_u as $0 until the Chancellor''s Office import lands. Stored order [0,2,1] extended to [0,2,1,3]. Superseded the same day: Sam deleted Completion with Transcription in Scenario 1, moved its 33% to Career attainment (19:44 UTC) and set the factor to 0.5 (21:30 UTC); the config read on 2026-09-24 shows slot 3 at share 0.33, factor 0.5. Written already superseded so the ship state stays on record without entering the default view. Staged by SkyFund S283 (2026-09-23); written by SkyGrant S285 (2026-09-24).', 'When the career attainment priority was first added to the funding model it carried no share of the funding, as a placeholder until the Chancellor''s Office could measure it. Later the same day Sam gave it a third of the funding, so this entry records only the starting point.', array['implementation-funding','career-attainment','edd','priorities']::text[], 'CPL-Initiative/cpl-project-tracker#1662', array['scenario-3-thirty-three-percent-into-career-attainment']::text[], 'superseded', 'scenario-3-thirty-three-percent-into-career-attainment', 'workstream-specific', 'SkyFund S283', '2026-09-23'::date, 'SkyGrant-s285'),
 ('a-control-that-does-nothing-read-the-request-log-first', 'pitfall', 'Dead button: read the request log', 'When a curator says a button does nothing, read the Supabase request log before the handler: no request means the client stopped, a 4xx means the server refused, and a 200 with the change missing means a later whole-config save overwrote it.', 'Sam reported the (D) card''s Designate button did nothing (2026-09-22). jsdom and Chromium replays worked. The Supabase edge logs showed nine 200 PATCHes on cpl_funding_config from 23:37 to 23:39 UTC, the last four his releases, and none after: the click never reached saveShared(). The handler''s reachable early return was an empty selection, which returned silently; #1662 makes it say what it needs. Carryover 2026-09-24: Sam has not yet retried Designate on the (D) card. Note: docs/kb-notes/methodology-a-control-that-does-nothing-read-the-request-log-first.md. Staged by SkyFund S283 (2026-09-23); written by SkyGrant S285 (2026-09-24).', 'When someone reports that a button on one of our pages does nothing, the first place to look is the database''s log of incoming requests, not the page''s code. If no request arrived, the page stopped before sending one; if a request was refused, the log says so; if it succeeded but the change is gone, a later save from another window wrote over it. In this case the button had quietly given up because nothing was selected, and it now says so.', array['debugging','supabase','curation-ui','implementation-funding']::text[], 'docs/kb-notes/methodology-a-control-that-does-nothing-read-the-request-log-first.md', '{}'::text[], 'proposed', null, 'general', 'SkyFund S283', '2026-09-23'::date, 'SkyGrant-s285'),
 ('stored-order-predating-a-priority-is-extended-not-reset', 'pitfall', 'Extend a stored order, never reset it', 'A stored display order written before a priority existed must be extended with the newcomers rather than reset to the natural order, because priorityOrder() once fell back whenever the stored permutation''s length differed from the priority count and would have swapped Sam''s P2 and P3 the day Priority 4 arrived.', 'Both cpl_funding.js priorityOrder() and college_briefing.js applyPriorityOrder() keep a shorter valid permutation and append the newcomers (#1662). The two copies of the rule must stay in step; sharing one is lane item (c). Live 2026-09-24: Scenario 1 stores priorityOrder [0,2,1] over four slots, so the rule is in use. Guard: tests/cpl_funding_career_attainment.test.js 2a and cpl_funding_reorder.test.js C. Staged by SkyFund S283 (2026-09-23); written by SkyGrant S285 (2026-09-24).', 'Sam can arrange the funding priorities in the order he wants, and that order is saved. When a new priority is added, the saved order must simply gain the new item at the end. An earlier version threw the saved order away whenever the counts did not match, which would have silently swapped two of his priorities the day a fourth was added.', array['implementation-funding','college-briefing','priority-order']::text[], 'CPL-Initiative/cpl-project-tracker#1662', '{}'::text[], 'proposed', null, 'workstream-specific', 'SkyFund S283', '2026-09-23'::date, 'SkyGrant-s285'),
 ('funding-review-rulings-2026-09-23', 'decision', 'Funding review sheet rulings, 2026-09-23', 'Sam ruled the 2026-09-23 funding review sheet (mark 3 of 3): hold Priority 4 at 0% until the first CO import, a hold he lifted that evening by funding Career attainment at 33%; CO research defines the career outcome, imported as per-college CPL units masked under 10; and each drill-in is one Baseline line with the CO''s control, then the priority table.', 'Sam, 2026-09-23 14:50Z (''Decisions done''; high-water mark 3 of 3 on https://claude.ai/artifact/9MfbN6jqio8as9mY4LwPB2). (1) Hold: Priority 4 stays at a 0% share until the first Chancellor''s Office import lands; its share and a funding factor of 0.5 are then set together. SUPERSEDED the same evening by Sam himself: ''I want to put the 33% into Career Attainment'', done 19:44 UTC in Scenario 1 with the factor 0.5 at 21:30 UTC (scenario-3-thirty-three-percent-into-career-attainment). (2) CO research defines the career outcome; the import carries, per college, the CPL units of students awarded CPL who reach it, counts under 10 masked before the file is committed; the receiver is funding/career_attainment_import.json read by funding/_build_funding_performance.py (docs/kb-notes/reference-career-attainment-import.md). (3) Each institution''s drill-in is one Baseline line with the CO''s control, then the priority table captioned Current Total and Total Possible; shipped in #1664. Staged by SkyFund S283 (2026-09-23); written by SkyGrant S285 (2026-09-24) with the evening reversal noted.', 'Sam answered three questions about the funding model on 2026-09-23. He first chose to leave the career attainment priority unfunded until the Chancellor''s Office delivers its first measurement, then changed his mind the same evening and gave it a third of the funding. He confirmed that the Chancellor''s Office research team defines what counts as a career outcome, with small counts hidden. And he approved a simpler per-college view: one line of baseline status, then the table of priorities.', array['implementation-funding','career-attainment','edd','decision-sheets','drill-in']::text[], 'https://claude.ai/artifact/9MfbN6jqio8as9mY4LwPB2', array['scenario-3-thirty-three-percent-into-career-attainment']::text[], 'proposed', null, 'workstream-specific', 'Sam Lee (2026-09-23), recorded by SkyFund S283', '2026-09-23'::date, 'SkyGrant-s285')
on conflict (slug) do nothing
returning slug, kind, status;

-- The playbook step 6 log, a SEPARATE statement (a data-modifying CTE cannot see its own rows). Idempotent.
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyGrant-s285', 'create',
       'S285 write of a row staged by ' || case when m.event_date = '2026-09-21' then 'SkyAnvil S281' else 'SkyFund S283' end
       || ' on ' || m.event_date::text || ', re-read against the state on 2026-09-24 (kb/receipts/cpl_memory_2026-09-24_s285.sql)',
       to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyGrant-s285'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
-- Verify (every slug should read creates = 1):
-- select m.slug, count(l.id) filter (where l.action = 'create') as creates from public.cpl_memory m
--   left join public.cpl_memory_log l on l.memory_id = m.id where m.author = 'SkyGrant-s285'
--   group by m.slug order by m.slug;

-- S283 planned this supersede in its 2026-09-23 receipt: a session-sourced row (verified_by = 'session',
-- author 'unknown', id 4cdf0e2e-739e-47b7-a715-f3d43a678c25, status proposed at read time 2026-09-24 00:2x UTC)
-- made false by Sam's 2026-09-22 ruling that the counselor step serves (B) alone. Rule 8 protects human-sourced
-- rows from silent supersession; this one is not human-sourced. Rollback: set status = 'proposed',
-- superseded_by = null where slug = 'counselor-step-is-the-only-campus-measure-for-goal-c'; delete its log row
-- (actor SkyGrant-s285, action supersede).
update public.cpl_memory
   set status = 'superseded', superseded_by = 'priority-2-serves-b-alone-career-attainment-is-priority-4'
 where slug = 'counselor-step-is-the-only-campus-measure-for-goal-c' and status = 'proposed'
returning slug, status, superseded_by;
insert into public.cpl_memory_log (memory_id, actor, action, note, before, after)
select m.id, 'SkyGrant-s285', 'supersede',
       'Superseded by priority-2-serves-b-alone-career-attainment-is-priority-4 (Sam, 2026-09-22); planned in kb/receipts/cpl_memory_2026-09-23_s283.sql, run by S285',
       to_jsonb(m) - 'status' - 'superseded_by' - 'updated_at'
         || jsonb_build_object('status', 'proposed', 'superseded_by', null, 'updated_at', '2026-09-13T23:34:04.80741+00:00'),
       to_jsonb(m)
from public.cpl_memory m
where m.slug = 'counselor-step-is-the-only-campus-measure-for-goal-c' and m.status = 'superseded'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'supersede');

-- ── Checkpoint, 2026-09-24 01:3x UTC: this run's two rows, their log and the verify, as THREE statements in ONE
-- execute_sql call (Sam's SQL budget ruling; a later statement sees an earlier one's rows). Rollback: delete the log
-- rows (actor SkyGrant-s285, event_date 2026-09-24 rows) then the two rows by slug.
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, verified_at, event_date, author)
values
 ('sam-do-not-work-the-approval-swarm-budget-sql-calls-2026-09-24', 'decision', 'Sam: stop working the SQL prompt swarm', 'Sam, 2026-09-24: stop working on the Allow-SQL prompt swarm, because two days of session time changed nothing and the handoff opening line already installs the fix that holds, so the remaining lever is the session''s own discipline of folding SQL into as few execute_sql calls as possible.', 'Verbatim, with two prompts arriving while he typed: ''I''m still getting a swarm of sql approves--been happening the last 10 days--very frustrating.'' Then: ''Don''t try and solve the swarm problem—I wasted 2 days of fable use and not changes helped. Look at the handoff prompt text for the solution that was supposed to solve it. Probably had a dozen or more approve requests this session so far.'' Measured the same session: check_hooks_live.py --fix read 33 allow rules with the execute_sql rule present, every other tool silent, and the LIVE line''s own caveat that this one tool still asks once per call (the 2026-09-20 finding: a per-tool mark upstream of the repo). The dozen prompts were the session''s twelve execute_sql calls plus one list_projects; five calls would have done. The discipline: budget a session''s SQL in prompts before the first call; one statement per purpose; reads folded with CTEs or UNION; a memory write, its log and its verify as three statements in ONE call (they see each other; only a data-modifying CTE does not). The connector''s own per-tool permission page is recorded in docs/reference/approval_prompt_hooks.md as a lever not to be pursued unless Sam asks.', 'Sam has asked us to stop trying to fix the approval prompts that appear every time a session runs a database query. The setup that was meant to fix it is in place and every other tool is quiet; only that one tool still asks each time. What we control is how many times we ask, so sessions now combine their queries into as few calls as possible.', array['approval-prompts','supabase','execute_sql','session-discipline']::text[], 'docs/reference/approval_prompt_hooks.md', array['execute-sql-prompts-by-the-connectors-own-mark-no-local-setting-reaches-it-2026-09-20']::text[], 'verified', 'general', 'Sam Lee (2026-09-24), recorded by SkyGrant S285', now(), '2026-09-24'::date, 'SkyGrant-s285'),
 ('staged-memory-rows-are-re-read-before-they-are-written', 'procedure', 'Re-read staged memory rows before writing', 'A memory receipt staged by an earlier session is re-read row by row against the current state before it is written, so a row that has since become false is written already superseded with superseded_by set, a changed consequence is rewritten with the change named inside detail, and the log note records who staged the row and who wrote it.', 'Worked example 2026-09-24 (kb/receipts/cpl_memory_2026-09-24_s285.sql): fifteen rows from S281 and S283 sat unwritten for three days behind a guard bug. Six changed on re-reading (a calibration rule superseded by Sam''s high-water mark; a reference wired since; a priority renumbered; a zero-share fact already false, written status superseded with superseded_by; a ruling reversed by Sam the same evening; a table field re-read live). Each summary was cut to one sentence under 400 characters (cpl_memory_summary_check) with the long text in detail and plain on every row; verified_by kept the staging session and Sam where he spoke; author named the writer so the log check (creates = 1 per slug) and the rollback find the cohort. The rows insert, the log insert and the verify select can travel as three statements in one execute_sql call: a later statement sees an earlier one''s rows, and only a data-modifying CTE hides its rows from the rest of its own statement.', 'When notes meant for the shared memory table were written down but never saved, and a later session saves them, it first checks each note against what is true today. A note that is no longer true is saved as outdated, a note whose conclusion changed is corrected with the change explained, and the log records both who wrote the note and who saved it.', array['cpl-memory','rule-8','receipts','procedure']::text[], 'kb/receipts/cpl_memory_2026-09-24_s285.sql', array['sql-guard-read-a-quote-in-a-comment-as-a-string']::text[], 'proposed', 'general', 'SkyGrant S285', null, '2026-09-24'::date, 'SkyGrant-s285')
on conflict (slug) do nothing;
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyGrant-s285', 'create', 'S285 checkpoint auto-write (Rule 9 step 10), rows, log and verify in one call', to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyGrant-s285' and m.event_date = '2026-09-24'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
select m.slug, m.status, count(l.id) filter (where l.action = 'create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyGrant-s285' and m.event_date = '2026-09-24'
group by m.slug, m.status order by m.slug;
