-- NAMING NOTE: the four log rows below cite kb/receipts/cpl_memory_2026-09-24_s287.sql, the name this file was
-- written under; another session (SkyMatrix, the EACR tweaks) had taken that name on main the same day, so this
-- copy carries the _skylane suffix. Same SQL, same rollback.
-- S287 (SkyLane) write of the four rows S286 (SkyTally) staged in docs/session_287_handoff.md, 2026-09-24. Rule 8 ingest.
-- S286 ended in an emergency checkpoint (Rule 9a) with the rows staged, not written. Each was re-read against the state on
-- 2026-09-24 before writing: #1677 and #1678 are merged on main, #1679 is the open draft that carries the drill-in columns,
-- and the review sheet's edits store (https://claude.ai/artifact/Ayp39ynE6Yw9cvsvQbH7eu) is the in-place layer row 4 names.
-- All four are Sam's words, so status is verified with him named in verified_by (playbook: Sam's yes corroborates).
-- Summary is one sentence of at most 400 characters; the long text sits in detail; plain on every row. INSERT-only,
-- idempotent on slug. The rows, their log and the verify travel as three statements in ONE execute_sql call (Sam's SQL
-- budget ruling, 2026-09-24).
-- Rollback: delete from cpl_memory_log where actor = 'SkyLane-s287' and action = 'create';
--           delete from cpl_memory where author = 'SkyLane-s287';
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, verified_at, event_date, author)
values
 ('map-partner-agencies-are-outside-the-ccc-funding-model', 'decision', 'MAP partner agencies are outside the funding model', 'Sam, 2026-09-24: MAP partner agencies such as Launch Apprenticeship and Futuro Health are not California community colleges and sit outside the CCC funding model, so the funding feed neither counts nor mentions them.', 'Verbatim, review sheet item 5: ''Launch is an agency partner ... should not be included in the college count or mentioned on the CCC CPL funding model.'' Shipped in #1678: funding/_build_funding_performance.py skips every row whose identity crosswalk entry carries entity_kind "partner" (Launch Apprenticeship, Futuro Health) at the row, like a test college: no college row, no statewide total, no unmatched entry; the run log names what it skipped. On 2026-09-24 that removed 44 eligible units from the statewide pe_u, which no funded priority reads, so no award moved. `unmatched` keeps its job for a CCC name the resolver misses. Guard: tests/cpl_funding_review_sheet_s286.test.js (a mutation disabling the skip fails three checks). Staged by SkyTally S286 (2026-09-24); written by SkyLane S287 the same day.', 'Some organizations in the MAP platform are training partners rather than community colleges. Sam ruled that they do not belong in the funding model at all, so the daily funding feed leaves them out of every count and never names them on the funding page.', array['implementation-funding','college-identity','partners','map-platform']::text[], 'CPL-Initiative/cpl-project-tracker#1678', '{}'::text[], 'verified', 'workstream-specific', 'Sam Lee (2026-09-24), recorded by SkyTally S286', now(), '2026-09-24'::date, 'SkyLane-s287'),
 ('drill-in-columns-outcomes-max-actual-difference-one-table-per-lane', 'decision', 'Drill-in columns and one table per lane', 'Sam, 2026-09-24: the funding drill-in reads Outcomes, Max FTES, Max Funds, Actual FTES, Actual Funds and Difference, as one credit table and one noncredit table so the noncredit figures do not get lost in the shuffle.', 'Verbatim, review sheet items 7.9a and 7.9b: the columns are ''Outcomes; Max FTES; Max Funds; Actual FTES; Actual Funds; Difference'', with one credit table and one noncredit table so ''the NCs [don''t] get lost in the shuffle''. Difference is Max Funds minus Actual Funds, with the FTES gap in its hover; diffMoney() subtracts the coarse public figure on the public page. Carried by draft #1679 (branch claude/funding-lane-tables-card-head) together with the one-line priority card head ''Priority N · (A) Access'' (Sam: ''I like your simplified priority card!''); the noncredit header rides a new --dtl-nc-head token in both HTMLs. The renderer is prioDetailTableHtml(scope) for college and statewide alike; the scope supplies the figures and the renderer never derives them. Staged by SkyTally S286 (2026-09-24); written by SkyLane S287 the same day while #1679 was still in draft.', 'When a reader opens a college on the funding page, the detail table now has six columns: the outcome, the most FTES and funding it could reach, the FTES and funding it has reached, and the gap between them. Credit and noncredit each get their own table so the noncredit numbers stay visible.', array['implementation-funding','drill-in','tables','noncredit']::text[], 'CPL-Initiative/cpl-project-tracker#1679', array['map-partner-agencies-are-outside-the-ccc-funding-model']::text[], 'verified', 'workstream-specific', 'Sam Lee (2026-09-24), recorded by SkyTally S286', now(), '2026-09-24'::date, 'SkyLane-s287'),
 ('house-table-format-first-column-left-the-rest-centered', 'decision', 'House table format: first column left, rest centered', 'Sam, 2026-09-24: the house format for a data table left-justifies the first column and center-justifies every other column, with each header sitting over its own column.', 'Verbatim, review sheet item 7: ''left justify the 1st column and center justify the rest''. Applied to the funding drill-in in #1678 after #1677 had put the headers over their columns (the outer .cplfund-table th and tr.cplfund-detail td rules were reaching the nested cells through descendant combinators, so every header sat 7px right of its figures; three rules at (0,2,1)+ restate the horizontal padding and alignment). Measured in Chromium: every header center equals its column center. Guards: tests/cpl_funding_dtl_align.test.js (a3 expects centered figures) and cpl_funding_review_sheet_s286.test.js. Apply the same rule to any new table a human reads, in COBI or an artifact. Staged by SkyTally S286 (2026-09-24); written by SkyLane S287 the same day.', 'Sam set the standard layout for our tables: the first column, which usually holds names, lines up on the left, and every column of figures is centered under its heading.', array['ui','tables','house-style','implementation-funding']::text[], 'CPL-Initiative/cpl-project-tracker#1678', '{}'::text[], 'verified', 'general', 'Sam Lee (2026-09-24), recorded by SkyTally S286', now(), '2026-09-24'::date, 'SkyLane-s287'),
 ('decision-sheets-revise-text-in-place-the-edits-layer', 'decision', 'Decision sheets: revise text in place', 'Sam, 2026-09-24: on a decision sheet he wants to revise the text of an item inside that item''s own box, so review sheets carry an edits layer that stores each line''s before and after beside the reply chips.', 'Verbatim: ''revise the text in, say, 3.1 in the 3.1 box''. The funding tab review sheet (https://claude.ai/artifact/Ayp39ynE6Yw9cvsvQbH7eu) is the first sheet with the layer: the live tab captured from the live config and numbered N.k, reply chips per item, and in-place line edits stored in the artifact''s `edits` collection as {ref, before, after}. His five timeline edits arrived that way (''Participation Request'' becomes ''Confirmation Deadline''; '' in MAP'' drops from the four disbursement lines) and are applied by him in the tab as stored settings, never by SQL. Tooling: scripts/tab_review_sheet/ (Playwright capture plus the snapshot JSON, then build_sheet.py on kb/_decision_sheet_replies.py); its paths still point at S286''s scratchpad. Mechanics belong in docs/reference/decision_sheets.md, which S286 did not get to refresh. Staged by SkyTally S286 (2026-09-24); written by SkyLane S287 the same day.', 'When Sam reviews a page item by item, he wants to correct wording right where the item is shown rather than describing the change elsewhere. Review sheets now let him edit a line in place, and the sheet keeps both the original and his version.', array['decision-sheets','artifacts','review-sheet','implementation-funding']::text[], 'scripts/tab_review_sheet/', array['decision-sheet-replies-are-keyed-to-card-position','opt-out-sheets-need-verdict-provenance']::text[], 'verified', 'general', 'Sam Lee (2026-09-24), recorded by SkyTally S286', now(), '2026-09-24'::date, 'SkyLane-s287')
on conflict (slug) do nothing;
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyLane-s287', 'create',
       'S287 write of a row staged by SkyTally S286 in docs/session_287_handoff.md on 2026-09-24, re-read against the state the same day (kb/receipts/cpl_memory_2026-09-24_s287.sql)',
       to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyLane-s287'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
select m.slug, m.status, count(l.id) filter (where l.action = 'create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyLane-s287'
group by m.slug, m.status order by m.slug;

-- ── Checkpoint, 2026-09-24 (SkyLane S287): two rows, their log and the verify as THREE statements in ONE
-- execute_sql call (Sam's SQL budget ruling). Rollback: delete the log rows (actor SkyLane-s287, these two slugs),
-- then the two rows by slug.
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, event_date, author)
values
 ('a-memory-bound-suite-scales-across-machines-not-workers', 'fact', 'Sharded CI: the suite scales across machines', 'Measured 2026-09-24: cpl_funding_* is 56 files and 87% of the jsdom suite''s 3,592 s of serial time and tests/run.js already ran at the 4-wide memory cap of one 16 GB runner, so js-tests.yml now runs four shards on four runners fanned into one check still named test, which reported in 7 minutes where the same tree took 20.', 'Sam, 2026-09-24: ''would it make sense to chunk our npm tests for git--they''re taking 20 mins + each now ... It''s probably suite growth.'' The npm test step read 18 min on run 36013462480 against 9-10 a month earlier, with a 9-minute run on 2026-09-23 between two 18-minute ones (runner variance on top of growth). Every file timed on a 4-cpu / 16 GB box at 4-wide: 362 files, 3,592 s serial, 898 s wall; cpl_funding_* 56 files and 3,111 s (28 files, 967 s, 78% on 2026-08-28); slowest cpl_funding_render 222 s. The wall time was serial / 4 to the second, so no scheduling was left to win and more machines was the lever. PR #1682: tests/run.js --shard i/N over the alphabetical list (each shard holds 14 funding files; four shards carry 777 / 1,000 / 1,021 / 794 s); js-tests.yml runs gate -> suite (matrix of 4) beside lints -> test, the fan-in that keeps the name the merge doctrine polls, on !cancelled() reading every need''s result, with the E gate''s if: on the shard jobs; an empty shard exits 1 and --update-floor on a shard is refused. First sharded run: gate 24 s, lints 1:47, shards 3:31 to 6:05, test at 7:16 after the push. Note: docs/kb-notes/methodology-a-memory-bound-suite-scales-across-machines-not-workers.md. Watch the family''s cost: the next 20 funding files cost more than the next 200 elsewhere.', 'Our automated test run had grown to twenty minutes because one family of tests, the funding tab''s, takes most of the time, and one machine cannot run more of them at once without running out of memory. The run is now split across four machines and finishes in about seven minutes. The check the merge rule watches keeps its name, so nothing else changed.', array['ci','testing','test-infra','github-actions','methodology']::text[], 'CPL-Initiative/cpl-project-tracker#1682', '{}'::text[], 'proposed', 'general', 'SkyLane S287', '2026-09-24'::date, 'SkyLane-s287'),
 ('parallel-sessions-take-the-next-free-handoff-number-and-name-the-sibling', 'procedure', 'Parallel sessions: next free handoff number, name the sibling', 'When two sessions start from the same handoff on one day they both carry its number, so each writes its handoff under the next FREE number on main, says in its opener which sibling ran beside it and what to read the sibling for, and leaves the sibling''s lane files alone; the docs auditor treats same-day handoffs as siblings.', 'Measured 2026-09-24: S286''s emergency checkpoint named the next session 287 (SkyLane); the EACR session that ran beside it also called itself S287 (SkyMatrix) and wrote docs/session_288_handoff.md first, so SkyLane''s checkpoint wrote 289 and pointed at 288 for the EACR carryover. The receipt name kb/receipts/cpl_memory_2026-09-24_s287.sql was taken the same way; the second file carries a _skylane suffix and a header saying why its log rows cite the shorter name. Rule 9''s ''highest-numbered handoff is authoritative'' still holds: the newest file carries every pointer a next session needs, including the sibling''s. The shared files two sessions collide on are tests/check_floor.json and kb/dependency_map.json: merge main and regenerate, never pick sides.', 'Sam often runs two Claude sessions at once, and both may think they are the same session number. Each one now writes its notes under the next unused number, says which other session was running beside it, and points to that session''s notes for the work it does not cover.', array['session-discipline','handoffs','rule-9','parallel-sessions']::text[], 'docs/session_289_handoff.md', '{}'::text[], 'proposed', 'general', 'SkyLane S287', '2026-09-24'::date, 'SkyLane-s287')
on conflict (slug) do nothing;
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyLane-s287', 'create', 'S287 SkyLane checkpoint auto-write (Rule 9 step 10), rows, log and verify in one call', to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyLane-s287' and m.slug in ('a-memory-bound-suite-scales-across-machines-not-workers', 'parallel-sessions-take-the-next-free-handoff-number-and-name-the-sibling')
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
select m.slug, m.status, count(l.id) filter (where l.action = 'create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyLane-s287'
group by m.slug, m.status order by m.slug;

-- ── 2026-09-24 evening (SkyLane S287): two rows, their log and the verify as THREE statements in ONE execute_sql
-- call (Sam's SQL budget ruling). Row 1 is the MAP load refusal and the widened student-key bound (receipt
-- kb/receipts/map_student_credit_key_range_2026-09-24_s287.sql); row 2 is Sam's correction that an interrupted tool
-- call is not a decline. Rollback: the log rows (actor SkyLane-s287, these two slugs), then the two rows by slug.
insert into public.cpl_memory (slug, kind, title, summary, detail, plain, tags, source, related, status, scope, verified_by, event_date, author)
values
 ('map-student-credit-key-range-is-a-check-constraint-widened-to-250k', 'fact', 'map_student_credit key range: a check constraint, now 250,000', 'The live table map_student_credit carries a check constraint, map_student_credit_key_range_ck, on student_key (1..250,000 since 2026-09-24, 1..50,000 before), created with the table on 2026-08-10 and recorded in no repo file; the 2026-09-24 scheduled load was refused by it (SQLSTATE 23514, no G number) when the pull carried 50,027 students.', 'Run 36037739222 (18:01 UTC): PROMOTION REFUSED (HTTP 400), 23514, new row for relation map_student_credit violates check constraint map_student_credit_key_range_ck; the whole transaction rolled back and live kept the 2026-09-23 pull (634,331 rows, 49,965 students). The loader assigns a dense surrogate 1..N by sorted hash, so the 27 students past 50,000 (338 rows) were the first to cross the cap. The bound is the static half of G5''s privacy tripwire (a MAP identifier reads in the millions; a per-row keying of 635,527 rows would also cross it), so it was widened to 250,000, Vision 2030''s Goal 1 student target, by migration widen_map_student_credit_key_range_to_250k (receipt kb/receipts/map_student_credit_key_range_2026-09-24_s287.sql: before, after, rollback); G5''s density check (max = count distinct) is unchanged. The re-dispatched load (run 36047213316) promoted at 19:21 UTC: 224,230 cr_unit rows, 635,527 student rows, 50,027 students, max key 50,027, all five rebuilt tables and their #1665 grants intact (counts 173/113/506/280/232). The runbook docs/map_custom_report_load.md names the bound under G5; the loader no longer prints the baked ''live holds 42,346'' bracket.', 'The nightly load of MAP''s student-level credit data failed because the database table refuses a student number above 50,000 and the data now holds 50,027 students. The limit exists to catch a real MAP identifier reaching the database by mistake, which would look like a number in the millions. It is now 250,000, and the load ran again and succeeded.', array['map-custom-reports','supabase','privacy','pipeline','data-loads']::text[], 'kb/receipts/map_student_credit_key_range_2026-09-24_s287.sql; runs 36037739222 and 36047213316', '{}'::text[], 'proposed', 'general', 'SkyLane S287', '2026-09-24'::date, 'SkyLane-s287'),
 ('an-interrupted-tool-call-is-not-a-decline', 'procedure', 'An interrupted tool call is not a decline', 'Sam, 2026-09-24: ''Never declined anything...I''''ve seen this assertion before'': when a new message arrives while a tool call is waiting on approval, the harness closes the prompt and the tool result reads ''The user doesn''''t want to proceed with this tool use''; that text is the interruption, not a decision, so the session re-issues the step and never reports that Sam declined.', 'Seen twice in S287. (1) subscribe_pr_activity: ''Tool call not completed: an approval request was still unanswered when the message that follows arrived and was closed, so the action awaiting approval did not run. Nobody refused it, so this is not the user''''s decision; ask again if it is still needed.'' (2) A commit-and-push Bash call and a send_later check-in, in flight when his side question arrived: ''The user doesn''''t want to proceed with this tool use. The tool use was rejected ... STOP what you are doing and wait for the user to tell you how to proceed.'' The session reported (2) as ''the interrupt declined two steps'' and held for a go; Sam: he had declined nothing and had seen the same claim before. Rule: after any message that lands mid-call, treat the closed calls as interrupted, handle the message, then re-issue them (or ask in one line if the step itself is doubtful), and say what was interrupted, never who decided. A real refusal is the person saying so in their own words.', 'If Sam types while the session is in the middle of a step that needs his approval, the system cancels that step and hands the session a message that sounds like Sam refused. He did not. The session should redo the step after answering him, and must not tell him he declined something.', array['claude-code','session-practice','working-with-claude-code','permissions']::text[], 'Sam, 2026-09-24 (S287 SkyLane session)', '{}'::text[], 'verified', 'general', 'Sam', '2026-09-24'::date, 'SkyLane-s287')
on conflict (slug) do nothing;
insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyLane-s287', 'create', 'S287 SkyLane write on 2026-09-24 after the MAP load refusal and Sam''s correction; rows, log and verify in one call (kb/receipts/cpl_memory_2026-09-24_s287_skylane.sql)', to_jsonb(m)
from public.cpl_memory m
where m.author = 'SkyLane-s287' and m.slug in ('map-student-credit-key-range-is-a-check-constraint-widened-to-250k', 'an-interrupted-tool-call-is-not-a-decline')
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');
select m.slug, m.status, count(l.id) filter (where l.action = 'create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyLane-s287'
group by m.slug, m.status order by m.slug;
