-- S334 (SkyAnchor), checkpoint 2026-10-05: record shape 3 built, a verdict held to its reading, the PAGE_JS escape pitfall.
-- Rollback: supersede each row by slug under actor 'SkyAnchor-s334-rollback'.
insert into public.cpl_memory (slug, title, kind, summary, detail, plain, tags, affects, source, author, event_date, status)
values
('record-shape-3-outcomes-as-printed-2026-10-05', 'Record shape 3 keeps program outcomes as printed: 19 of 20 pilot records carry them', 'milestone', 'Sam''s sheet 33 card 4 is built: extraction v4 keeps program and course outcomes as printed, and the scorer fails a reworded or empty one. 19 of 20 pilot records carry outcomes (1 to 11 each). The live rows wait on open-asks sheet 41 card 1.', 'Runs 37345734457 (20 of 20, $1.31) and 37350789203 (Mt. San Antonio, 4 of 4, $0.26). Receipt for the live write: kb/receipts/program_requirement_records_outcomes_2026-10-05.sql (guarded by each row''s md5 before outcomes; all 20 read before on 2026-10-05). PRs #1870, #1871. Miramar prints "Learning Outcome(s):", which S327''s 13-of-20 count missed.', 'The program records now hold each program''s learning outcomes word for word from its catalog, for 19 of the 20 pilot programs; the live copy waits on Sam''s go.', array['program-requirements-harvest','outcomes','record-shape','decision-sheet'], array['kb/program_requirements_pilot/records','program_requirement_records','chatbox/supabase/functions/program-requirements-extract'], 'S334 (#1870, #1871)', 'SkyAnchor-s334', '2026-10-05', 'proposed'),
('verdict-held-to-requirements-fingerprint-2026-10-05', 'A person''s verdict on a harvested record holds only while its requirements fingerprint matches; a rerun adds only machine-proved fields', 'procedure', 'reviewed_readings.json fingerprints the requirements each of Sam''s 20 verdicts covers; the loader counts a verdict only while it matches. The filer keeps a read record''s requirements and takes only outcomes proved word for word. A rerun relabeled blocks on 6 of 20.', 'KB note docs/kb-notes/methodology-a-verdict-covers-the-reading-it-saw.md. The display build stayed at 799bfb9a7dbf because the display depends only on the requirements.', 'When a person has approved a record, a later automated run can add proven fields to it but cannot quietly replace what they approved.', array['program-requirements-harvest','human-review','provenance'], array['kb/_program_requirements_load.py','kb/_program_requirements_file.py'], 'S334 (#1870)', 'SkyAnchor-s334', '2026-10-05', 'proposed'),
('page-js-python-escape-pitfall-2026-10-05', 'An escape in PAGE_JS''s Python source becomes a real character in the browser: run 9''s page script threw on every page', 'pitfall', 'PAGE_JS sits in a non-raw Python string, so an escape written for JavaScript reaches the browser as a real newline or tab. A newline inside a regex broke the script and capture run 9 fell back to plain text. Double the escapes; the guard runs node --check on PAGE_JS.', 'Found S334 (#1871). Also: innerText of a hidden element returns raw textContent in Chromium, so a hidden panel is read leaf by leaf.', 'A small typing detail in the reader code broke a whole capture run; a test now catches it before any college page is read.', array['program-requirements-harvest','capture','pitfall'], array['kb/_program_requirements_pilot.py'], 'S334 (#1871)', 'SkyAnchor-s334', '2026-10-05', 'proposed')
on conflict (slug) do nothing;

insert into public.cpl_memory_log (memory_id, actor, action, note, after)
select m.id, 'SkyAnchor-s334', 'create', 'checkpoint auto-write (S334)', to_jsonb(m)
from public.cpl_memory m where m.author = 'SkyAnchor-s334'
  and not exists (select 1 from public.cpl_memory_log l where l.memory_id = m.id and l.action = 'create');

select m.slug, m.status, count(l.id) filter (where l.action='create') as creates
from public.cpl_memory m left join public.cpl_memory_log l on l.memory_id = m.id
where m.author = 'SkyAnchor-s334' group by m.slug, m.status order by m.slug;
