-- cr_reference_decisions: Sam Lee's 51 verdicts (41 fold, 10 keep after his same-anchor review) from the decision sheet of 2026-09-20.
-- INSERT-only, ON CONFLICT DO NOTHING; the table held 0 rows at write time. Rollback: delete from cr_reference_decisions where updated_by = 'cr-reference-s280@bot';
insert into cr_reference_decisions (group_key, decision, canonical, members, excluded, note, updated_by, updated_at)
select v.k, 'confirmed', v.c, v.m, '[]'::jsonb, v.n, 'cr-reference-s280@bot', now() from (values
('child growth development','CDEV 100 — Child Growth and Development','["3 hours in Child Growth and Development","3 hours in CHILD GROWTH AND DEVELOPMENT","3 hours in Child Growth and Development (DS1)","3 hours in Child Development"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 7: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('criminal investigation','AJ 140 — Criminal Investigation','["3 hours in Criminal Investigation","3.0 hours in Criminal Investigation","3 hours in CRIMINAL INVESTIGATION","3 hours in Criminal Investigations"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 3: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('elementary spanish i','SPAN 100 — Elementary Spanish I','["4 hours in Elementary Spanish I","5 hours in Elementary Spanish I","5 hours in BEGINNING SPANISH I","5 hours in Spanish 1"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 18, 26: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('elementary spanish ii','SPAN 110 — Elementary Spanish II','["4 hours in Elementary Spanish II","5 hours in Elementary Spanish II","5 hours in Spanish 2","5 hours in BEGINNING SPANISH II","5 hours in Elementary Spanish 2"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 19, 28, 32: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('environmental science','ENVS 100 — Introduction to Environmental Science','["3 hours in Environmental Science","4 hours in Environmental Science","3 hours in Introduction to Environmental Science"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 20: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('fire protection systems','FIRE 120 X — Fire Protection Systems','["3 hours in Fire Protection Systems","3 hours in Fire Protection Equipment and Systems"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 25: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('first aid cpr aed','KIN 101 — First Aid, CPR and AED','["3 hours in First Aid, CPR and AED","0.5 hours in First Aid, CPR and AED","3 hours in Standard First Aid/CPR/AED","3 hours in Community First Aid & Safety"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 5, 37: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('fundamentals music','MUS 110 — Music Fundamentals','["4 hours in Fundamentals of Music","3 hours in Fundamentals of Music","3 hours in Music Fundamentals"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 24: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('intermediate spanish i','SPAN 200 — Intermediate Spanish I','["4 hours in Intermediate Spanish I","5 hours in Intermediate Spanish I","5 hours in Spanish 3"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 51: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction administration justice','AJ 110 — Introduction to Criminal Justice','["3 hours in Intro to Administration of Justice","3 hours in Introduction to Administration of Justice","3.0 hours in Introduction to the Administration of Justice","3 hours in INTRODUCTION TO ADMINISTRATION OF JUSTICE","3 hours in Introduction to the Administration of Justice","3 hours in Introduction to Criminal Justice","3 hours in Introduction to the Criminal Justice System","3 hours in Introduction to Criminology"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 10, 21, 49: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction biotechnology','BIOT 101 B X — Introductory Biotechnology with Laboratory','["3 hours in Introduction to Biotechnology","4 hours in Introduction to Biotechnology","1 hour in Introductory Biotech Lab"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 48: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction chemistry','CHEM 101 — Introduction to Chemistry','["4 hours in Introduction to Chemistry","5 hours in Introduction to Chemistry","4 hours in Introductory General Chemistry","4 hours in Introductory College Chemistry","4 hours in FUNDAMENTAL CHEMISTRY","5 hours in Introductory Chemistry"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 12, 13, 16, 23: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction hospitality management','HOSP 100 — Introduction to Hospitality Management','["3 hours in INTRODUCTION TO HOSPITALITY MANAGEMENT","3 hours in Introduction to Hospitality Management","3 hours in Introduction to Hospitality"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 14: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction physics','PHYS 100 S — Algebra/Trigonometry-Based Physics: AB','["3 hours in INTRO PHYSICS","5 hours in INTRODUCTION TO PHYSICS","3 hours in Introduction To Physics","4 hours in Algebra Based Physics: Mechanics","4 hours in Algebra Based Physics: Electricity and Magnetism"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 42, 50: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction psychology','PSY 110 — Introductory Psychology','["3 hours in Introduction to Psychology","3 hours in INTRODUCTION TO PSYCHOLOGY","3 hours in Introductory Psychology"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 1: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction statistics','MATH 110 — Introduction to Statistics','["4 hours in Introduction to Statistics","3 hours in INTRODUCTION TO STATISTICS","3 hours in Introduction to Statistics","4 hours in Elementary Statistics","4 hours in Introduction to Probability and Statistics","3 hours in Business Statistics"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 27, 35, 46: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('juvenile law procedures','AJ 220 — Juvenile Procedures','["3 hours in Juvenile Law and Procedures","3.0 hours in Juvenile Law and Procedures","3 hours in Juvenile Justice Procedures","3 hours in Juvenile Procedures","3 hours in Juvenile Delinquency"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 22, 38, 43: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('networking fundamentals','ITIS 150 — Computer Network Fundamentals','["3 hours in Networking Fundamentals","3 hours in Introduction to Computer Networks"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 15: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('programming concepts methodology i','COMP 122 — Programming Concepts and Methodology I','["3 hours in Programming Concepts and Methodology I","3 hours in Programming Concepts and Methodology I (C++)","3 hours in Programming Concepts and Methodology 1","3 hours in Programming Concepts","3 hours in Problem Solving and Programming 1","3 hours in C++ Programming I"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 2, 9, 29, 45: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('world history since 1500','HIST 160 — World History since 1500','["3 hours in WORLD HISTORY SINCE 1500","3 hours in World History Since 1500","3 hours in World History since 1500","3 hours in World History from 1500 to Present","3 hours in World Civilization From the 16th Century","3 hours in World History 2","3 hours in World Civilizations II","3 hours in History of World Civilizations - II"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, items 4, 6, 8, 11, 17: fold into the published line. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('financial accounting i','ACCT 110 — Financial Accounting','["5 hours in Financial Accounting I"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 30: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('juvenile justice system','AJ 220 — Juvenile Procedures','["3 hours in The Juvenile Justice System"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 31: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction correctional administration','AJ 200 — Introduction to Corrections','["3 hours in Introduction to Correctional Administration"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 33: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('introduction evidence','AJ 124 — Legal Aspects of Evidence','["3 hours in Introduction to Evidence"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 34: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('environmental conservation','ENVS 100 — Introduction to Environmental Science','["3 hours in Environmental Conservation"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 36: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('principles investigation','AJ 140 — Criminal Investigation','["3 hours in Principles of Investigation"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 39: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('suspension steering alignment','AUTO 140 X — Automotive Suspension and Steering Systems','["3 hours in Suspension, Steering, and Alignment"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 40: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('principles composition i','ENGL 100 — College Composition','["4 hours in Principles of Composition I"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 41: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('constitutional criminal procedure','AJ 122 — Criminal Court Process','["3 hours in Constitutional Criminal Procedure"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 44: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json'),
('emergency medical response cpr pro healthcare provider','KIN 101 — First Aid, CPR and AED','["3 hours in Emergency Medical Response; CPR PRO/Healthcare Provider"]'::jsonb,'Sam Lee, 2026-09-20, decision sheet Jev on the CR Reference, item 47: keep separate. Receipt kb/receipts/cr_reference_decisions_2026-09-20_s280.json')
) as v(k, c, m, n)
on conflict (group_key) do nothing;
