-- S339 SkyReel, 2026-10-06: Santa Monica College's first procedure record, through program_source_procedure_set
-- (service role, guarded md5 'none'). Handoff 338: "Write one ... that names the full-catalog PDF ... This is
-- reversible from the registry's history trigger, so go with it and put a Proceeded card on the next sheet."
-- Applied 2026-10-06 22:57:19Z: was_md5 none -> md5 060d7b667c3b8a0694c670d97ab0683e (read back).
-- Rollback: program_source_registry_history holds the before-row (procedure null); restore it with
--   update program_source_registry set procedure = null, procedure_by = null, procedure_at = null
--    where college = 'Santa Monica College' and md5(procedure::text) = '060d7b667c3b8a0694c670d97ab0683e';
select public.program_source_procedure_set('Santa Monica College', '{"v": 1, "college": "Santa Monica College", "catalog": {"start": "https://catalog.smc.edu/current/index.php", "follow": "Download the Full Catalog", "format": "pdf", "why": "The online catalog links no page for Barbering A.S. 43767 on any host: capture run 37488858548 followed Academic and Career Paths to SMC Degrees and Certificates and printed every link naming the program (title_links), none on five pages. The front page offers the whole 2026-27 catalog as one PDF."}, "reader": "kb/_program_requirements_pilot.py (robots.txt first, the census''s delay and user agent); a procedure''s catalog step opens the start page, follows the named link and reads the PDF (pypdf, then pdfminer)", "hosts": [{"host": "catalog.smc.edu", "access": "open", "platform": "custom_html", "note": "The 2026-27 catalog (current/index.php). Its hub path (Academic and Career Paths, then SMC Degrees and Certificates) names no program page for Barbering A.S. 43767 (run 37488858548). The front page links the full catalog as one PDF: Download the Full Catalog."}, {"host": "www.smc.edu", "access": "open", "platform": "custom_html", "note": "The college''s own pages. Program Maps (/academics/classes/program-maps.php) prints term-by-term maps; run 37372136739 read them into the sequence record for Barbering A.S. 43767 (kb/program_requirements_pilot/sequences/). The page timed out once in a morning probe and answered later (run 37209313523)."}], "steps": [{"run": "37209313523", "date": "2026-10-04", "plan": "the registry-aware sequence probe", "found": "Program Maps answers after a morning timeout; filed as an open sequence source."}, {"run": "37372136739", "date": "2026-10-05", "plan": "kb/_program_map_parse.py", "found": "The Barbering A.S. map: 24 of 25 listed courses placed by term; every COSM course in year one carries CPL through the Barbering License exhibit."}, {"run": "37488858548", "date": "2026-10-06", "plan": "capture, sample maps (hub path)", "found": "Academic and Career Paths leads to SMC Degrees and Certificates; no page on that path links the Barbering A.S. on any host."}], "answers": [], "open": [{"question": "Barbering A.S. 43767''s requirements as the 2026-27 catalog prints them", "next": "Capture with --sample maps: the catalog step reads the full-catalog PDF, then extraction and the scorer."}], "nuances": ["The online catalog''s hub pages do not link every program; the full-catalog PDF prints them all.", "Santa Monica''s program maps live on www.smc.edu, apart from the catalog host."], "requests": [], "workarounds": [{"for": "A program the online catalog never links", "tried": "Link-following from the front page and the hub path, with every link naming the program printed (run 37488858548)", "result": "nothing to follow; the procedure reads the full-catalog PDF instead (S339)"}], "request_ready": false}'::jsonb, 'S339 SkyReel, 2026-10-06 (handoff 338: go with it)', 'none') as result;
-- Read back
select college, procedure_by, procedure_at, md5(procedure::text) from program_source_registry where college = 'Santa Monica College';
