insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at)
values
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 910', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 911', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 912', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 913', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 914', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 915', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 916', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — FA/C', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ceiling and Soffit Finishing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Chef Ann Foundation Pre-Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Electrical Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Floor Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Roof Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Concealed/Glue-Up/Staple-Up Ceiling Systems', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Concrete Slabs and Footings', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Construction Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Construction Craft Laborer Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Designer and Specialty Trims', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Door and Door Frames — Layout and Frame', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Doors and Door Hardware', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Drywall and Acoustical Ceilings', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Drywall Applications — Production Drywall Hanging', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Drywall Installation and Finish Trims', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — Orientation', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC100', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC200', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC300', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC400', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC500', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC600', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC700', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC800', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Exit and Electrical Security Devices', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Exterior Finish Details', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Fire Fighter Paramedic Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Fire Officer Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Firefighter EMT Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Firefighter Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Firestop and Fireproofing Procedures', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Foundations and Flatwork (Carpentry)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Framing Ceilings and Soffits', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Framing Curves and Arches (Carpentry)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Framing Suspended Ceilings (Carpentry)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Freeform Lathing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Gang Forms and Columns', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Hand and Power Tools Safety', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Hand Tools Safety Orientation', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Heavy/Medium Duty Truck Technology Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 1', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 2', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 3', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 4', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 5', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 110', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 111', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 120', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 121', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 130', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 131', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 140', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 141', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 150', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 151', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H01', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H07/H47/H75/H77', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H08/H97', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H15', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H20', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H25', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H28', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H30', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H36', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H40', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H45/B87', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H52', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H54', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H62/H18/H95', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H65/H70', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — Saturday Classes', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Cranes', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Detailing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — General Rigging', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Ironworker History', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Lead Hazard', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Mixed Base', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Post Tensioning I', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Post Tensioning II', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing II', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 1', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 2', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 3', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 4', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 5', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 6', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 7', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 8', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 1', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 2', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 3', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 4', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 5', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 6', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 7', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 8', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Welding I', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Welding II', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Acoustical Installer', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Drywall Finisher', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Drywall/Lather', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Drywall/Lather (Interior Systems)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Insulator', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Millwrighting', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Pile Driver', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Plastering', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Tilt-Up', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::LiUNA Laborers'' Construction Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Marine Technology Apprenticeship Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Metal Framing Advanced', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Metal Pan and Security Systems', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Molding and Trims', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Multi-Craft Core Curriculum (MC3) Pre-Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Nursing Apprenticeship Program', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Panelized Roofing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Paramedic Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Pharmacy Technology Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Print Reading — Specifications', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Residential Electrical Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Roof Framing Advanced', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Social and Human Services Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Sound and Communication Systems Installer Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Sprinkler Fitter Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Stairs Advanced', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 100', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 101', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 110', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 111', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 120', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 121', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 130', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 131', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 140', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 141', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 150', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 151', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 100', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 101', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 110', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 111', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 120', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 121', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 130', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 131', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 140', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 141', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now())
on conflict (course_id, field) do nothing;
