insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at)
values
('_CREDENTIAL_REVIEW::Abutments', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Acoustical Ceilings', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Acoustical Soffits', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Acoustical Ceiling Installation', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Acoustical Ceiling Layout', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Automatic Finishing Tools', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Commercial Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Apprenticeship Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Automotive Technology Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Basic Hand Finishing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Basic Lathing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Basic Metal Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Basic Roof Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Basic Stairs', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Basic Wall Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Beam and Deck Forming', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Bridge Construction', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Bridge Falsework', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Cabinet Installation', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Cabinet Millwork and Assembly', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Acoustical Installer', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Cabinetmaker', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 001', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 002', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 004', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 005', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 006', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 007', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 008', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 009', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 010', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 011', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 012', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 013', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 014', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 015', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 016', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 017', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 018', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 019', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 020', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 101', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 102', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 103', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 104', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 105', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 106', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 107', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 108', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 109', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 110', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 111', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 112', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 113', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 114', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Carpenter', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Drywall Applicator', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Drywall Finisher', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Drywall/Lather', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Hardwood Floor Layer', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Insulator', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Millwright', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Modular Installer', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Pile Driver', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Scaffold Erector', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Shingler', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Tilt-Up', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 115', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 116', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 117', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1201', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1202', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1203', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1204', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1205', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1206', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1207', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1208', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 278', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 279', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 280', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 281', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 282', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 283', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 284', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 285', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 286', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 287', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 288', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 289', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 290', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 291', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 292', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 293', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 294', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 302', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 305', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 306', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 307', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 308', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 309', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 310', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 311', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 312', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 313', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 314', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 315', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 316', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 404', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 405', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 503', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 504', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 505', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 506', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 507', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 508', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 605', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 608', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 701', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 702', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 703', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 704', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 705', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 706', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 707', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 708', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 709', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 710', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 711', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 712', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 713', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 714', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 715', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 856', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 857', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 858', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 859', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 860', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 861', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 862', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 863', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 864', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 865', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 866', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 867', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 868', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 869', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 870', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 871', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 872', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 901', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 902', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 903', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 904', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 905', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 906', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 907', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 908', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 909', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 910', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 911', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 912', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 913', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 914', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 915', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 916', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — FA/C', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ceiling and Soffit Finishing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Chef Ann Foundation Pre-Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Electrical Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Floor Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Roof Framing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Concealed/Glue-Up/Staple-Up Ceiling Systems', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Concrete Slabs and Footings', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Construction Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Construction Craft Laborer Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Designer and Specialty Trims', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Door and Door Frames — Layout and Frame', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Doors and Door Hardware', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Drywall and Acoustical Ceilings', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Drywall Applications — Production Drywall Hanging', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Drywall Installation and Finish Trims', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — Orientation', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC100', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC200', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC300', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC400', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC500', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC600', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC700', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — RC800', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Elevator Constructor Apprenticeship — Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Exit and Electrical Security Devices', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Exterior Finish Details', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Fire Fighter Paramedic Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Fire Officer Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Firefighter EMT Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Firefighter Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Firestop and Fireproofing Procedures', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Foundations and Flatwork (Carpentry)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Framing Ceilings and Soffits', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Framing Curves and Arches (Carpentry)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Framing Suspended Ceilings (Carpentry)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Freeform Lathing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Gang Forms and Columns', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Hand and Power Tools Safety', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Hand Tools Safety Orientation', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Heavy/Medium Duty Truck Technology Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 1', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 2', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 3', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 4', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW Electrician Apprenticeship — Year 5', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 110', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 111', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 120', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 121', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 130', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 131', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 140', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 141', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 150', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — ELECT 151', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::IBEW/NECA Electrical Apprenticeship — Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H01', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H07/H47/H75/H77', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H08/H97', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H15', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H20', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H25', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H28', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H30', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H36', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H40', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H45/B87', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H52', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H54', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H62/H18/H95', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — H65/H70', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — Saturday Classes', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Iron Workers Apprenticeship — Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Cranes', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Detailing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — General Rigging', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Ironworker History', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Lead Hazard', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Mixed Base', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Post Tensioning I', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Post Tensioning II', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing II', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 1', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 2', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 3', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 4', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 5', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 6', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 7', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Reinforcing, Period 8', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 1', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 2', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 3', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 4', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 5', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 6', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 7', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Structural, Period 8', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Welding I', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Ironworker Apprenticeship — Welding II', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Acoustical Installer', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Drywall Finisher', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Drywall/Lather', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Drywall/Lather (Interior Systems)', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Insulator', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Millwrighting', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Pile Driver', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Plastering', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Journeyman Certificate- Apprenticeship Carpentry, Tilt-Up', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::LiUNA Laborers'' Construction Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Marine Technology Apprenticeship Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Metal Framing Advanced', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Metal Pan and Security Systems', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Molding and Trims', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Multi-Craft Core Curriculum (MC3) Pre-Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Nursing Apprenticeship Program', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Panelized Roofing', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Paramedic Journeyperson Certificate', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Pharmacy Technology Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Print Reading — Specifications', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Residential Electrical Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Roof Framing Advanced', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Social and Human Services Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Sound and Communication Systems Installer Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Sprinkler Fitter Apprenticeship', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::Stairs Advanced', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship Work Experience', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 100', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 101', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 110', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 111', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 120', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 121', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 130', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 131', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 140', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 141', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 150', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SHME 151', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 100', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 101', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 110', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 111', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 120', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 121', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 130', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 131', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 140', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now()),
('_CREDENTIAL_REVIEW::UA Local 342 Plumbers/Pipefitters Apprenticeship — SMTEC 141', 'cpl_type_override', 'Apprenticeship', 'apprentice-tag-s109@bot', now())
on conflict (course_id, field) do nothing;
