/*
 * COBI — Card action opener  (window.CPL_CARD_ACTIONS)
 *
 * The Activity / Project cards (Activities & Projects tab + Dashboard activity
 * metrics) carry 📝 Update and 📣 Nudge affordances emitted by the generator as
 *   <a href="#raci" class="update-link" onclick="…setItem('cpl_update_focus','project:5.1')…">
 * Historically those navigated to the Team & RACI tab, where raci.js read the
 * stashed key and opened the composer / nudge. Sam (2026-06-29): "none of this
 * should direct the user to RACI, rather to the Activity and Project tab."
 *
 * This tiny, globally-loaded module makes the popup open RIGHT THERE instead:
 *   • it intercepts clicks on the card .update-link / .nudge-link affordances,
 *     cancels the #raci navigation, lazy-loads raci.js, and opens the popup in
 *     place via window.CPL_RACI_TAB.openCardUpdate / openCardNudge;
 *   • it consumes the nudge-email deep-link (?update=<key> / ?nudge=<key>) on ANY
 *     tab at boot, so an emailed link opens the composer wherever it lands (the
 *     email now points at #activities-projects).
 * The composer carries its own team-phrase unlock box, so the user can edit
 * without leaving the tab.
 *
 * STATIC asset — NOT regenerated by excel_to_dashboard.py; no writes, no auth of
 * its own (raci.js owns the Supabase write + the phrase gate). Loaded after
 * tabs.js (it uses CPL_TABS.loadScript). Mirrored in BOTH HTMLs (Rule 4).
 */
(function () {
  "use strict";

  // The card affordances whose clicks we open in place (and the kind each maps to).
  var UPDATE_SEL = "a.update-link, a.act-update-link";
  var NUDGE_SEL = "a.nudge-link, a.act-nudge-link";

  // The item key (`activity:N` | `project:<id>`) lives in the link's inline
  // onclick — read it from there (deterministic, independent of event order)
  // with the sessionStorage the onclick sets as a fallback.
  function keyFromLink(a, kind) {
    var oc = (a && a.getAttribute && a.getAttribute("onclick")) || "";
    var m = oc.match(/cpl_(?:update|nudge)_focus'\s*,\s*'([^']+)'/);
    if (m && m[1]) return m[1];
    try { return sessionStorage.getItem(kind === "nudge" ? "cpl_nudge_focus" : "cpl_update_focus"); } catch (e) { return null; }
  }

  // Lazy-load raci.js (idempotent via CPL_TABS.loadScript) then open the popup.
  function openInPlace(kind, key) {
    if (!key || key.indexOf(":") < 0) return false;
    var tabs = (typeof window !== "undefined") && window.CPL_TABS;
    if (!tabs || typeof tabs.loadScript !== "function") return false;
    tabs.loadScript("raci.js", "CPL_RACI_TAB", function () {
      var api = window.CPL_RACI_TAB;
      if (!api) return;
      if (kind === "nudge") { if (api.openCardNudge) api.openCardNudge(key); }
      else if (api.openCardUpdate) api.openCardUpdate(key);
    });
    return true;
  }

  function onClick(e) {
    var t = e && e.target;
    if (!t || !t.closest) return;
    var a = t.closest(UPDATE_SEL + ", " + NUDGE_SEL);
    if (!a) return;
    var cls = a.className || "";
    var kind = /nudge-link/.test(cls) ? "nudge" : "update";
    var key = keyFromLink(a, kind);
    if (!key) return; // unknown key — let the default #raci navigation happen
    if (openInPlace(kind, key)) {
      e.preventDefault();
      // The inline onclick just stashed the key in sessionStorage; clear it so a
      // later manual visit to #raci doesn't replay this as a stale focus-open.
      try { sessionStorage.removeItem(kind === "nudge" ? "cpl_nudge_focus" : "cpl_update_focus"); } catch (x) {}
    }
  }

  // The nudge email links to …?update=<key>#activities-projects (or ?nudge=).
  // Consume it on ANY tab at boot, open the popup in place, and strip the param
  // (so a reload / raci.js's own consumer don't re-fire it).
  function consumeQueryParam() {
    var key = null, kind = "update";
    try {
      var qp = new URLSearchParams(location.search || "");
      if (qp.get("update")) { key = qp.get("update"); kind = "update"; qp.delete("update"); }
      else if (qp.get("nudge")) { key = qp.get("nudge"); kind = "nudge"; qp.delete("nudge"); }
      if (key) {
        var qs = qp.toString();
        history.replaceState(null, "", location.pathname + (qs ? "?" + qs : "") + location.hash);
      }
    } catch (e) {}
    if (key) openInPlace(kind, key);
  }

  // ── Boot ────────────────────────────────────────────────────────────────────
  if (typeof document !== "undefined" && document.addEventListener) {
    document.addEventListener("click", onClick, false);
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", consumeQueryParam);
    } else {
      consumeQueryParam();
    }
  }

  var api = { keyFromLink: keyFromLink, openInPlace: openInPlace, onClick: onClick, consumeQueryParam: consumeQueryParam };
  if (typeof window !== "undefined") window.CPL_CARD_ACTIONS = api;
  else if (typeof module !== "undefined" && module.exports) module.exports = api;
})();
