/*
 * COBI — Card live-update overlay  (window.CPL_CARD_UPDATES)
 *
 * Surfaces the newest posted status update from the Supabase `item_updates`
 * table (written by the Team & RACI tab's 📝 braindump→CC composer) directly
 * onto the Activity / sub-activity / project cards in the Activities & Projects
 * tab — closing the gap where an update saved on the RACI tab showed there but
 * not on the card face.
 *
 * How it works: the generator stamps an empty, hidden
 *   <div class="cpl-live-update" data-update-key="project:1.1"></div>
 * on every card (key = `activity:N` or `project:<id>`, the same item_updates
 * key the RACI composer writes). This overlay fetches item_updates (public anon
 * read, newest first), keeps the newest row per key, fills each matching hook
 * with the body + a timestamp, and hides the creation-era static "Latest Update"
 * line in that same card so there's a single, current "Latest Update".
 *
 * STATIC asset — NOT regenerated by excel_to_dashboard.py; read-only (no writes,
 * no auth). Mirrors the anon-read pattern of the other tabs.
 */
(function () {
  "use strict";

  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";

  // ── Pure helpers (also exported for tests) ──────────────────────────────────
  function escapeHtml(s) {
    return (s == null ? "" : String(s)).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  // Reduce item_updates rows (ordered newest-first by the query) to the newest
  // row per `item_type:item_id` key. Tolerant of unordered input — keeps the row
  // with the latest created_at.
  function latestByKey(rows) {
    var out = {};
    (rows || []).forEach(function (r) {
      if (!r || r.item_type == null || r.item_id == null) return;
      var k = r.item_type + ":" + r.item_id;
      var cur = out[k];
      if (!cur || new Date(r.created_at).getTime() > new Date(cur.created_at).getTime()) out[k] = r;
    });
    return out;
  }

  // "today" / "3d ago" / "5mo ago" — matches raci.js relTime so the two surfaces
  // read consistently.
  function relTime(iso) {
    if (!iso) return "";
    var t = new Date(iso).getTime();
    if (isNaN(t)) return "";
    var days = Math.floor((Date.now() - t) / 86400000);
    if (days <= 0) return "today";
    if (days === 1) return "1d ago";
    if (days < 30) return days + "d ago";
    var mo = Math.floor(days / 30);
    return mo + "mo ago";
  }

  function fmtDate(iso) {
    var d = new Date(iso);
    if (isNaN(d.getTime())) return "";
    try {
      return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
    } catch (e) {
      return d.toISOString().slice(0, 10);
    }
  }

  // The HTML for one filled hook: a "Latest Update" badge + body + a meta line
  // ("<author> · <date> (<rel>)"). Body is escaped (item_updates is reviewer-
  // written, but treat as untrusted).
  function blockHtml(u) {
    var when = fmtDate(u.created_at);
    var rel = relTime(u.created_at);
    var meta = [];
    if (u.author) meta.push(escapeHtml(u.author));
    if (when) meta.push(when + (rel ? " · " + rel : ""));
    return (
      '<div style="font-size:0.75rem;color:#444;line-height:1.4;margin-bottom:0.3rem;">' +
        '<span style="font-size:0.62rem;font-weight:600;background:var(--navy-secondary,#1b3a5c);color:#fff;' +
        'padding:0.1rem 0.3rem;border-radius:3px;margin-right:0.25rem;">Latest Update</span>' +
        escapeHtml(u.body) +
      '</div>' +
      (meta.length
        ? '<div style="font-size:0.62rem;color:#888;font-style:italic;">' + meta.join(" · ") + "</div>"
        : "")
    );
  }

  // ── DOM application ─────────────────────────────────────────────────────────
  var _latest = null;

  function applyTo(root) {
    if (!_latest) return;
    var scope = root || document;
    var hooks = scope.querySelectorAll(".cpl-live-update[data-update-key]");
    Array.prototype.forEach.call(hooks, function (hook) {
      if (hook.getAttribute("data-filled") === "1") return;
      var u = _latest[hook.getAttribute("data-update-key")];
      if (!u) return;
      hook.innerHTML = blockHtml(u);
      hook.style.display = "";
      hook.setAttribute("data-filled", "1");
      // Hide the creation-era static "Latest Update" line in the same card so the
      // live one is the single current update.
      var card = (hook.closest && hook.closest(".activity-kpi-card, .project-card, .activity-group")) || hook.parentNode;
      if (card) {
        Array.prototype.forEach.call(card.querySelectorAll(".cpl-static-update"), function (s) {
          s.style.display = "none";
        });
      }
    });
  }

  function fetchUpdates() {
    return fetch(
      SUPABASE_URL +
        "/rest/v1/item_updates?select=item_type,item_id,body,author,created_at&order=created_at.desc",
      { headers: { apikey: SUPABASE_ANON } }
    )
      .then(function (r) { return r.ok ? r.json() : []; })
      .catch(function () { return []; });
  }

  var _loading = false;
  function run() {
    if (_loading) { applyTo(); return; }
    _loading = true;
    fetchUpdates().then(function (rows) {
      _latest = latestByKey(rows);
      applyTo();
    });
  }

  // ── Boot ────────────────────────────────────────────────────────────────────
  if (typeof document !== "undefined" && document.addEventListener) {
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", run);
    } else {
      run();
    }
    // The cards live in the Activities & Projects tab (and the Dashboard's
    // activity metrics). Re-apply when those tabs activate (tabs.js dispatches
    // `cpl-tab-activated` on window), in case the fetch resolved before the pane
    // was in view, or a curator just posted an update.
    if (typeof window !== "undefined" && window.addEventListener) {
      window.addEventListener("cpl-tab-activated", function (e) {
        var tab = e && e.detail && e.detail.tab;
        if (tab === "activities-projects" || tab === "dashboard" || tab == null) run();
      });
    }
  }

  var api = {
    run: run,
    applyTo: applyTo,
    latestByKey: latestByKey,
    blockHtml: blockHtml,
    relTime: relTime,
    fmtDate: fmtDate,
    escapeHtml: escapeHtml,
    _setLatest: function (m) { _latest = m; } // test hook
  };
  if (typeof window !== "undefined") window.CPL_CARD_UPDATES = api;
  else if (typeof module !== "undefined" && module.exports) module.exports = api;
})();
