/* cip_crosswalk.js — "CIP Code Taxonomy" reference tab (window.CPL_CIP_CROSSWALK)
 *
 * The CO is transitioning course/program coding from TOP to CIP effective fall
 * 2026 (ESS 26-06). This tab is the faculty-facing REFERENCE MANUAL — the
 * successor to the CCC TOP Code Manual, an "easy button" that replaces the
 * multi-tab spreadsheet ESS was going to email to the field. It surfaces the
 * full federal CIP-2020 list: search, a plain-English program finder, and each
 * code's certified CTE category, definition, examples, family, and a course-
 * level C-ID/CCN floor. COE hosts the actual TOP↔CIP crosswalk (linked out) —
 * per the CO's reframe (Jenni Abbott, AA), TOP→CIP is one-to-many and we are
 * the reference, not a crosswalk recreator. No "suggest" form (CO direction).
 *
 * Ported from the locked prototype at docs/cip_prototype/ (prototype→lock→port).
 * STATIC — NOT regenerated by excel_to_dashboard.py. Lazy-loaded on first
 * #cip-crosswalk open (boot block in both HTMLs). Data: window.CIP_CROSSWALK
 * (cip_crosswalk_data.js, built by kb/_build_cip_crosswalk.py) — {fams, rows}.
 * Injects its own scoped CSS (everything under .cipx, no :root) so the daily
 * regen can't strand it and there's no Rule-4 mirror beyond the boot <script>.
 * DOM built with createElement/textContent (never innerHTML with data) for
 * CodeQL XSS safety. Tests: tests/cip_crosswalk.test.js
 */
(function () {
  "use strict";

  var ROOT_ID = "cip-crosswalk-root";
  var CSS_ID = "cip-crosswalk-css";
  var PAGE = 200; // rows rendered per page

  // External references (the reference manual links OUT to the hosted crosswalk).
  var COE_CROSSWALK = "https://datastudio.google.com/u/0/reporting/62925aaa-3c91-48ab-941b-2473c0e17cb7/page/iCRlF";
  var NCES = "https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=56";
  var ESS_MEMO = "https://www.cccco.edu/-/media/CCCCO-Website/docs/memo/ess-26-06-top-to-cip-transition-implementation-guidance-a11y.pdf";

  // ── tiny DOM helper ────────────────────────────────────────────────────────
  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) {
      Object.keys(attrs).forEach(function (k) {
        if (k === "class") n.className = attrs[k];
        else if (k === "text") n.textContent = attrs[k];
        else if (k.slice(0, 2) === "on" && typeof attrs[k] === "function") n[k] = attrs[k];
        else if (attrs[k] != null) n.setAttribute(k, attrs[k]);
      });
    }
    (kids || []).forEach(function (c) {
      if (c == null) return;
      n.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
    });
    return n;
  }
  function clear(n) { while (n && n.firstChild) n.removeChild(n.firstChild); }

  // ── state ──────────────────────────────────────────────────────────────────
  var D = null;      // window.CIP_CROSSWALK
  var ROWS = [];     // [{code,t,cat,fam,def,ex,act,x}] sorted by title
  var FAMS = {};     // fam2 -> title
  var GOFORWARD = { "CTE": 1, "Both": 1, "Non-CTE": 1, "Noncredit": 1 };
  var st = { q: "", cat: "all", fam: "", xfer: false, showRetired: false, limit: PAGE, open: {} };

  // live refs (for reset + re-render)
  var inputRef, pillsRef, famRef, cbRef, xferRef, listHost, countHost, finderOut;

  function ingest(data) {
    D = data;
    FAMS = (D && D.fams) || {};
    ROWS = ((D && D.rows) || []).slice();
    // list alphabetically by program title (Jenni: not CIP-code order), code tiebreak
    ROWS.sort(function (a, b) {
      var x = (a.t || "").toLowerCase(), y = (b.t || "").toLowerCase();
      return x < y ? -1 : x > y ? 1 : (a.code < b.code ? -1 : 1);
    });
  }

  // ── filtering ────────────────────────────────────────────────────────────────
  function passes(r) {
    if (!st.showRetired && !GOFORWARD[r.cat]) return false;
    if (st.cat !== "all" && r.cat !== st.cat) return false;
    if (st.fam && r.fam !== st.fam) return false;
    if (st.xfer && !r.x) return false;
    if (st.q) {
      var toks = st.q.split(/\s+/);
      var hay = (r.code + " " + (r.t || "") + " " + (r.def || "")).toLowerCase();
      for (var i = 0; i < toks.length; i++) if (toks[i] && hay.indexOf(toks[i]) < 0) return false;
    }
    return true;
  }
  function filtered() { return ROWS.filter(passes); }

  function catTip(c) {
    return ({
      "CTE": "Career Technical Education", "Both": "Both CTE and non-CTE",
      "Non-CTE": "Not Career Technical Education", "Noncredit": "Noncredit CIP",
      "Retired": "Moved or deleted in the 2020 CIP edition", "Reserved": "Reserved placeholder code",
    })[c] || c;
  }
  function catClass(c) { return "cipx-cat cipx-cat-" + String(c || "").replace(/[^A-Za-z]/g, ""); }

  function activeFilterLabels() {
    var out = [];
    if (st.cat !== "all") out.push(st.cat);
    if (st.xfer) out.push("C-ID/CCN");
    if (st.fam) out.push((FAMS[st.fam] || st.fam) + " family");
    if (st.showRetired) out.push("incl. retired/reserved");
    return out;
  }
  function resetAll() {
    st.q = ""; st.cat = "all"; st.fam = ""; st.xfer = false; st.showRetired = false; st.limit = PAGE; st.open = {};
    if (inputRef) inputRef.value = "";
    if (famRef) famRef.value = "";
    if (cbRef) cbRef.checked = false;
    if (xferRef) xferRef.setAttribute("aria-pressed", "false");
    if (pillsRef) Array.prototype.forEach.call(pillsRef.querySelectorAll(".cipx-pill"), function (x, i) {
      x.setAttribute("aria-pressed", i === 0 ? "true" : "false");
    });
    render();
  }

  // highlight query tokens in a string → array of nodes (text-only; XSS-safe)
  function hl(s) {
    s = s || "";
    if (!st.q) return [s];
    var toks = st.q.split(/\s+/).filter(Boolean).map(function (t) { return t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); });
    if (!toks.length) return [s];
    var re = new RegExp("(" + toks.join("|") + ")", "ig");
    var out = [], last = 0, m;
    while ((m = re.exec(s))) {
      if (m.index > last) out.push(s.slice(last, m.index));
      out.push(el("mark", {}, [m[0]]));
      last = m.index + m[0].length;
      if (re.lastIndex === m.index) re.lastIndex++;
    }
    if (last < s.length) out.push(s.slice(last));
    return out;
  }

  // ── plain-English finder (Phase 0: NO backend — grounded client-side retrieval
  //    over the real CIP records, so it can never invent a code) ──
  var STOP = { i: 1, a: 1, an: 1, the: 1, to: 1, for: 1, of: 1, in: 1, on: 1, at: 1, and: 1, or: 1, my: 1, our: 1, we: 1, want: 1,
    wanting: 1, need: 1, would: 1, like: 1, which: 1, what: 1, should: 1, cip: 1, code: 1, codes: 1, assign: 1, use: 1,
    using: 1, program: 1, programs: 1, course: 1, courses: 1, degree: 1, certificate: 1, "new": 1, build: 1, building: 1,
    start: 1, starting: 1, launch: 1, launching: 1, offer: 1, offering: 1, is: 1, are: 1, me: 1, help: 1, find: 1, about: 1,
    "with": 1, that: 1, "this": 1, it: 1, "do": 1, how: 1, best: 1, fit: 1 };
  function esc(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
  function stem(w) { return w.length < 5 ? w : (w.replace(/(ings?|edly|ed|ations?|tions?|ers?|ors?|ies|es|s)$/, "") || w); }
  function tokenize(q) { return (q || "").toLowerCase().split(/[^a-z0-9]+/).filter(function (w) { return w && w.length > 1 && !STOP[w]; }); }
  function rankCIP(q) {
    var toks = tokenize(q);
    if (!toks.length) return [];
    // word-boundary + stem = prefix-on-word-boundary: "weld"→welding/welder,
    // "assist"→assistant/assisting, but "gis" WON'T match "logistics"/"registered".
    var res = toks.map(function (w) { return { tok: w, s: stem(w), re: new RegExp("\\b" + esc(stem(w))) }; });
    var out = [];
    for (var i = 0; i < ROWS.length; i++) {
      var r = ROWS[i];
      if (!GOFORWARD[r.cat]) continue;               // active codes only
      var t = (r.t || "").toLowerCase(), d = (r.def || "").toLowerCase(), e = (r.ex || "").toLowerCase();
      var score = 0, hits = 0, matched = [];
      for (var j = 0; j < res.length; j++) {
        var m = res[j], hit = 0;
        if (m.re.test(t)) { score += (t.indexOf(m.s) === 0 ? 9 : 7); hit = 1; }  // title word
        if (m.re.test(e)) { score += 3; hit = 1; }                              // examples
        if (m.re.test(d)) { score += 1; hit = 1; }                              // definition
        if (hit) { hits++; matched.push(m.tok); }
      }
      if (hits) {
        score += hits * hits * 2;                     // reward covering more of the query
        if (t === (q || "").toLowerCase().trim()) score += 60; // exact title
        out.push({ r: r, score: score, matched: matched });
      }
    }
    out.sort(function (a, b) { return b.score - a.score || (a.r.t < b.r.t ? -1 : 1); });
    return out.slice(0, 6);
  }
  function renderFinder(q) {
    clear(finderOut);
    if (!tokenize(q).length) return;
    var hits = rankCIP(q);
    if (!hits.length) {
      finderOut.appendChild(el("div", { class: "cipx-fnd-empty" },
        ["No close matches yet — try a program name or a key skill (e.g. \"welding\", \"medical assisting\", \"GIS\")."]));
      return;
    }
    finderOut.appendChild(el("div", { class: "cipx-fnd-lead" },
      ["Closest CIP codes for “" + q.trim() + "” — open each to confirm against its definition:"]));
    hits.forEach(function (h) {
      var r = h.r;
      var caret = el("span", { class: "cipx-caret" }, ["▸"]);
      var crow = el("div", { class: "cipx-fnd-crow", role: "button", tabindex: "0" }, [
        caret, el("span", { class: "cipx-code" }, [r.code]),
        el("span", { class: "cipx-fnd-ct" }, [r.t]),
        r.cat ? el("span", { class: catClass(r.cat), title: catTip(r.cat) }, [r.cat]) : null,
      ]);
      var card = el("div", { class: "cipx-fnd-card" }, [crow]);
      if (h.matched.length) card.appendChild(el("div", { class: "cipx-fnd-why" }, ["matched: " + h.matched.join(", ")]));
      var open = false, det = null;
      function tog() {
        open = !open; caret.textContent = open ? "▾" : "▸";
        if (open) { det = detail(r); card.appendChild(det); } else if (det) { card.removeChild(det); det = null; }
      }
      crow.onclick = tog;
      crow.onkeydown = function (ev) { if (ev.key === "Enter" || ev.key === " ") { ev.preventDefault(); tog(); } };
      finderOut.appendChild(card);
    });
    finderOut.appendChild(el("div", { class: "cipx-fnd-foot" },
      ["Suggestions to review — the CIP definition is the final word, and your college enters the chosen code in COCI. (An AI-assisted version is on the way.)"]));
  }

  // ── list + detail ─────────────────────────────────────────────────────────────
  function render() {
    var rows = filtered();
    clear(countHost);
    countHost.appendChild(el("span", { class: "cipx-cnum" }, [
      rows.length.toLocaleString() + " CIP code" + (rows.length === 1 ? "" : "s") +
      (rows.length > st.limit ? "  ·  showing " + st.limit.toLocaleString() : ""),
    ]));
    var af = activeFilterLabels();
    if (af.length) countHost.appendChild(el("span", { class: "cipx-cfilters" }, [" · " + af.join(" · ")]));
    if (af.length || st.q) {
      var clr = el("button", { class: "cipx-clearbtn", type: "button" },
        ["✕ Clear " + (af.length && st.q ? "search + filters" : (st.q ? "search" : "filters"))]);
      clr.onclick = resetAll;
      countHost.appendChild(clr);
    }
    var csv = el("button", { class: "cipx-csv", type: "button", title: "Download the current filtered list as CSV",
      onclick: function () { exportCsv(rows); } }, ["⬇ CSV"]);
    countHost.appendChild(csv);

    clear(listHost);
    if (!rows.length) {
      listHost.appendChild(el("div", { class: "cipx-empty" }, ["No CIP codes match — try a different word or clear the filters."]));
      return;
    }
    var shown = rows.slice(0, st.limit);
    shown.forEach(function (r) {
      var isOpen = !!st.open[r.code];
      var badges = el("div", { class: "cipx-tags" }, []);
      if (r.act === "New") badges.appendChild(el("span", { class: "cipx-new", title: "New in the 2020 CIP edition" }, ["NEW"]));
      if (r.cat) badges.appendChild(el("span", { class: catClass(r.cat), title: catTip(r.cat) }, [r.cat]));
      var row = el("div", { class: "cipx-row", role: "button", tabindex: "0" }, [
        el("span", { class: "cipx-caret" }, [isOpen ? "▾" : "▸"]),
        el("span", { class: "cipx-code" }, [r.code]),
        el("span", { class: "cipx-ttl" }, hl(r.t)),
        badges,
      ]);
      var item = el("div", { class: "cipx-item" + (isOpen ? " cipx-open" : "") }, [row]);
      row.onclick = function () { toggle(r.code); };
      row.onkeydown = function (e) { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); toggle(r.code); } };
      if (isOpen) item.appendChild(detail(r));
      listHost.appendChild(item);
    });
    if (rows.length > st.limit) {
      listHost.appendChild(el("div", { class: "cipx-more" }, [
        el("button", { class: "cipx-morebtn", type: "button", onclick: function () { st.limit += PAGE; render(); } },
          ["Show " + Math.min(PAGE, rows.length - st.limit).toLocaleString() + " more"]),
      ]));
    }
  }

  function detail(r) {
    var box = el("div", { class: "cipx-detail" }, []);
    box.appendChild(el("p", { class: "cipx-def" }, [r.def || "No published definition for this code."]));
    if (r.ex) box.appendChild(el("p", { class: "cipx-ex" }, [el("b", {}, ["Examples: "]), r.ex]));
    var meta = el("div", { class: "cipx-dmeta" }, []);
    if (r.fam) meta.appendChild(el("span", {}, [el("b", {}, ["CIP family " + r.fam + " · "]), FAMS[r.fam] || ""]));
    if (r.x) meta.appendChild(el("span", { class: "cipx-xnote",
      title: "At least one TOP that maps to this CIP has courses carrying a C-ID (transfer-model articulation) or CCN (AB 1111 common course number). A course-level floor — not full CSU/UC transferability." },
      ["🎓 C-ID/CCN coursework exists"]));
    box.appendChild(meta);
    box.appendChild(el("a", { class: "cipx-ncesbtn", target: "_blank", rel: "noopener", href: NCES },
      ["Look up " + r.code + " in the NCES CIP-2020 list ↗"]));
    return box;
  }
  function toggle(code) { if (st.open[code]) delete st.open[code]; else st.open[code] = true; render(); }

  // ── CSV export of the current filtered list ───────────────────────────────────
  function exportCsv(rows) {
    var out = ["CIP Code,Title,Category,Family,Family Title,2020 CIP Action,C-ID/CCN,Definition"];
    rows.forEach(function (r) {
      function q(v) { return '"' + String(v == null ? "" : v).replace(/"/g, '""') + '"'; }
      out.push([q(r.code), q(r.t), q(r.cat), q(r.fam), q(FAMS[r.fam] || ""),
                q(r.act), q(r.x ? "Yes" : "No"), q(r.def)].join(","));
    });
    var blob = new Blob([out.join("\n")], { type: "text/csv" });
    var a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "cip_code_taxonomy.csv";
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
  }

  // ── shell ────────────────────────────────────────────────────────────────────
  function header() {
    return el("div", { class: "cipx-head" }, [
      el("div", { class: "cipx-eyebrow" }, ["California Community Colleges · Chancellor's Office"]),
      el("h2", { class: "cipx-h2" }, ["CIP Code Taxonomy"]),
      el("p", { class: "cipx-sub" }, [
        "The successor to the CCC TOP Code Manual. Course & program coding is moving from ",
        el("b", {}, ["TOP"]), " to ", el("b", {}, ["CIP"]), " for fall 2026 — search the full federal ",
        "CIP-2020 list below to find the right code, and see at a glance whether it's CTE, non-CTE, both, ",
        "or noncredit. (You'll enter your chosen code in COCI.)",
      ]),
      el("div", { class: "cipx-hlinks" }, [
        el("a", { href: COE_CROSSWALK, target: "_blank", rel: "noopener" }, ["TOP ↔ CIP crosswalk (COE) ↗"]),
        el("a", { href: NCES, target: "_blank", rel: "noopener" }, ["NCES CIP-2020 taxonomy ↗"]),
        el("a", { href: ESS_MEMO, target: "_blank", rel: "noopener" }, ["ESS 26-06 transition guidance ↗"]),
      ]),
    ]);
  }

  function buildFinder() {
    var finder = el("div", { class: "cipx-finder" }, [
      el("div", { class: "cipx-fnd-h" }, ["Not sure which code? Describe your program"]),
      el("div", { class: "cipx-fnd-sub" }, ["Type what you're building in plain English and we'll surface the closest CIP codes to review."]),
    ]);
    var fin = el("input", { class: "cipx-fnd-in", type: "text", "aria-label": "Describe your program",
      placeholder: "e.g. medical assisting · GIS mapping · wildland firefighting · HVAC technician" });
    var _ft;
    fin.oninput = function () { var v = fin.value; clearTimeout(_ft); _ft = setTimeout(function () { renderFinder(v); }, 180); };
    fin.onkeydown = function (ev) { if (ev.key === "Enter") { ev.preventDefault(); renderFinder(fin.value); } };
    finder.appendChild(fin);
    finderOut = el("div", { class: "cipx-fnd-out" }, []);
    finder.appendChild(finderOut);
    return finder;
  }

  function buildBar() {
    var bar = el("div", { class: "cipx-bar" }, []);

    // search
    var input = el("input", { class: "cipx-search", id: "cipx-q", type: "search", autocomplete: "off",
      "aria-label": "Search CIP codes",
      placeholder: "Search by code, program title, or keyword — e.g. nursing, welding, 51.3801" });
    inputRef = input;
    var _t;
    input.oninput = function () { var v = input.value; clearTimeout(_t); _t = setTimeout(function () { st.q = v.toLowerCase().trim(); st.limit = PAGE; render(); }, 140); };
    bar.appendChild(el("div", { class: "cipx-searchrow" }, [input]));

    var controls = el("div", { class: "cipx-controls" }, []);

    // category pills
    var pills = el("div", { class: "cipx-pills" }, []); pillsRef = pills;
    [["all", "All"], ["CTE", "CTE"], ["Non-CTE", "Non-CTE"], ["Both", "Both"], ["Noncredit", "Noncredit"]].forEach(function (p) {
      var b = el("button", { class: "cipx-pill", type: "button", "aria-pressed": st.cat === p[0] ? "true" : "false" }, [p[1]]);
      b.onclick = function () {
        st.cat = p[0]; st.limit = PAGE;
        Array.prototype.forEach.call(pills.querySelectorAll(".cipx-pill"), function (x) { x.setAttribute("aria-pressed", "false"); });
        b.setAttribute("aria-pressed", "true");
        render();
      };
      pills.appendChild(b);
    });
    controls.appendChild(pills);

    // C-ID/CCN toggle chip (ANDs with the category)
    controls.appendChild(el("span", { class: "cipx-chipsep" }, []));
    var xferChip = el("button", { class: "cipx-pill cipx-pill-xfer", type: "button", "aria-pressed": st.xfer ? "true" : "false",
      title: "CIP codes whose courses carry a C-ID (transfer-model articulation) or CCN (common course number). A course-level floor — not a guarantee of full transferability." },
      ["🎓 C-ID/CCN"]);
    xferRef = xferChip;
    xferChip.onclick = function () { st.xfer = !st.xfer; xferChip.setAttribute("aria-pressed", st.xfer ? "true" : "false"); st.limit = PAGE; render(); };
    controls.appendChild(xferChip);

    // CIP family select
    var fam = el("select", { class: "cipx-fsel", "aria-label": "CIP family" }, [el("option", { value: "" }, ["All CIP families"])]);
    famRef = fam;
    Object.keys(FAMS).sort().forEach(function (f) { fam.appendChild(el("option", { value: f }, [f + " · " + FAMS[f]])); });
    fam.onchange = function () { st.fam = fam.value; st.limit = PAGE; render(); };
    controls.appendChild(fam);

    // include retired/reserved
    var tog = el("label", { class: "cipx-retiredtog", title: "Retired = moved/deleted in 2020. Reserved = placeholder codes." }, []);
    var cb = el("input", { type: "checkbox" }); cbRef = cb;
    cb.onchange = function () { st.showRetired = cb.checked; st.limit = PAGE; render(); };
    tog.appendChild(cb); tog.appendChild(document.createTextNode("Include retired / reserved"));
    controls.appendChild(tog);

    bar.appendChild(controls);
    countHost = el("div", { class: "cipx-count" }, []);
    bar.appendChild(countHost);
    return bar;
  }

  function footer() {
    var active = ROWS.filter(function (r) { return GOFORWARD[r.cat]; }).length;
    return el("div", { class: "cipx-foot" }, [
      "CIP-2020 data from the Chancellor's Office CIP Searchable Workbook (2026-07-15 cut). " +
      active.toLocaleString() + " active CIP codes shown by default; retired and reserved codes are " +
      "hidden unless you tick the box above. The CTE / non-CTE / both / noncredit label reflects the " +
      "Chancellor's Office certified CIP CTE designations.",
    ]);
  }

  function rebuildShell() {
    var root = document.getElementById(ROOT_ID);
    if (!root) return;
    clear(root);
    root.removeAttribute("style");
    var wrap = el("div", { class: "cipx" }, []);
    wrap.appendChild(header());
    wrap.appendChild(buildFinder());
    wrap.appendChild(buildBar());
    listHost = el("div", { class: "cipx-list" }, []);
    wrap.appendChild(listHost);
    wrap.appendChild(footer());
    root.appendChild(wrap);
    render();
  }

  // ── CSS (scoped under .cipx; no :root — the dashboard owns the theme) ──────────
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var css = [
      ".cipx{max-width:1000px;margin:0 auto;font-size:.95rem;color:var(--text,#243b53);line-height:1.5;}",
      // header
      ".cipx-head{padding:2px 0 6px;}",
      ".cipx-eyebrow{font-size:.72rem;font-weight:700;letter-spacing:.09em;text-transform:uppercase;color:var(--seal-blue,#00356B);}",
      ".cipx-h2{margin:.28em 0 .1em;font-size:1.6rem;line-height:1.15;color:var(--text-strong,#102a43);}",
      ".cipx-sub{margin:.2em 0 0;color:var(--text,#3c526b);max-width:70ch;font-size:.98rem;}",
      ".cipx-hlinks{display:flex;gap:18px;flex-wrap:wrap;margin:12px 0 2px;font-size:.82rem;}",
      ".cipx-hlinks a{color:var(--link,#0b5fa8);text-decoration:none;font-weight:600;}",
      ".cipx-hlinks a:hover{text-decoration:underline;}",
      // finder
      ".cipx-finder{background:var(--surface-2,#eef3f9);border:1px solid var(--border,#dbe4ee);border-radius:14px;padding:15px 18px 16px;margin:14px 0 18px;}",
      ".cipx-fnd-h{font-weight:700;color:var(--text-strong,#102a43);font-size:1.04rem;}",
      ".cipx-fnd-sub{color:var(--text,#3c526b);font-size:.88rem;margin:3px 0 11px;}",
      ".cipx-fnd-in{width:100%;box-sizing:border-box;padding:12px 14px;font-size:1rem;border:1.5px solid var(--border-strong,#c3d1e0);border-radius:10px;background:var(--surface,#fff);color:var(--text,#243b53);font-family:inherit;}",
      ".cipx-fnd-in:focus{outline:2px solid var(--seal-blue,#00356B);outline-offset:1px;border-color:var(--seal-blue,#00356B);}",
      ".cipx-fnd-out{margin-top:2px;}",
      ".cipx-fnd-lead{font-size:.82rem;color:var(--text,#3c526b);font-weight:600;margin:13px 2px 6px;}",
      ".cipx-fnd-card{background:var(--surface,#fff);border:1px solid var(--border,#dbe4ee);border-radius:10px;margin:7px 0;}",
      ".cipx-fnd-crow{display:grid;grid-template-columns:16px 92px 1fr auto;gap:12px;align-items:center;padding:11px 12px;cursor:pointer;}",
      ".cipx-fnd-crow:hover{background:var(--surface-subtle,#f2f6fb);}",
      ".cipx-fnd-ct{font-weight:600;color:var(--text-strong,#102a43);min-width:0;}",
      ".cipx-fnd-why{font-size:.74rem;color:var(--text-muted,#6a7f96);padding:0 12px 9px 120px;}",
      ".cipx-fnd-card .cipx-detail{padding:0 12px 16px 120px;}",
      ".cipx-fnd-empty{font-size:.86rem;color:var(--text-muted,#6a7f96);padding:10px 2px;}",
      ".cipx-fnd-foot{font-size:.77rem;color:var(--text-muted,#6a7f96);margin:11px 2px 2px;font-style:italic;line-height:1.5;}",
      // sticky bar
      ".cipx-bar{position:sticky;top:0;z-index:5;background:var(--surface,#fff);padding:10px 0 8px;border-bottom:1px solid var(--border,#dbe4ee);margin-bottom:4px;}",
      ".cipx-search{width:100%;box-sizing:border-box;padding:12px 14px;font-size:1.03rem;color:var(--text,#243b53);background:var(--surface,#fff);border:1.5px solid var(--border-strong,#c3d1e0);border-radius:10px;}",
      ".cipx-search:focus{outline:2px solid var(--seal-blue,#00356B);outline-offset:1px;border-color:var(--seal-blue,#00356B);}",
      ".cipx-controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:10px;}",
      ".cipx-pills{display:flex;gap:6px;flex-wrap:wrap;}",
      ".cipx-pill{font-size:.82rem;font-weight:600;padding:6px 13px;border-radius:999px;cursor:pointer;border:1px solid var(--border-strong,#c3d1e0);background:var(--surface,#fff);color:var(--text,#3c526b);font-family:inherit;}",
      ".cipx-pill:hover{border-color:var(--seal-blue,#00356B);}",
      ".cipx-pill[aria-pressed=\"true\"]{background:var(--seal-blue,#00356B);border-color:var(--seal-blue,#00356B);color:#fff;}",
      ".cipx-pill-xfer[aria-pressed=\"true\"]{background:#3730a3;border-color:#3730a3;}",
      ".cipx-chipsep{width:1px;align-self:stretch;min-height:22px;background:var(--border-strong,#c3d1e0);margin:0 2px;}",
      ".cipx-fsel{font-family:inherit;font-size:.84rem;padding:6px 10px;border-radius:8px;border:1px solid var(--border-strong,#c3d1e0);background:var(--surface,#fff);color:var(--text,#243b53);cursor:pointer;max-width:230px;}",
      ".cipx-retiredtog{display:inline-flex;align-items:center;gap:6px;font-size:.78rem;color:var(--text-muted,#6a7f96);cursor:pointer;margin-left:auto;}",
      ".cipx-count{font-size:.82rem;color:var(--text-muted,#6a7f96);font-weight:600;margin:9px 2px 2px;display:flex;align-items:baseline;flex-wrap:wrap;gap:2px;}",
      ".cipx-cfilters{color:var(--seal-blue,#00356B);font-weight:650;}",
      ".cipx-clearbtn{margin-left:10px;font-size:.78rem;font-weight:600;color:var(--link,#0b5fa8);background:none;border:0;cursor:pointer;padding:0;font-family:inherit;}",
      ".cipx-clearbtn:hover{text-decoration:underline;}",
      ".cipx-csv{margin-left:auto;font-size:.76rem;font-weight:700;color:var(--link,#0b5fa8);background:none;border:1px solid var(--border,#dbe4ee);border-radius:6px;padding:3px 9px;cursor:pointer;}",
      // list
      ".cipx-list{display:flex;flex-direction:column;}",
      ".cipx-item{border-bottom:1px solid var(--border,#eef2f7);}",
      ".cipx-row{display:grid;grid-template-columns:16px 92px 1fr auto;gap:12px;align-items:center;padding:12px 8px;cursor:pointer;}",
      ".cipx-row:hover{background:var(--surface-subtle,#f2f6fb);}",
      ".cipx-item.cipx-open .cipx-row{background:var(--surface-subtle,#f2f6fb);}",
      ".cipx-caret{color:var(--text-muted,#6a7f96);font-size:.8rem;width:14px;text-align:center;}",
      ".cipx-code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-weight:600;font-size:.9rem;color:var(--seal-blue,#00356B);}",
      ".cipx-ttl{font-weight:550;color:var(--text-strong,#102a43);min-width:0;}",
      ".cipx-tags{display:flex;gap:6px;align-items:center;flex-wrap:wrap;justify-content:flex-end;}",
      ".cipx-cat{font-size:.66rem;font-weight:700;letter-spacing:.03em;text-transform:uppercase;padding:3px 9px;border-radius:6px;white-space:nowrap;}",
      ".cipx-cat-CTE{background:#dcfce7;color:#166534;}",
      ".cipx-cat-Both{background:#e0e7ff;color:#3730a3;}",
      ".cipx-cat-NonCTE{background:#eaeef4;color:#334155;}",
      ".cipx-cat-Noncredit{background:#cff5fb;color:#0e5e75;}",
      ".cipx-cat-Retired,.cipx-cat-Reserved{background:#eceff3;color:#6b7280;}",
      ".cipx-new{background:#dbeafe;color:#1e40af;font-size:.6rem;font-weight:800;padding:2px 6px;border-radius:5px;letter-spacing:.05em;}",
      // detail
      ".cipx-detail{padding:4px 8px 20px 120px;}",
      ".cipx-def{margin:2px 0 0;color:var(--text,#3c526b);line-height:1.6;max-width:74ch;}",
      ".cipx-ex{margin-top:8px;font-size:.85rem;color:var(--text-muted,#6a7f96);}",
      ".cipx-ex b{color:var(--text,#3c526b);}",
      ".cipx-dmeta{display:flex;gap:14px;flex-wrap:wrap;margin-top:12px;font-size:.82rem;color:var(--text-muted,#6a7f96);align-items:baseline;}",
      ".cipx-dmeta b{color:var(--text,#3c526b);font-weight:650;}",
      ".cipx-xnote{cursor:help;color:#3730a3;font-weight:600;}",
      ".cipx-ncesbtn{display:inline-block;margin-top:12px;font-size:.82rem;font-weight:600;color:var(--link,#0b5fa8);text-decoration:none;border:1px solid var(--border-strong,#c3d1e0);border-radius:8px;padding:6px 12px;}",
      ".cipx-ncesbtn:hover{border-color:var(--link,#0b5fa8);}",
      ".cipx-more{text-align:center;margin:20px 0;}",
      ".cipx-morebtn{font-size:.86rem;font-weight:650;color:var(--seal-blue,#00356B);background:var(--surface,#fff);border:1px solid var(--border-strong,#c3d1e0);border-radius:9px;padding:9px 20px;cursor:pointer;font-family:inherit;}",
      ".cipx-empty{text-align:center;padding:48px 12px;color:var(--text-muted,#6a7f96);}",
      ".cipx mark{background:#ffe89c;color:inherit;border-radius:2px;padding:0 1px;}",
      ".cipx-foot{margin-top:26px;font-size:.76rem;color:var(--text-muted,#6a7f96);border-top:1px solid var(--border,#dbe4ee);padding-top:14px;line-height:1.6;}",
      "@media (max-width:640px){.cipx-row,.cipx-fnd-crow{grid-template-columns:14px 66px 1fr auto;gap:8px;}.cipx-detail,.cipx-fnd-why,.cipx-fnd-card .cipx-detail{padding-left:14px;}}",
    ].join("");
    var stEl = el("style", { id: CSS_ID });
    stEl.textContent = css;
    document.head.appendChild(stEl);
  }

  // ── public API / lifecycle ────────────────────────────────────────────────────
  var _rendered = false;
  function activate() {
    ensureCss();
    var root = document.getElementById(ROOT_ID);
    if (!root) return;
    if (_rendered) return;
    var data = window.CIP_CROSSWALK;
    if (!data || !data.rows) {
      clear(root); root.removeAttribute("style");
      root.appendChild(el("div", { class: "cipx-empty" },
        ["CIP taxonomy data unavailable — cip_crosswalk_data.js failed to load. Rebuild: python3 kb/_build_cip_crosswalk.py"]));
      return;
    }
    _rendered = true;
    ingest(data);
    rebuildShell();
  }

  window.CPL_CIP_CROSSWALK = {
    activate: activate,
    // test seams
    _setData: function (d) { ingest(d); },
    _passes: passes, _filtered: filtered, _rankCIP: rankCIP,
  };
})();
