/* cip_crosswalk.js — "TOP ↔ CIP Crosswalk" tab renderer (window.CPL_CIP_CROSSWALK)
 *
 * The CO is transitioning course/program coding from TOP to CIP effective fall
 * 2026 (ESS 26-06). This tab replaces the searchable spreadsheet ESS was going
 * to email to the field: faculty search/filter the TOP↔CIP crosswalk, read the
 * CIP definitions/occupations, see which colleges already use a pairing, and —
 * TMC-style — file SUGGESTED CHANGES + NOTES for the Chancellor's Office to
 * curate. Submissions are open (anon INSERT into cip_crosswalk_suggestion, no
 * public SELECT); the CO reads the queue behind the team-phrase / reviewer gate.
 *
 * STATIC — NOT regenerated by excel_to_dashboard.py. Lazy-loaded on first
 * #cip-crosswalk open (boot block in both HTMLs). Data: window.CIP_CROSSWALK
 * (cip_crosswalk_data.js, built by kb/_build_cip_crosswalk.py). Injects its own
 * scoped CSS (everything under .cipx) so the daily regen can never strand it and
 * there's no Rule-4 mirror beyond the boot <script>. DOM is built with
 * createElement/textContent (never innerHTML with data) for CodeQL XSS safety.
 * Tests: tests/cip_crosswalk.test.js
 */
(function () {
  "use strict";

  var ROOT_ID = "cip-crosswalk-root";
  var CSS_ID = "cip-crosswalk-css";
  var PAGE = 300; // rows rendered per page (refine to narrow)

  // Supabase (anon key is public + RLS-gated; mirrors cpl_pathways.js / map_export.js).
  // cip_crosswalk_suggestion is anon INSERT-only (no public SELECT — contact info
  // is never publicly readable). Schema of record: kb/supabase_cip_crosswalk_suggestion.sql.
  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var SUGGEST_INTAKE = SUPABASE_URL + "/rest/v1/cip_crosswalk_suggestion";

  var ESS_MEMO = "https://www.cccco.edu/-/media/CCCCO-Website/docs/memo/ess-26-06-top-to-cip-transition-implementation-guidance-a11y.pdf";
  var NONCREDIT_MAP = "https://www.cccco.edu/About-Us/Chancellors-Office/Divisions/Educational-Services-and-Support/TOP-to-CIP-Code-Transition-Project/TOP-to-CIP-Noncredit-Mapping";
  var CIP_BROWSE = "https://nces.ed.gov/ipeds/cipcode/browse.aspx?y=56";

  // ── tiny DOM helper ────────────────────────────────────────────────────────
  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) {
      Object.keys(attrs).forEach(function (k) {
        if (k === "class") n.className = attrs[k];
        else if (k === "text") n.textContent = attrs[k];
        else if (k === "html") { /* intentionally unused — no data via innerHTML */ }
        else if (k.slice(0, 2) === "on" && typeof attrs[k] === "function") n[k] = attrs[k];
        else if (attrs[k] != null) n.setAttribute(k, attrs[k]);
      });
    }
    (kids || []).forEach(function (c) {
      if (c == null) return;
      n.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
    });
    return n;
  }
  function clear(n) { while (n && n.firstChild) n.removeChild(n.firstChild); }

  // ── state ──────────────────────────────────────────────────────────────────
  var D = null;          // window.CIP_CROSSWALK
  var INDEX = [];        // per-pair search/display index
  var state = {
    q: "", group: "top", credit: "all", cte: "all",
    sources: {},         // srcIdx -> true (empty = all)
    sector: "", family: "",
    limit: PAGE,
    open: {},            // rowKey -> true (expanded detail)
  };

  // source presentation: tier drives the badge color
  var SRC_TIER = {
    "COCI": "official", "CCCCO TOP-CIP": "official",
    "Noncredit TOP-CIP": "noncredit", "COE TOP-CIP": "coe",
    "Submitted by Field": "field", "CIP Code File (No TOP Relationship)": "none",
  };
  var SRC_SHORT = {
    "COCI": "COCI", "CCCCO TOP-CIP": "CCCCO", "Noncredit TOP-CIP": "Noncredit",
    "COE TOP-CIP": "COE", "Submitted by Field": "Field", "CIP Code File (No TOP Relationship)": "CIP file",
  };

  function buildIndex() {
    INDEX = D.pairs.map(function (p, i) {
      var topCode = p[0], cipCode = p[1];
      var t = topCode ? D.top[topCode] : null;
      var c = D.cip[cipCode] || null;
      var srcName = D.sources[p[2]] || "";
      var hay = ((topCode || "") + " " + (t ? t.t : "") + " " +
                 cipCode + " " + (c ? c.t : "") + " " + srcName + " " +
                 (c ? c.def : "")).toLowerCase();
      return {
        i: i, topCode: topCode, cipCode: cipCode, t: t, c: c,
        src: p[2], srcName: srcName, nc: p[3] === 1,
        colleges: p[4] || "", count: p[5] || 0, hay: hay,
      };
    });
  }

  function passes(r) {
    if (state.q) {
      var toks = state.q.split(/\s+/);
      for (var i = 0; i < toks.length; i++)
        if (toks[i] && r.hay.indexOf(toks[i]) < 0) return false;
    }
    if (state.credit === "credit" && r.nc) return false;
    if (state.credit === "noncredit" && !r.nc) return false;
    if (state.cte !== "all") {
      var isCte = (r.c && /CTE|Both/i.test(r.c.cte)) || (r.t && r.t.cte === 1);
      if (state.cte === "cte" && !isCte) return false;
      if (state.cte === "notcte" && isCte) return false;
    }
    var srcKeys = Object.keys(state.sources);
    if (srcKeys.length && !state.sources[r.src]) return false;
    if (state.sector && (!r.t || r.t.sec !== state.sector)) return false;
    if (state.family && (!r.c || r.c.fam !== state.family)) return false;
    return true;
  }

  // nulls-last, plain string order — codes are zero-padded so "<" collates
  // correctly ("01.0000" < "01.0102" < "52.0201"); avoids locale/punctuation
  // surprises from localeCompare with a sentinel.
  function cmp(a, b) {
    if (a === b) return 0;
    if (a == null) return 1;
    if (b == null) return -1;
    return a < b ? -1 : 1;
  }
  function filtered() {
    var out = INDEX.filter(passes);
    if (state.group === "cip") {
      out.sort(function (a, b) { return cmp(a.cipCode, b.cipCode) || cmp(a.topCode, b.topCode); });
    } else {
      out.sort(function (a, b) { return cmp(a.topCode, b.topCode) || cmp(a.cipCode, b.cipCode); });
    }
    return out;
  }

  // ── small UI atoms ──────────────────────────────────────────────────────────
  function chip(text, cls, title) {
    return el("span", { class: "cipx-chip " + (cls || ""), title: title || "" }, [text]);
  }
  function srcBadge(name) {
    var tier = SRC_TIER[name] || "none";
    return el("span", { class: "cipx-src cipx-src-" + tier, title: name }, [SRC_SHORT[name] || name]);
  }
  function cteChips(r) {
    var out = [];
    if (r.c && /CTE|Both/i.test(r.c.cte)) out.push(chip("CTE", "cte", "Career Technical Education"));
    if (r.nc) out.push(chip("Noncredit", "nc", "Noncredit CIP"));
    if (r.c && r.c.act === "New") out.push(chip("NEW", "new", "New in the 2020 CIP edition"));
    if (r.c && r.c.act === "Deleted") out.push(chip("DELETED", "del", "Deleted from the CIP taxonomy"));
    if (r.c && (r.c.act === "Moved to" || r.c.act === "Moved from"))
      out.push(chip("MOVED", "moved", r.c.act + " in the 2020 CIP edition"));
    return out;
  }

  // ── code cell (TOP or CIP) with a quick-filter click ─────────────────────────
  function codeCell(code, title, kind) {
    var codeEl = el("button", {
      class: "cipx-code cipx-code-" + kind, type: "button",
      title: "Filter to " + code,
      onclick: function (e) {
        e.stopPropagation();
        setSearch(code);
      },
    }, [code || "— no TOP —"]);
    var wrap = el("div", { class: "cipx-codewrap" }, [codeEl]);
    if (title) wrap.appendChild(el("span", { class: "cipx-codettl", title: title }, [title]));
    return wrap;
  }

  function rowKey(r) { return r.i; }

  // ── detail (expanded) ────────────────────────────────────────────────────────
  function detailPanel(r) {
    var box = el("div", { class: "cipx-detail" }, []);

    // TOP side
    if (r.t) {
      var topBlk = el("div", { class: "cipx-dcol" }, [
        el("div", { class: "cipx-dh" }, ["TOP  " + r.topCode]),
        el("div", { class: "cipx-dttl" }, [r.t.t]),
        el("div", { class: "cipx-dmeta" }, [
          el("span", {}, ["Division " + r.t.div + " · " + r.t.divt]),
        ]),
        r.t.sec ? el("div", { class: "cipx-dmeta" }, ["Sector: " + r.t.sec]) : null,
        el("div", { class: "cipx-dlinks" }, [
          el("button", {
            class: "cipx-linkbtn", type: "button",
            title: "Open the COCI course browser filtered to this TOP code",
            onclick: function () { gotoCoci(r.topCode); },
          }, ["🔎 COCI courses with TOP " + r.topCode]),
        ]),
      ]);
      box.appendChild(topBlk);
    } else {
      box.appendChild(el("div", { class: "cipx-dcol" }, [
        el("div", { class: "cipx-dh" }, ["TOP"]),
        el("div", { class: "cipx-dnote" }, ["No TOP relationship on record for this CIP code — a candidate for a field suggestion."]),
      ]));
    }

    // CIP side
    var c = r.c || { t: "", def: "", ex: "", xref: "", fam: "", famt: "", cte: "", act: "", soc: [] };
    var cipMeta = [];
    if (c.fam) cipMeta.push(el("div", { class: "cipx-dmeta" }, ["Family " + c.fam + " · " + c.famt]));
    if (c.cte) cipMeta.push(el("div", { class: "cipx-dmeta" }, ["CIP flag: " + c.cte]));
    if (c.act && c.act !== "No substantive changes")
      cipMeta.push(el("div", { class: "cipx-dmeta cipx-dchange" }, ["2020 CIP change: " + c.act]));

    var cipBlk = el("div", { class: "cipx-dcol" }, [
      el("div", { class: "cipx-dh" }, ["CIP  " + r.cipCode]),
      el("div", { class: "cipx-dttl" }, [c.t]),
    ].concat(cipMeta));
    if (c.def) cipBlk.appendChild(el("p", { class: "cipx-ddef" }, [c.def]));
    if (c.ex) cipBlk.appendChild(el("p", { class: "cipx-dsub" }, [el("b", {}, ["Examples: "]), c.ex]));
    if (c.xref) cipBlk.appendChild(el("p", { class: "cipx-dsub" }, [el("b", {}, ["See also: "]), c.xref]));

    // occupations (SOC → O*NET)
    if (c.soc && c.soc.length) {
      var socWrap = el("div", { class: "cipx-soc" }, []);
      socWrap.appendChild(el("div", { class: "cipx-dsublbl" }, ["Related occupations (SOC)"]));
      var list = el("div", { class: "cipx-socchips" }, []);
      c.soc.slice(0, 24).forEach(function (s) {
        list.appendChild(el("a", {
          class: "cipx-socchip", target: "_blank", rel: "noopener",
          href: "https://www.onetonline.org/link/summary/" + s[0] + ".00",
          title: "Open " + s[1] + " on O*NET",
        }, [s[0] + " · " + s[1]]));
      });
      socWrap.appendChild(list);
      if (c.soc.length > 24)
        socWrap.appendChild(el("div", { class: "cipx-dsub" }, ["+" + (c.soc.length - 24) + " more"]));
      cipBlk.appendChild(socWrap);
    }
    box.appendChild(cipBlk);

    // provenance + colleges
    var prov = el("div", { class: "cipx-dcol cipx-dprov" }, [
      el("div", { class: "cipx-dh" }, ["This mapping"]),
      el("div", { class: "cipx-dmeta" }, [el("b", {}, ["Source: "]), r.srcName]),
    ]);
    if (r.count) {
      prov.appendChild(el("div", { class: "cipx-dmeta" }, [el("b", {}, [r.count + " college" + (r.count === 1 ? "" : "s") + " "]), "already use this pairing:"]));
      prov.appendChild(el("div", { class: "cipx-colleges" }, [r.colleges]));
    } else {
      prov.appendChild(el("div", { class: "cipx-dnote" }, ["No colleges recorded on this pairing yet."]));
    }
    prov.appendChild(el("button", {
      class: "cipx-suggestbtn", type: "button",
      onclick: function (e) {
        var host = e.target.closest(".cipx-dprov");
        if (host.querySelector(".cipx-form")) return;
        host.appendChild(suggestForm({ top: r.topCode || "", topTitle: r.t ? r.t.t : "", cip: r.cipCode, cipTitle: c.t }));
        e.target.disabled = true;
      },
    }, ["✍️ Suggest a change / add a note"]));
    box.appendChild(prov);

    return box;
  }

  // ── the suggest-to-curate form (open/anon → cip_crosswalk_suggestion) ────────
  function suggestForm(ctx) {
    ctx = ctx || {};
    var form = el("form", { class: "cipx-form" }, []);
    var msg = el("div", { class: "cipx-formmsg" }, []);

    function field(label, node) {
      return el("label", { class: "cipx-fl" }, [el("span", {}, [label]), node]);
    }
    var typeSel = el("select", { class: "cipx-in", required: "required" }, [
      el("option", { value: "" }, ["— what kind of suggestion? —"]),
      el("option", { value: "add-mapping" }, ["Add a TOP↔CIP mapping"]),
      el("option", { value: "flag-mapping" }, ["Flag / remove an incorrect mapping"]),
      el("option", { value: "better-cip" }, ["A better-fit CIP for this TOP"]),
      el("option", { value: "note" }, ["General note / context"]),
      el("option", { value: "question" }, ["Question for the Chancellor's Office"]),
    ]);
    var topIn = el("input", { class: "cipx-in", type: "text", value: ctx.top || "", placeholder: "e.g. 0501.00" });
    var cipIn = el("input", { class: "cipx-in", type: "text", value: ctx.cip || "", placeholder: "e.g. 52.0201" });
    var body = el("textarea", { class: "cipx-in cipx-ta", required: "required", rows: "3",
      placeholder: "What should the CO know? Be as specific as you can — the right code, why, your program context…" }, []);
    var name = el("input", { class: "cipx-in", type: "text", placeholder: "Your name (optional)" });
    var email = el("input", { class: "cipx-in", type: "email", required: "required", placeholder: "you@college.edu" });
    var college = el("input", { class: "cipx-in", type: "text", placeholder: "Your college (optional)" });

    form.appendChild(field("Suggestion type", typeSel));
    form.appendChild(el("div", { class: "cipx-frow" }, [field("TOP code", topIn), field("CIP code", cipIn)]));
    form.appendChild(field("Your suggestion", body));
    form.appendChild(el("div", { class: "cipx-frow" }, [field("Email", email), field("Name", name)]));
    form.appendChild(field("College", college));

    var submit = el("button", { class: "cipx-fsubmit", type: "submit" }, ["Send to the Chancellor's Office"]);
    form.appendChild(el("div", { class: "cipx-factions" }, [submit, msg]));

    form.onsubmit = function (e) {
      e.preventDefault();
      if (!typeSel.value) { msg.textContent = "Pick a suggestion type."; msg.className = "cipx-formmsg err"; return; }
      if (!body.value.trim()) { msg.textContent = "Add your suggestion."; msg.className = "cipx-formmsg err"; return; }
      if ((email.value || "").indexOf("@") < 1) { msg.textContent = "A valid email lets the CO follow up."; msg.className = "cipx-formmsg err"; return; }
      submit.disabled = true;
      msg.textContent = "Sending…"; msg.className = "cipx-formmsg";
      var payload = {
        suggestion_type: typeSel.value,
        top_code: (topIn.value || "").trim().slice(0, 20) || null,
        top_title: (ctx.topTitle || "").slice(0, 200) || null,
        cip_code: (cipIn.value || "").trim().slice(0, 20) || null,
        cip_title: (ctx.cipTitle || "").slice(0, 200) || null,
        suggestion: body.value.trim().slice(0, 8000),
        submitter_name: (name.value || "").trim().slice(0, 120) || null,
        submitter_email: (email.value || "").trim().slice(0, 200),
        college: (college.value || "").trim().slice(0, 120) || null,
      };
      fetch(SUGGEST_INTAKE, {
        method: "POST",
        headers: {
          "apikey": SUPABASE_ANON,
          "Authorization": "Bearer " + SUPABASE_ANON,
          "Content-Type": "application/json",
          "Prefer": "return=minimal",
        },
        body: JSON.stringify(payload),
      }).then(function (res) {
        if (!res.ok) throw new Error("intake " + res.status);
        var ok = el("div", { class: "cipx-formok" }, [
          el("div", { class: "cipx-okh" }, ["✓ Sent to the Chancellor's Office"]),
          el("div", {}, ["Thank you — the CO curation team will review your suggestion. Nothing you submit is shown publicly."]),
        ]);
        form.parentNode.replaceChild(ok, form);
      }).catch(function () {
        submit.disabled = false;
        msg.textContent = "Couldn't send just now — please try again in a moment.";
        msg.className = "cipx-formmsg err";
      });
    };
    return form;
  }

  // ── cross-tab jump to the COCI course browser, prefiltered by TOP code ───────
  function gotoCoci(topCode) {
    try { sessionStorage.setItem("cpl_coci_focus", topCode); } catch (e) {}
    if (window.CPL_TABS && window.CPL_TABS.navigate) window.CPL_TABS.navigate("coci-lookup");
  }

  // ── results table ────────────────────────────────────────────────────────────
  function renderResults(host) {
    clear(host);
    var rows = filtered();
    var total = rows.length;
    var shown = rows.slice(0, state.limit);

    var count = el("div", { class: "cipx-count" }, [
      total.toLocaleString() + " mapping" + (total === 1 ? "" : "s") +
      (total > state.limit ? "  ·  showing " + state.limit.toLocaleString() : ""),
    ]);
    var csv = el("button", { class: "cipx-csv", type: "button", title: "Download the current filtered set as CSV",
      onclick: function () { exportCsv(rows); } }, ["⬇ CSV"]);
    host.appendChild(el("div", { class: "cipx-resbar" }, [count, csv]));

    if (!total) {
      host.appendChild(el("div", { class: "cipx-empty" }, ["No mappings match — loosen the search or filters."]));
      return;
    }

    var table = el("table", { class: "cipx-table" }, []);
    table.appendChild(el("colgroup", {}, [
      el("col", { style: "width:29%" }), el("col", { style: "width:33%" }),
      el("col", { style: "width:13%" }), el("col", { style: "width:12%" }),
      el("col", { style: "width:13%" }),
    ]));
    var thead = el("thead", {}, [el("tr", {}, [
      el("th", {}, [state.group === "cip" ? "CIP code" : "TOP code"]),
      el("th", {}, [state.group === "cip" ? "TOP code" : "CIP code"]),
      el("th", {}, ["Source"]),
      el("th", { class: "cipx-num" }, ["Colleges"]),
      el("th", {}, [""]),
    ])]);
    table.appendChild(thead);
    var tbody = el("tbody", {}, []);

    var prevA = null;
    shown.forEach(function (r) {
      var primary = state.group === "cip" ? r.cipCode : (r.topCode || "");
      var same = primary && primary === prevA;
      prevA = primary;

      var aCell, bCell;
      if (state.group === "cip") {
        aCell = same ? el("div", { class: "cipx-codewrap cipx-dim" }, []) : codeCell(r.cipCode, r.c ? r.c.t : "", "cip");
        bCell = codeCell(r.topCode, r.t ? r.t.t : "", "top");
      } else {
        aCell = same ? el("div", { class: "cipx-codewrap cipx-dim" }, []) : codeCell(r.topCode, r.t ? r.t.t : "", "top");
        bCell = codeCell(r.cipCode, r.c ? r.c.t : "", "cip");
      }
      // chips ride under the CIP cell
      var chipsHost = state.group === "cip" ? aCell : bCell;
      var chips = cteChips(r);
      if (chips.length) chipsHost.appendChild(el("div", { class: "cipx-chips" }, chips));

      var key = rowKey(r);
      var isOpen = !!state.open[key];
      var tr = el("tr", { class: "cipx-row" + (isOpen ? " cipx-open" : ""),
        onclick: function () { toggleRow(host, key); } }, [
        el("td", {}, [aCell]),
        el("td", {}, [bCell]),
        el("td", {}, [srcBadge(r.srcName)]),
        el("td", { class: "cipx-num" }, [r.count ? String(r.count) : "—"]),
        el("td", { class: "cipx-caret" }, [el("span", { class: "cipx-carets" }, [isOpen ? "▾" : "▸"])]),
      ]);
      tbody.appendChild(tr);

      if (isOpen) {
        var dtr = el("tr", { class: "cipx-detailrow" }, [el("td", { colspan: "5" }, [detailPanel(r)])]);
        tbody.appendChild(dtr);
      }
    });
    table.appendChild(tbody);
    host.appendChild(table);

    if (total > state.limit) {
      host.appendChild(el("div", { class: "cipx-more" }, [
        el("button", { class: "cipx-morebtn", type: "button",
          onclick: function () { state.limit += PAGE; renderResults(host); } },
          ["Show " + Math.min(PAGE, total - state.limit).toLocaleString() + " more"]),
      ]));
    }
  }

  function toggleRow(host, key) {
    if (state.open[key]) delete state.open[key]; else state.open[key] = true;
    renderResults(host);
  }

  function exportCsv(rows) {
    var out = ["TOP Code,TOP Title,CIP Code,CIP Title,Source,Noncredit,Colleges,Count"];
    rows.forEach(function (r) {
      function q(v) { return '"' + String(v == null ? "" : v).replace(/"/g, '""') + '"'; }
      out.push([q(r.topCode || ""), q(r.t ? r.t.t : ""), q(r.cipCode), q(r.c ? r.c.t : ""),
                q(r.srcName), q(r.nc ? "Yes" : "No"), q(r.colleges), q(r.count)].join(","));
    });
    var blob = new Blob([out.join("\n")], { type: "text/csv" });
    var a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "top_cip_crosswalk.csv";
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
  }

  // ── filter bar ───────────────────────────────────────────────────────────────
  var resultsHost = null;
  function refresh() { if (resultsHost) { state.limit = PAGE; renderResults(resultsHost); } }
  function setSearch(v) {
    state.q = (v || "").toLowerCase().trim();
    var box = document.getElementById("cipx-q"); if (box) box.value = v || "";
    refresh();
  }

  function filterBar() {
    var bar = el("div", { class: "cipx-filters" }, []);

    var q = el("input", { class: "cipx-search", id: "cipx-q", type: "search",
      placeholder: "Search TOP code, CIP code, title, or keyword (e.g. 0501, welding, nursing)…",
      autocomplete: "off" });
    var _t;
    q.oninput = function () {
      var v = q.value; clearTimeout(_t);
      _t = setTimeout(function () { state.q = v.toLowerCase().trim(); refresh(); }, 160);
    };
    bar.appendChild(el("div", { class: "cipx-searchrow" }, [q]));

    function sel(id, label, opts, onchange) {
      var s = el("select", { class: "cipx-fsel", id: id, "aria-label": label, onchange: onchange }, []);
      opts.forEach(function (o) { s.appendChild(el("option", { value: o[0] }, [o[1]])); });
      return el("label", { class: "cipx-fsell" }, [el("span", {}, [label]), s]);
    }

    var row = el("div", { class: "cipx-frow2" }, []);
    row.appendChild(sel("cipx-group", "Group by", [["top", "TOP → CIP"], ["cip", "CIP → TOP"]],
      function (e) { state.group = e.target.value; refresh(); }));
    row.appendChild(sel("cipx-credit", "Credit", [["all", "All credit types"], ["credit", "Credit only"], ["noncredit", "Noncredit only"]],
      function (e) { state.credit = e.target.value; refresh(); }));
    row.appendChild(sel("cipx-cte", "CTE", [["all", "CTE & non-CTE"], ["cte", "CTE only"], ["notcte", "Non-CTE only"]],
      function (e) { state.cte = e.target.value; refresh(); }));

    // sector (TOP) + family (CIP) dropdowns
    var secs = [["", "All sectors"]];
    var secSet = {}; Object.keys(D.top).forEach(function (k) { if (D.top[k].sec) secSet[D.top[k].sec] = 1; });
    Object.keys(secSet).sort().forEach(function (s) { secs.push([s, s]); });
    row.appendChild(sel("cipx-sector", "TOP sector", secs, function (e) { state.sector = e.target.value; refresh(); }));

    var fams = [["", "All CIP families"]];
    var famSet = {}; Object.keys(D.cip).forEach(function (k) { var c = D.cip[k]; if (c.fam && c.famt) famSet[c.fam] = c.famt; });
    Object.keys(famSet).sort().forEach(function (f) { fams.push([f, f + " · " + famSet[f]]); });
    row.appendChild(sel("cipx-family", "CIP family", fams, function (e) { state.family = e.target.value; refresh(); }));
    bar.appendChild(row);

    // source toggle chips
    var srcRow = el("div", { class: "cipx-srcrow" }, [el("span", { class: "cipx-srclbl" }, ["Source"])]);
    D.sources.forEach(function (name, idx) {
      var b = el("button", { class: "cipx-srctog cipx-src-" + (SRC_TIER[name] || "none"), type: "button",
        "data-idx": idx, title: name,
        onclick: function () {
          if (state.sources[idx]) delete state.sources[idx]; else state.sources[idx] = true;
          b.classList.toggle("on");
          refresh();
        } }, [SRC_SHORT[name] || name]);
      srcRow.appendChild(b);
    });
    var reset = el("button", { class: "cipx-reset", type: "button", title: "Clear all filters",
      onclick: function () {
        state = { q: "", group: "top", credit: "all", cte: "all", sources: {}, sector: "", family: "", limit: PAGE, open: {} };
        rebuildShell();
      } }, ["Reset"]);
    srcRow.appendChild(reset);
    bar.appendChild(srcRow);

    return bar;
  }

  // ── header ────────────────────────────────────────────────────────────────────
  function header() {
    var nTop = Object.keys(D.top).length, nCip = Object.keys(D.cip).length, nPair = D.pairs.length;
    var stats = el("div", { class: "cipx-stats" }, [
      statCard(nTop.toLocaleString(), "TOP codes"),
      statCard(nCip.toLocaleString(), "CIP codes"),
      statCard(nPair.toLocaleString(), "mappings"),
      statCard("Fall 2026", "transition", true),
    ]);
    return el("div", { class: "cipx-head" }, [
      el("div", { class: "cipx-titlerow" }, [
        el("h2", { class: "cipx-h2" }, ["TOP ↔ CIP Crosswalk"]),
        el("button", { class: "cipx-topsuggest", type: "button",
          onclick: openGlobalSuggest }, ["✍️ Suggest a change"]),
      ]),
      el("p", { class: "cipx-lede" }, [
        "The Chancellor's Office is transitioning course & program coding from ",
        el("b", {}, ["TOP"]), " to ", el("b", {}, ["CIP"]), " codes, effective fall 2026. ",
        "Search the crosswalk, read the CIP definitions, see which colleges already use each pairing — and ",
        el("b", {}, ["send the CO your suggested changes and notes"]), " as faculty in the field.",
      ]),
      el("div", { class: "cipx-links" }, [
        el("a", { href: ESS_MEMO, target: "_blank", rel: "noopener" }, ["ESS 26-06 implementation guidance ↗"]),
        el("a", { href: NONCREDIT_MAP, target: "_blank", rel: "noopener" }, ["Noncredit TOP-CIP mapping ↗"]),
        el("a", { href: CIP_BROWSE, target: "_blank", rel: "noopener" }, ["Browse the full CIP taxonomy (NCES) ↗"]),
      ]),
      stats,
    ]);
  }
  function statCard(n, label, accent) {
    return el("div", { class: "cipx-stat" + (accent ? " cipx-stat-accent" : "") }, [
      el("div", { class: "cipx-statn" }, [n]),
      el("div", { class: "cipx-statl" }, [label]),
    ]);
  }

  // global suggest (not tied to a row) — opens a modal-ish overlay
  function openGlobalSuggest() {
    var back = el("div", { class: "cipx-modalback", onclick: function (e) { if (e.target === back) document.body.removeChild(back); } }, []);
    var card = el("div", { class: "cipx-modal" }, [
      el("div", { class: "cipx-modalh" }, [
        el("h3", {}, ["Suggest a change to the TOP ↔ CIP crosswalk"]),
        el("button", { class: "cipx-modalx", type: "button", title: "Close",
          onclick: function () { document.body.removeChild(back); } }, ["✕"]),
      ]),
      el("p", { class: "cipx-modalsub" }, ["Propose a new mapping, flag a wrong one, or leave a note for the Chancellor's Office. Your submission is private to the CO curation team."]),
    ]);
    card.appendChild(suggestForm({}));
    back.appendChild(card);
    document.body.appendChild(back);
  }

  // ── shell ────────────────────────────────────────────────────────────────────
  function rebuildShell() {
    var root = document.getElementById(ROOT_ID);
    if (!root) return;
    clear(root);
    root.removeAttribute("style");
    var wrap = el("div", { class: "cipx" }, []);
    wrap.appendChild(header());
    wrap.appendChild(filterBar());
    resultsHost = el("div", { class: "cipx-results" }, []);
    wrap.appendChild(resultsHost);
    root.appendChild(wrap);
    renderResults(resultsHost);
  }

  // ── CSS (scoped under .cipx) ─────────────────────────────────────────────────
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var css = [
      ".cipx{max-width:1180px;margin:0 auto;font-size:.92rem;color:var(--text,#243b53);}",
      ".cipx-head{margin:4px 0 14px;}",
      ".cipx-titlerow{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;}",
      ".cipx-h2{margin:0;font-size:1.5rem;color:var(--text-strong,#102a43);}",
      ".cipx-topsuggest,.cipx-suggestbtn{background:var(--seal-blue,#00356B);color:#fff;border:0;border-radius:7px;padding:8px 14px;font-weight:700;cursor:pointer;font-size:.85rem;}",
      ".cipx-topsuggest:hover,.cipx-suggestbtn:hover{filter:brightness(1.12);}",
      ".cipx-lede{margin:8px 0 6px;line-height:1.5;color:var(--text,#334e68);max-width:78ch;}",
      ".cipx-links{display:flex;gap:16px;flex-wrap:wrap;margin:6px 0 12px;font-size:.82rem;}",
      ".cipx-links a{color:var(--link,#0b6bcb);text-decoration:none;font-weight:600;}",
      ".cipx-links a:hover{text-decoration:underline;}",
      ".cipx-stats{display:flex;gap:10px;flex-wrap:wrap;}",
      ".cipx-stat{background:var(--surface-2,rgba(20,30,60,.05));border:1px solid var(--border,#d9e2ec);border-radius:8px;padding:8px 14px;min-width:96px;}",
      ".cipx-stat-accent{background:var(--seal-blue,#00356B);border-color:var(--seal-blue,#00356B);}",
      ".cipx-stat-accent .cipx-statn,.cipx-stat-accent .cipx-statl{color:#fff;}",
      ".cipx-statn{font-size:1.25rem;font-weight:800;color:var(--text-strong,#102a43);line-height:1.1;}",
      ".cipx-statl{font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;color:var(--text-muted,#829ab1);margin-top:2px;}",
      // filters
      ".cipx-filters{position:sticky;top:0;z-index:5;background:var(--surface,#fff);padding:10px 0;border-bottom:1px solid var(--border,#d9e2ec);margin-bottom:8px;}",
      ".cipx-search{width:100%;box-sizing:border-box;padding:11px 14px;border:1.5px solid var(--border-strong,#bcccdc);border-radius:9px;font-size:1rem;color:var(--text,#243b53);background:var(--surface,#fff);}",
      ".cipx-search:focus{outline:2px solid var(--seal-blue,#00356B);outline-offset:1px;border-color:var(--seal-blue,#00356B);}",
      ".cipx-frow2{display:flex;gap:10px;flex-wrap:wrap;margin-top:9px;}",
      ".cipx-fsell{display:flex;flex-direction:column;gap:2px;font-size:.66rem;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted,#829ab1);}",
      ".cipx-fsel{padding:6px 8px;border:1px solid var(--border,#d9e2ec);border-radius:6px;font-size:.82rem;background:var(--surface,#fff);color:var(--text,#243b53);cursor:pointer;max-width:220px;}",
      ".cipx-srcrow{display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin-top:9px;}",
      ".cipx-srclbl{font-size:.66rem;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted,#829ab1);margin-right:2px;}",
      ".cipx-srctog{font-size:.74rem;font-weight:700;border:1px solid var(--border-strong,#bcccdc);background:var(--surface,#fff);color:var(--text-muted,#627d98);border-radius:20px;padding:4px 11px;cursor:pointer;opacity:.7;}",
      ".cipx-srctog.on{opacity:1;color:#fff;}",
      ".cipx-srctog.cipx-src-official.on{background:#1a7f43;border-color:#1a7f43;}",
      ".cipx-srctog.cipx-src-field.on{background:#b5730a;border-color:#b5730a;}",
      ".cipx-srctog.cipx-src-noncredit.on{background:#0e7490;border-color:#0e7490;}",
      ".cipx-srctog.cipx-src-coe.on{background:#6b46c1;border-color:#6b46c1;}",
      ".cipx-srctog.cipx-src-none.on{background:#627d98;border-color:#627d98;}",
      ".cipx-reset{margin-left:auto;font-size:.76rem;font-weight:600;color:var(--link,#0b6bcb);background:none;border:0;cursor:pointer;text-decoration:underline;}",
      // results
      ".cipx-resbar{display:flex;align-items:center;justify-content:space-between;margin:6px 2px 6px;}",
      ".cipx-count{font-size:.82rem;color:var(--text-muted,#627d98);font-weight:600;}",
      ".cipx-csv{font-size:.78rem;font-weight:700;color:var(--link,#0b6bcb);background:none;border:1px solid var(--border,#d9e2ec);border-radius:6px;padding:4px 10px;cursor:pointer;}",
      ".cipx-table{width:100%;table-layout:fixed;border-collapse:collapse;font-size:.86rem;}",
      ".cipx-table th{text-align:left;font-size:.66rem;text-transform:uppercase;letter-spacing:.05em;color:var(--text-muted,#829ab1);padding:6px 8px;border-bottom:1px solid var(--border,#d9e2ec);}",
      ".cipx-table td{padding:8px;border-bottom:1px solid var(--border,#eef2f7);vertical-align:top;}",
      ".cipx-num{text-align:center;}",
      "th.cipx-num{text-align:center;}",
      ".cipx-row{cursor:pointer;}",
      ".cipx-row:hover{background:var(--surface-subtle,#f5f8fc);}",
      ".cipx-open{background:var(--surface-subtle,#f0f6ff);}",
      ".cipx-codewrap{display:flex;flex-direction:column;gap:2px;min-height:1px;}",
      ".cipx-code{align-self:flex-start;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-weight:700;font-size:.82rem;border:0;background:none;cursor:pointer;padding:0;}",
      ".cipx-code-top{color:#0e7490;}",
      ".cipx-code-cip{color:#6b46c1;}",
      ".cipx-code:hover{text-decoration:underline;}",
      ".cipx-codettl{font-size:.8rem;color:var(--text,#334e68);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}",
      ".cipx-dim{opacity:.35;}",
      ".cipx-chips{display:flex;gap:4px;flex-wrap:wrap;margin-top:3px;}",
      ".cipx-chip{font-size:.62rem;font-weight:800;text-transform:uppercase;letter-spacing:.04em;padding:1px 6px;border-radius:4px;}",
      ".cipx-chip.cte{background:#dcfce7;color:#166534;}",
      ".cipx-chip.nc{background:#cffafe;color:#155e75;}",
      ".cipx-chip.new{background:#dbeafe;color:#1e40af;}",
      ".cipx-chip.del{background:#fee2e2;color:#991b1b;}",
      ".cipx-chip.moved{background:#fef3c7;color:#92400e;}",
      ".cipx-src{font-size:.68rem;font-weight:800;padding:2px 8px;border-radius:20px;white-space:nowrap;}",
      ".cipx-src-official{background:#dcfce7;color:#14532d;}",
      ".cipx-src-field{background:#fef3c7;color:#854d0e;}",
      ".cipx-src-noncredit{background:#cffafe;color:#155e75;}",
      ".cipx-src-coe{background:#ede9fe;color:#5b21b6;}",
      ".cipx-src-none{background:#eef2f7;color:#627d98;}",
      ".cipx-caret{text-align:center;color:var(--text-muted,#829ab1);}",
      // detail
      ".cipx-detailrow td{background:var(--surface-subtle,#f7fafe);padding:0;}",
      ".cipx-detail{display:grid;grid-template-columns:1fr 1.3fr 1fr;gap:18px;padding:16px 14px;}",
      ".cipx-dcol{min-width:0;}",
      ".cipx-dh{font-size:.64rem;text-transform:uppercase;letter-spacing:.07em;color:var(--text-muted,#829ab1);font-weight:800;margin-bottom:3px;}",
      ".cipx-dttl{font-weight:700;color:var(--text-strong,#102a43);line-height:1.25;margin-bottom:4px;}",
      ".cipx-dmeta{font-size:.78rem;color:var(--text,#486581);margin:2px 0;}",
      ".cipx-dchange{color:#92400e;font-weight:600;}",
      ".cipx-ddef{font-size:.82rem;line-height:1.5;color:var(--text,#334e68);margin:6px 0;}",
      ".cipx-dsub{font-size:.78rem;line-height:1.45;color:var(--text,#486581);margin:4px 0;}",
      ".cipx-dsublbl{font-size:.64rem;text-transform:uppercase;letter-spacing:.06em;color:var(--text-muted,#829ab1);font-weight:800;margin:8px 0 4px;}",
      ".cipx-dnote{font-size:.8rem;font-style:italic;color:var(--text-muted,#627d98);}",
      ".cipx-socchips{display:flex;flex-wrap:wrap;gap:5px;}",
      ".cipx-socchip{font-size:.7rem;background:var(--surface,#fff);border:1px solid var(--border,#d9e2ec);border-radius:5px;padding:2px 7px;color:var(--link,#0b6bcb);text-decoration:none;}",
      ".cipx-socchip:hover{border-color:var(--link,#0b6bcb);}",
      ".cipx-dlinks{margin-top:8px;}",
      ".cipx-linkbtn{font-size:.78rem;font-weight:700;color:#0e7490;background:none;border:1px solid #0e7490;border-radius:6px;padding:5px 10px;cursor:pointer;}",
      ".cipx-linkbtn:hover{background:#ecfeff;}",
      ".cipx-colleges{font-size:.76rem;line-height:1.45;color:var(--text,#486581);margin-top:3px;max-height:120px;overflow:auto;}",
      ".cipx-suggestbtn{margin-top:12px;}",
      // form
      ".cipx-form{margin-top:12px;display:flex;flex-direction:column;gap:8px;background:var(--surface,#fff);border:1px solid var(--border,#d9e2ec);border-radius:9px;padding:14px;}",
      ".cipx-fl{display:flex;flex-direction:column;gap:3px;font-size:.68rem;text-transform:uppercase;letter-spacing:.04em;color:var(--text-muted,#829ab1);font-weight:700;}",
      ".cipx-frow{display:flex;gap:10px;flex-wrap:wrap;}",
      ".cipx-frow .cipx-fl{flex:1;min-width:120px;}",
      ".cipx-in{padding:7px 9px;border:1px solid var(--border-strong,#bcccdc);border-radius:6px;font-size:.86rem;color:var(--text,#243b53);background:var(--surface,#fff);font-family:inherit;text-transform:none;letter-spacing:normal;font-weight:400;}",
      ".cipx-ta{resize:vertical;min-height:56px;}",
      ".cipx-factions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;}",
      ".cipx-fsubmit{background:var(--seal-blue,#00356B);color:#fff;border:0;border-radius:7px;padding:9px 16px;font-weight:700;cursor:pointer;}",
      ".cipx-fsubmit:disabled{opacity:.6;cursor:default;}",
      ".cipx-formmsg{font-size:.8rem;color:var(--text-muted,#627d98);}",
      ".cipx-formmsg.err{color:#b91c1c;font-weight:600;}",
      ".cipx-formok{background:#dcfce7;border:1px solid #86efac;border-radius:9px;padding:14px;margin-top:12px;}",
      ".cipx-okh{font-weight:800;color:#166534;margin-bottom:3px;}",
      ".cipx-more{text-align:center;margin:14px 0;}",
      ".cipx-morebtn{font-size:.84rem;font-weight:700;color:var(--seal-blue,#00356B);background:var(--surface,#fff);border:1px solid var(--border-strong,#bcccdc);border-radius:7px;padding:8px 18px;cursor:pointer;}",
      ".cipx-empty{text-align:center;padding:40px;color:var(--text-muted,#829ab1);}",
      // modal
      ".cipx-modalback{position:fixed;inset:0;background:rgba(16,42,67,.5);z-index:1000;display:flex;align-items:flex-start;justify-content:center;padding:40px 16px;overflow:auto;}",
      ".cipx-modal{background:var(--surface,#fff);border-radius:12px;max-width:560px;width:100%;padding:22px;box-shadow:0 20px 60px rgba(0,0,0,.3);}",
      ".cipx-modalh{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;}",
      ".cipx-modalh h3{margin:0;font-size:1.15rem;color:var(--text-strong,#102a43);}",
      ".cipx-modalx{background:none;border:0;font-size:1.2rem;cursor:pointer;color:var(--text-muted,#829ab1);}",
      ".cipx-modalsub{font-size:.84rem;color:var(--text,#486581);margin:6px 0 2px;line-height:1.45;}",
      "@media (max-width:820px){.cipx-detail{grid-template-columns:1fr;}.cipx-codettl{white-space:normal;}}",
    ].join("");
    var st = el("style", { id: CSS_ID });
    st.textContent = css;
    document.head.appendChild(st);
  }

  // ── public API / lifecycle ────────────────────────────────────────────────────
  var _rendered = false;
  function activate() {
    ensureCss();
    var root = document.getElementById(ROOT_ID);
    if (!root) return;
    if (_rendered) return;
    D = window.CIP_CROSSWALK;
    if (!D || !D.pairs) {
      clear(root); root.removeAttribute("style");
      root.appendChild(el("div", { class: "cipx-empty" },
        ["CIP crosswalk data unavailable — cip_crosswalk_data.js failed to load. Rebuild: python3 kb/_build_cip_crosswalk.py"]));
      return;
    }
    _rendered = true;
    buildIndex();
    rebuildShell();
  }

  window.CPL_CIP_CROSSWALK = {
    activate: activate,
    // test seams
    _passes: passes, _filtered: filtered, _buildIndex: function (d) { D = d; buildIndex(); },
  };
})();
