window.CCC_COLLEGE_LOOKUP = {
  // Bay Area Region (Region 3)
  "Allan Hancock College": { district: "Santa Barbara County Community College District", swRegion: "South Central Coast (Region 6)" },
  "Cabrillo College": { district: "Cabrillo College District", swRegion: "South Central Coast (Region 6)" },
  "Canada College": { district: "San Mateo County Community College District", swRegion: "Bay Area (Region 3)" },
  "Chabot College": { district: "Chabot-Las Positas Community College District", swRegion: "Bay Area (Region 3)" },
  "Chaffey College": { district: "Chaffey Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "City College of San Francisco": { district: "San Francisco Community College District", swRegion: "Bay Area (Region 3)" },
  "College of Alameda": { district: "Peralta Community College District", swRegion: "Bay Area (Region 3)" },
  "College of the Desert": { district: "College of the Desert District", swRegion: "Inland Empire/Desert (Region 9)" },
  "College of the Redwoods": { district: "College of the Redwoods District", swRegion: "North Far North (Region 1)" },
  "Compton College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Copper Mountain College": { district: "Copper Mountain College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Cosumnes River College": { district: "Los Rios Community College District", swRegion: "Capital (Region 2)" },
  "Crafton Hills College": { district: "San Bernardino Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Cuesta College": { district: "Cuesta College District", swRegion: "South Central Coast (Region 6)" },
  "Cuyamaca College": { district: "Grossmont-Cuyamaca Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "De Anza College": { district: "Foothill-De Anza Community College District", swRegion: "Bay Area (Region 3)" },
  "Diablo Valley College": { district: "Contra Costa Community College District", swRegion: "Bay Area (Region 3)" },
  "East Los Angeles College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "El Camino College": { district: "El Camino Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Feather River College": { district: "Feather River Community College District", swRegion: "North Far North (Region 1)" },
  "Foothill College": { district: "Foothill-De Anza Community College District", swRegion: "Bay Area (Region 3)" },
  "Fullerton College": { district: "North Orange County Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Gavilan College": { district: "Gavilan Joint Community College District", swRegion: "Capital (Region 2)" },
  "Glendale Community College": { district: "Glendale Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Golden West College": { district: "Coast Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Grossmont College": { district: "Grossmont-Cuyamaca Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "Hartnell College": { district: "Hartnell Community College District", swRegion: "Capital (Region 2)" },
  "Imperial Valley College": { district: "Imperial Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "Irvine Valley College": { district: "Saddleback Valley Unified School District", swRegion: "LA/Orange County (Region 7/8)" },
  "Lake Tahoe Community College": { district: "Lake Tahoe Community College District", swRegion: "Capital (Region 2)" },
  "Laney College": { district: "Peralta Community College District", swRegion: "Bay Area (Region 3)" },
  "Lassen Community College": { district: "Lassen Community College District", swRegion: "North Far North (Region 1)" },
  "Long Beach City College": { district: "Long Beach Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Angeles City College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Angeles Harbor College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Angeles Mission College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Angeles Pierce College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Angeles Southwest College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Angeles Trade-Technical College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Angeles Valley College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Los Rios Community College District": { district: "Los Rios Community College District", swRegion: "Capital (Region 2)" },
  "Mendocino College": { district: "Mendocino-Lake Community College District", swRegion: "North Far North (Region 1)" },
  "Merced College": { district: "Merced Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Merritt College": { district: "Peralta Community College District", swRegion: "Bay Area (Region 3)" },
  "MiraCosta College": { district: "MiraCosta Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "Mission College": { district: "Santa Clara County Community College District", swRegion: "Bay Area (Region 3)" },
  "Modesto Junior College": { district: "Modesto Junior College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Monterey Peninsula College": { district: "Monterey Peninsula College District", swRegion: "South Central Coast (Region 6)" },
  "Moorpark College": { district: "Ventura County Community College District", swRegion: "South Central Coast (Region 6)" },
  "Moreno Valley College": { district: "Riverside Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Mt. San Antonio College": { district: "Mt. San Antonio Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Mt. San Jacinto College": { district: "Mt. San Jacinto Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Napa Valley College": { district: "Napa Valley Community College District", swRegion: "Bay Area (Region 3)" },
  "Norco College": { district: "Riverside Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Orange Coast College": { district: "Coast Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Oxnard College": { district: "Ventura County Community College District", swRegion: "South Central Coast (Region 6)" },
  "Palo Verde College": { district: "Palo Verde Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Palomar College": { district: "Palomar Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "Pasadena City College": { district: "Pasadena Area Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Reedley College": { district: "State Center Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Rio Hondo College": { district: "Rio Hondo Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Riverside City College": { district: "Riverside Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Sacramento City College": { district: "Los Rios Community College District", swRegion: "Capital (Region 2)" },
  "Saddleback College": { district: "Saddleback Valley Unified School District", swRegion: "LA/Orange County (Region 7/8)" },
  "San Bernardino Valley College": { district: "San Bernardino Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "San Diego City College": { district: "San Diego Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "San Diego College of Continuing Education": { district: "San Diego Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "San Diego Mesa College": { district: "San Diego Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "San Diego Miramar College": { district: "San Diego Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "San Jose City College": { district: "San Jose-Evergreen Community College District", swRegion: "Bay Area (Region 3)" },
  "San Mateo College of San Mateo": { district: "San Mateo County Community College District", swRegion: "Bay Area (Region 3)" },
  "Santa Ana College": { district: "Santa Ana Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Santa Barbara City College": { district: "Santa Barbara Community College District", swRegion: "South Central Coast (Region 6)" },
  "Santa Cruz County Office of Education Community Colleges": { district: "Santa Cruz County", swRegion: "South Central Coast (Region 6)" },
  "Santa Monica College": { district: "Santa Monica Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Santiago Canyon College": { district: "Rancho Santiago Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Sequoias, College of the": { district: "College of the Sequoias District", swRegion: "Capital (Region 2)" },
  "Shasta College": { district: "Shasta-Tehama-Trinity Joint Community College District", swRegion: "North Far North (Region 1)" },
  "Sierra College": { district: "Sierra Joint Community College District", swRegion: "Capital (Region 2)" },
  "Skyline College": { district: "San Mateo County Community College District", swRegion: "Bay Area (Region 3)" },
  "Southwestern College": { district: "Southwestern Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "St. Mary's College of California": { district: "Saint Mary's College District", swRegion: "Bay Area (Region 3)" },
  "State Center Community College District": { district: "State Center Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Taft College": { district: "Taft Community College District", swRegion: "Capital (Region 2)" },
  "Tulare County Office of Education Community Colleges": { district: "Tulare County", swRegion: "Capital (Region 2)" },
  "Ventura College": { district: "Ventura County Community College District", swRegion: "South Central Coast (Region 6)" },
  "Victorville, Victor Valley College": { district: "Victor Valley Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "West Los Angeles College": { district: "Los Angeles Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "West Valley College": { district: "West Valley-Mission Community College District", swRegion: "Bay Area (Region 3)" },

  // Additional colleges - Capital/Central Valley Regions
  "American River College": { district: "Los Rios Community College District", swRegion: "Capital (Region 2)" },
  "Antelope Valley College": { district: "Antelope Valley Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Bakersfield College": { district: "Kern Community College District", swRegion: "Capital (Region 2)" },
  "Barstow Community College": { district: "Barstow Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Cerritos College": { district: "Cerritos Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Citrus College": { district: "Citrus Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Coastline Community College": { district: "Coast Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Columbia College": { district: "Tuolumne County Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Consumnes River College": { district: "Los Rios Community College District", swRegion: "Capital (Region 2)" },
  "Contra Costa College": { district: "Contra Costa Community College District", swRegion: "Bay Area (Region 3)" },
  "Cuesta College": { district: "Cuesta College District", swRegion: "South Central Coast (Region 6)" },
  "Folsom Lake College": { district: "Los Rios Community College District", swRegion: "Capital (Region 2)" },
  "Fresno City College": { district: "State Center Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Humboldt State University": { district: "Humboldt State University System", swRegion: "North Far North (Region 1)" },
  "Las Positas College": { district: "Chabot-Las Positas Community College District", swRegion: "Bay Area (Region 3)" },
  "Madera Community College": { district: "Madera Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Porterville College": { district: "Kern Community College District", swRegion: "Capital (Region 2)" },
  "Rancho Santiago": { district: "Rancho Santiago Community College District", swRegion: "LA/Orange County (Region 7/8)" },
  "Santa Cruz County Office": { district: "Santa Cruz County", swRegion: "South Central Coast (Region 6)" },
  "Tulare County": { district: "Tulare County", swRegion: "Capital (Region 2)" },

  // Additional colleges from MAP exhibit data
  "Berkeley City College": { district: "Peralta Community College District", swRegion: "Bay Area (Region 3)" },
  "Butte College": { district: "Butte-Glenn Community College District", swRegion: "North Far North (Region 1)" },
  "Calbright College Credit": { district: "Calbright College", swRegion: "Capital (Region 2)" },
  "Cañada College": { district: "San Mateo County Community College District", swRegion: "Bay Area (Region 3)" },
  "Cerro Coso Community College": { district: "Kern Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Clovis Community College": { district: "State Center Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Coalinga College": { district: "West Hills Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "College of Marin": { district: "Marin Community College District", swRegion: "Bay Area (Region 3)" },
  "College of San Mateo": { district: "San Mateo County Community College District", swRegion: "Bay Area (Region 3)" },
  "College of the Canyons": { district: "Santa Clarita Community College District", swRegion: "LA/Orange County (Region 7)" },
  "College of the Sequoias": { district: "Sequoias Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "College of the Siskiyous": { district: "Siskiyous Joint Community College District", swRegion: "North Far North (Region 1)" },
  "Cypress College": { district: "North Orange County Community College District", swRegion: "Orange County (Region 8)" },
  "Evergreen Valley College": { district: "San Jose-Evergreen Community College District", swRegion: "Bay Area (Region 3)" },
  "Lassen College": { district: "Lassen Community College District", swRegion: "North Far North (Region 1)" },
  "Lemoore College": { district: "West Hills Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Los Angeles Trade Technical College": { district: "Los Angeles Community College District", swRegion: "LA Basin (Region 7)" },
  "Los Medanos College": { district: "Contra Costa Community College District", swRegion: "Bay Area (Region 3)" },
  "Madera College": { district: "State Center Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "North Orange Continuing Education": { district: "North Orange County Community College District", swRegion: "Orange County (Region 8)" },
  "North Orange Continuing Education Credit": { district: "North Orange County Community College District", swRegion: "Orange County (Region 8)" },
  "Ohlone College": { district: "Ohlone Community College District", swRegion: "Bay Area (Region 3)" },
  "San Diego College of Continuing Education Credit": { district: "San Diego Community College District", swRegion: "San Diego/Imperial (Region 10)" },
  "San Joaquin Delta College": { district: "San Joaquin Delta Community College District", swRegion: "Central/Mother Lode (Region 5)" },
  "Santa Rosa Junior College": { district: "Sonoma County Junior College District", swRegion: "Bay Area (Region 3)" },
  "Solano Community College": { district: "Solano Community College District", swRegion: "Bay Area (Region 3)" },
  "Victor Valley College": { district: "Victor Valley Community College District", swRegion: "Inland Empire/Desert (Region 9)" },
  "Woodland Community College": { district: "Yuba Community College District", swRegion: "North Far North (Region 1)" },
  "Yuba College": { district: "Yuba Community College District", swRegion: "North Far North (Region 1)" },
};
