// Course Credit tab — per-college Veteran Sprint goal 2 (SkyNaut, Session 128, 2026-08-08).
//
// STATIC consumer asset (NOT regenerated by excel_to_dashboard.py), lazy-loaded
// by the inline boot in the tab shell on first activation of #tab-course-credit.
//
// WHAT IT ANSWERS. Veteran Sprint goal 2 is "award COURSE credit for basic
// training, not generic elective / CSU-GE Area E". MAP already labels every
// awarded row with which of those three it is, in `course_type` — a field the
// colleges do NOT fill in themselves, which is exactly why it is trustworthy
// where `College Course` and `Status` were not. This tab is that split, per
// college.
//
// THREE RULES IT FOLLOWS:
//  1. NEVER RANK COLLEGES. Standing project rule. The table sorts, because a
//     curator needs to find things, but nothing here carries a position number,
//     a league placing, or a word like "worst". The framing is unclaimed
//     opportunity — the statewide backlog is credit students have ALREADY
//     EARNED and nobody has awarded.
//  2. It reads the PUBLISHED table (map_college_goal2), never the student grain.
//     Suppression is already applied at write time per
//     docs/kb-notes/adr-student-detail-aggregate-disclosure-control.md — k=10 on
//     distinct students, plus complementary suppression so a hidden cell cannot
//     be recovered by subtracting its siblings from a total.
//  3. It states its own freshness. Sam wants this reloaded NIGHTLY, so a tab
//     showing last week's numbers as if they were today's is worse than one that
//     says it is stale.
//
// TEAM-GATED (the governance.js / sierra_training.js posture). The underlying
// table is RLS-gated to reviewer-or-team anyway, so a logged-out visitor sees
// the gate rather than an empty table pretending to be zero.
(function () {
  "use strict";

  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var REST = SUPABASE_URL + "/rest/v1";
  var TEAM_PASS_KEY = "cpl_team_pass";
  // College names come from the live map_colleges lookup, not a committed file:
  // map_college_users is the only source carrying MAP's numeric CollegeID next to
  // a name, and a snapshot would drift the moment a college is added. Publicly
  // readable, so this resolves even before sign-in.
  var NAMES_URL = REST + "/map_colleges?select=college_id,college_name";

  var DESTS = ["COURSE", "AREA", "ELECTIVE"];

  var state = {
    cells: null,      // rows from map_college_goal2
    credits: null,    // rows from map_college_credit_summary, keyed by college_id
    load: null,       // latest map_data_loads row for map_student_credit
    names: null,      // { "<college_id>": "College Name" }
    namesMissing: false,
    loading: false,
    error: null,
    loadedSignedIn: false,
    q: "",
    band: "all",
    sort: "share"
  };

  // ── Auth (shared cpl_sb magic-link session + cpl_team_pass phrase) ──
  function isValidJwt(t) { return typeof t === "string" && t.split(".").length === 3 && t.length > 40; }
  function getSession() {
    try {
      var s = JSON.parse(sessionStorage.getItem("cpl_sb") || "null");
      if (s && isValidJwt(s.access_token)) return { access_token: s.access_token, email: s.email || "(reviewer)" };
    } catch (e) {}
    try {
      var p = localStorage.getItem(TEAM_PASS_KEY);
      if (p) return { teamPass: p, email: "(team)" };
    } catch (e) {}
    return null;
  }
  function authHeaders() {
    var s = getSession();
    var token = (s && s.access_token) || SUPABASE_ANON;
    var h = { apikey: SUPABASE_ANON, Authorization: "Bearer " + token };
    if (s && s.teamPass) h["x-team-pass"] = s.teamPass;
    return h;
  }
  function signedIn() { return !!getSession(); }

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function pct(x) { return (Math.round(x * 1000) / 10).toFixed(1) + "%"; }
  function num(x) {
    if (x == null) return null;
    return Math.round(Number(x)).toLocaleString("en-US");
  }

  var CSS_ID = "goal2-css";
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var css = [
      ".g2 { max-width: 1100px; margin: 0 auto; color: var(--text-body); }",
      ".g2 h2 { color: var(--navy-primary); margin: 16px 0 4px; }",
      ".g2 h3 { color: var(--navy-primary); margin: 26px 0 6px; font-size: 1.05rem; }",
      ".g2-intro { color: var(--text-muted); max-width: 900px; margin: 0 0 14px; font-size: .92rem; }",
      ".g2-principle { border-left:3px solid var(--seal-blue); padding:8px 12px; margin:0 0 16px;"
        + " background: var(--surface-subtle); font-size:.92rem; }",
      ".g2-stat { display:flex; flex-wrap:wrap; gap:10px; margin:0 0 6px; }",
      ".g2-stat .box { flex:1 1 150px; border:1px solid var(--border); border-radius:8px;"
        + " background: var(--surface-subtle); padding:10px 12px; }",
      ".g2-stat .box .n { font-size:1.4rem; font-weight:700; color: var(--navy-primary); }",
      ".g2-stat .box .l { font-size:.72rem; color: var(--text-muted); }",
      ".g2-fresh { font-size:.72rem; color: var(--text-muted); margin:0 0 18px; }",
      ".g2-fresh.stale { color: var(--danger, #b3261e); font-weight:600; }",
      ".g2-toolbar { display:flex; gap:8px; align-items:center; margin:0 0 10px; flex-wrap:wrap; }",
      ".g2-toolbar input[type=search] { flex:1 1 220px; min-width:160px; padding:5px 9px; font-size:.82rem;"
        + " border:1px solid var(--border); border-radius:6px; background: var(--surface); color: var(--text-body); }",
      ".g2-toolbar select { padding:5px 8px; font-size:.8rem; border:1px solid var(--border);"
        + " border-radius:6px; background: var(--surface); color: var(--text-body); }",
      ".g2-count { font-size:.75rem; color: var(--text-muted); }",
      ".g2-table { width:100%; border-collapse:collapse; table-layout:fixed; font-size:.82rem; }",
      ".g2-table th { text-align:left; padding:6px 8px; border-bottom:2px solid var(--border-strong);"
        + " color: var(--text-muted); font-size:.72rem; text-transform:uppercase; letter-spacing:.03em; }",
      ".g2-table td { padding:7px 8px; border-bottom:1px solid var(--border); vertical-align:middle;"
        + " overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }",
      ".g2-table td.num, .g2-table th.num { text-align:right; font-variant-numeric:tabular-nums; }",
      ".g2-name { font-weight:600; }",
      ".g2-sup { color: var(--text-muted); font-style:italic; }",
      ".g2-bar { position:relative; height:14px; border-radius:7px; background: var(--surface-muted); overflow:hidden; }",
      ".g2-bar i { position:absolute; left:0; top:0; bottom:0; background: var(--hunter, #2c601a); }",
      ".g2-share { font-weight:700; color: var(--navy-primary); }",
      ".g2-chip { font-size:.68rem; border-radius:10px; padding:1px 8px; white-space:nowrap;"
        + " background: var(--surface-muted); color: var(--text-muted); }",
      ".g2-chip.full { background: var(--hunter, #2c601a); color:#fff; }",
      ".g2-exemplar { border:1px solid var(--border); border-radius:8px; padding:10px 12px; margin:0 0 18px;"
        + " background: var(--surface-subtle); }",
      ".g2-exemplar .who { font-size:.82rem; line-height:1.7; }",
      ".g2-gate { color: var(--text-muted); padding:18px; border:1px dashed var(--border-strong);"
        + " border-radius:8px; background: var(--surface-subtle); }",
      ".g2-note { font-size:.75rem; color: var(--text-muted); margin-top:8px; }",
      ".g2-wrap { overflow-x:auto; }"
    ].join("\n");
    var el = document.createElement("style");
    el.id = CSS_ID; el.textContent = css;
    document.head.appendChild(el);
  }

  // ── Data ──
  function jget(url, opts) {
    return fetch(url, opts || {}).then(function (r) {
      // A failed read is NOT an empty result — never render a 401 as "no data".
      if (!r.ok) throw new Error("HTTP " + r.status + " on " + url.split("?")[0]);
      return r.json();
    });
  }

  function load() {
    state.loading = true; state.error = null;
    state.loadedSignedIn = signedIn();
    var h = authHeaders();
    return Promise.all([
      jget(REST + "/map_college_goal2?select=college_id,dest,students,rows_n,suppressed,reason", { headers: h }),
      jget(REST + "/map_data_loads?table_name=eq.map_student_credit&order=loaded_at.desc&limit=1", { headers: h }),
      jget(REST + "/map_college_credit_summary?select=college_id,students,suppressed,"
                + "dormant_credits,articulated_waiting,applied_credits,transcribed_credits", { headers: h }),
      // A failed name lookup is a KNOWN state the UI discloses, not a silent
      // fallback to ids — otherwise "College 122" reads as a naming choice
      // rather than a gap.
      fetch(NAMES_URL, { headers: h })
        .then(function (r) { return r.ok ? r.json() : null; })
        .catch(function () { return null; })
    ]).then(function (res) {
      state.cells = res[0];
      state.load = (res[1] && res[1][0]) || null;
      state.credits = {};
      if (Array.isArray(res[2])) {
        res[2].forEach(function (c) { state.credits[String(c.college_id)] = c; });
      }
      if (Array.isArray(res[3])) {
        var m = {};
        res[3].forEach(function (c) { m[String(c.college_id)] = c.college_name; });
        state.names = m;
        state.namesMissing = false;
      } else {
        state.names = null;
        state.namesMissing = true;
      }
      state.loading = false;
    }).catch(function (e) {
      state.error = e.message || String(e);
      state.loading = false;
    });
  }

  function collegeName(id) {
    if (state.names && state.names[String(id)]) return state.names[String(id)];
    return "College " + id;
  }

  // Fold the cell rows into one record per college.
  function byCollege() {
    var m = {};
    (state.cells || []).forEach(function (c) {
      var r = m[c.college_id] || (m[c.college_id] = {
        id: c.college_id, name: collegeName(c.college_id),
        cells: {}, hidden: 0, shown: 0, awardedRows: 0, allShown: true
      });
      r.cells[c.dest] = c;
      if (c.suppressed) { r.hidden++; r.allShown = false; }
      else { r.shown++; r.awardedRows += (c.rows_n || 0); }
    });
    return Object.keys(m).map(function (k) {
      var r = m[k];
      // A rate is only published where EVERY cell is visible. Publishing it
      // alongside suppressed cells would hand back what suppression removed —
      // any two of {total, part, rate} give you the third.
      var course = r.cells.COURSE;
      r.share = (r.allShown && r.awardedRows > 0 && course && course.rows_n != null)
        ? course.rows_n / r.awardedRows : null;
      r.credit = (state.credits && state.credits[String(r.id)]) || null;
      return r;
    });
  }

  function bandOf(r) {
    if (r.share == null) return "hidden";
    if (r.share >= 1) return "full";
    if (r.share >= 0.75) return "high";
    if (r.share >= 0.5) return "mid";
    return "low";
  }

  function filtered(rows) {
    var q = state.q.trim().toLowerCase();
    return rows.filter(function (r) {
      if (state.band !== "all" && bandOf(r) !== state.band) return false;
      if (q && r.name.toLowerCase().indexOf(q) < 0) return false;
      return true;
    }).sort(function (a, b) {
      if (state.sort === "name") return a.name.localeCompare(b.name);
      if (state.sort === "volume") return (b.awardedRows || 0) - (a.awardedRows || 0);
      // share: nulls last, so suppressed colleges don't masquerade as 0%
      if (a.share == null && b.share == null) return a.name.localeCompare(b.name);
      if (a.share == null) return 1;
      if (b.share == null) return -1;
      return b.share - a.share;
    });
  }

  function cellHtml(c) {
    if (!c) return '<span class="g2-sup">—</span>';
    if (c.suppressed) {
      var why = c.reason === "complement"
        ? "Hidden so a thin cell elsewhere in this row cannot be recovered by subtraction"
        : "Fewer than 10 students";
      return '<span class="g2-sup" title="' + esc(why) + '">&lt;10</span>';
    }
    return esc(String(c.students));
  }

  function render(root) {
    ensureCss();

    if (!signedIn()) {
      root.innerHTML = '<div class="g2"><h2>Course Credit — Veteran Sprint goal 2</h2>'
        + '<div class="g2-gate">This view is for the MAP team. Sign in, or enter the team phrase, '
        + 'on any tab with the 🔑 control and reopen this tab.</div></div>';
      return;
    }
    if (state.loading) { root.innerHTML = '<div class="g2"><p>Loading…</p></div>'; return; }
    if (state.error) {
      root.innerHTML = '<div class="g2"><h2>Course Credit</h2><div class="g2-gate">'
        + 'Could not read the data: ' + esc(state.error)
        + '<br><br>This is a failed read, <b>not</b> an empty result — nothing here should be '
        + 'taken as "no college has awarded anything".</div></div>';
      return;
    }

    var rows = byCollege();
    var withRate = rows.filter(function (r) { return r.share != null; });
    var atFull = withRate.filter(function (r) { return r.share >= 1; });
    var hiddenOnly = rows.filter(function (r) { return r.shown === 0; });

    var shares = withRate.map(function (r) { return r.share; }).sort(function (a, b) { return a - b; });
    var median = shares.length ? shares[Math.floor(shares.length / 2)] : null;

    var totCourse = 0, totAwarded = 0;
    rows.forEach(function (r) {
      DESTS.forEach(function (d) {
        var c = r.cells[d];
        if (c && c.rows_n != null) { totAwarded += c.rows_n; if (d === "COURSE") totCourse += c.rows_n; }
      });
    });

    var view = filtered(rows);

    var fresh = "";
    if (state.load) {
      var when = new Date(state.load.loaded_at);
      var days = Math.floor((Date.now() - when.getTime()) / 86400000);
      var stale = days >= 2;
      fresh = '<div class="g2-fresh' + (stale ? " stale" : "") + '">Data loaded '
        + esc(when.toISOString().slice(0, 10))
        + (days > 0 ? " (" + days + " day" + (days === 1 ? "" : "s") + " ago)" : " (today)")
        + " · " + esc(String(state.load.loaded_rows)) + " rows"
        + (state.load.reconciled ? ", count reconciled against the source"
                                 : ", ⚠ count NOT reconciled against the source")
        + (stale ? " · this is meant to refresh nightly" : "")
        + "</div>";
    }

    var namesWarn = state.namesMissing
      ? '<div class="g2-note">⚠ College names are not loaded yet (<code>' + esc(NAMES_URL)
        + '</code> is missing), so colleges show by MAP id.</div>' : "";

    var html = [];
    html.push('<div class="g2">');
    html.push('<h2>Course Credit <span class="g2-chip">Veteran Sprint goal 2</span></h2>');
    html.push('<p class="g2-intro">Of the credit colleges have actually awarded from military and '
      + 'other prior learning, how much lands on a <b>real college course</b> — versus a general-education '
      + 'area (nearly always CSU-GE Area E) or a generic elective? MAP labels every awarded row with '
      + 'which of the three it is, so this is measured, not estimated.</p>');
    html.push('<div class="g2-principle">This is not a scoreboard. Every figure below is credit students '
      + 'have <b>already earned</b>; the gap is credit nobody has awarded yet. Colleges are never ranked, '
      + 'and the colleges at 100% are here because they show what solved looks like.</div>');

    html.push('<div class="g2-stat">');
    html.push('<div class="box"><div class="n">' + (totAwarded ? pct(totCourse / totAwarded) : "—")
      + '</div><div class="l">statewide, of awarded credit<br>(volume-weighted)</div></div>');
    html.push('<div class="box"><div class="n">' + (median != null ? pct(median) : "—")
      + '</div><div class="l">the median college<br>(each college counts once)</div></div>');
    html.push('<div class="box"><div class="n">' + atFull.length
      + '</div><div class="l">colleges at 100%<br>no area or elective at all</div></div>');
    html.push('<div class="box"><div class="n">' + withRate.length + " of " + rows.length
      + '</div><div class="l">colleges with a publishable rate<br>the rest are too thin to break out</div></div>');
    html.push('</div>');

    var dormant = 0, ready = 0, creditRows = 0;
    rows.forEach(function (r) {
      if (r.credit && r.credit.dormant_credits != null) {
        dormant += Number(r.credit.dormant_credits) || 0;
        ready   += Number(r.credit.articulated_waiting) || 0;
        creditRows++;
      }
    });
    if (creditRows) {
      html.push('<div class="g2-stat">');
      html.push('<div class="box"><div class="n">' + num(dormant)
        + '</div><div class="l">units of credit at Needs Action<br>already earned, never awarded</div></div>');
      html.push('<div class="box"><div class="n">' + num(ready)
        + '</div><div class="l">of those ALREADY ARTICULATED<br>everything built — nobody acted</div></div>');
      html.push('</div>');
      html.push('<div class="g2-principle">⭐ <b>' + num(ready) + ' units</b> is the number to act on. '
        + 'That credit is articulated, valued and mapped to a course — roughly '
        + num(Math.round(ready / 60)) + ' associate degrees\u2019 worth — and the only missing step is a '
        + 'college acting on it. The larger figure is the ceiling; not all of it would be awarded, '
        + 'since ruling a recommendation out is legitimate work. Of credit already reviewed, '
        + 'about two-thirds was applied and a third correctly found not applicable.</div>');
    }
    html.push(fresh);

    html.push('<p class="g2-intro"><b>Those first two numbers are different on purpose.</b> The statewide '
      + 'figure is volume-weighted, so a few large colleges leaning on Area E pull it down; the median is '
      + 'what a typical college looks like. Quote whichever answers the question actually being asked, and '
      + 'say which one it is.</p>');

    if (atFull.length) {
      html.push('<h3>Colleges already at 100%</h3>');
      html.push('<div class="g2-exemplar"><div class="who">'
        + atFull.map(function (r) { return '<span class="g2-chip full">' + esc(r.name) + "</span>"; }).join(" ")
        + '</div><div class="g2-note">Every unit of prior-learning credit these colleges have awarded went to '
        + 'a named course. Nobody is at zero, so this is a spread between good and better — and these are the '
        + 'colleges worth asking how they did it.</div></div>');
    }

    html.push('<h3>By college</h3>');
    html.push('<div class="g2-toolbar">');
    html.push('<input type="search" id="g2-q" placeholder="Search colleges…" value="' + esc(state.q) + '">');
    html.push('<select id="g2-band">'
      + '<option value="all">All colleges</option>'
      + '<option value="full">At 100%</option>'
      + '<option value="high">75–99%</option>'
      + '<option value="mid">50–74%</option>'
      + '<option value="low">Under 50%</option>'
      + '<option value="hidden">Too thin to publish</option>'
      + '</select>');
    html.push('<select id="g2-sort">'
      + '<option value="share">Sort: course share</option>'
      + '<option value="name">Sort: name</option>'
      + '<option value="volume">Sort: volume awarded</option>'
      + '</select>');
    html.push('<span class="g2-count">' + view.length + " of " + rows.length + " colleges</span>");
    html.push('</div>');

    html.push('<div class="g2-wrap"><table class="g2-table">');
    html.push('<colgroup><col style="width:26%"><col style="width:8%"><col style="width:8%">'
      + '<col style="width:8%"><col style="width:20%"><col style="width:15%"><col style="width:15%"></colgroup>');
    html.push('<tr><th>College</th><th class="num">Course</th><th class="num">Area</th>'
      + '<th class="num">Elective</th><th>Share to course credit</th>'
      + '<th class="num" title="Credit recommended and still sitting at Needs Action">Dormant</th>'
      + '<th class="num" title="Already articulated AND still at Needs Action — every piece of the work '
      + 'is done except a college acting on it">Ready to award</th></tr>');

    view.forEach(function (r) {
      html.push("<tr>");
      html.push('<td class="g2-name" title="' + esc(r.name) + '">' + esc(r.name) + "</td>");
      DESTS.forEach(function (d) { html.push('<td class="num">' + cellHtml(r.cells[d]) + "</td>"); });
      if (r.share == null) {
        html.push('<td><span class="g2-sup" title="Not published because at least one cell in this row '
          + 'is suppressed — publishing the rate would give back what suppression removed">not published</span></td>');
        html.push('<td class="num g2-sup">—</td>');
      } else {
        html.push('<td><div class="g2-bar"><i style="width:' + (r.share * 100).toFixed(1) + '%"></i></div>'
          + '<span class="g2-share">' + pct(r.share) + "</span></td>");
      }
      // Credit columns are suppressed independently of the goal-2 cells: their
      // gate is the college's distinct-student count, not cell size.
      if (r.credit && r.credit.dormant_credits != null) {
        html.push('<td class="num">' + num(r.credit.dormant_credits) + "</td>");
        html.push('<td class="num g2-share">' + num(r.credit.articulated_waiting) + "</td>");
      } else {
        html.push('<td class="num"><span class="g2-sup" title="Fewer than 10 students at this college">'
          + '&lt;10 students</span></td><td class="num g2-sup">—</td>');
      }
      html.push("</tr>");
    });
    html.push("</table></div>");

    html.push('<div class="g2-note">Cells with fewer than 10 students read <b>&lt;10</b>. Where only one '
      + 'cell in a row would have been hidden, a second is hidden too — otherwise the first is recoverable '
      + 'by subtracting the visible ones. '
      + (hiddenOnly.length ? hiddenOnly.length + ' colleges are too small to break out at all and appear '
         + 'with no figures. ' : "")
      + 'Rules: <code>docs/kb-notes/adr-student-detail-aggregate-disclosure-control.md</code>.</div>');
    html.push(namesWarn);
    html.push("</div>");

    root.innerHTML = html.join("");

    var q = document.getElementById("g2-q");
    if (q) q.addEventListener("input", function () { state.q = q.value; render(root); q = document.getElementById("g2-q"); if (q) { q.focus(); q.setSelectionRange(q.value.length, q.value.length); } });
    var band = document.getElementById("g2-band");
    if (band) { band.value = state.band; band.addEventListener("change", function () { state.band = band.value; render(root); }); }
    var sort = document.getElementById("g2-sort");
    if (sort) { sort.value = state.sort; sort.addEventListener("change", function () { state.sort = sort.value; render(root); }); }
  }

  function activate() {
    var root = document.getElementById("course-credit-root");
    if (!root) return;
    ensureCss();
    // Re-read when the sign-in state changed since the last load, so signing in
    // on another tab does not leave this one showing the gate or stale figures.
    if (state.cells && state.loadedSignedIn === signedIn()) { render(root); return; }
    render(root);
    load().then(function () { render(root); });
  }

  // _state / render / _byCollege are exported for tests/college_goal2.test.js —
  // the disclosure rules are the point of this module, so they have to be
  // drivable without a live database.
  window.CPL_GOAL2 = { activate: activate, render: render, _byCollege: byCollege, _state: state };
})();
