/*
 * CPL Assistant — in-dashboard chat panel (Phase 1 of the chatbox integration).
 *
 * A native chat surface for the "CPL Assistant" tab. It talks DIRECTLY to the
 * shared Supabase Edge Function `cpl-chat` (the same RAG backend that powers the
 * live map.rccd.edu widget — see docs/kb-notes/cpl-chatbox-integration-scope.md),
 * which runs 4 parallel lookups (vector RAG + college detection + live metrics +
 * topic exhibit search) and streams a Claude Sonnet answer back over SSE.
 *
 * Why direct-to-Edge-Function (not via the Cloudflare proxy like quickstart.js):
 * the proxy buffers a single non-streaming Claude call, whereas this needs the
 * function's RAG orchestration + token-by-token SSE. The DOM/markdown scaffolding
 * is modeled on quickstart.js; the SSE contract is the function's own
 * (`event: sources` → `event: text` deltas → `event: done`).
 *
 * SAFETY: only the publishable anon key is used client-side (already shipped in
 * unified_courses.js; RLS gates everything). Model output is HTML-escaped BEFORE
 * the markdown-lite pass, so a crafted answer can't inject markup.
 *
 * This file is a STATIC asset (not regenerated by excel_to_dashboard.py). It is
 * the artifact the future Student CPL Portal embed reuses — keep it
 * self-contained behind the CONFIG block below.
 */
(function () {
  'use strict';

  // ── Config ── (anon key is public + RLS-gated; mirrors unified_courses.js)
  var SUPABASE_URL = 'https://hvuwhnbuahrtptokpqfh.supabase.co';
  var SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM';
  var CHAT_URL = SUPABASE_URL + '/functions/v1/cpl-chat';

  var SUGGESTED = [
    'What is Credit for Prior Learning?',
    'Does Riverside City College offer firefighter CPL?',
    'Which colleges give credit for a real estate license?',
    'How many students has CPL served statewide?',
  ];

  // ── Session id (one per browser tab session, reused across tab switches) ──
  function sessionId() {
    try {
      var k = 'cpl_chat_session';
      var v = sessionStorage.getItem(k);
      if (!v) {
        v = (window.crypto && crypto.randomUUID) ? crypto.randomUUID()
          : 'sess-' + Date.now() + '-' + Math.random().toString(16).slice(2);
        sessionStorage.setItem(k, v);
      }
      return v;
    } catch (e) {
      return 'sess-' + Date.now();
    }
  }

  // ── Tiny DOM helper (same shape as quickstart.js) ──
  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        if (k === 'style') { for (var s in attrs.style) n.style[s] = attrs.style[s]; }
        else if (k.indexOf('on') === 0 && typeof attrs[k] === 'function') { n.addEventListener(k.slice(2), attrs[k]); }
        else if (k === 'className') { n.className = attrs[k]; }
        else { n.setAttribute(k, attrs[k]); }
      }
    }
    if (kids) {
      if (!Array.isArray(kids)) kids = [kids];
      kids.forEach(function (c) {
        if (typeof c === 'string') n.appendChild(document.createTextNode(c));
        else if (c instanceof Node) n.appendChild(c);
      });
    }
    return n;
  }

  // ── Markdown-lite → safe HTML ──
  // Escape FIRST (so model text can't inject), then render the subset Sierra
  // actually writes. Upgraded 2026-07-02 (SkySierra): ##/### headings, | pipe |
  // tables |, --- rules, and 1. numbered lists used to show as raw text — the
  // block pass below handles them. Re-runs on every streamed delta, so a
  // half-arrived table degrades to a paragraph until its separator row lands.
  // Mirrors sierra/sierra.js + fact-sheet/factsheet_sierra.js (each surface is
  // deliberately self-contained — keep the three in sync).
  function escapeHtml(s) {
    return String(s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
  function inlineMd(s) {
    return s
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/(^|[^*])\*([^*\s][^*]*)\*(?!\*)/g, '$1<em>$2</em>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      // links: only http(s), target=_blank, escaped text already
      .replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,
        '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>')
      // bare URLs → links
      .replace(/(^|[\s(])((https?:\/\/)[^\s)]+)(?=[\s).,;!?]|$)/g,
        '$1<a href="$2" target="_blank" rel="noopener noreferrer">$2</a>');
  }
  var MD_TABLE_SEP = /^\s*\|?\s*:?-{2,}[-\s:|]*$/;   // | --- | :--- | …
  function mdCells(row) {
    return row.replace(/^\s*\|/, '').replace(/\|\s*$/, '').split('|')
      .map(function (c) { return c.trim(); });
  }
  function renderMarkdown(text) {
    var lines = escapeHtml(text).split(/\n/);
    var html = '', para = [], list = null;
    function flushPara() {
      if (para.length) { html += '<p>' + para.map(inlineMd).join('<br>') + '</p>'; para = []; }
    }
    function flushList() {
      if (list) {
        html += '<' + list.t + '>' + list.items.map(function (it) {
          return '<li>' + inlineMd(it) + '</li>';
        }).join('') + '</' + list.t + '>';
        list = null;
      }
    }
    for (var i = 0; i < lines.length; i++) {
      var t = lines[i].trim();
      if (!t) { flushPara(); flushList(); continue; }
      // horizontal rule (--- / *** / ___ on its own line)
      if (/^(?:-{3,}|_{3,}|\*{3,})$/.test(t)) { flushPara(); flushList(); html += '<hr>'; continue; }
      // headings: # / ## → h3 (bubble-scale), ### → h4, #### → h5
      var hm = t.match(/^(#{1,4})\s+(.+)$/);
      if (hm) {
        flushPara(); flushList();
        var lvl = hm[1].length <= 2 ? 3 : hm[1].length + 1;
        html += '<h' + lvl + '>' + inlineMd(hm[2]) + '</h' + lvl + '>';
        continue;
      }
      // table: a | header | row directly above a |---|---| separator row
      if (t.indexOf('|') > -1 && i + 1 < lines.length
          && lines[i + 1].indexOf('|') > -1 && MD_TABLE_SEP.test(lines[i + 1])) {
        flushPara(); flushList();
        var head = mdCells(t), body = [];
        i += 1; // consume the separator row
        while (i + 1 < lines.length && lines[i + 1].trim().indexOf('|') > -1
               && !MD_TABLE_SEP.test(lines[i + 1])) {
          i += 1;
          body.push(mdCells(lines[i].trim()));
        }
        html += '<table><thead><tr>' + head.map(function (c) {
          return '<th>' + inlineMd(c) + '</th>';
        }).join('') + '</tr></thead>';
        if (body.length) {
          html += '<tbody>' + body.map(function (r) {
            return '<tr>' + r.map(function (c) { return '<td>' + inlineMd(c) + '</td>'; }).join('') + '</tr>';
          }).join('') + '</tbody>';
        }
        html += '</table>';
        continue;
      }
      // bullet + numbered lists (consecutive runs group; type switch splits)
      var ul = t.match(/^[-*•]\s+(.+)$/);
      var ol = ul ? null : t.match(/^\d{1,3}[.)]\s+(.+)$/);
      if (ul || ol) {
        flushPara();
        var kind = ul ? 'ul' : 'ol';
        if (!list || list.t !== kind) { flushList(); list = { t: kind, items: [] }; }
        list.items.push(ul ? ul[1] : ol[1]);
        continue;
      }
      flushList();
      para.push(t);
    }
    flushPara(); flushList();
    return html;
  }

  // ── Conversation history (multi-turn) ──
  // Prior {role,content} turns sent with each request so the cpl-chat function
  // can carry a back-and-forth (e.g. ask a focusing follow-up before dumping a
  // big list, then honor "Southern California" / "show all"). Sending this field
  // — even as [] on the first turn — opts this client into multi-turn mode; the
  // production map.rccd.edu widget omits it and stays single-turn. Bounded to the
  // last few turns (the function re-trims to 6).
  var convo = [];
  var CONVO_MAX = 8;

  // ── Chat transcript helpers ──
  var logEl, inputEl, sendBtn, statusEl, audEl;

  // ── Audience (primary population) ──
  // Required before the first question (Sam, 2026-07-01): the visitor picks who
  // they are so Sierra tailors tone + content per audience — students shouldn't
  // get system inside-baseball. Single-select, persisted per-browser and SHARED
  // with the standalone sierra/ page (same origin, same localStorage key). Sent
  // as an optional `audience` body field — the production map.rccd.edu widget
  // omits it and is unaffected.
  //
  // TEXT LABELS, NO GLYPHS (Sam, 2026-08-14 and again 2026-08-17: "Delete emoji
  // glyphs. Keep text labels."). The emoji were decoration on top of words that
  // already said the same thing, and a screen reader announced each one — the
  // chip for a college administrator read "classical building college
  // administrator". Nothing is lost by removing them.
  var AUDIENCES = [
    { k: 'student',       label: 'Student / future student' },
    { k: 'faculty',       label: 'Faculty' },
    { k: 'administrator', label: 'College administrator' },
    { k: 'employer',      label: 'Employer / industry' },
    { k: 'civic',         label: 'Civic leader' },
  ];
  var AUD_KEY = 'cplSierraAudience.v1';
  var audience = null;

  function loadAudience() {
    try {
      var v = localStorage.getItem(AUD_KEY);
      if (AUDIENCES.some(function (a) { return a.k === v; })) audience = v;
    } catch (e) { /* keep in-memory only */ }
  }
  function setAudience(k) {
    audience = k;
    try { localStorage.setItem(AUD_KEY, k); } catch (e) { /* in-memory only */ }
    renderAudience();
  }
  function renderAudience() {
    if (!audEl) return;
    audEl.textContent = '';
    audEl.appendChild(el('span', { className: 'cplchat-aud-label' }, "I'm a…"));
    AUDIENCES.forEach(function (a) {
      audEl.appendChild(el('button', {
        type: 'button',
        className: 'cplchat-aud-chip' + (audience === a.k ? ' on' : ''),
        'aria-pressed': audience === a.k ? 'true' : 'false',
        onclick: function () { setAudience(a.k); setStatus(''); },
      }, a.label));
    });
  }
  function needAudience() {
    setStatus('First, tap who you are above — it helps the assistant tailor the answer.', 'error');
    if (!audEl) return;
    audEl.classList.add('need');
    setTimeout(function () { audEl.classList.remove('need'); }, 1700);
  }

  // ── Per-answer feedback (Helpful / Not helpful + note → sierra_feedback) ──
  // One row per assistant turn, keyed by a client uuid: a thumb click logs
  // immediately and an added note / switched rating updates the SAME row.
  // Writes go through the SECURITY DEFINER RPC `sierra_feedback_upsert` — a
  // direct PostgREST upsert (ON CONFLICT) needs SELECT visibility of the
  // conflicting row, which this table deliberately denies to anon (write-only
  // for the public; the team reads it via the reviewer/team-phrase gate).
  // Mirrors sierra/sierra.js.
  function newTurnId() {
    return (window.crypto && crypto.randomUUID) ? crypto.randomUUID()
      : 'turn-' + Date.now() + '-' + Math.random().toString(16).slice(2);
  }

  // ── Copy an answer ─────────────────────────────────────────────────────────
  // Mirrors sierra/sierra.js — the two chat surfaces have carried parallel
  // implementations since the feedback bar, and a shared module would mean a new
  // <script> in BOTH mirrored dashboard HTMLs (Rule 4) for ~40 lines. Keep the
  // two copies identical; change them together.
  //
  // Writes text/html (the rendered bubble, so a paste into Word/Outlook/Teams
  // keeps headings, tables and links) alongside text/plain (the markdown Sierra
  // emitted). Falls back to writeText, then to execCommand — which is the only
  // route inside a cross-origin iframe, where the async Clipboard API is denied.
  // Never throws into the chat flow; on total failure it selects the answer so
  // the visitor can press Ctrl+C.
  function copyRich(html, text) {
    try {
      if (html && navigator.clipboard && navigator.clipboard.write && window.ClipboardItem) {
        return navigator.clipboard.write([new window.ClipboardItem({
          'text/html': new Blob([html], { type: 'text/html' }),
          'text/plain': new Blob([text], { type: 'text/plain' }),
        })]);
      }
    } catch (e) { /* fall through to plain */ }
    return Promise.reject(new Error('rich copy unavailable'));
  }
  function copyPlain(text) {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        return navigator.clipboard.writeText(text);
      }
    } catch (e) { /* fall through to execCommand */ }
    return Promise.reject(new Error('async clipboard unavailable'));
  }
  function copyLegacy(text) {
    try {
      var ta = document.createElement('textarea');
      ta.value = text;
      ta.setAttribute('readonly', '');
      ta.style.position = 'fixed';
      ta.style.top = '-1000px';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      var ok = !!(document.execCommand && document.execCommand('copy'));
      document.body.removeChild(ta);
      return ok;
    } catch (e) { return false; }
  }
  function selectNode(node) {
    try {
      var sel = window.getSelection();
      var range = document.createRange();
      range.selectNodeContents(node);
      sel.removeAllRanges();
      sel.addRange(range);
    } catch (e) { /* selection is a courtesy, not a requirement */ }
  }
  function copyAnswer(html, text, done) {
    copyRich(html, text).then(
      function () { done(true); },
      function () {
        copyPlain(text).then(
          function () { done(true); },
          function () { done(copyLegacy(text)); }
        );
      }
    );
  }
  // Builds the Copy pill for one assistant turn. `answer` is the markdown;
  // the bubble is looked up from the row so an error turn still copies what the
  // visitor can see.
  function makeCopyBtn(afterRow, answer) {
    var timer = null;
    var btn = el('button', {
      type: 'button', className: 'cplchat-fb-copy',
      title: 'Copy this answer — formatting is kept when you paste into Word, Outlook or Teams',
      'aria-label': 'Copy this answer to the clipboard',
      onclick: function () {
        var bub = afterRow && afterRow.querySelector ? afterRow.querySelector('.cplchat-bubble') : null;
        var plain = answer || (bub ? bub.textContent : '') || '';
        copyAnswer(bub ? bub.innerHTML : '', plain, function (ok) {
          // Words, not ticks — the state is already carried by the `on` class
          // and its colour, so the glyph was decoration on a label that says
          // the same thing (Sam, 2026-08-17).
          btn.textContent = ok ? 'Copied' : 'Press Ctrl+C';
          btn.classList.toggle('on', ok);
          if (!ok && bub) selectNode(bub);
          if (timer) clearTimeout(timer);
          timer = setTimeout(function () {
            btn.textContent = 'Copy';
            btn.classList.remove('on');
          }, 2200);
        });
      },
    }, 'Copy');
    return btn;
  }
  function feedbackPayload(o) {
    return {
      p_turn_id: o.turnId,
      p_rating: o.rating,
      p_session_id: o.sessionId || null,
      p_page: o.page || 'cobi-tab',
      p_audience: o.audience || null,
      p_question: String(o.question || '').slice(0, 4000),
      p_response: String(o.response || '').slice(0, 12000),
      p_note: o.note ? String(o.note).slice(0, 2000) : null,
    };
  }
  // Resolves TRUE only when the row actually landed. A rejected promise and a
  // non-2xx response are both failures, and fetch does not reject on HTTP
  // errors — sierra_feedback_upsert RAISES on an invalid rating, so "it
  // returned" never meant "it saved". Ratings stay fire-and-forget (the bar
  // already shows its own state); the NOTE path awaits this, because telling
  // someone their note was sent when it was not is worse than telling them
  // nothing — they close the tab and the report is gone.
  function sendFeedback(payload) {
    try {
      return fetch(SUPABASE_URL + '/rest/v1/rpc/sierra_feedback_upsert', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': SUPABASE_ANON,
          'Authorization': 'Bearer ' + SUPABASE_ANON,
        },
        body: JSON.stringify(payload),
      }).then(function (res) { return !!(res && res.ok); },
              function () { return false; });
    } catch (e) { return Promise.resolve(false); }
  }
  function addFeedbackBar(afterRow, question, answer) {
    var tid = newTurnId();
    var rating = null;

    var hint = el('span', null, 'Rate this answer:');
    var noteIn = el('input', {
      type: 'text', maxlength: '2000',
      placeholder: 'Optional note for the CPL team — what was right or missing? (no personal info)',
      'aria-label': 'Optional feedback note',
    });
    var noteBtn = el('button', { type: 'button' }, 'Send note');
    // The confirmation lives INSIDE the composer, so it appears exactly where
    // the button was. Sam: "it turns gray but nothing else — not sure if it
    // registers." The greying was the only local signal; the words appeared far
    // away in the rating row next to Copy.
    var noteDone = el('span', { className: 'cplchat-fb-done' }, '');
    noteDone.hidden = true;
    var noteWrap = el('div', { className: 'cplchat-fb-note' }, [noteIn, noteBtn, noteDone]);
    noteWrap.hidden = true;

    function upsert(note) {
      return sendFeedback(feedbackPayload({
        turnId: tid, sessionId: sessionId(), page: 'cobi-tab', audience: audience,
        question: question, response: answer, rating: rating, note: note,
      }));
    }

    var btns = {};
    // Copy sits FIRST — it is what people reach for on a GOOD answer, and it
    // should not sit behind the rating flow.
    var bar = el('div', { className: 'cplchat-fb' }, [makeCopyBtn(afterRow, answer), hint]);
    // The thumbs are now WORDS. They were the one place a glyph carried meaning
    // no text repeated, so removing them without a label would have destroyed
    // the control — the visible label now says what the aria-label said, which
    // is also the accessible improvement (a bare 👍 announces as "thumbs up",
    // not as "this answer was helpful").
    [['up', 'Helpful', 'This answer was helpful'], ['down', 'Not helpful', 'This answer was not helpful']]
      .forEach(function (spec) {
        var b = el('button', {
          type: 'button', className: 'cplchat-fb-btn', 'aria-label': spec[2],
          onclick: function () {
            rating = spec[0];
            btns.up.classList.toggle('on', rating === 'up');
            btns.down.classList.toggle('on', rating === 'down');
            hint.textContent = 'Thanks — logged.';
            noteWrap.hidden = false;
            upsert(noteIn.value.trim() || null);
          },
        }, spec[1]);
        btns[spec[0]] = b;
        bar.appendChild(b);
      });

    noteBtn.addEventListener('click', function () {
      var n = noteIn.value.trim();
      // `rating` is guaranteed here now that [hidden] actually hides the
      // composer until one is given — the guard stays as a backstop, but it can
      // no longer swallow a click the way it did when the box was always
      // visible: you could type a note, press Send, and get NOTHING.
      if (!n || !rating) return;
      noteBtn.disabled = true;
      noteDone.hidden = false;
      noteDone.className = 'cplchat-fb-sending';
      noteDone.textContent = 'Sending…';
      upsert(n).then(function (ok) {
        noteDone.hidden = false;
        if (ok) {
          // Consume the text so it is visibly taken, and close the composer.
          noteIn.value = '';
          noteIn.hidden = true;
          noteBtn.hidden = true;
          noteDone.className = 'cplchat-fb-done';
          noteDone.textContent = 'Note sent — thank you!';
        } else {
          // KEEP THE TYPED TEXT. The same guarantee the guidance editor and the
          // contact proposals carry: a write that did not land must report as a
          // failure with the words still in the box, never as a cheerful tick.
          noteBtn.disabled = false;
          noteDone.className = 'cplchat-fb-fail';
          noteDone.textContent = 'Not sent — your note is still here, try again.';
        }
      });
    });
    noteIn.addEventListener('keydown', function (e) {
      if (e.key === 'Enter') { e.preventDefault(); noteBtn.click(); }
    });

    bar.appendChild(noteWrap);
    if (afterRow && afterRow.parentNode) {
      afterRow.parentNode.insertBefore(bar, afterRow.nextSibling);
    } else {
      logEl.appendChild(bar);
    }
    scrollDown();
  }

  // New-class CSS injected from the JS (covers BOTH HTMLs without a Rule-4
  // mirror — the CER ensureCerScopeCss() pattern). The pre-existing cplchat-*
  // styles stay in the HTML <style> blocks; only the audience + feedback
  // additions live here.
  function ensureChatCss() {
    if (document.getElementById('cplchat-aud-css')) return;
    var css = [
      '.cplchat-audience { display:flex; flex-wrap:wrap; align-items:center; gap:7px; margin:8px 0 2px; padding:8px 11px; background:var(--surface-subtle, #f2f6fb); border:1px solid var(--border, #d8dde6); border-radius:10px; }',
      '.cplchat-aud-label { font-size:.82rem; font-weight:600; color:var(--text-muted, #5a6478); margin-right:2px; }',
      '.cplchat-aud-chip { border:1px solid var(--border-strong, #cdd6e3); background:var(--surface-opaque, #fff); color:var(--text-body, #1c2433); border-radius:999px; padding:6px 12px; font-size:.82rem; font-weight:600; cursor:pointer; }',
      '.cplchat-aud-chip:hover { border-color:var(--cobalt, #0047AB); }',
      '.cplchat-aud-chip.on { background:var(--seal-blue, #002F6D); border-color:var(--seal-blue, #002F6D); color:#fff; }',
      '.cplchat-audience.need { outline:2px solid var(--crimson, #920000); }',
      '.cplchat-fb { display:flex; flex-wrap:wrap; align-items:center; gap:6px; margin:2px 0 8px 38px; font-size:.78rem; color:var(--text-faint, #8a94a6); }',
      '.cplchat-fb-btn { border:1px solid var(--border, #d8dde6); background:var(--surface-opaque, #fff); border-radius:999px; padding:2px 9px; cursor:pointer; font-size:.85rem; line-height:1.4; opacity:.75; }',
      '.cplchat-fb-btn:hover { opacity:1; border-color:var(--cobalt, #0047AB); }',
      '.cplchat-fb-btn.on { opacity:1; background:var(--surface-subtle, #eef3fa); border-color:var(--cobalt, #0047AB); }',
      // Copy shares the pill shape but NOT the .cplchat-fb-btn class — that class
      // means "a rating button" to the code (btns.up/btns.down) and to the tests,
      // which assert exactly two of them.
      '.cplchat-fb-copy { border:1px solid var(--border, #d8dde6); background:var(--surface-opaque, #fff); border-radius:999px; padding:2px 9px; cursor:pointer; font-size:.78rem; font-family:inherit; line-height:1.4; opacity:.75; color:inherit; white-space:nowrap; }',
      '.cplchat-fb-copy:hover { opacity:1; border-color:var(--cobalt, #0047AB); }',
      '.cplchat-fb-copy.on { opacity:1; background:var(--surface-subtle, #eef3fa); border-color:var(--cobalt, #0047AB); }',
      // THE ROOT DEFECT. An author `display` rule beats the UA stylesheet's
      // `[hidden] { display:none }`, so `noteWrap.hidden = true` was INERT:
      // the composer never closed on success, and it was on screen from the
      // start instead of appearing after a rating — which is how a click could
      // hit the `!rating` guard and do nothing at all. Every `display` rule on
      // an element that gets toggled with `hidden` needs this companion.
      '.cplchat-fb-note { display:flex; flex:1 1 100%; gap:6px; margin-top:4px; }',
      '.cplchat-fb-note[hidden] { display:none; }',
      '.cplchat-fb-note input { flex:1; border:1px solid var(--border-strong, #cdd6e3); border-radius:8px; padding:6px 10px; font-size:.82rem; background:var(--surface-opaque, #fff); color:var(--text-body, #1c2433); }',
      '.cplchat-fb-note button { border:none; border-radius:8px; padding:6px 12px; cursor:pointer; background:var(--cobalt, #0047AB); color:#fff; font-size:.8rem; font-weight:600; }',
      '.cplchat-fb-note button:disabled { opacity:.6; cursor:default; }',
      '.cplchat-fb-done { color:var(--text-muted, #5a6478); font-weight:600; }',
      '.cplchat-fb-sending { color:var(--text-faint, #8a94a6); font-weight:600; }',
      '.cplchat-fb-fail { color:var(--crimson, #920000); font-weight:600; }',
      // Sierra-mark avatar (SVG roundel replaces the emoji glyph)
      '.cplchat-avatar { background: transparent; }',
      '.cplchat-avatar svg { width:100%; height:100%; display:block; }',
      // Markdown upgrades (2026-07-02): headings, rules, ordered lists, tables
      '.cplchat-bubble h3, .cplchat-bubble h4, .cplchat-bubble h5 { margin:13px 0 5px; line-height:1.3; color:var(--navy-primary, #0b3d61); }',
      '.cplchat-bubble h3 { font-size:1.04rem; } .cplchat-bubble h4 { font-size:.96rem; } .cplchat-bubble h5 { font-size:.9rem; }',
      '.cplchat-bubble h3:first-child, .cplchat-bubble h4:first-child, .cplchat-bubble h5:first-child { margin-top:2px; }',
      '.cplchat-bubble hr { border:none; border-top:1px solid var(--border, #d8dde6); margin:11px 0; }',
      '.cplchat-bubble ol { margin:5px 0 9px; padding-left:21px; }',
      '.cplchat-bubble table { border-collapse:collapse; margin:8px 0 10px; font-size:.92em; display:block; max-width:100%; overflow-x:auto; }',
      '.cplchat-bubble th, .cplchat-bubble td { border:1px solid var(--border, #d8dde6); padding:4px 10px; text-align:left; vertical-align:top; }',
      '.cplchat-bubble th { background:var(--surface-subtle, #f2f6fb); color:var(--navy-primary, #0b3d61); font-weight:700; }',
      '.cplchat-bubble tbody tr:nth-child(even) { background:var(--surface-subtle, #f2f6fb); }',
      // ── The Sierra AI heading + its Whitney mark (Sam, 2026-08-17) ─────────
      // The mark is the same roundel the answer avatars carry, at heading size.
      // `em` so it tracks the h2 rather than needing a second breakpoint.
      '.cplchat-title { display:flex; align-items:center; gap:10px; }',
      '.cplchat-title-mark { flex:0 0 auto; width:1.25em; height:1.25em; display:block; }',
      '.cplchat-title-mark svg { width:100%; height:100%; display:block; }',
      // ── Measure control, so widening the log does not widen the PROSE ─────
      // Sam, 2026-08-17: "use as much of the screen as possible for usable
      // space". The log and the bubble now take the container's width, which is
      // what a table or a long list of courses needs — but a 1,200px paragraph
      // is unreadable, so the cap is applied to the PROSE elements instead of
      // to the bubble. Tables keep their own overflow-x and are unaffected.
      '.cplchat-bubble > p, .cplchat-bubble > ul, .cplchat-bubble > ol { max-width:82ch; }',
      // ── Growing log: the reader-facing half of "don't scroll so much" ─────
      // See the .cplchat-log rule in the HTML for the growth range itself.
      // scroll-padding keeps a smooth page-follow from parking the newest line
      // hard against the bottom edge.
      'html { scroll-padding-bottom:96px; }',
      '@media (prefers-reduced-motion:reduce){ html { scroll-behavior:auto; } }',
    ].join('\n');
    var st = document.createElement('style');
    st.id = 'cplchat-aud-css';
    st.textContent = css;
    document.head.appendChild(st);
  }

  // ── Keep the newest line in view ───────────────────────────────────────────
  // The log used to be a FIXED 460px box, so "scroll to the bottom" meant one
  // thing: scroll the box. It now GROWS with the answer (Sam, 2026-08-17:
  // "allow Sierra's window to grow with her answers — so users don't have to
  // scroll so much"), which introduces a second case the old one-liner could
  // not reach: a growing box is not internally scrollable, so setting scrollTop
  // is a no-op while the bottom of the answer — and the input under it — walks
  // off the bottom of the PAGE. Growth without page-follow would have made the
  // scrolling worse, not better.
  //
  // Both cases are handled, and the page half is deliberately conservative:
  //   · only when the anchor is actually below the fold (never scroll up, and
  //     never scroll at all when it already fits);
  //   · only while `stick` — set at send time and cleared the moment the reader
  //     scrolls away from the bottom themselves. Yanking someone who scrolled
  //     up to re-read an earlier answer is the failure mode that makes chat UIs
  //     unusable, and it is silent: they just fight the page and give up.
  var stick = true;
  var windowScrollWatched = false;
  function nearBottom() {
    var slack = 120;                                    // a comfortable "still at the end"
    if (logEl && logEl.scrollHeight > logEl.clientHeight + 1) {
      return logEl.scrollTop + logEl.clientHeight >= logEl.scrollHeight - slack;
    }
    var doc = document.documentElement;
    if (!doc) return true;
    var below = doc.scrollHeight - (window.pageYOffset || doc.scrollTop || 0) - doc.clientHeight;
    return below <= slack;
  }
  function stickToBottom() { stick = true; }
  function noteReaderScroll() { stick = nearBottom(); }
  function scrollDown() {
    if (!logEl) return;
    requestAnimationFrame(function () {
      if (!logEl) return;
      // Internal scroll first. Still correct for a long answer that has hit the
      // max-height cap; a harmless no-op while the box is still growing.
      logEl.scrollTop = logEl.scrollHeight;
      if (!stick) return;
      try {
        var r = logEl.getBoundingClientRect();
        var vh = window.innerHeight || (document.documentElement || {}).clientHeight || 0;
        // Nothing to do unless the bottom edge is genuinely past the fold.
        if (!vh || r.bottom <= vh - 8) return;
        // Move by exactly the overshoot, plus room for the input row beneath.
        // A JS `behavior:'smooth'` is NOT covered by the CSS reduced-motion
        // rule, so the preference is read here as well.
        var calm = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
        window.scrollBy({
          top: Math.ceil(r.bottom - vh + 96), left: 0,
          behavior: calm ? 'auto' : 'smooth',
        });
      } catch (e) { /* no layout (jsdom) or no scrollBy — internal scroll stands */ }
    });
  }
  function addUserMsg(text) {
    var row = el('div', { className: 'cplchat-msg cplchat-user' },
      el('div', { className: 'cplchat-bubble' }, text));
    logEl.appendChild(row);
    scrollDown();
  }
  // The Sierra mark — Mt Whitney's east-face ridge (sierra/whitney-mark.svg)
  // in a navy roundel. A STATIC, trusted string (never user input) inlined so
  // the avatar needs no relative-path asset. Mirrors sierra/sierra.js.
  var SIERRA_MARK =
    '<svg viewBox="0 0 40 40" aria-hidden="true" focusable="false">' +
    '<circle cx="20" cy="20" r="19" style="fill:var(--seal-blue,#0b3d61)"/>' +
    '<path d="M2 30 L12 25 21 17 29 9 35 4 40 1 43 6 46 4 49 9 52 7 55 11 59 15 63 19 66 22 70 18 73 20 76 15 79 13 82 16 85 20 90 24 97 27 105 29 118 30"' +
    ' transform="translate(4 15.4) scale(0.2667)" fill="none" stroke="#fff" stroke-width="9" stroke-linejoin="round" stroke-linecap="round"/>' +
    '<path d="M40 5.4 L37.4 10.6 38.9 9.6 40 11 41.1 9.5 42.6 10.7 40 5.4 Z"' +
    ' transform="translate(-7.33 13.83) scale(0.55)" fill="#fff"/>' +
    '</svg>';

  // Returns the row + bubble; the streamer appends deltas to the bubble and the
  // feedback bar anchors after the row.
  function addAssistantMsg() {
    var bubble = el('div', { className: 'cplchat-bubble' });
    var avatar = el('div', { className: 'cplchat-avatar', 'aria-hidden': 'true' });
    avatar.innerHTML = SIERRA_MARK;
    var row = el('div', { className: 'cplchat-msg cplchat-bot' }, [avatar, bubble]);
    logEl.appendChild(row);
    scrollDown();
    return { row: row, bubble: bubble };
  }
  function setStatus(text, kind) {
    if (!statusEl) return;
    statusEl.textContent = text || '';
    statusEl.className = 'cplchat-status' + (kind ? ' cplchat-' + kind : '');
  }

  // ── Call the Edge Function + stream the SSE response ──
  async function ask(query) {
    var msg = addAssistantMsg();
    var bubble = msg.bubble;
    bubble.innerHTML = '<span class="cplchat-typing">●●●</span>';
    var full = '';

    var resp;
    try {
      resp = await fetch(CHAT_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': SUPABASE_ANON,
          'Authorization': 'Bearer ' + SUPABASE_ANON,
        },
        // Send the PRIOR turns; the function appends this query as the final
        // user turn. The empty [] on turn 1 still opts us into multi-turn mode.
        body: JSON.stringify({
          query: query, session_id: sessionId(), history: convo.slice(),
          audience: audience,
        }),
      });
    } catch (e) {
      bubble.innerHTML = renderMarkdown('Sorry — I couldn\'t reach the assistant. Please check your connection and try again.');
      return;
    }

    if (!resp.ok) {
      var msg = 'Sorry — something went wrong (error ' + resp.status + ').';
      if (resp.status === 429) msg = 'I\'m getting a lot of questions right now. Please wait a minute and try again.';
      bubble.innerHTML = renderMarkdown(msg);
      return;
    }
    if (!resp.body || !resp.body.getReader) {
      // No streaming support — fall back to text().
      var txt = await resp.text();
      bubble.innerHTML = renderMarkdown(txt || 'No response.');
      return;
    }

    var reader = resp.body.getReader();
    var decoder = new TextDecoder();
    var buffer = '';
    var firstToken = true;
    try {
      while (true) {
        var chunk = await reader.read();
        if (chunk.done) break;
        buffer += decoder.decode(chunk.value, { stream: true });
        var rawEvents = buffer.split('\n\n');
        buffer = rawEvents.pop() || '';
        for (var i = 0; i < rawEvents.length; i++) {
          var evt = parseSse(rawEvents[i]);
          if (!evt) continue;
          if (evt.event === 'text') {
            try {
              var d = JSON.parse(evt.data);
              if (d && typeof d.text === 'string') {
                if (firstToken) { bubble.innerHTML = ''; firstToken = false; }
                full += d.text;
                bubble.innerHTML = renderMarkdown(full);
                scrollDown();
              }
            } catch (e) { /* skip malformed delta */ }
          } else if (evt.event === 'done') {
            // stream complete
          }
          // evt.event === 'sources' is available but not surfaced in Phase 1.
        }
      }
    } finally {
      reader.releaseLock();
    }
    if (!full) {
      bubble.innerHTML = renderMarkdown('I don\'t have an answer for that yet. Try rephrasing, or email MAP@rccd.edu.');
      return;
    }
    // Record this completed turn so the next request carries the back-and-forth.
    convo.push({ role: 'user', content: query }, { role: 'assistant', content: full });
    if (convo.length > CONVO_MAX) convo = convo.slice(-CONVO_MAX);
    addFeedbackBar(msg.row, query, full);
  }

  // Parse one SSE event block ("event: <name>\ndata: <json>")
  function parseSse(block) {
    var out = { event: 'message', data: '' };
    var got = false;
    block.split('\n').forEach(function (line) {
      if (line.indexOf('event:') === 0) { out.event = line.slice(6).trim(); got = true; }
      else if (line.indexOf('data:') === 0) { out.data += line.slice(5).trim(); got = true; }
    });
    return got ? out : null;
  }

  // ── Submit flow ──
  var busy = false;
  async function submit() {
    if (busy) return;
    var q = (inputEl.value || '').trim();
    if (!q) { inputEl.focus(); return; }
    if (!audience) { needAudience(); return; }
    busy = true;
    // Asking is an explicit "show me the answer", so re-arm page-follow even if
    // the reader had scrolled up to look at an earlier turn.
    stickToBottom();
    sendBtn.disabled = true; inputEl.disabled = true;
    addUserMsg(q);
    inputEl.value = '';
    setStatus('Thinking…', 'pending');
    var firstChips = document.getElementById('cplchat-suggest');
    if (firstChips) firstChips.remove(); // hide starter chips after first question
    try {
      await ask(q);
      setStatus('');
    } catch (e) {
      setStatus('Something went wrong. Try again.', 'error');
    } finally {
      busy = false;
      sendBtn.disabled = false; inputEl.disabled = false;
      inputEl.focus();
    }
  }

  // ── Build the panel ──
  function build(mount) {
    ensureChatCss();
    var wrap = el('div', { className: 'cplchat' });

    // ── The one heading (Sam, 2026-08-17) ──────────────────────────────────
    // "Change CPL Assistant title to Sierra AI with her mountain logo". She is
    // named "Sierra AI" and not "Sierra" because Sierra alone reads as Sierra
    // College (Sam, 2026-08-11). The mark is the SAME static SIERRA_MARK the
    // chat avatars use, so the header and the answers beneath it carry one
    // identity — and it needs no relative-path asset, which matters because
    // this widget mounts in two panes and on two mirrored HTMLs.
    //
    // This is now the ONLY heading on My College's assistant box: that tab used
    // to print its own "Sierra AI" h3 and purpose paragraph directly above this
    // one, so the pane opened with two titles and two descriptions of the same
    // thing. college_briefing.js no longer emits its copy.
    var title = el('h2', { className: 'cplchat-title' });
    var mark = el('span', { className: 'cplchat-title-mark', 'aria-hidden': 'true' });
    mark.innerHTML = SIERRA_MARK;                 // static, trusted (see SIERRA_MARK)
    title.appendChild(mark);
    title.appendChild(el('span', null, 'Sierra AI'));

    wrap.appendChild(el('div', { className: 'cplchat-intro' }, [
      title,
      // One description, and it has to read correctly in BOTH hosts — this
      // widget mounts on My College and on the CPL Assistant tab, so it cannot
      // say "the sections below" (the wording My College's deleted paragraph
      // used, which would be a promise about a page that isn't always there).
      el('p', null,
        'Ask her anything about Credit for Prior Learning — what a college ' +
        'offers, what credit is sitting unawarded, where to find credit for a ' +
        'license or certification, who a student should contact, or statewide ' +
        'CPL numbers. She reads the same CPL Initiative records and knowledge ' +
        'base these pages are built from, so it is usually faster to ask than ' +
        'to go looking.'),
      el('p', { className: 'cplchat-beta' },
        'Beta — in development. Please don\'t enter personal information; ' +
        'questions are logged to improve answers.'),
    ]));

    audEl = el('div', {
      className: 'cplchat-audience', id: 'cplchat-audience', role: 'radiogroup',
      'aria-label': 'Tell the assistant who you are so answers fit your needs',
    });
    loadAudience();
    renderAudience();
    wrap.appendChild(audEl);

    logEl = el('div', { className: 'cplchat-log', id: 'cplchat-log', 'aria-live': 'polite' });
    // A reader who scrolls away from the bottom takes control; asking again
    // hands it back (see scrollDown). Passive: this must never delay a scroll.
    // The log's own listener dies with the element, but build() runs again on
    // every mountInto() — so the WINDOW listener is attached exactly once, or
    // switching between My College and CPL Assistant would stack one per visit.
    try {
      logEl.addEventListener('scroll', noteReaderScroll, { passive: true });
      if (!windowScrollWatched) {
        window.addEventListener('scroll', noteReaderScroll, { passive: true });
        windowScrollWatched = true;
      }
    } catch (e) { /* no addEventListener options support — follow stays armed */ }

    // Starter suggestion chips
    var chips = el('div', { className: 'cplchat-suggest', id: 'cplchat-suggest' });
    SUGGESTED.forEach(function (s) {
      chips.appendChild(el('button', {
        type: 'button', className: 'cplchat-chip',
        onclick: function () { inputEl.value = s; submit(); },
      }, s));
    });
    logEl.appendChild(chips);
    wrap.appendChild(logEl);

    statusEl = el('div', { className: 'cplchat-status', id: 'cplchat-status', 'aria-live': 'polite' });
    wrap.appendChild(statusEl);

    var row = el('div', { className: 'cplchat-inputrow' });
    inputEl = el('input', {
      type: 'text', id: 'cplchat-input', className: 'cplchat-input',
      placeholder: 'Ask a question about CPL…', autocomplete: 'off', maxlength: '1000',
    });
    sendBtn = el('button', { type: 'button', className: 'cplchat-send' }, 'Send');
    inputEl.addEventListener('keydown', function (e) { if (e.key === 'Enter') { e.preventDefault(); submit(); } });
    sendBtn.addEventListener('click', submit);
    row.appendChild(inputEl); row.appendChild(sendBtn);
    wrap.appendChild(row);

    mount.appendChild(wrap);
  }

  // ── "Test in Sierra" prefill (Sierra Training tab handoff) ──
  // The Training tab stores a logged question under this key then navigates to
  // #chatbot; we fill the input (never auto-send) so the reviewer can tweak
  // before replaying it. Consumed on tab activation (tabs.js dispatches
  // cpl-tab-activated on WINDOW) + once at mount for the deep-link landing.
  var TEST_Q_KEY = 'cplSierraTestQ.v1';

  // The #chatbot pane's OWN input, which is not necessarily `inputEl`.
  //
  // WHY (Sam, 2026-08-13: "tried to use Try it With Sierra but it didn't copy
  // the question into Sierra"). My College mounts this SAME widget through
  // mountInto(), and build() re-points the module-level `inputEl` at THAT
  // pane's input. mount() then early-returns on the data-cplchat-mounted flag,
  // so coming back to #chatbot never re-points it. After one visit to My
  // College, `inputEl` is the hidden pane's input for the rest of the session —
  // so the handoff typed the question into an invisible box.
  // Is the dedicated CPL Assistant tab actually reachable? cobi_orgs.js hides a
  // nav button with style.display + data-org-hidden="1"; the Admin tab Sam is
  // planning will suppress tabs the same way. data-org-hidden is used rather
  // than offsetParent because jsdom has no layout, so a visibility test based on
  // rendering cannot be tested at all.
  function chatbotTabSuppressed() {
    var pane = document.getElementById('tab-chatbot');
    if (!pane) return true;
    var btn = document.querySelector('.cpl-tab[data-tab="chatbot"]');
    return !!(btn && btn.getAttribute('data-org-hidden') === '1');
  }

  // The pane that should receive a Sierra Training hand-off.
  //
  // PREFERS the dedicated CPL Assistant pane, and falls back to My College —
  // which mounts this SAME widget via mountInto() — when CPL Assistant is
  // suppressed or absent. Sam, 2026-08-14, planning to suppress that tab from an
  // Admin tab: the two surfaces are the same assistant, but the hand-off names
  // #chatbot specifically, so suppressing it would have silently broken the only
  // way to test an instruction. A button that does nothing looks like one that
  // was never wired — the exact failure #1166 existed to fix.
  //
  // Still pane-scoped rather than using the module-level `inputEl`, because that
  // reference goes stale after a second mount (see the note below).
  function chatbotInputEl() {
    if (!chatbotTabSuppressed()) {
      var pane = document.getElementById('tab-chatbot');
      var el = pane && pane.querySelector('#cplchat-input, .cplchat-input');
      if (el) return el;
    }
    var mc = document.getElementById('tab-college-briefing');
    return (mc && mc.querySelector('#cplchat-input, .cplchat-input')) || null;
  }

  function consumeTestQuestion() {
    var q = null;
    try { q = sessionStorage.getItem(TEST_Q_KEY); } catch (e) { return; }
    if (!q) return;
    var el = chatbotInputEl() || inputEl;
    // KEY IS NOT REMOVED ON FAILURE. It used to be deleted before the input was
    // known to exist, so an activation that fired before the widget was built
    // consumed the question and dropped it — and because the key was gone, the
    // reviewer could not retry: the button appeared to do nothing, twice. The
    // handoff now survives until it is actually delivered.
    if (!el) return;
    el.value = q.slice(0, 1000);
    try { sessionStorage.removeItem(TEST_Q_KEY); } catch (e) { /* storage unavailable */ }
    try { el.focus(); } catch (e) { /* hidden pane */ }
  }
  window.addEventListener('cpl-tab-activated', function (e) {
    // Both hosts of this widget, so a hand-off still lands when CPL Assistant is
    // suppressed and the reviewer is routed to My College instead. The key is
    // not consumed until an input is actually found, so listening on the wrong
    // one costs nothing.
    var t = e && e.detail && e.detail.tab;
    if (t === 'chatbot' || t === 'college-briefing') consumeTestQuestion();
  });

  function mount() {
    var pane = document.getElementById('tab-chatbot');
    if (!pane) return;
    var host = pane.querySelector('.cplchat-mount') || pane.querySelector('.main-container') || pane;
    if (host.getAttribute('data-cplchat-mounted') === '1') return; // idempotent
    host.setAttribute('data-cplchat-mounted', '1');
    build(host);
    consumeTestQuestion();
  }

  // ── Mount the SAME assistant somewhere else (Sam, 2026-08-11) ──────────────
  // The My College tab embeds the assistant rather than linking out to
  // #chatbot, so a coordinator never leaves the page. This is deliberately a
  // SECOND MOUNT of the one instance, not a second assistant: the audience
  // rules, the feedback path, the markdown renderer and the conversation
  // history all stay in this file, so they cannot drift apart. `convo` is
  // module-level on purpose — the thread follows you between the two places.
  //
  // Only one host is live at a time (they are tab panes), and build() re-points
  // the module's element refs, so re-mounting on tab switch is correct rather
  // than duplicative. `_host` tracks which one currently owns the widget.
  var _host = null;
  function mountInto(host) {
    if (!host || host === _host) return;
    _host = host;
    host.innerHTML = '';
    host.setAttribute('data-cplchat-mounted', '1');
    build(host);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }

  // Pure helpers exposed for the jsdom tests (tests/cpl_chat_audience.test.js,
  // tests/sierra_markdown.test.js).
  window.CPL_CHAT = {
    AUDIENCES: AUDIENCES, AUD_KEY: AUD_KEY, feedbackPayload: feedbackPayload,
    escapeHtml: escapeHtml, inlineMd: inlineMd, renderMarkdown: renderMarkdown,
    SIERRA_MARK: SIERRA_MARK, TEST_Q_KEY: TEST_Q_KEY,
    consumeTestQuestion: consumeTestQuestion,
    // The growing-log follow (tests/my_college_refinement.test.js). jsdom has no
    // layout, so the only way to exercise the below-the-fold branch is to stub
    // the geometry and drive scrollDown() directly; `_setStick` reproduces the
    // reader-scrolled-away state that `nearBottom()` cannot reach with every
    // rect at zero. Test seams, not API — underscored, and nothing calls them.
    _scrollDown: scrollDown,
    _setStick: function (v) { stick = !!v; },
    // Embed the one assistant elsewhere (My College). See mountInto above.
    mountInto: mountInto,
    // Prefill the box without sending — the visitor edits before asking.
    // ⚠ Do NOT make this send. The Sierra Training tab's "Test in Sierra"
    // hand-off depends on the reviewer being able to tweak a logged question
    // before replaying it. Use ask() when you want one click to be enough.
    prefill: function (q) {
      if (!inputEl) return false;
      inputEl.value = String(q == null ? '' : q).slice(0, 1000);
      try { inputEl.focus(); } catch (e) { /* hidden pane */ }
      return true;
    },
    // Fill AND send — the behaviour of this assistant's own starter chips,
    // exposed so an embedding tab's suggested questions cost one click rather
    // than two (Sam, 2026-08-11: "so they don't have to take 2 steps and get
    // lost"). Returns false if the assistant is not mounted, so the caller can
    // fall back to navigating to the full tab.
    ask: function (q) {
      if (!inputEl) return false;
      inputEl.value = String(q == null ? '' : q).slice(0, 1000);
      submit();
      return true;
    },
  };
})();
