/*
 * CPL Assistant — in-dashboard chat panel (Phase 1 of the chatbox integration).
 *
 * A native chat surface for the "CPL Assistant" tab. It talks DIRECTLY to the
 * shared Supabase Edge Function `cpl-chat` (the same RAG backend that powers the
 * live map.rccd.edu widget — see docs/kb-notes/cpl-chatbox-integration-scope.md),
 * which runs 4 parallel lookups (vector RAG + college detection + live metrics +
 * topic exhibit search) and streams a Claude Sonnet answer back over SSE.
 *
 * Why direct-to-Edge-Function (not via the Cloudflare proxy like quickstart.js):
 * the proxy buffers a single non-streaming Claude call, whereas this needs the
 * function's RAG orchestration + token-by-token SSE. The DOM/markdown scaffolding
 * is modeled on quickstart.js; the SSE contract is the function's own
 * (`event: sources` → `event: text` deltas → `event: done`).
 *
 * SAFETY: only the publishable anon key is used client-side (already shipped in
 * unified_courses.js; RLS gates everything). Model output is HTML-escaped BEFORE
 * the markdown-lite pass, so a crafted answer can't inject markup.
 *
 * This file is a STATIC asset (not regenerated by excel_to_dashboard.py). It is
 * the artifact the future Student CPL Portal embed reuses — keep it
 * self-contained behind the CONFIG block below.
 */
(function () {
  'use strict';

  // ── Config ── (anon key is public + RLS-gated; mirrors unified_courses.js)
  var SUPABASE_URL = 'https://hvuwhnbuahrtptokpqfh.supabase.co';
  var SUPABASE_ANON = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM';
  var CHAT_URL = SUPABASE_URL + '/functions/v1/cpl-chat';

  var SUGGESTED = [
    'What is Credit for Prior Learning?',
    'Does Riverside City College offer firefighter CPL?',
    'Which colleges give credit for a real estate license?',
    'How many students has CPL served statewide?',
  ];

  // ── Session id (one per browser tab session, reused across tab switches) ──
  function sessionId() {
    try {
      var k = 'cpl_chat_session';
      var v = sessionStorage.getItem(k);
      if (!v) {
        v = (window.crypto && crypto.randomUUID) ? crypto.randomUUID()
          : 'sess-' + Date.now() + '-' + Math.random().toString(16).slice(2);
        sessionStorage.setItem(k, v);
      }
      return v;
    } catch (e) {
      return 'sess-' + Date.now();
    }
  }

  // ── Tiny DOM helper (same shape as quickstart.js) ──
  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        if (k === 'style') { for (var s in attrs.style) n.style[s] = attrs.style[s]; }
        else if (k.indexOf('on') === 0 && typeof attrs[k] === 'function') { n.addEventListener(k.slice(2), attrs[k]); }
        else if (k === 'className') { n.className = attrs[k]; }
        else { n.setAttribute(k, attrs[k]); }
      }
    }
    if (kids) {
      if (!Array.isArray(kids)) kids = [kids];
      kids.forEach(function (c) {
        if (typeof c === 'string') n.appendChild(document.createTextNode(c));
        else if (c instanceof Node) n.appendChild(c);
      });
    }
    return n;
  }

  // ── Markdown-lite → safe HTML ──
  // Escape FIRST (so model text can't inject), then apply a tiny subset:
  // **bold**, `code`, [text](http…) links, "- " bullet lists, blank-line paras.
  function escapeHtml(s) {
    return String(s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
  function inlineMd(s) {
    return s
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      // links: only http(s), target=_blank, escaped text already
      .replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,
        '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>')
      // bare URLs → links
      .replace(/(^|[\s(])((https?:\/\/)[^\s)]+)(?=[\s).,;!?]|$)/g,
        '$1<a href="$2" target="_blank" rel="noopener noreferrer">$2</a>');
  }
  function renderMarkdown(text) {
    var safe = escapeHtml(text);
    var blocks = safe.split(/\n{2,}/);
    var html = '';
    blocks.forEach(function (block) {
      var lines = block.split(/\n/);
      var isList = lines.length && lines.every(function (l) { return /^\s*[-*]\s+/.test(l) || l.trim() === ''; });
      if (isList) {
        html += '<ul>' + lines.filter(function (l) { return l.trim(); })
          .map(function (l) { return '<li>' + inlineMd(l.replace(/^\s*[-*]\s+/, '')) + '</li>'; })
          .join('') + '</ul>';
      } else {
        html += '<p>' + inlineMd(block.replace(/\n/g, '<br>')) + '</p>';
      }
    });
    return html;
  }

  // ── Chat transcript helpers ──
  var logEl, inputEl, sendBtn, statusEl;

  function scrollDown() {
    if (logEl) requestAnimationFrame(function () { logEl.scrollTop = logEl.scrollHeight; });
  }
  function addUserMsg(text) {
    var row = el('div', { className: 'cplchat-msg cplchat-user' },
      el('div', { className: 'cplchat-bubble' }, text));
    logEl.appendChild(row);
    scrollDown();
  }
  // Returns the bubble node so the streamer can append to it as deltas arrive.
  function addAssistantMsg() {
    var bubble = el('div', { className: 'cplchat-bubble' });
    var row = el('div', { className: 'cplchat-msg cplchat-bot' },
      [el('div', { className: 'cplchat-avatar', 'aria-hidden': 'true' }, '🎓'), bubble]);
    logEl.appendChild(row);
    scrollDown();
    return bubble;
  }
  function setStatus(text, kind) {
    if (!statusEl) return;
    statusEl.textContent = text || '';
    statusEl.className = 'cplchat-status' + (kind ? ' cplchat-' + kind : '');
  }

  // ── Call the Edge Function + stream the SSE response ──
  async function ask(query) {
    var bubble = addAssistantMsg();
    bubble.innerHTML = '<span class="cplchat-typing">●●●</span>';
    var full = '';

    var resp;
    try {
      resp = await fetch(CHAT_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': SUPABASE_ANON,
          'Authorization': 'Bearer ' + SUPABASE_ANON,
        },
        body: JSON.stringify({ query: query, session_id: sessionId() }),
      });
    } catch (e) {
      bubble.innerHTML = renderMarkdown('Sorry — I couldn\'t reach the assistant. Please check your connection and try again.');
      return;
    }

    if (!resp.ok) {
      var msg = 'Sorry — something went wrong (error ' + resp.status + ').';
      if (resp.status === 429) msg = 'I\'m getting a lot of questions right now. Please wait a minute and try again.';
      bubble.innerHTML = renderMarkdown(msg);
      return;
    }
    if (!resp.body || !resp.body.getReader) {
      // No streaming support — fall back to text().
      var txt = await resp.text();
      bubble.innerHTML = renderMarkdown(txt || 'No response.');
      return;
    }

    var reader = resp.body.getReader();
    var decoder = new TextDecoder();
    var buffer = '';
    var firstToken = true;
    try {
      while (true) {
        var chunk = await reader.read();
        if (chunk.done) break;
        buffer += decoder.decode(chunk.value, { stream: true });
        var rawEvents = buffer.split('\n\n');
        buffer = rawEvents.pop() || '';
        for (var i = 0; i < rawEvents.length; i++) {
          var evt = parseSse(rawEvents[i]);
          if (!evt) continue;
          if (evt.event === 'text') {
            try {
              var d = JSON.parse(evt.data);
              if (d && typeof d.text === 'string') {
                if (firstToken) { bubble.innerHTML = ''; firstToken = false; }
                full += d.text;
                bubble.innerHTML = renderMarkdown(full);
                scrollDown();
              }
            } catch (e) { /* skip malformed delta */ }
          } else if (evt.event === 'done') {
            // stream complete
          }
          // evt.event === 'sources' is available but not surfaced in Phase 1.
        }
      }
    } finally {
      reader.releaseLock();
    }
    if (!full) bubble.innerHTML = renderMarkdown('I don\'t have an answer for that yet. Try rephrasing, or email MAP@rccd.edu.');
  }

  // Parse one SSE event block ("event: <name>\ndata: <json>")
  function parseSse(block) {
    var out = { event: 'message', data: '' };
    var got = false;
    block.split('\n').forEach(function (line) {
      if (line.indexOf('event:') === 0) { out.event = line.slice(6).trim(); got = true; }
      else if (line.indexOf('data:') === 0) { out.data += line.slice(5).trim(); got = true; }
    });
    return got ? out : null;
  }

  // ── Submit flow ──
  var busy = false;
  async function submit() {
    if (busy) return;
    var q = (inputEl.value || '').trim();
    if (!q) { inputEl.focus(); return; }
    busy = true;
    sendBtn.disabled = true; inputEl.disabled = true;
    addUserMsg(q);
    inputEl.value = '';
    setStatus('Thinking…', 'pending');
    var firstChips = document.getElementById('cplchat-suggest');
    if (firstChips) firstChips.remove(); // hide starter chips after first question
    try {
      await ask(q);
      setStatus('');
    } catch (e) {
      setStatus('Something went wrong. Try again.', 'error');
    } finally {
      busy = false;
      sendBtn.disabled = false; inputEl.disabled = false;
      inputEl.focus();
    }
  }

  // ── Build the panel ──
  function build(mount) {
    var wrap = el('div', { className: 'cplchat' });

    wrap.appendChild(el('div', { className: 'cplchat-intro' }, [
      el('h2', null, 'CPL Assistant'),
      el('p', null,
        'Ask about Credit for Prior Learning — what a college offers, where to ' +
        'find credit for a license or certification, or statewide CPL numbers. ' +
        'Answers draw on the CPL knowledge base, live dashboard metrics, and ' +
        '2,300+ statewide exhibits.'),
      el('p', { className: 'cplchat-beta' },
        '🧪 Beta — in development. Please don\'t enter personal information; ' +
        'questions are logged to improve answers.'),
    ]));

    logEl = el('div', { className: 'cplchat-log', id: 'cplchat-log', 'aria-live': 'polite' });

    // Starter suggestion chips
    var chips = el('div', { className: 'cplchat-suggest', id: 'cplchat-suggest' });
    SUGGESTED.forEach(function (s) {
      chips.appendChild(el('button', {
        type: 'button', className: 'cplchat-chip',
        onclick: function () { inputEl.value = s; submit(); },
      }, s));
    });
    logEl.appendChild(chips);
    wrap.appendChild(logEl);

    statusEl = el('div', { className: 'cplchat-status', id: 'cplchat-status', 'aria-live': 'polite' });
    wrap.appendChild(statusEl);

    var row = el('div', { className: 'cplchat-inputrow' });
    inputEl = el('input', {
      type: 'text', id: 'cplchat-input', className: 'cplchat-input',
      placeholder: 'Ask a question about CPL…', autocomplete: 'off', maxlength: '1000',
    });
    sendBtn = el('button', { type: 'button', className: 'cplchat-send' }, 'Send');
    inputEl.addEventListener('keydown', function (e) { if (e.key === 'Enter') { e.preventDefault(); submit(); } });
    sendBtn.addEventListener('click', submit);
    row.appendChild(inputEl); row.appendChild(sendBtn);
    wrap.appendChild(row);

    mount.appendChild(wrap);
  }

  function mount() {
    var pane = document.getElementById('tab-chatbot');
    if (!pane) return;
    var host = pane.querySelector('.cplchat-mount') || pane.querySelector('.main-container') || pane;
    if (host.getAttribute('data-cplchat-mounted') === '1') return; // idempotent
    host.setAttribute('data-cplchat-mounted', '1');
    build(host);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }
})();
