// CPL Pathways — pathway definitions (curated, static).
//
// Consumed by cpl_pathways.js (the 🎓 CPL Pathways tab). Each program lists the
// degree's required coursework by section; the renderer DERIVES the CPL ✓ marks
// from the live CER dataset (credential_reference_data.js) at render time, so
// this file only needs to be right about the REQUIREMENTS — the articulation
// state stays live (a course added to the MAP platform tomorrow lights up ✓
// here with no edit). `cpl:` stamps and `clep_fallback:` lists are fallbacks
// used only when the live CER payload fails to load. Sections flagged
// `no_count: true` render + live-resolve but stay out of the unit buckets
// (alternate-track lists would otherwise double-count the major).
//
// First pathway: Cerritos College — Field Ironworker Supervisor BS (first
// cohort fall 2027), built for the California Apprenticeship Council
// presentation (2026-08-13). Sourcing (researched 2026-07-10):
//  · regionalcte.org/browse/ZyxAg — the LAOCRC program record (TOP 095700;
//    two-part structure; GE gate; the ten upper-division topic areas). NOTE:
//    the record's section-4 COURSES table is JavaScript-rendered — invisible
//    to crawlers/archives; grab the course-by-course list from a real browser
//    when Cerritos publishes the final curriculum, and replace the topic rows.
//  · CCCCO COCI course inventory (kb/reference/coci_course_list.xlsx,
//    2026-07-09 snapshot) — all 24 Cerritos IWAP apprenticeship courses.
//  · Cerritos catalog (courseleaf): Apprenticeship: Field Ironworkers A.S. —
//    60 units, 27–29 major units, Reinforcing or Structural core.
//  · EdSource 2026-02: CSU withdrew its duplication objection; CCCCO final
//    approval under the AB 927 statewide baccalaureate process.
//  · ESLEI 24-35 (title 5 §55052.5): systemwide CLEP GE-credit chart.
// This file is hand-curated (NOT regenerated by excel_to_dashboard.py).
window.CPL_PATHWAYS = {
  _as_of: "2026-07-10",
  programs: [
    {
      id: "cerritos-field-ironworker-bs",
      college: "Cerritos College",
      program: "Field Ironworker Supervisor",
      degree: "Bachelor of Science",
      start: "Fall 2027",
      status: "Approved Feb 2026 — AB 927 CCC baccalaureate",
      audience: "Ironworker journeyworkers — any JATC, anywhere",
      blurb: "The nation's first bachelor's degree built on a field-ironworker "
        + "apprenticeship — developed with the California Field Ironworkers (Locals 416 "
        + "and 433). A journeyworker card is college credit at Cerritos: every course "
        + "below with a ✓ is already articulated for Credit for Prior Learning in the "
        + "MAP platform, wherever the ironworker apprenticed. CLEP exams (◆) can clear "
        + "general-education requirements the same way — proof of learning, not seat time.",
      facts: [
        "A journeyworker card = 4,800–6,000 on-the-job hours plus ~4 years of classroom training — the learning CPL recognizes",
        "1,300+ supervisor openings a year in LA County alone",
        "+$34,000/yr average wage premium with the bachelor's",
        "≈$10,560 total tuition for all 120 units",
        "Upper-division coursework online — built for working ironworkers",
      ],
      total_units: 120,
      campaign: {
        kicker: "The billboard",
        headline: "Iron workers: your journeyworker training is already worth {cpl_units}+ units at Cerritos College. Finish the bachelor's the way you built your trade.",
        sub: "Regional outreach concept — billboard + social. CPL for the apprenticeship major, CLEP for GE, one application. The trade you mastered is a year of the degree, already done.",
      },
      sections: [
        {
          id: "as-major",
          title: "Ironworker apprenticeship major — articulated in MAP today",
          note: "The Apprenticeship: Field Ironworkers A.S. requires 27–29 major units (Reinforcing or Structural core). Cerritos has 31.5 units of apprenticeship coursework articulated as Credit by Exam — a journeyworker clears the entire major without repeating a class.",
          wide: true,
          courses: [
            { code: "IWAP 40.07", title: "FIW — Orientation", units: 4.0,
              cpl: { credential: "FIW Orientation", types: ["Credit By Exam"] } },
            { code: "IWAP 40.09", title: "IW — General Rigging", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — General Rigging", types: ["Credit By Exam"] } },
            { code: "IWAP 40.11", title: "Welding II — Reinforcing", units: 2.5,
              cpl: { credential: "Ironworker Apprenticeship — Welding II", types: ["Credit By Exam"] } },
            { code: "IWAP 40.12", title: "IW — Reinforcing Iron I", units: 2.0,
              cpl: { credential: "Reinforcing 1", types: ["Credit By Exam"] } },
            { code: "IWAP 40.15", title: "IW — Post Tension I", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Post Tensioning I", types: ["Credit By Exam"] } },
            { code: "IWAP 40.22", title: "IW — Cranes", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Cranes", types: ["Credit By Exam"] } },
            { code: "IWAP 40.50", title: "IW — Mixed Base / Reinforcing", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Mixed Base", types: ["Credit By Exam"] } },
            { code: "IWAP 40.53", title: "IW — Detailing / Reinforcing Iron", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Detailing", types: ["Credit By Exam"] } },
            { code: "IWAP 40.55", title: "IWS — Reinforcing Foreman Training", units: 2.0,
              cpl: { credential: "Foreman Training", types: ["Credit By Exam"] } },
            { code: "IWAP 40.56", title: "IW — Trade Science / Ironworker History", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Ironworker History", types: ["Credit By Exam"] } },
            { code: "IWAP 40.63", title: "IW — Structural Lead Hazard", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Lead Hazard", types: ["Credit By Exam"] } },
            { code: "IWAP 41.03", title: "IW — Reinforcing II", units: 1.0,
              cpl: { credential: "Ironworker Apprenticeship — Reinforcing II", types: ["Credit By Exam"] } },
            { code: "IWAP 41.07", title: "IW — Post Tension II", units: 2.5,
              cpl: { credential: "Ironworker Apprenticeship — Post Tensioning II", types: ["Credit By Exam"] } },
            { code: "IWAP 41.08", title: "IW — Post Tension III", units: 2.0,
              cpl: { credential: "Post Tensioning 3", types: ["Credit By Exam"] } },
            { code: "IWAP 41.09", title: "OSHA 30 / Extension Review", units: 1.5,
              cpl: { credential: "Ext & Review", types: ["Credit By Exam"] } },
          ],
        },
        {
          id: "ge-lower",
          title: "General Education — the admission gate (CGEC)",
          note: "A completed GE pattern — the Cerritos General Education Curriculum (24–28 units; Cal-GETC also accepted) — is required before admission to the upper division. Every ◆ area has CLEP exams carrying systemwide GE credit (ESLEI 24-35) — test out instead of sitting in class.",
          courses: [
            { title: "CGEC 1A — English Composition", units: 3 },
            { title: "CGEC 1B — Oral Communication & Critical Thinking", units: 3,
              clep_area: "Language and Rationality" },
            { title: "CGEC 2 — Mathematical Concepts & Quantitative Reasoning", units: 3,
              clep_area: "Language and Rationality" },
            { title: "CGEC 3 — Arts & Humanities", units: 3,
              clep_area: "Arts and Humanities" },
            { title: "CGEC 4 — Social & Behavioral Sciences", units: 3,
              clep_area: "Social/Behavioral Sciences" },
            { title: "CGEC 5 — Natural Sciences", units: 3,
              clep_area: "Natural Sciences" },
            { title: "CGEC 6 — Ethnic Studies", units: 3 },
            { title: "CGEC 7 — American Institutions", units: 3 },
          ],
        },
        {
          id: "as-electives",
          title: "Electives (to the 60-unit associate degree)",
          note: "Degree-applicable electives round out the associate degree; additional apprenticeship or work-experience credit can apply here too.",
          courses: [
            { title: "Degree-applicable electives", units: 4.5 },
          ],
        },
        {
          id: "upper-ge-note",
          title: "Upper-division General Education (within years 3–4)",
          note: "Title 5 (effective Aug 2025) requires ≥9 units of upper-division GE inside the baccalaureate's ≥40 upper-division units — taken alongside the major.",
          courses: [
            { title: "Upper-division GE", units: 9 },
          ],
        },
        {
          id: "as-major-progress",
          title: "More apprenticeship coursework — articulations in progress",
          note: "The rest of Cerritos's IWAP inventory (Structural-track and welding courses). These flip to ✓ automatically as Cerritos adds their MAP articulations — no edit to this page needed. Not counted in the unit totals (a student completes one track).",
          no_count: true,
          courses: [
            { code: "IWAP 40.05", title: "IW — Welding III", units: 2.5 },
            { code: "IWAP 40.10", title: "Welding I — Reinforcing", units: 2.5 },
            { code: "IWAP 40.21", title: "Structural Steel I", units: 2.5 },
            { code: "IWAP 40.26", title: "Metal Building Erection / Foreman Training", units: 2.5 },
            { code: "IWAP 40.60", title: "Structural, Architectural & Ornamental I", units: 2.5 },
            { code: "IWAP 40.61", title: "IW — Structural Precast Concrete / Qualified Rigger", units: 2.0 },
            { code: "IWAP 41.04", title: "IW — Architectural III", units: 2.5 },
            { code: "IWAP 41.05", title: "IW — Architectural II", units: 2.5 },
            { code: "IWAP 41.06", title: "IW — Structural Steel II", units: 2.0 },
          ],
        },
        {
          id: "upper-major",
          title: "Upper-division major — years 3–4 (online, while working)",
          note: "The baccalaureate coursework: 60 upper-division units of supervision and management curriculum plus upper-division GE. Topic areas below are from the approved program record; the course-by-course catalog publishes ahead of the fall 2027 cohort.",
          wide: true,
          courses: [
            { title: "Industrial Trades Leadership" },
            { title: "Human Resources for Skilled Trades" },
            { title: "Labor Law" },
            { title: "Operations" },
            { title: "IT for Enterprise Management for Skilled Trades" },
            { title: "Cost Estimating and Control" },
            { title: "Negotiations" },
            { title: "Accounting" },
            { title: "Multicultural Communication" },
            { title: "Advanced CAD" },
          ],
        },
      ],
      footnotes: [
        "CPL ✓ courses are articulated by Cerritos College in the Mapping Articulated Pathways (MAP) platform as Credit by Exam for the ironworker apprenticeship curriculum — available to journeyworkers regardless of where they completed their training.",
        "◆ CLEP GE options reflect the CCCCO systemwide exam-credit charts (ESLEI 24-35, title 5 §55052.5): a passing score of 50 grants a minimum of 3 semester units in the GE division shown. The college applies the credit on receipt of scores.",
        "Degree structure per the title 5 baccalaureate regulations effective Aug 2025 (governing a fall 2027 start): ≥120 units total, ≥40 upper-division units (major + GE inclusive), ≥36 GE units with ≥9 upper-division. Tuition ≈$46/unit lower division, ≈$130/unit upper division — about $10,560 total on the 60/60 model. Admission to the upper division requires the completed associate degree and GE pattern.",
        "The associate-degree major (27–29 units, Reinforcing or Structural core) is fully covered by the 31.5 articulated units; surplus apprenticeship credit applies as electives. Stackable along the way: Certificates of Achievement in Field Ironworks Reinforcing (34 units) and Structural (38 units).",
        "Approval: provisionally approved 2025; CSU withdrew its duplication objection and the Chancellor's Office granted final approval under AB 927 in February 2026 (EdSource, 2026-02-20).",
        "Veterans: Cerritos also articulates Basic Military Training (health/kinesiology GE-area credit) — service members entering the trades bring additional CPL.",
        "IWAP course inventory verified against the CCCCO COCI course catalog (snapshot 2026-07-09).",
      ],
      sources: [
        { label: "Program record (LAOCRC / Regional CTE)", url: "https://regionalcte.org/browse/ZyxAg" },
        { label: "Cerritos College Field Ironworkers apprenticeship", url: "https://www.cerritos.edu/apprenticeship-programs/Field_Ironwork.htm" },
        { label: "Apprenticeship: Field Ironworkers A.S. (catalog)", url: "https://cerritos-public.courseleaf.com/degrees-certificates-courses/degrees-certificates-programs-majors/field-ironworkers-aa/" },
        { label: "EdSource — final approval (2026-02)", url: "https://edsource.org/2026/california-community-colleges-approve-3-new-bachelors-degrees-over-california-state-university-objections/751678" },
        { label: "MAP CPL Insights Dashboard", url: "https://cpldashboardcccco.azurewebsites.net/insights/dashboard" },
      ],
    },
  ],
};
