/*
 * cpl_todos.js — the 📋 To-Do button on every dashboard tab.
 *
 * A simple, layman-readable daily checklist split into "For Sam" (human
 * curation) and "For Fable" (the Claude session's engineering / pre-curation
 * queue), with a one-paragraph "where we are" status distilled from the
 * latest session handoff.
 *
 * Data: kb/cpl_todos.json — refreshed at every Rule-8 checkpoint alongside
 * the session handoff (it IS the handoff distilled for the dashboard).
 * Static asset: NOT regenerated by excel_to_dashboard.py; no Supabase, no
 * auth. Check-off state is per-browser localStorage (cplTodos.v1), keyed by
 * the feed's _as_of date so each feed refresh starts a fresh checklist —
 * done items are deleted from the feed at checkpoint, not left checked.
 *
 * UI: one floating button (bottom-right, above the toast slot) visible on
 * every tab; the badge counts this tab's unchecked items. The panel lists
 * the current tab's items first; items for other tabs carry a clickable tab
 * chip that navigates there (tabs.js routes on location.hash). Injects its
 * own CSS from var(--token)s, so both HTMLs are covered without a Rule-4
 * mirror beyond the <script> tag.
 */
(function () {
  "use strict";

  var FEED_URL = "kb/cpl_todos.json";
  var LS_KEY = "cplTodos.v1";
  var WHO_LABELS = {
    sam: "For Sam — curation",
    fable: "For Fable — engineering (next session)",
    other: "Other",
  };
  // The feed writes `for: "Sam" | "Fable"` (that is the field CLAUDE.md Rule 9
  // documents and every checkpoint has written since the feed shipped); this
  // module was reading `it.who`, the name an early fixture used. Nothing threw:
  // `byWho[undefined]` is a perfectly good key, so the live panel rendered ONE
  // section headed "For Undefined" holding every item, and the split this
  // feature exists for was invisible. Accept both spellings, fold to a
  // lowercase key, and never let the label be built from a missing value.
  function whoKey(item) {
    return String((item && (item.who || item.for)) || "").toLowerCase() || "other";
  }

  var feed = null;     // parsed kb/cpl_todos.json
  var open = false;

  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) Object.keys(attrs).forEach(function (k) {
      if (k === "class") n.className = attrs[k];
      else if (k === "title") n.title = attrs[k];
      else n.setAttribute(k, attrs[k]);
    });
    (kids || []).forEach(function (c) { n.appendChild(typeof c === "string" ? document.createTextNode(c) : c); });
    return n;
  }

  function currentTab() {
    var h = (location.hash || "").replace(/^#/, "").split("?")[0];
    return h || "dashboard";
  }

  // Display label for a tab key — read from the rendered nav (the same
  // source tabs.js derives VALID_TABS from), falling back to a prettified key.
  function tabLabel(key) {
    var btns = document.querySelectorAll(".cpl-tab[data-tab]");
    for (var i = 0; i < btns.length; i++) {
      if (btns[i].getAttribute("data-tab") === key) return (btns[i].textContent || "").trim() || key;
    }
    return key.replace(/-/g, " ").replace(/\b[a-z]/g, function (c) { return c.toUpperCase(); });
  }

  // ── check-off state (per-browser; keyed by the feed's _as_of) ─────────────
  function loadDone() {
    try {
      var all = JSON.parse(localStorage.getItem(LS_KEY) || "{}");
      if (!feed) return {};
      // Prune stale feeds so the key never accumulates old dates.
      var keep = {};
      if (all[feed._as_of]) keep[feed._as_of] = all[feed._as_of];
      if (JSON.stringify(keep) !== JSON.stringify(all)) {
        localStorage.setItem(LS_KEY, JSON.stringify(keep));
      }
      return keep[feed._as_of] || {};
    } catch (e) { return {}; }
  }
  function setDone(id, isDone) {
    try {
      var all = JSON.parse(localStorage.getItem(LS_KEY) || "{}");
      var rec = all[feed._as_of] = all[feed._as_of] || {};
      if (isDone) rec[id] = 1; else delete rec[id];
      localStorage.setItem(LS_KEY, JSON.stringify(all));
    } catch (e) {}
  }

  function itemOnTab(item, tab) { return item.tab === tab || item.tab === "all"; }

  function uncheckedCountFor(tab) {
    if (!feed || !feed.items) return 0;
    var done = loadDone();
    return feed.items.filter(function (it) { return itemOnTab(it, tab) && !done[it.id]; }).length;
  }

  // ── CSS (tokens only — no raw hex) ────────────────────────────────────────
  function ensureCss() {
    if (document.getElementById("cpl-todo-css")) return;
    var css =
      ".cpl-todo-btn{position:fixed;right:18px;bottom:56px;z-index:900;display:flex;align-items:center;gap:6px;" +
        "padding:8px 14px;border-radius:20px;border:none;background:var(--cobalt);" +
        "color:#fff;font-size:.88rem;cursor:pointer;box-shadow:0 4px 12px rgba(20,20,30,0.25);}" +
      ".cpl-todo-btn:hover{background:#003B8E;}" +
      ".cpl-todo-badge{background:var(--gold-accent);color:var(--navy-primary);border-radius:10px;font-size:.72rem;" +
        "font-weight:700;padding:1px 7px;}" +
      ".cpl-todo-panel{display:none;position:fixed;right:18px;bottom:104px;z-index:901;width:380px;max-width:92vw;" +
        "max-height:70vh;overflow-y:auto;background:var(--surface-opaque);border:1px solid var(--border-strong);" +
        "border-radius:10px;box-shadow:0 8px 28px rgba(0,0,0,0.3);padding:14px 16px;text-align:left;}" +
      ".cpl-todo-panel.show{display:block;}" +
      ".cpl-todo-panel h4{margin:0 0 2px;color:var(--navy-primary);font-size:1rem;}" +
      ".cpl-todo-meta{color:var(--text-faint);font-size:.72rem;margin:0 0 8px;}" +
      ".cpl-todo-status{color:var(--text-body);font-size:.8rem;line-height:1.45;background:var(--surface-subtle);" +
        "border:1px solid var(--border);border-radius:8px;padding:8px 10px;margin:0 0 10px;}" +
      ".cpl-todo-sec{margin:10px 0 4px;font-size:.82rem;font-weight:700;color:var(--text-strong);" +
        "border-bottom:1px solid var(--border);padding-bottom:3px;}" +
      ".cpl-todo-item{display:flex;gap:8px;align-items:flex-start;padding:6px 4px;border-radius:6px;" +
        "font-size:.82rem;color:var(--text-body);line-height:1.4;}" +
      ".cpl-todo-item.here{background:var(--surface-subtle);border-left:3px solid var(--gold-accent);padding-left:6px;}" +
      ".cpl-todo-item.done label{text-decoration:line-through;color:var(--text-faint);}" +
      ".cpl-todo-item input{margin-top:3px;flex:none;cursor:pointer;}" +
      ".cpl-todo-item label{cursor:pointer;}" +
      ".cpl-todo-chip{display:inline-block;flex:none;margin-left:6px;font-size:.68rem;color:var(--accent-link);" +
        "border:1px solid var(--border-strong);border-radius:9px;padding:0 7px;cursor:pointer;white-space:nowrap;" +
        "background:var(--surface-subtle);}" +
      ".cpl-todo-chip:hover{background:var(--surface-muted);}" +
      ".cpl-todo-foot{color:var(--text-faint);font-size:.7rem;margin-top:10px;}" +
      ".cpl-todo-close{float:right;border:none;background:none;font-size:1.1rem;color:var(--text-muted);cursor:pointer;}";
    document.head.appendChild(el("style", { id: "cpl-todo-css" }, [css]));
  }

  // ── render ────────────────────────────────────────────────────────────────
  function renderBadge() {
    var b = document.getElementById("cpl-todo-badge");
    if (!b) return;
    var n = uncheckedCountFor(currentTab());
    b.textContent = String(n);
    b.style.display = n ? "" : "none";
  }

  function renderPanel() {
    var panel = document.getElementById("cpl-todo-panel");
    if (!panel || !feed) return;
    var tab = currentTab();
    var done = loadDone();
    panel.innerHTML = "";

    var close = el("button", { class: "cpl-todo-close", type: "button", "aria-label": "Close" }, ["×"]);
    close.onclick = togglePanel;
    panel.appendChild(close);
    panel.appendChild(el("h4", null, ["📋 Daily To-Do"]));
    panel.appendChild(el("p", { class: "cpl-todo-meta" },
      ["as of " + (feed._as_of || "—") + (feed._session ? " · Session " + feed._session : "") +
       " · " + tabLabel(tab)]));
    if (feed._status) {
      panel.appendChild(el("p", { class: "cpl-todo-status" }, ["Where we are: " + feed._status]));
    }

    var byWho = {};
    (feed.items || []).forEach(function (it) {
      var k = whoKey(it);
      (byWho[k] = byWho[k] || []).push(it);
    });
    Object.keys(byWho).forEach(function (who) {
      panel.appendChild(el("div", { class: "cpl-todo-sec" },
        [WHO_LABELS[who] || ("For " + who.charAt(0).toUpperCase() + who.slice(1))]));
      // This tab's items first (feed order preserved within each half).
      var items = byWho[who].filter(function (it) { return itemOnTab(it, tab); })
        .concat(byWho[who].filter(function (it) { return !itemOnTab(it, tab); }));
      items.forEach(function (it) {
        var here = itemOnTab(it, tab);
        var row = el("div", { class: "cpl-todo-item" + (here ? " here" : "") + (done[it.id] ? " done" : "") });
        var cbId = "cpl-todo-cb-" + it.id;
        var cb = el("input", { type: "checkbox", id: cbId });
        cb.checked = !!done[it.id];
        cb.onchange = function () {
          setDone(it.id, cb.checked);
          row.classList.toggle("done", cb.checked);
          renderBadge();
        };
        row.appendChild(cb);
        // The chip lives on the ROW, not inside the <label> — a chip click
        // must navigate, not toggle the checkbox via label activation.
        row.appendChild(el("label", { for: cbId }, [it.text]));
        if (!here && it.tab && it.tab !== "all") {
          var chip = el("span", { class: "cpl-todo-chip", title: "Open the " + tabLabel(it.tab) + " tab" },
            [tabLabel(it.tab) + " →"]);
          chip.onclick = function () {
            location.hash = it.tab; // tabs.js routes; hashchange re-renders us
          };
          row.appendChild(chip);
        }
        panel.appendChild(row);
      });
    });

    panel.appendChild(el("p", { class: "cpl-todo-foot" }, [
      "Check-offs live in this browser only and reset when the list refreshes (every work session). " +
      "Done items get deleted from the list itself at the next checkpoint."]));
  }

  function togglePanel() {
    var panel = document.getElementById("cpl-todo-panel");
    if (!panel) return;
    open = !open;
    if (open) renderPanel();
    panel.classList.toggle("show", open);
  }

  function init() {
    // Fetch first: a missing/broken feed (404 on a preview deploy) means the
    // button never appears — fail soft, no dead chrome.
    fetch(FEED_URL, { cache: "no-store" })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (data) {
        if (!data || !data.items || !data.items.length) return;
        feed = data;
        ensureCss();
        var badge = el("span", { class: "cpl-todo-badge", id: "cpl-todo-badge" }, ["0"]);
        var btn = el("button", {
          class: "cpl-todo-btn", id: "cpl-todo-btn", type: "button",
          title: "Daily to-do list — curation work for Sam + the engineering queue for Fable, refreshed each work session.",
        }, ["📋 To-Do", badge]);
        btn.onclick = togglePanel;
        document.body.appendChild(btn);
        document.body.appendChild(el("div", { class: "cpl-todo-panel", id: "cpl-todo-panel" }));
        renderBadge();
        window.addEventListener("hashchange", function () {
          renderBadge();
          if (open) renderPanel();
        });
      })
      .catch(function () { /* fail soft */ });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
