// CPL Implementation Funding tab — renderer.
//
// STATIC consumer asset (NOT regenerated by excel_to_dashboard.py), lazy-loaded
// by the inline boot in the tab shell on first activation of
// #tab-implementation-funding (see the shell snippet next to the script
// includes in both HTMLs). Data: cpl_funding_data.js (window.CPL_FUNDING),
// built one-shot by funding/_build_funding_data.py from the committed
// funding/CPL_Funding_Model_2026.xlsx — also lazy-loaded here, never eager.
//
// Self-contained behind this file: scoped CSS is injected from JS (the CER
// ensureCerScopeCss pattern) so both HTMLs are covered without a Rule-4
// mirror; everything renders into the shell's #cplFundingMount.
//
// v1.1 (2026-06-11): Colleges|Districts rollup toggle, Per-year|2026-30-total
// period toggle, and click-to-expand drill-in rows (college: per-priority
// math + county context; district: member colleges).
(function () {
  "use strict";

  var CSS_ID = "cpl-funding-css";
  var CSS = [
    ".cplfund { color: var(--text-body); }",
    ".cplfund-src { font-size: .8rem; color: var(--text-faint); margin: -6px 0 14px; }",
    ".cplfund-src a { color: var(--accent-link); }",
    ".cplfund h3 { color: var(--navy-primary); margin: 22px 0 10px; font-size: 1.15rem; }",
    ".cplfund-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 12px; }",
    ".cplfund-card { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 14px 16px; }",
    ".cplfund-card .v { font-size: 1.35rem; font-weight: 700; color: var(--navy-primary); }",
    ".cplfund-card .v.neg { color: var(--red-alert); }",
    ".cplfund-card .l { font-size: .8rem; color: var(--text-muted); margin-top: 2px; line-height: 1.35; }",
    ".cplfund-card.hero { background: var(--navy-primary); border-color: var(--navy-primary); }",
    ".cplfund-card.hero .v { color: var(--gold-accent); }",
    ".cplfund-card.hero .l { color: var(--light-blue); }",
    ".cplfund-prio { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 12px; }",
    ".cplfund-prio .p { background: var(--surface-subtle); border: 1px solid var(--border); border-left: 4px solid var(--gold-accent); border-radius: 8px; padding: 14px 16px; }",
    ".cplfund-prio .p h4 { margin: 0 0 6px; color: var(--navy-primary); font-size: 1rem; }",
    ".cplfund-prio .p .share { float: right; font-weight: 700; color: var(--green-progress); }",
    ".cplfund-prio .p .desc { font-size: .9rem; margin: 0 0 8px; }",
    ".cplfund-prio .p .metric { font-size: .78rem; color: var(--text-muted); border-top: 1px dashed var(--border-strong); padding-top: 6px; }",
    ".cplfund-prio .p .nums { font-size: .85rem; color: var(--text-body); margin: 0 0 6px; }",
    ".cplfund-formula { background: var(--surface-muted); border: 1px solid var(--border); border-radius: 8px; padding: 12px 16px; font-size: .9rem; line-height: 1.55; }",
    ".cplfund-formula code { background: var(--surface); border: 1px solid var(--border); border-radius: 4px; padding: 1px 6px; white-space: nowrap; }",
    ".cplfund-toolbar { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin: 0 0 10px; }",
    ".cplfund-toolbar input { padding: 8px 12px; border: 1px solid var(--border-strong); border-radius: 6px; font-size: .9rem; min-width: 220px; }",
    ".cplfund-toolbar input:focus { outline: none; border-color: var(--navy-secondary); }",
    ".cplfund-seg { display: inline-flex; border: 1px solid var(--border-strong); border-radius: 6px; overflow: hidden; }",
    ".cplfund-seg button { background: var(--surface); color: var(--text-body); border: none; padding: 8px 12px; font-size: .85rem; cursor: pointer; }",
    ".cplfund-seg button + button { border-left: 1px solid var(--border-strong); }",
    ".cplfund-seg button.on { background: var(--navy-primary); color: var(--white); font-weight: 600; }",
    ".cplfund-count { font-size: .85rem; color: var(--text-muted); }",
    ".cplfund-tablewrap { overflow-x: auto; border: 1px solid var(--border); border-radius: 8px; background: var(--surface); }",
    "table.cplfund-table { border-collapse: collapse; width: 100%; font-size: .87rem; }",
    ".cplfund-table th { background: var(--navy-primary); color: var(--white); padding: 8px 10px; text-align: right; white-space: nowrap; cursor: pointer; user-select: none; position: sticky; top: 0; }",
    ".cplfund-table th.t, .cplfund-table td.t { text-align: left; }",
    ".cplfund-table th .arr { font-size: .7rem; opacity: .85; }",
    ".cplfund-table td { padding: 7px 10px; border-top: 1px solid var(--border); text-align: right; white-space: nowrap; }",
    ".cplfund-table tbody tr.cplfund-row { cursor: pointer; }",
    ".cplfund-table tbody tr:nth-child(even) { background: var(--surface-subtle); }",
    ".cplfund-table tbody tr:hover { background: var(--surface-muted); }",
    ".cplfund-table td.tot, .cplfund-table tfoot td { font-weight: 700; color: var(--navy-primary); }",
    ".cplfund-table tfoot td { border-top: 2px solid var(--navy-primary); background: var(--surface-muted); }",
    ".cplfund-table td .sub { display: block; font-weight: 400; font-size: .75rem; color: var(--text-faint); }",
    ".cplfund-caret { display: inline-block; width: 1em; color: var(--text-faint); transition: transform .12s; }",
    "tr.cplfund-open .cplfund-caret { transform: rotate(90deg); }",
    "tr.cplfund-detail td { background: var(--surface-subtle); border-top: none; text-align: left; white-space: normal; padding: 10px 16px 12px 30px; cursor: default; }",
    ".cplfund-detail-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 6px 22px; font-size: .83rem; }",
    ".cplfund-detail-grid .dk { color: var(--text-muted); }",
    ".cplfund-foot { font-size: .78rem; color: var(--text-faint); margin: 10px 2px; }",
    ".cplfund-foot div { margin: 2px 0; overflow-wrap: anywhere; }",
    ".cplfund-empty { border: 1px dashed var(--border-strong); border-radius: 8px; background: var(--surface-subtle); color: var(--text-muted); padding: 28px; text-align: center; }",
    "@media (max-width: 700px) { .cplfund-toolbar input { min-width: 140px; flex: 1; } }"
  ].join("\n");

  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var s = document.createElement("style");
    s.id = CSS_ID;
    s.textContent = CSS;
    document.head.appendChild(s);
  }

  // ── formatting helpers ────────────────────────────────────────────────
  function esc(v) {
    return String(v == null ? "" : v).replace(/[&<>"']/g, function (ch) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[ch];
    });
  }
  function fmtInt(v) {
    if (v == null) return "—";
    return Math.round(v).toLocaleString("en-US");
  }
  function fmtMoney(v) {
    if (v == null) return "—";
    return "$" + Math.round(v).toLocaleString("en-US");
  }
  function fmtRate(v) {
    if (v == null) return "—";
    return "$" + v.toFixed(2);
  }
  function fmtPct(v, dp) {
    if (v == null) return "—";
    return (v * 100).toFixed(dp == null ? 1 : dp) + "%";
  }

  // ── render pieces ─────────────────────────────────────────────────────
  function poolCardsHtml(d) {
    var p = d.pool;
    var cards = [
      { v: fmtMoney(p.remaining_2025_26), l: "2025-26 CPL remaining one-time funding" },
      { v: fmtMoney(p.one_time_2026_27), l: "2026-27 CPL one-time funding" },
      { v: "−" + fmtMoney(p.admin_cost), l: esc(p.admin_cost_label.toLowerCase().replace(/^admin cost/, "Admin cost")), neg: true },
      { v: "−" + fmtMoney(p.scaling_projects_tech), l: "Scaling projects &amp; tech", neg: true },
      { v: fmtMoney(p.total_college_funding), l: "Available college funding 2026-30 &mdash; " + p.years.length + " annual tranches of " + fmtMoney(p.available_per_year) + " (" + esc(p.years[0]) + " &rarr; " + esc(p.years[p.years.length - 1]) + ")", hero: true },
      { v: fmtRate(p.per_student), l: "Per-student rate &mdash; " + fmtMoney(p.available_per_year) + " &divide; " + fmtInt(p.ccc_headcount) + " CCC headcount" }
    ];
    return '<div class="cplfund-cards">' + cards.map(function (c) {
      return '<div class="cplfund-card' + (c.hero ? " hero" : "") + '">' +
        '<div class="v' + (c.neg ? " neg" : "") + '">' + c.v + "</div>" +
        '<div class="l">' + c.l + "</div></div>";
    }).join("") + "</div>";
  }

  function prioritiesHtml(d) {
    return '<div class="cplfund-prio">' + d.priorities.map(function (p) {
      var sys = d.system ? d.system[p.key] : null;
      var sysHeads = d.system ? d.system[p.key + "_heads"] : null;
      return '<div class="p">' +
        "<h4>" + esc(p.label) + '<span class="share">' + fmtPct(p.share, 0) + " of each tranche</span></h4>" +
        '<p class="desc">' + esc(p.description) + "</p>" +
        '<p class="nums">Funding factor <strong>' + esc(p.factor) + "</strong> &times; projected " +
        "<strong>" + fmtPct(p.rate, p.rate * 100 % 1 ? 2 : 0) + "</strong> of headcount" +
        (sys != null ? " &mdash; statewide " + fmtMoney(sys) + " / " + fmtInt(sysHeads) + " students" : "") + "</p>" +
        '<div class="metric">METRIC: ' + esc(p.metric) + "</div></div>";
    }).join("") + "</div>";
  }

  function formulaHtml(d) {
    var p = d.pool;
    return '<div class="cplfund-formula">' +
      "Each college&#39;s potential allocation of one annual tranche is " +
      "<code>headcount &times; projection rate &times; funding factor &times; " + fmtRate(p.per_student) + "</code> " +
      "per priority. The three priority shares (30% + 42% + 28%) sum to 100%, so a college&#39;s " +
      "<strong>total potential allocation equals its share of statewide headcount</strong> applied to the " +
      fmtMoney(p.available_per_year) + " annual pool &mdash; the same again in each of the " +
      p.years.length + " years through " + esc(p.years[p.years.length - 1]) + ".</div>";
  }

  // ── table state + data shaping ────────────────────────────────────────
  var COLS_COLLEGE = [
    { key: "order", label: "#", cls: "" },
    { key: "college", label: "College", cls: "t" },
    { key: "district", label: "District", cls: "t" },
    { key: "county", label: "County", cls: "t" },
    { key: "headcount", label: "Headcount", cls: "" },
    { key: "p1", label: "Priority 1", cls: "" },
    { key: "p2", label: "Priority 2", cls: "" },
    { key: "p3", label: "Priority 3", cls: "" },
    { key: "total", label: "TOTAL_LABEL", cls: "" },
    { key: "working_adults", label: "Working adults*", cls: "" }
  ];
  var COLS_DISTRICT = [
    { key: "district", label: "District", cls: "t" },
    { key: "n", label: "Colleges", cls: "" },
    { key: "counties", label: "Counties", cls: "t" },
    { key: "headcount", label: "Headcount", cls: "" },
    { key: "p1", label: "Priority 1", cls: "" },
    { key: "p2", label: "Priority 2", cls: "" },
    { key: "p3", label: "Priority 3", cls: "" },
    { key: "total", label: "TOTAL_LABEL", cls: "" }
  ];

  var state = {
    q: "", view: "college", period: 1,        // period: 1 = per year, 3 = 2026-30 total (years.length)
    sortKey: "order", sortDir: 1,
    open: {}                                   // row id → true (drill-ins; cleared on re-render)
  };

  var _districtsCache = null;
  function districts(d) {
    if (_districtsCache) return _districtsCache;
    var by = {};
    d.colleges.forEach(function (c) {
      var k = c.district || "(no district)";
      var g = by[k] || (by[k] = { district: k, n: 0, counties: [], headcount: 0, p1: 0, p2: 0, p3: 0, total: 0, members: [] });
      g.n += 1;
      g.headcount += c.headcount || 0;
      g.p1 += c.p1; g.p2 += c.p2; g.p3 += c.p3; g.total += c.total;
      if (c.county && g.counties.indexOf(c.county) === -1) g.counties.push(c.county);
      g.members.push(c);
    });
    _districtsCache = Object.keys(by).map(function (k) {
      var g = by[k];
      g.counties = g.counties.sort().join(", ");
      g.members.sort(function (a, b) { return b.total - a.total; });
      return g;
    });
    return _districtsCache;
  }

  function activeCols() { return state.view === "district" ? COLS_DISTRICT : COLS_COLLEGE; }
  function periodMult(d) { return state.period === 1 ? 1 : d.pool.years.length; }
  function totalLabel() { return state.period === 1 ? "Total / yr" : "Total 2026-30"; }

  function rowsFiltered(d) {
    var q = state.q.trim().toLowerCase();
    var rows = state.view === "district" ? districts(d) : d.colleges;
    if (q) {
      rows = rows.filter(function (r) {
        var hay = state.view === "district"
          ? [r.district, r.counties].join(" ")
          : [r.college, r.district, r.county].join(" ");
        return hay.toLowerCase().indexOf(q) !== -1;
      });
    }
    rows = rows.slice().sort(function (a, b) {
      var ka = a[state.sortKey], kb = b[state.sortKey];
      if (ka == null && kb == null) return 0;
      if (ka == null) return 1;             // nulls last either direction
      if (kb == null) return -1;
      if (typeof ka === "string") return state.sortDir * ka.localeCompare(kb);
      return state.sortDir * (ka - kb);
    });
    return rows;
  }

  function rowId(r) { return state.view === "district" ? "d:" + r.district : "c:" + r.order; }

  // ── row + drill-in rendering ──────────────────────────────────────────
  function collegeRowHtml(c, m) {
    function pCell(k) {
      return '<td title="projected ' + fmtInt(c[k + "_heads"]) + ' students/yr">' + fmtMoney(c[k] * m) + "</td>";
    }
    var id = "c:" + c.order;
    return '<tr class="cplfund-row' + (state.open[id] ? " cplfund-open" : "") + '" data-id="' + esc(id) + '">' +
      "<td>" + esc(c.order) + "</td>" +
      '<td class="t"><span class="cplfund-caret">▸</span><strong>' + esc(c.college) + "</strong></td>" +
      '<td class="t">' + esc(c.district || "—") + "</td>" +
      '<td class="t">' + esc(c.county || "—") + "</td>" +
      '<td title="' + fmtPct(c.headcount_pct, 2) + ' of statewide headcount">' + fmtInt(c.headcount) + "</td>" +
      pCell("p1") + pCell("p2") + pCell("p3") +
      '<td class="tot">' + fmtMoney(c.total * m) + "</td>" +
      "<td>" + (c.working_adults == null ? "—" : fmtInt(c.working_adults) +
        '<span class="sub">' + fmtPct(c.county_pop_pct, 1) + " of county</span>") + "</td>" +
      "</tr>" + (state.open[id] ? collegeDetailHtml(c, m) : "");
  }

  function collegeDetailHtml(c, m) {
    var d = window.CPL_FUNDING;
    var per = d.pool.per_student;
    var prio = d.priorities.map(function (p) {
      return '<div><span class="dk">' + esc(p.label) + ":</span> " +
        fmtInt(c[p.key + "_heads"]) + " projected (" + fmtPct(p.rate, 2) + " of headcount) &times; factor " +
        esc(p.factor) + " &times; " + fmtRate(per) + " = <strong>" + fmtMoney(c[p.key] * m) + "</strong>" +
        (m > 1 ? " over " + d.pool.years.length + " yrs" : "/yr") + "</div>";
    }).join("");
    var county = c.working_adults == null
      ? '<div><span class="dk">County context:</span> not estimated (county &lt; 65K population)</div>'
      : '<div><span class="dk">County context (' + esc(c.county) + "):</span> " + fmtInt(c.working_adults) +
        " working adults with some college, no degree (" + fmtPct(c.county_pop_pct, 1) + " of county population)</div>";
    return '<tr class="cplfund-detail"><td colspan="' + COLS_COLLEGE.length + '">' +
      '<div class="cplfund-detail-grid">' +
      '<div><span class="dk">Headcount share:</span> ' + fmtInt(c.headcount) + " students = " +
      fmtPct(c.headcount_pct, 3) + " of the statewide " + fmtInt(d.pool.ccc_headcount) + "</div>" +
      prio + county +
      '<div><span class="dk">District:</span> ' + esc(c.district || "—") + "</div>" +
      "</div></td></tr>";
  }

  function districtRowHtml(g, m, i) {
    var id = "d:" + g.district;
    return '<tr class="cplfund-row' + (state.open[id] ? " cplfund-open" : "") + '" data-id="' + esc(id) + '">' +
      '<td class="t"><span class="cplfund-caret">▸</span><strong>' + esc(g.district) + "</strong></td>" +
      "<td>" + g.n + "</td>" +
      '<td class="t">' + esc(g.counties) + "</td>" +
      "<td>" + fmtInt(g.headcount) + "</td>" +
      "<td>" + fmtMoney(g.p1 * m) + "</td><td>" + fmtMoney(g.p2 * m) + "</td><td>" + fmtMoney(g.p3 * m) + "</td>" +
      '<td class="tot">' + fmtMoney(g.total * m) + "</td>" +
      "</tr>" + (state.open[id] ? districtDetailHtml(g, m) : "");
  }

  function districtDetailHtml(g, m) {
    var rows = g.members.map(function (c) {
      return '<div><span class="dk">' + esc(c.college) + ":</span> " + fmtInt(c.headcount) +
        " students &middot; <strong>" + fmtMoney(c.total * m) + "</strong></div>";
    }).join("");
    return '<tr class="cplfund-detail"><td colspan="' + COLS_DISTRICT.length + '">' +
      '<div class="cplfund-detail-grid">' + rows + "</div></td></tr>";
  }

  function tableHtml(d) {
    var m = periodMult(d);
    var rows = rowsFiltered(d);
    var cols = activeCols();
    var sys = d.system;
    var head = cols.map(function (col) {
      var label = col.label === "TOTAL_LABEL" ? totalLabel() : col.label;
      var arr = state.sortKey === col.key ? ' <span class="arr">' + (state.sortDir === 1 ? "▲" : "▼") + "</span>" : "";
      var title = (col.key === "headcount" && d.headcount_label) ? ' title="' + esc(d.headcount_label) + '"' : "";
      return '<th class="' + col.cls + '" data-sort="' + col.key + '"' + title + ">" + label + arr + "</th>";
    }).join("");
    var body;
    if (!rows.length) {
      body = '<tr><td colspan="' + cols.length + '" class="t">No ' +
        (state.view === "district" ? "districts" : "colleges") + " match the search.</td></tr>";
    } else if (state.view === "district") {
      body = rows.map(function (g, i) { return districtRowHtml(g, m, i); }).join("");
    } else {
      body = rows.map(function (c) { return collegeRowHtml(c, m); }).join("");
    }
    var foot;
    if (state.view === "district") {
      foot = "<tr>" +
        '<td class="t">SYSTEM (statewide)</td>' +
        "<td>" + districts(d).reduce(function (s, g) { return s + g.n; }, 0) + "</td>" +
        '<td class="t"></td>' +
        "<td>" + fmtInt(sys.headcount) + "</td>" +
        "<td>" + fmtMoney(sys.p1 * m) + "</td><td>" + fmtMoney(sys.p2 * m) + "</td><td>" + fmtMoney(sys.p3 * m) + "</td>" +
        "<td>" + fmtMoney(sys.total * m) + "</td></tr>";
    } else {
      foot = "<tr>" +
        '<td></td><td class="t">SYSTEM (statewide)</td><td class="t">' + esc(sys.district || "") + '</td><td class="t">' + esc(sys.county || "") + "</td>" +
        "<td>" + fmtInt(sys.headcount) + "</td>" +
        "<td>" + fmtMoney(sys.p1 * m) + "</td><td>" + fmtMoney(sys.p2 * m) + "</td><td>" + fmtMoney(sys.p3 * m) + "</td>" +
        "<td>" + fmtMoney(sys.total * m) + "</td>" +
        "<td>" + (sys.working_adults == null ? "—" : fmtInt(sys.working_adults)) + "</td></tr>";
    }
    return '<div class="cplfund-tablewrap"><table class="cplfund-table">' +
      "<thead><tr>" + head + "</tr></thead>" +
      "<tbody>" + body + "</tbody>" +
      "<tfoot>" + foot + "</tfoot>" +
      "</table></div>";
  }

  // Headcount provenance footnote — vintage comes from the workbook's own
  // column header (carried as headcount_label), source identified by Sam
  // (2026-06-11): CCCCO MIS DataMart, Annual/Term Student Count, Collegewide.
  function headcountSourceHtml(d) {
    if (!d.headcount_label && !d.headcount_source) return "";
    var src = d.headcount_source || {};
    var inner = esc(src.name || "source") + (src.selection ? " (" + esc(src.selection) + ")" : "");
    var linked = src.url
      ? '<a href="' + esc(src.url) + '" target="_blank" rel="noopener">' + inner + "</a>"
      : inner;
    return "<div>College headcounts: " + esc(d.headcount_label || "per the workbook") +
      " &mdash; " + linked + ".</div>";
  }

  // Data-driven honesty note: the 2026-06-11 workbook's college rows sum to
  // 8,417 more heads (+$44.6K/yr) than its own SYSTEM/pool row — the pool's
  // SUM range appears to stop one row short of the list. Rendered only while
  // the source actually disagrees with itself, so it disappears the day a
  // corrected workbook edition is committed.
  function varianceNoteHtml(d) {
    var heads = 0, total = 0;
    d.colleges.forEach(function (c) { heads += c.headcount || 0; total += c.total; });
    if (heads === d.system.headcount && Math.abs(total - d.system.total) <= 1) return "";
    return "<div>Note: the " + d.colleges.length + " college rows sum to " + fmtInt(heads) +
      " students / " + fmtMoney(total) + "/yr, while the workbook&#39;s SYSTEM row carries " +
      fmtInt(d.system.headcount) + " / " + fmtMoney(d.system.total) +
      " &mdash; a source-workbook variance (flagged for the next model edition).</div>";
  }

  function segHtml(id, items, current) {
    return '<span class="cplfund-seg" id="' + id + '">' + items.map(function (it) {
      return '<button type="button" data-val="' + esc(it.val) + '"' +
        (String(current) === String(it.val) ? ' class="on"' : "") + ">" + esc(it.label) + "</button>";
    }).join("") + "</span>";
  }

  function render() {
    var mount = document.getElementById("cplFundingMount");
    if (!mount) return;
    var d = window.CPL_FUNDING;
    if (!d || !d.colleges || !d.system) {
      mount.innerHTML = '<div class="cplfund-empty">Funding model data is unavailable right now (cpl_funding_data.js failed to load). Try a hard refresh.</div>';
      return;
    }
    ensureCss();
    mount.innerHTML = '<div class="cplfund">' +
      '<div class="cplfund-src">Model version ' + esc(d.model_version) + " &middot; extracted from the " +
      '<a href="' + esc(d.source) + '">funding model workbook</a> (sheet &ldquo;' + esc(d.sheet) + "&rdquo;)</div>" +
      "<h3>Funding pools</h3>" + poolCardsHtml(d) +
      "<h3>The three funding priorities</h3>" + prioritiesHtml(d) +
      "<h3>How an allocation is computed</h3>" + formulaHtml(d) +
      "<h3>Potential allocation by college</h3>" +
      '<div class="cplfund-toolbar">' +
      segHtml("cplFundView", [{ val: "college", label: "Colleges" }, { val: "district", label: "Districts" }], state.view) +
      segHtml("cplFundPeriod", [{ val: 1, label: "Per year" }, { val: 3, label: "2026-30 total" }], state.period) +
      '<input type="search" id="cplFundSearch" placeholder="Search college / district / county&hellip;" aria-label="Search colleges">' +
      '<span class="cplfund-count" id="cplFundCount"></span></div>' +
      '<div id="cplFundTable">' + tableHtml(d) + "</div>" +
      '<div class="cplfund-foot">' +
      "<div>Dollar cells round to whole dollars; click a row to expand its detail. Priority-cell hovers and projected " +
      "student counts are per year, whichever period is shown. " +
      "&ldquo;Working adults&rdquo; = 2022 estimated working adults with some college, no degree, in the college&#39;s county.</div>" +
      headcountSourceHtml(d) +
      varianceNoteHtml(d) +
      d.footnotes.map(function (f) { return "<div>" + esc(f) + "</div>"; }).join("") +
      "</div></div>";
    updateCount(d);
    wire(d);
  }

  function updateCount(d) {
    var el = document.getElementById("cplFundCount");
    if (!el) return;
    var n = rowsFiltered(d).length;
    var m = periodMult(d);
    var unit = state.view === "district" ? "districts" : "colleges";
    var denom = state.view === "district" ? districts(d).length : d.colleges.length;
    el.textContent = n + " of " + denom + " " + unit +
      (d.average_allocation != null && state.view === "college"
        ? " · average allocation " + fmtMoney(d.average_allocation * m) + (m === 1 ? "/yr" : " over 2026-30")
        : "");
  }

  function refreshTable(d) {
    var holder = document.getElementById("cplFundTable");
    if (holder) holder.innerHTML = tableHtml(d);
    updateCount(d);
    wireTable(d);
  }

  function wireTable(d) {
    var holder = document.getElementById("cplFundTable");
    if (!holder) return;
    holder.querySelectorAll("th[data-sort]").forEach(function (th) {
      th.addEventListener("click", function () {
        var k = th.getAttribute("data-sort");
        if (state.sortKey === k) state.sortDir = -state.sortDir;
        else {
          state.sortKey = k;
          state.sortDir = (k === "college" || k === "district" || k === "county" || k === "counties" || k === "order") ? 1 : -1;
        }
        refreshTable(d);
      });
    });
    holder.querySelectorAll("tr.cplfund-row").forEach(function (tr) {
      tr.addEventListener("click", function () {
        var id = tr.getAttribute("data-id");
        if (state.open[id]) delete state.open[id];
        else state.open[id] = true;
        refreshTable(d);
      });
    });
  }

  function wire(d) {
    var input = document.getElementById("cplFundSearch");
    if (input) {
      input.addEventListener("input", function () {
        state.q = input.value || "";
        refreshTable(d);
      });
    }
    function wireSeg(id, apply) {
      var seg = document.getElementById(id);
      if (!seg) return;
      seg.querySelectorAll("button").forEach(function (b) {
        b.addEventListener("click", function () {
          apply(b.getAttribute("data-val"));
          seg.querySelectorAll("button").forEach(function (x) { x.classList.toggle("on", x === b); });
          refreshTable(d);
        });
      });
    }
    wireSeg("cplFundView", function (v) {
      if (v === state.view) return;
      state.view = v;
      state.open = {};
      // Keep the sort meaningful across views: college-only/district-only keys reset.
      var valid = activeCols().some(function (c) { return c.key === state.sortKey; });
      if (!valid) { state.sortKey = v === "district" ? "district" : "order"; state.sortDir = 1; }
    });
    wireSeg("cplFundPeriod", function (v) { state.period = Number(v) || 1; });
    wireTable(d);
  }

  // ── boot ──────────────────────────────────────────────────────────────
  var booted = false;
  function boot() {
    if (booted) { render(); return; }
    booted = true;
    if (window.CPL_FUNDING) { render(); return; }
    if (window.CPL_TABS && typeof window.CPL_TABS.loadScript === "function") {
      window.CPL_TABS.loadScript("cpl_funding_data.js", "CPL_FUNDING", render);
    } else {
      // No tabs helper (e.g. embedded standalone) — plain one-shot injection.
      var s = document.createElement("script");
      s.src = "cpl_funding_data.js";
      s.onload = render;
      s.onerror = render; // render() shows the graceful empty state
      document.head.appendChild(s);
    }
  }

  window.CPL_FUNDING_TAB = { boot: boot, render: render, _state: state };
})();
