// CPL Pathways — pathway definitions (curated, static).
//
// Consumed by cpl_pathways.js (the 🎓 CPL Pathways tab). Each program lists the
// degree's required coursework by section; the renderer DERIVES the CPL ✓ marks
// from the live CER dataset (credential_reference_data.js) at render time, so
// this file only needs to be right about the REQUIREMENTS — the articulation
// state stays live (a course added to the MAP platform tomorrow lights up ✓
// here with no edit). `cpl:` stamps and `clep_fallback:` lists are fallbacks
// used only when the live CER payload fails to load. Sections flagged
// `no_count: true` render + live-resolve but stay out of the unit buckets
// (alternate-track lists would otherwise double-count the major).
//
// First pathway: Cerritos College — Field Ironworker Supervisor BS (first
// cohort spring 2027, per Cerritos's Field Ironwork page, read 2026-10-04), built for the California Apprenticeship Council
// presentation (2026-08-13). Sourcing (researched 2026-07-10):
//  · regionalcte.org/browse/ZyxAg — the LAOCRC program record (TOP 095700;
//    two-part structure; GE gate). Its course table renders only in a browser:
//    the college page read (kb/_college_page_read.py, run 37232742985,
//    2026-10-04) read it, and the upper-major rows below are that proposed
//    list. Replace them when Cerritos publishes the approved curriculum.
//  · CCCCO COCI course inventory (kb/reference/coci_course_list.xlsx,
//    2026-07-09 snapshot) — all 24 Cerritos IWAP apprenticeship courses.
//  · Cerritos catalog (courseleaf): Apprenticeship: Field Ironworkers A.S. —
//    60 units, 27–29 major units, Reinforcing or Structural core.
//  · EdSource 2026-02: CSU withdrew its duplication objection; CCCCO final
//    approval under the AB 927 statewide baccalaureate process.
//  · ESLEI 24-35 (title 5 §55052.5): systemwide CLEP GE-credit chart.
// This file is hand-curated (NOT regenerated by excel_to_dashboard.py).
window.CPL_PATHWAYS = {
  _as_of: "2026-07-10",
  programs: [
    // The proof of concept (Sam, 2026-10-04 18:23Z): one pathway shown whole, high
    // school to career, and "leverage CPL on clear paths to increase access and
    // completion leading to career improvement." Ported from mock-up 1
    // (docs/visuals/2026-10-04-ironworker-ladder.html) at his word: "port it to CPL
    // Pathways. Add a simple graphical map summarizing the steps leading to career
    // at the beginning. Allow a click through to the sections of the steps."
    // kind "ladder" renders a step map, then one section per step (cpl_pathways.js
    // renderLadder). Steps marked `derive` read the display build
    // (cpl_pathways_roep_data.js, record `roep_key`), the same facts Sierra reads;
    // every point carries `s`: "data" (read from the catalog, COCI, MAP or the
    // Centers of Excellence) or "confirm" (a public web page the harvest has not read).
    {
      id: "cerritos-ironworker-ladder",
      kind: "ladder",
      college: "Cerritos College",
      program: "Field Ironworkers, high school to career",
      title: "From high school to the job site",
      roep_key: "cerritos_42158",
      blurb: "One Field Ironworkers pathway at Cerritos College, step by step: where a learner can start, what each award requires, the credit for prior learning (CPL) Cerritos has already articulated, and the jobs at the end. A label on each line says whether it comes from our data or still needs confirming.",
      steps: [
        { id: "start", stage: "Start", map: "High school, adult school, ROP",
          title: "High school, adult school and ROP",
          what: "The earliest doors into the trade, before a learner enrolls at Cerritos.",
          points: [
            { t: "Columbus High School's welding pathway (Downey Unified) maps to Cerritos's WELD 160 Welding and Metal Fabrication Safety (formerly WELD 60, 1 unit) and WELD 100 Welding Fundamentals (2.5 units), per the district's June 2023 board presentation.", s: "data" },
            { t: "Whether that credit comes by articulation or by dual enrollment, and which other high school courses Cerritos has articulated: Cerritos publishes its agreements through Statewide Career Pathways.", s: "confirm" },
            { t: "Norwalk-La Mirada Adult School and Southeast ROP teach welding.", s: "confirm" },
            { t: "MAP holds no high school, adult school or ROP credit for prior learning at Cerritos.", s: "data" },
          ],
          cpl_map: "No CPL yet",
          cpl: "None articulated yet. The high school list comes from Cerritos's Educational Partnerships office." },
        { id: "noncredit", stage: "Noncredit", map: "Pre-Apprenticeship",
          title: "Pre-Apprenticeship and noncredit ironworker courses",
          what: "Tuition-free noncredit courses at Cerritos that prepare a learner for the apprenticeship.",
          points: [
            { t: "Pre-Apprenticeship certificate (control number 24102): AED 36.02, 36.03 and 36.04 (36 hours each) and AED 80.01 Intro to Electrical Trades (80 hours), 188 hours in all.", s: "data" },
            { t: "The certificate admits registered apprentices only: the 2026–27 catalog requires acceptance by an apprenticeship program and registration with the State.", s: "data" },
            { t: "AED 36.05 Basic Welding, and OSHA 10 in AED 90.05.", s: "data" },
            { t: "Twenty-six noncredit courses, AED 40.01 through 41.10, mirror the credit IWAP courses one for one; all 26 are in the 2026–27 catalog.", s: "data" },
            { t: "Whether those 26 courses have sections this term.", s: "confirm" },
          ],
          cpl_map: "No CPL yet",
          cpl: "None yet. A noncredit-to-credit articulation would let each AED course count toward its IWAP twin; Santa Ana College's noncredit exhibit in MAP is the model." },
        { id: "apprenticeship", stage: "Apprenticeship", map: "Locals 433 and 416",
          title: "Ironworkers Locals 433 and 416",
          what: "Paid on-the-job training with classroom instruction. This training is what Cerritos credits through CPL.",
          points: [
            { t: "The apprenticeship runs four years, joining related technical instruction to on-the-job training (Cerritos's Field Ironwork page).", s: "data" },
            { t: "Classroom hours at Cerritos: the Reinforcing track's 16 courses carry 878 contact hours (622 lecture, 256 laboratory) and the Structural track's 898 (677 and 221), per the 2026–27 course descriptions.", s: "data" },
            { t: "Local 433's joint apprenticeship committee trains at La Palma, and Local 416 in Norwalk.", s: "confirm" },
          ],
          cpl_map: "Credit by exam",
          cpl: "The apprenticeship's coursework earns credit by exam toward the certificates and the A.S." },
        { id: "certificates", stage: "Certificates", map: "Reinforcing, Structural", derive: "certificates",
          title: "Reinforcing and Structural certificates",
          what: "Each certificate is one complete A.S. major option: the core plus its option's courses.",
          certificates: [
            { name: "Reinforcing", control: "36002", blocks: [0, 1] },
            { name: "Structural", control: "36003", blocks: [0, 2] },
          ],
          cpl: "The certificate figures follow from the A.S. record, since COCI lists the same courses." },
        { id: "associate", stage: "Associate degree", map: "A.S., Field Ironworkers", derive: "associate",
          title: "A.S., Apprenticeship: Field Ironworkers",
          what: "Control number 42158. The major is the core plus one option." },
        { id: "bachelor", stage: "Bachelor's degree", map: "B.S., Field Ironworker Supervisor",
          title: "B.S., Field Ironworker Supervisor",
          what: "A bachelor's degree for journeyworkers moving into supervision.",
          points: [
            { t: "Cerritos lists it as approved, its second bachelor's degree beside Dental Hygiene (State of the College, May 2026).", s: "data" },
            { t: "Admission follows two years of prerequisite courses and a completed general education pattern: Cerritos GE, IGETC or CSU GE Breadth.", s: "data" },
            { t: "The proposed upper division: 23 courses and 60 units over years 3 and 4, IWAP 301–310 and 401–410 with intercultural communication and two statistics courses (regional program record, recommended June 2024).", s: "data" },
            { t: "Graduates of the apprenticeship can begin the B.S. in Spring 2027 (Cerritos's Field Ironwork page).", s: "data" },
            { t: "Whether the approved degree keeps the 2024 course list and runs online; the 2026–27 catalog does not list it yet.", s: "confirm" },
          ],
          cpl_map: "A.S. credit carries",
          cpl: "The A.S. credit carries into the lower division; exams such as CLEP can meet general education through the systemwide credit chart.",
          open: { id: "cerritos-field-ironworker-bs", label: "Open the B.S. course map" } },
        { id: "career", stage: "Career", map: "Ironworker to supervisor",
          title: "The jobs at the end of the ladder",
          what: "Centers of Excellence projections for 2024–2029, Los Angeles and Orange County regions.",
          points: [
            { t: "Structural iron and steel workers: median $35 an hour in Los Angeles and $37 in Orange County; about 130 and 80 openings a year.", s: "data" },
            { t: "First-line supervisors of construction trades: median $43 an hour in Los Angeles and $48 in Orange County; 1,130 and 680 openings a year.", s: "data" },
            { t: "Internships and employers recruiting from the program.", s: "confirm" },
          ],
          cpl_map: "1,810 supervisor openings a year" },
      ],
      confirm: [
        "Whether the approved B.S. keeps the 2024 course list.",
        "Cerritos's high school articulation agreements, published through Statewide Career Pathways, and how Columbus High's welding pathway earns its credit.",
        "Whether the 26 noncredit AED courses have sections this term (Schedule+ lists the term's sections).",
      ],
      confirm_note: "The harvest agent reads these pages first, from a runner. A request goes to Cerritos only after Cerritos's procedure record shows every step tried.",
      sources: [
        { label: "Cerritos College catalog 2026–27, Apprenticeship: Field Ironworkers A.S.", url: "https://cerritos-public.courseleaf.com/degrees-certificates-courses/degrees-certificates-programs-majors/field-ironworkers-aa/" },
        { label: "Cerritos College catalog 2026–27, Pre-Apprenticeship (Non Credit)", url: "https://cerritos-public.courseleaf.com/degrees-certificates-courses/noncredit-career-development-college-preparation/pre-apprenticeship-certificate-completion/" },
        { label: "Field Ironworker Supervisor, Los Angeles regional program record (recommended June 2024)", url: "https://regionalcte.org/browse/ZyxAg" },
        { label: "Cerritos College, Field Ironwork apprenticeship", url: "https://www.cerritos.edu/academics/aed/apprenticeship-programs/Field_Ironwork.htm" },
        { label: "Cerritos College catalog 2026–27, IWAP course descriptions", url: "https://cerritos-public.courseleaf.com/degrees-certificates-courses/course-descriptions/iwap/" },
        { label: "Cerritos College catalog 2026–27, WELD and AED course descriptions", url: "https://cerritos-public.courseleaf.com/degrees-certificates-courses/course-descriptions/weld/" },
        { label: "Downey Unified, CTE pathways board presentation (June 27, 2023)", url: "https://web.dusd.net/wp-content/uploads/2023/06/CTE_6-27-23_BoE.pdf" },
        { label: "Cerritos College, 2026 State of the College (May 19, 2026)", url: "https://www.cerritos.edu/newsroom/releases/2026/05/SOTC.htm" },
        { label: "Chancellor's Office COCI program and course files (load of 16 July 2026)" },
        { label: "MAP articulated-exhibit records (read 4 October 2026)" },
        { label: "Centers of Excellence occupational demand 2024–2029" },
      ],
    },
    {
      id: "cerritos-field-ironworker-bs",
      college: "Cerritos College",
      program: "Field Ironworker Supervisor",
      degree: "Bachelor of Science",
      // Publication stage — drives the big status banner + hero chip. One of
      // "discussion-draft" | "active" | "tabled". The on-page selector is a
      // per-browser view override; THIS is the published default.
      stage: "discussion-draft",
      start: "Spring 2027",
      status: "Approved Feb 2026 — AB 927 CCC baccalaureate",
      audience: "Ironworker journeyworkers — any JATC, anywhere",
      blurb: "The nation's first bachelor's degree built on a field-ironworker "
        + "apprenticeship — developed with the California Field Ironworkers (Locals 416 "
        + "and 433). A journeyworker card is college credit at Cerritos: every course "
        + "below with a ✓ is already articulated for Credit for Prior Learning in the "
        + "MAP platform, wherever the ironworker apprenticed. CLEP exams (◆) can clear "
        + "general-education requirements the same way — proof of learning, not seat time.",
      facts: [
        "A journeyworker card = 4,800–6,000 on-the-job hours plus ~4 years of classroom training — the learning CPL recognizes",
        "1,300+ supervisor openings a year in LA County alone",
        "+$34,000/yr average wage premium with the bachelor's",
        "≈$10,560 total tuition for all 120 units",
        "Upper-division coursework online — built for working ironworkers",
      ],
      total_units: 120,
      cpl_tile_label: "CPL on day one — journeyworker apprenticeship credit already articulated in MAP",
      campaign: {
        kicker: "The billboard",
        headline: "Iron workers: your journeyworker training is already worth {cpl_units}+ units at Cerritos College. Finish the bachelor's the way you built your trade.",
        sub: "Regional outreach concept — billboard + social. CPL for the apprenticeship major, CLEP for GE, one application. The trade you mastered is a year of the degree, already done.",
      },
      sections: [
        {
          id: "as-major",
          title: "Ironworker apprenticeship major — articulated in MAP today",
          note: "The Apprenticeship: Field Ironworkers A.S. requires 34–38 major units in the 2026–27 catalog: the core plus the Reinforcing or Structural option. Cerritos has articulated up to 31.5 of the 34 Reinforcing units as Credit by Exam; Welding I (IWAP 40.10) and the Structural option carry none yet.",
          wide: true,
          courses: [
            { code: "IWAP 40.07", title: "FIW — Orientation", units: 4.0,
              cpl: { credential: "FIW Orientation", types: ["Credit By Exam"] } },
            { code: "IWAP 40.09", title: "IW — General Rigging", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — General Rigging", types: ["Credit By Exam"] } },
            { code: "IWAP 40.11", title: "Welding II — Reinforcing", units: 2.5,
              cpl: { credential: "Ironworker Apprenticeship — Welding II", types: ["Credit By Exam"] } },
            { code: "IWAP 40.12", title: "IW — Reinforcing Iron I", units: 2.0,
              cpl: { credential: "Reinforcing 1", types: ["Credit By Exam"] } },
            { code: "IWAP 40.15", title: "IW — Post Tension I", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Post Tensioning I", types: ["Credit By Exam"] } },
            { code: "IWAP 40.22", title: "IW — Cranes", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Cranes", types: ["Credit By Exam"] } },
            { code: "IWAP 40.50", title: "IW — Mixed Base / Reinforcing", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Mixed Base", types: ["Credit By Exam"] } },
            { code: "IWAP 40.53", title: "IW — Detailing / Reinforcing Iron", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Detailing", types: ["Credit By Exam"] } },
            { code: "IWAP 40.55", title: "IWS — Reinforcing Foreman Training", units: 2.0,
              cpl: { credential: "Foreman Training", types: ["Credit By Exam"] } },
            { code: "IWAP 40.56", title: "IW — Trade Science / Ironworker History", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Ironworker History", types: ["Credit By Exam"] } },
            { code: "IWAP 40.63", title: "IW — Structural Lead Hazard", units: 2.0,
              cpl: { credential: "Ironworker Apprenticeship — Lead Hazard", types: ["Credit By Exam"] } },
            { code: "IWAP 41.03", title: "IW — Reinforcing II", units: 1.0,
              cpl: { credential: "Ironworker Apprenticeship — Reinforcing II", types: ["Credit By Exam"] } },
            { code: "IWAP 41.07", title: "IW — Post Tension II", units: 2.5,
              cpl: { credential: "Ironworker Apprenticeship — Post Tensioning II", types: ["Credit By Exam"] } },
            { code: "IWAP 41.08", title: "IW — Post Tension III", units: 2.0,
              cpl: { credential: "Post Tensioning 3", types: ["Credit By Exam"] } },
            { code: "IWAP 41.09", title: "OSHA 30 / Extension Review", units: 1.5,
              cpl: { credential: "Ext & Review", types: ["Credit By Exam"] } },
          ],
        },
        {
          id: "ge-lower",
          title: "General Education — the admission gate (CGEC)",
          note: "A completed GE pattern — the Cerritos General Education Curriculum (24–28 units; Cal-GETC also accepted) — is required before admission to the upper division. Every ◆ area has CLEP exams carrying systemwide GE credit (ESLEI 24-35) — test out instead of sitting in class.",
          courses: [
            { title: "CGEC 1A — English Composition", units: 3 },
            { title: "CGEC 1B — Oral Communication & Critical Thinking", units: 3,
              clep_area: "Language and Rationality" },
            { title: "CGEC 2 — Mathematical Concepts & Quantitative Reasoning", units: 3,
              clep_area: "Language and Rationality" },
            { title: "CGEC 3 — Arts & Humanities", units: 3,
              clep_area: "Arts and Humanities" },
            { title: "CGEC 4 — Social & Behavioral Sciences", units: 3,
              clep_area: "Social/Behavioral Sciences" },
            { title: "CGEC 5 — Natural Sciences", units: 3,
              clep_area: "Natural Sciences" },
            { title: "CGEC 6 — Ethnic Studies", units: 3 },
            { title: "CGEC 7 — American Institutions", units: 3 },
          ],
        },
        {
          id: "as-electives",
          title: "Electives (to the 60-unit associate degree)",
          note: "Degree-applicable electives round out the associate degree; additional apprenticeship or work-experience credit can apply here too.",
          courses: [
            { title: "Degree-applicable electives", units: 4.5 },
          ],
        },
        {
          id: "upper-ge-note",
          title: "Upper-division General Education (within years 3–4)",
          note: "Title 5 (effective Aug 2025) requires ≥9 units of upper-division GE inside the baccalaureate's ≥40 upper-division units — taken alongside the major.",
          courses: [
            { title: "Upper-division GE", units: 9 },
          ],
        },
        {
          id: "as-major-progress",
          title: "More apprenticeship coursework — articulations in progress",
          note: "The rest of Cerritos's IWAP inventory (Structural-track and welding courses). These flip to ✓ automatically as Cerritos adds their MAP articulations — no edit to this page needed. Not counted in the unit totals (a student completes one track).",
          no_count: true,
          courses: [
            { code: "IWAP 40.05", title: "IW — Welding III", units: 2.5 },
            { code: "IWAP 40.10", title: "Welding I — Reinforcing", units: 2.5 },
            { code: "IWAP 40.21", title: "Structural Steel I", units: 2.5 },
            { code: "IWAP 40.26", title: "Metal Building Erection / Foreman Training", units: 2.5 },
            { code: "IWAP 40.60", title: "Structural, Architectural & Ornamental I", units: 2.5 },
            { code: "IWAP 40.61", title: "IW — Structural Precast Concrete / Qualified Rigger", units: 2.0 },
            { code: "IWAP 41.04", title: "IW — Architectural III", units: 2.5 },
            { code: "IWAP 41.05", title: "IW — Architectural II", units: 2.5 },
            { code: "IWAP 41.06", title: "IW — Structural Steel II", units: 2.0 },
          ],
        },
        {
          id: "upper-major",
          title: "Upper-division major — years 3–4 (online, while working)",
          note: "The proposed course list in the Los Angeles regional program record (recommended June 2024): 23 courses, 60 units over years 3 and 4, in the order the record schedules them. The approved curriculum may differ; the 2026–27 catalog does not list the degree yet.",
          wide: true,
          courses: [
            { code: "IWAP 301", title: "IW Advanced Rigging / Rigging II", units: 2 },
            { code: "IWAP 302", title: "IW Cranes II", units: 3 },
            { code: "IWAP 303", title: "IW Reinforcing III", units: 3 },
            { code: "IWAP 304", title: "IW Detailing II (Reinforcing)", units: 3 },
            { code: "IWAP 305", title: "IW Detailing IV (Structural)", units: 3 },
            { code: "COMM 320", title: "Intercultural Communication: Contexts and Dialogue", units: 3 },
            { code: "PSYC 210", title: "Elementary Statistics", units: 4 },
            { code: "IWAP 306", title: "IW Welding IV / Seismic for Structural Steel Welding", units: 3 },
            { code: "IWAP 307", title: "IW Welding V / LA City Stick and Wire Preparation", units: 3 },
            { code: "IWAP 308", title: "IW Welding VI / TIG Welding", units: 3 },
            { code: "IWAP 309", title: "IW Certified Rigger", units: 2 },
            { code: "IWAP 310", title: "Layout Instruments for Ironworkers II", units: 3 },
            { code: "IWAP 401", title: "Advanced Layout and Total Station for Ironworkers IV", units: 2 },
            { code: "IWAP 402", title: "Ironworker Union Politics", units: 1 },
            { code: "IWAP 403", title: "Ironworker Collective Bargaining Agreement (CBA) Law", units: 1 },
            { code: "IWAP 404", title: "IW Superintendent Training", units: 2 },
            { code: "IWAP 405", title: "IW Advanced Blueprint Reading", units: 3 },
            { code: "IWAP 406", title: "Bonded Post-Tensioned Concrete II", units: 2 },
            { code: "IWAP 407", title: "Ironworker Fundamentals: Cost Estimation and Bidding", units: 2 },
            { code: "IWAP 408", title: "IW Metal Building Assembly / Certified Installer", units: 3 },
            { code: "IWAP 409", title: "IW Bolting Up / Structural III", units: 3 },
            { code: "IWAP 410", title: "IW Ornamental II", units: 2 },
            { code: "PSYCH 410", title: "Advanced Statistics", units: 4 },
          ],
        },
      ],
      footnotes: [
        "CPL ✓ courses are articulated by Cerritos College in the Mapping Articulated Pathways (MAP) platform as Credit by Exam for the ironworker apprenticeship curriculum — available to journeyworkers regardless of where they completed their training.",
        "◆ CLEP GE options reflect the CCCCO systemwide exam-credit charts (ESLEI 24-35, title 5 §55052.5): a passing score of 50 grants a minimum of 3 semester units in the GE division shown. The college applies the credit on receipt of scores.",
        "Degree structure per the title 5 baccalaureate regulations effective Aug 2025 (governing a spring 2027 start): ≥120 units total, ≥40 upper-division units (major + GE inclusive), ≥36 GE units with ≥9 upper-division. Tuition ≈$46/unit lower division, ≈$130/unit upper division — about $10,560 total on the 60/60 model. Admission to the upper division requires the completed associate degree and GE pattern.",
        "The associate-degree major (27–29 units, Reinforcing or Structural core) is fully covered by the 31.5 articulated units; surplus apprenticeship credit applies as electives. Stackable along the way: Certificates of Achievement in Field Ironworks Reinforcing (34 units) and Structural (38 units).",
        "Approval: provisionally approved 2025; CSU withdrew its duplication objection and the Chancellor's Office granted final approval under AB 927 in February 2026 (EdSource, 2026-02-20).",
        "Veterans: Cerritos also articulates Basic Military Training (health/kinesiology GE-area credit) — service members entering the trades bring additional CPL.",
        "IWAP course inventory verified against the CCCCO COCI course catalog (snapshot 2026-07-09).",
      ],
      sources: [
        { label: "Program record (LAOCRC / Regional CTE)", url: "https://regionalcte.org/browse/ZyxAg" },
        { label: "Cerritos College Field Ironworkers apprenticeship", url: "https://www.cerritos.edu/apprenticeship-programs/Field_Ironwork.htm" },
        { label: "Apprenticeship: Field Ironworkers A.S. (catalog)", url: "https://cerritos-public.courseleaf.com/degrees-certificates-courses/degrees-certificates-programs-majors/field-ironworkers-aa/" },
        { label: "EdSource — final approval (2026-02)", url: "https://edsource.org/2026/california-community-colleges-approve-3-new-bachelors-degrees-over-california-state-university-objections/751678" },
        { label: "MAP CPL Insights Dashboard", url: "https://cpldashboardcccco.azurewebsites.net/insights/dashboard" },
      ],
    },
    {
      id: "foothill-dental-hygiene-bs",
      college: "Foothill College",
      program: "Dental Hygiene",
      degree: "Bachelor of Science",
      stage: "discussion-draft",
      start: "Fall 2016",
      status: "SB 850 pilot original — permanent under AB 927",
      audience: "Dental professionals — RDAs & licensed RDHs",
      unit_system: "quarter",
      cpl_tile_label: "CPL articulated by Foothill in MAP today — the ⊕ chips show what peers have proven",
      blurb: "One of California's original community college baccalaureates (first BS "
        + "class 2018 — 100% national board pass rate; CODA-accredited). Foothill's MAP "
        + "articulations today cover AP exams only — so this map is the ADOPTION view: "
        + "every ⊕ chip marks coursework where another college already articulates a "
        + "dental credential for CPL. West Los Angeles College is the model — the RDA "
        + "License articulates to 11 of its courses, the RDH License to its capstone, "
        + "pharmacology, and nutrition coursework.",
      facts: [
        "≈$4,000 total CA-resident cost for the whole BS — vs $40–70K/yr at private alternatives",
        "First BS cohort graduated 2018 with a 100% National Board pass rate",
        "Licensed RDHs: a fully-online 44-unit AS-to-BS completion track (1–2 years)",
        "Quarter system — 180+ quarter units (≈120 semester)",
      ],
      total_units: 180,
      campaign: {
        kicker: "The adoption opportunity",
        headline: "Every ⊕ on this map is CPL another California college has already proven. Adopting it is a decision, not an experiment.",
        sub: "The model: West Los Angeles College articulates the RDA License (11 courses) and the RDH License (capstone · pharmacology · nutrition); BLS and EMT credentials are articulated at colleges statewide. MAP makes the precedent visible — adoption makes it count.",
      },
      sections: [
        {
          id: "prereq-sci",
          title: "Science prerequisites (years 1–2)",
          note: "Wet labs required; biological sciences subject to a 6-year recency rule. Competitive cohort admission follows (top 30 by points).",
          courses: [
            { code: "D H 200L", title: "Orientation to Dental Hygiene (online, at Foothill)", units: 1,
              adopt: { credentials: ["Dental Assisting Orientation", "Registered Dental Assistant (RDA) License"],
                       note: "West LA articulates dental-assisting orientation coursework" } },
            { code: "CHEM 30A", title: "Survey of Chemistry I" },
            { code: "CHEM 30B", title: "Survey of Chemistry II" },
            { code: "BIOL 40A", title: "Human Anatomy & Physiology I", units: 5 },
            { code: "BIOL 40B", title: "Human Anatomy & Physiology II", units: 5 },
            { code: "BIOL 40C", title: "Human Anatomy & Physiology III", units: 5 },
            { code: "BIOL 41", title: "Microbiology", units: 6 },
            { code: "BIOL 45", title: "Introduction to Human Nutrition", units: 4,
              adopt: { credentials: ["Registered Dental Hygienist (RDH) License"],
                       note: "West LA articulates the RDH License to Preventative Dentistry & Nutrition" } },
          ],
        },
        {
          id: "ge-lower",
          title: "General Education + prerequisites (years 1–2)",
          note: "Cal-GETC, CSU GE Breadth, IGETC, or Foothill GE — years 1–2 total ≈91.5 quarter units including the sciences. Every ◆ area has CLEP exams carrying systemwide GE credit (min 4 quarter units each).",
          courses: [
            { code: "ENGL 1A+1B", title: "English Composition + Critical Thinking" },
            { code: "COMM 1A", title: "Public Speaking" },
            { code: "PSYC 1", title: "General Psychology", units: 4,
              clep_area: "Social/Behavioral Sciences" },
            { code: "SOC 1", title: "Introduction to Sociology", units: 4,
              clep_area: "Social/Behavioral Sciences" },
            { title: "Statistics (MATH 10 / PSYC 7 / SOC 7)", units: 5,
              clep_area: "Language and Rationality" },
            { title: "Arts & Humanities GE", units: 4,
              clep_area: "Arts and Humanities" },
            { title: "Health (HLTH 20/21) + Ethnic Studies + remaining GE" },
          ],
        },
        {
          id: "dh-core",
          title: "Dental Hygiene core — years 3–4 (CODA-accredited cohort)",
          note: "≈91.5 quarter units of D H 300-level coursework after admission. ⊕ rows: another college already articulates a credential to equivalent coursework — the adoption menu.",
          wide: true,
          courses: [
            { code: "D H 300A+B", title: "Oral Biology I–II", units: 6 },
            { code: "D H 302", title: "Assessment Procedures in Dental Hygiene", units: 3 },
            { code: "D H 304", title: "Pre-Clinical Dental Hygiene", units: 4 },
            { code: "D H 305A–D", title: "Dental Radiography I–IV", units: 6,
              adopt: { credentials: ["Dental Board of California Certificates", "Registered Dental Assistant (RDA) License"],
                       note: "West LA articulates RDA radiology coursework" } },
            { code: "D H 306", title: "Pharmacology for the Dental Hygienist", units: 2,
              adopt: { credentials: ["Registered Dental Hygienist (RDH) License"],
                       note: "West LA + Glendale articulate licensure to pharmacology" } },
            { code: "D H 308", title: "Clinical Technique", units: 6 },
            { code: "D H 310", title: "Dental Materials", units: 3 },
            { code: "D H 312", title: "Emergency Procedures", units: 1,
              adopt: { credentials: ["Basic Life Support (BLS) Certification", "Dental Board of California Certificates"],
                       note: "BLS is articulated at multiple colleges" } },
            { code: "D H 314", title: "Dental Health Education", units: 2 },
            { code: "D H 316A+B", title: "Periodontics I–II", units: 5 },
            { code: "D H 318", title: "Introduction to Clinic", units: 7 },
            { code: "D H 320A–D", title: "Clinical Dental Hygiene I–IV", units: 27.5 },
            { code: "D H 322", title: "Local Anesthesia", units: 2.5 },
            { code: "D H 324", title: "Oral Pathology", units: 2 },
            { code: "D H 326A–C", title: "Community Dental Health I–III", units: 6 },
            { code: "D H 328A–C", title: "Clinical Dental Hygiene Theory I–III", units: 6 },
            { code: "D H 330", title: "Nitrous Oxide / Oxygen Analgesia", units: 1 },
            { code: "D H 332", title: "Ethics, Law & Business Practices", units: 3 },
          ],
        },
        {
          id: "upper-ge",
          title: "Upper-division General Education",
          courses: [
            { title: "Upper-division GE (alongside the DH core)", units: 14 },
          ],
        },
        {
          id: "rdh-completion",
          title: "Already a licensed RDH? The online AS-to-BS completion track",
          note: "44 quarter units, fully online, ≈$87/unit, 1–2 years: 30 units of upper-division DH + 14 units UD GE for licensed RDH/RDHAPs with a CODA-accredited associate. The CPL frontier: recognizing the license itself — as West LA already articulates. Not counted in the entry-track unit totals.",
          no_count: true,
          courses: [
            { code: "D H 350A–C", title: "Dental Hygiene Research & Capstone I–III", units: 15,
              adopt: { credentials: ["Registered Dental Hygienist (RDH) License"],
                       note: "West LA articulates the RDH License to its DH capstone" } },
            { code: "D H 352", title: "Health Communication & Cultural Issues", units: 5 },
            { code: "D H 354", title: "Health Care Management", units: 5 },
            { code: "D H 356", title: "Education Theory, Practice & Administration", units: 5 },
            { title: "Upper-division GE", units: 14 },
          ],
        },
      ],
      footnotes: [
        "Foothill's MAP articulations today are AP-exam lines (12); no industry or licensure credentials are articulated yet — that is the ⊕ opportunity this map surfaces. Adoption chips derive live from other colleges' MAP articulations in this dashboard's CER dataset.",
        "◆ CLEP GE options reflect the CCCCO systemwide exam-credit charts (ESLEI 24-35, title 5 §55052.5): passing score 50 grants a minimum of 4 quarter units in the GE division shown; the college applies the credit.",
        "Quarter system: the catalog requires a minimum of 180 quarter units (≈120 semester); the published 2026-27 ed plan totals ≈197 quarter units (≈91.5 in years 1–2, ≈105.5 in years 3–4 incl. 14 units upper-division GE). Unit values shown are per the 2026-27 ed plan / catalog outlines; a few (CHEM/ENGL/COMM) publish per-quarter and are left unmarked — verify against the catalog before print.",
        "Program history: SB 850 (2014) pilot original, launched fall 2016; first BS class June 2018 (23 graduates, 100% National Board Dental Hygiene Exam pass rate); CODA-accredited (2018 site visit: approval without reporting requirements); permanent under AB 927.",
        "Admission (entry track): competitive — top 30 qualified applicants by points; min GPA 2.5; science prerequisites C-or-better with wet labs and a 6-year recency rule.",
      ],
      sources: [
        { label: "BS Dental Hygiene (Foothill catalog)", url: "https://catalog.foothill.edu/degrees-certificates/dental-hygiene/" },
        { label: "2026-27 BS-DH ed plan (PDF)", url: "https://foothill.edu/dental-hygiene/entry-track/pdf/foothill-BS-DH-ed-plan-26-27.pdf" },
        { label: "AS-to-BS completion track (PDF)", url: "https://foothill.edu/dentalhygiene/completion/pdf/AS-TO-BSDH-PROGRAM-INFORMATION-rev2.4.25.pdf" },
        { label: "First BS class (Foothill news, 2018)", url: "https://foothill.edu/news/dentalhygiene.html" },
        { label: "MAP CPL Insights Dashboard", url: "https://cpldashboardcccco.azurewebsites.net/insights/dashboard" },
      ],
    },
    {
      id: "foothill-respiratory-care-bs",
      college: "Foothill College",
      program: "Respiratory Care (RRT-to-BS completion)",
      degree: "Bachelor of Science",
      stage: "discussion-draft",
      start: "Fall 2024",
      status: "AB 927 first cycle (approved Nov 2022)",
      audience: "Licensed RRTs / RCPs — one online year",
      unit_system: "quarter",
      cpl_tile_label: "CPL Foothill ALREADY awards — in its catalog — for the NBRC exams + RCP license",
      total_tile_label: "quarter units between a licensed RRT and the BS (24 CPL + 44 coursework)",
      blurb: "Foothill's second baccalaureate is a degree-completion pathway: a licensed "
        + "Respiratory Care Practitioner with a CoARC-accredited associate finishes the BS "
        + "in ONE fully-online year. And here is the CPL story the map exists to tell: "
        + "Foothill's own catalog already awards 24 quarter units of Credit for Prior "
        + "Learning for the NBRC TMC (high cut) + Clinical Simulation Exam, state "
        + "licensure, and the RCP Law & Ethics course — real CPL, in production, that no "
        + "one can see in the MAP platform yet.",
      facts: [
        "24 quarter units of CPL for licensure — already in Foothill's catalog",
        "One online year — built for working therapists (cohort 30–40, fall start)",
        "≈$87/quarter unit for CA residents; Bay Area RRTs earn ~$110–120K",
        "BS Respiratory Care = 7 of the 31 CCC baccalaureates statewide",
      ],
      total_units: 68,
      campaign: {
        kicker: "The visibility opportunity",
        headline: "Foothill already gives RRTs {cpl_units} units for their license — it's in the catalog. Putting it in MAP puts it on every counselor's screen in California.",
        sub: "CPL that lives only in a catalog PDF reaches the students who already found it. CPL articulated in the MAP platform reaches all of them — and shows the other 6 BSRC colleges the adoption precedent.",
      },
      sections: [
        {
          id: "rrt-arrives",
          title: "What a licensed RRT arrives with (the admission gate)",
          note: "Required for admission — not part of the completion-year unit math: a CoARC-accredited associate in respiratory care, a completed GE pattern, and the California RCP license. The ⊕ chips show EMS-credential CPL other colleges articulate into the feeder associate.",
          no_count: true,
          courses: [
            { title: "CoARC-accredited AS in Respiratory Care (≈2 years incl. clinical rotations)",
              adopt: { credentials: ["EMT Certification", "Paramedic License", "Basic Life Support (BLS) Certification"],
                       note: "EMS credentials articulate at 40+ colleges statewide — feeder CPL into the respiratory associate" } },
            { title: "Completed GE pattern (Cal-GETC, CSU GE Breadth, IGETC, or Foothill GE)" },
            { title: "California Respiratory Care Practitioner (RCP) license — or eligibility" },
          ],
        },
        {
          id: "cpl-award",
          title: "Credit for Prior Learning — already in Foothill's catalog",
          note: "Foothill awards these 24 quarter units on entry. The gap: this CPL lives in the catalog, not in the MAP platform — articulating it there makes it visible statewide.",
          wide: true,
          courses: [
            { title: "NBRC TMC Exam (high cut score) + Clinical Simulation Exam + CA state licensure + RCP Law & Ethics course", units: 24,
              cpl: { credential: "NBRC/RCP licensure package (Foothill catalog CPL award)",
                     types: ["Industry Certification"],
                     source: "Awarded by Foothill College per its catalog — not yet articulated in MAP" } },
          ],
        },
        {
          id: "upper-major",
          title: "Upper-division major — one online year (RSPT 300-level)",
          note: "Advanced scope of practice for working therapists. Unit values per catalog course outlines (RSPT 300/304 inferred from the published hours pattern — verify before print).",
          courses: [
            { code: "RSPT 300", title: "Leadership & Management in Health Care", units: 5 },
            { code: "RSPT 304", title: "Clinical Specialist & Chronic Disease Management", units: 5 },
            { code: "RSPT 305", title: "Respiratory Care Capstone Research Project", units: 5 },
            { code: "RSPT 306", title: "Advanced Pulmonary Diagnostics", units: 5 },
            { code: "RSPT 307", title: "Interventional Pulmonology Theory & Application", units: 5 },
            { code: "RSPT 308", title: "Interventional Pulmonology Procedures", units: 5 },
          ],
        },
        {
          id: "upper-ge",
          title: "Upper-division General Education (14 quarter units)",
          note: "Shared with the BS Dental Hygiene — Foothill's upper-division GE core.",
          courses: [
            { code: "BIOL 300", title: "Human Pathophysiology & Pharmacology", units: 4 },
            { code: "HLTH 300", title: "Health Across the Lifespan", units: 5 },
            { code: "IDS 300", title: "Research Methodology for Health Professionals", units: 5 },
          ],
        },
      ],
      footnotes: [
        "The 24-unit CPL award is Foothill's own published policy (catalog: NBRC TMC high cut + Clinical Simulation Exam + state licensure + Law & Ethics course). It is shown ✓ because the college grants it today — the opportunity is ARTICULATING it in the MAP platform so counselors and students statewide can see it, and the other six BSRC colleges can adopt it.",
        "Completion-year scope: this map counts the 68 quarter units between a licensed RRT and the BS (24 CPL + 30 upper-division major + 14 upper-division GE). The associate degree and GE pattern the RRT arrives with are admission requirements, shown for context and not counted.",
        "Approved in the first AB 927 cycle (reported Nov 2022); first cohort fall 2024; fully online; cohort 30–40. Fees ≈$87/quarter unit CA-resident.",
        "RSPT 300 and 304 unit values are inferred from Foothill's published hours pattern (the other four RSPT 300-level outlines publish 5 units at 5 lecture-hrs/week); the printed catalog total could not be fetched (CourseLeaf bot-block) — verify the 44-unit coursework figure against the catalog before print.",
        "⊕ adoption options derive live from other colleges' MAP articulations in this dashboard's CER dataset.",
      ],
      sources: [
        { label: "BS Respiratory Care (Foothill catalog)", url: "https://catalog.foothill.edu/degrees-certificates/respiratory-care/" },
        { label: "Program page — admission, fees, one-year online", url: "https://foothill.edu/respiratory-therapy/bachelor-science.html" },
        { label: "Approval reported (Los Altos Town Crier, Nov 2022)", url: "https://www.losaltosonline.com/schools/foothill-set-to-offer-second-bachelor-s-degree/article_3397b9f2-5fb7-11ed-b491-7386fde2665b.html" },
        { label: "CoARC accreditation (associate program #200017)", url: "https://coarc.com/accredited_program/foothill-college/" },
        { label: "MAP CPL Insights Dashboard", url: "https://cpldashboardcccco.azurewebsites.net/insights/dashboard" },
      ],
    },
  ],
};
