/* gr_priorities.js — COBI "GR" (Government Relations) REGISTER.
 *
 * WHAT THIS IS
 * ------------
 * A register of regulatory / Ed. Code revisions under consideration, grouped by
 * CO PRIORITY AREA (CPL, Dual Enrollment, …), with the source ARTIFACTS that
 * inform them. It replaces the single hardcoded briefing this tab used to be
 * (one jsonb blob, one topic, read-only, `writes: []`).
 *
 * WHY A REGISTER AND NOT A DOCUMENT (Sam, 2026-08-18)
 * --------------------------------------------------
 * The tab is being shown to CO General Counsel as a possible instrument for ALL
 * their policy and regulation reviews. A document scales to one topic; a
 * register scales to every priority area, and everything asked for falls out of
 * it as a column — areas, revisions, artifacts, filters, section dropdowns, and
 * the division/priority tags. Three tables, no cleverness:
 *   gr_areas → gr_revisions → gr_artifacts   (kb/supabase_gr_register.sql)
 *
 * CITATIONS ARE DATA, NOT PROSE — that is the load-bearing change. A "Title 5 /
 * Ed. Code section" filter cannot exist while §55050 lives only inside a
 * sentence. `citations` is text[] in the canonical form `T5 §55050` /
 * `EC §76004` / `GC §11342.2`; the dropdowns are built from what is actually
 * stored, so a section nobody cited never appears as an empty option.
 *
 * ⚠️ A DERIVED CITATION IS LABELLED AS ONE. The CPL area's citations were
 * machine-extracted from prose at migration (`citations_derived`). Shown to a
 * lawyer, an extracted citation presented as curated fact is a credibility
 * failure, so those rows carry a "from text" marker until a human edits them.
 * Codes are assigned by EXPLICIT range, never "everything else" — §11342.2 is
 * GOVERNMENT Code (the APA definition of a regulation), and a 5xxxx/else rule
 * would have filed it under Ed. Code.
 *
 * SENSITIVE / GATED — unchanged from the briefing this replaces. Content lives
 * ONLY in Supabase, released by RLS when the correct MAP-team GR phrase rides in
 * `x-team-pass`; the gate is COHORT-SPECIFIC (gr_pass_ok() accepts ONLY the 'gr'
 * secret, so CO-held phrases cannot read it). WRITES are reviewer-only
 * (magic-link), never phrase-only — a shared phrase is a read credential.
 * ⚠️ Widening read access to CO divisions waits on the phrase-scope fix
 * (CLAUDE.md §11 "Org & phrase scope") — the GR phrase currently also opens
 * every shared team tab.
 *
 * Rendering is CodeQL-XSS-safe: DOM is built with createElement/textContent;
 * the small inline allowlist (a/b/i) goes through appendRich, and link hrefs are
 * guarded to https:// only. STATIC — NOT regenerated by excel_to_dashboard.py.
 * Lazy-loaded on first #gr-priorities open (boot block in BOTH HTMLs, Rule 4).
 * Injects its own scoped CSS under .grx. Tests: tests/gr_priorities.test.js
 */
(function () {
  "use strict";

  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var GR_KEY = "cpl_gr_pass";           // GR-specific — separate from the generic cpl_team_pass
  var ROOT_ID = "gr-priorities-root";
  var CSS_ID = "gr-priorities-css";
  var DOC_ID = "cpl-t5-priorities";

  // ── tiny DOM helper ────────────────────────────────────────────────────────
  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) {
      Object.keys(attrs).forEach(function (k) {
        if (k === "class") n.className = attrs[k];
        else if (k === "text") n.textContent = attrs[k];
        else if (k.slice(0, 2) === "on" && typeof attrs[k] === "function") n[k] = attrs[k];
        else if (attrs[k] != null) n.setAttribute(k, attrs[k]);
      });
    }
    (kids || []).forEach(function (c) {
      if (c == null) return;
      n.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
    });
    return n;
  }
  function clear(n) { while (n && n.firstChild) n.removeChild(n.firstChild); }

  // ── safe rich text: allowlist <a>/<b>/<i> → DOM (no innerHTML with data) ────
  function decode(s) {
    return String(s == null ? "" : s)
      .replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"').replace(/&#0?39;/g, "'");
  }
  var RICH = /<a href="([^"]+)"(?:\s+style="[^"]*")?>([^<]*)<\/a>|<b>([^<]*)<\/b>|<i>([^<]*)<\/i>/g;
  // Append rich inline HTML to `node`, building only allowlisted elements.
  function appendRich(node, html) {
    html = String(html == null ? "" : html).replace(/^<p>/, "").replace(/<\/p>$/, "");
    RICH.lastIndex = 0;
    var last = 0, m;
    function txt(s) { if (s) node.appendChild(document.createTextNode(decode(s))); }
    while ((m = RICH.exec(html))) {
      txt(html.slice(last, m.index));
      if (m[1] !== undefined) {
        var url = m[1];
        if (/^https:\/\//.test(url)) {         // guard: only real https links
          var a = el("a", { href: url, target: "_blank", rel: "noopener" });
          a.textContent = decode(m[2]);
          node.appendChild(a);
        } else { txt(m[2]); }
      } else if (m[3] !== undefined) {
        node.appendChild(el("b", { text: decode(m[3]) }));
      } else if (m[4] !== undefined) {
        node.appendChild(el("i", { text: decode(m[4]) }));
      }
      last = RICH.lastIndex;
    }
    txt(html.slice(last));
    return node;
  }
  function richP(html, cls) { return appendRich(el("p", cls ? { class: cls } : null), html); }

  // ── gate: GR-cohort phrase, validated server-side via rpc/gr_pass_ok ────────
  function getPass() { try { return localStorage.getItem(GR_KEY) || null; } catch (e) { return null; } }
  function setPass(p) { try { localStorage.setItem(GR_KEY, p); } catch (e) { /* ignore */ } }
  function clearPass() { try { localStorage.removeItem(GR_KEY); } catch (e) { /* ignore */ } }

  function verify(phrase) {
    return fetch(SUPABASE_URL + "/rest/v1/rpc/gr_pass_ok", {
      method: "POST",
      headers: {
        apikey: SUPABASE_ANON, Authorization: "Bearer " + SUPABASE_ANON,
        "Content-Type": "application/json", "x-team-pass": phrase
      },
      body: "{}"
    }).then(function (r) {
      if (r.status === 429 || r.status >= 500) return null;   // transient
      if (!r.ok) return false;
      return r.json().then(function (v) { return v === true; });
    }).catch(function () { return null; });
  }
  function fetchDoc(phrase) {
    return fetch(SUPABASE_URL + "/rest/v1/gr_content?id=eq." + DOC_ID + "&select=doc", {
      headers: { apikey: SUPABASE_ANON, Authorization: "Bearer " + SUPABASE_ANON, "x-team-pass": phrase }
    }).then(function (r) {
      if (!r.ok) return null;
      return r.json().then(function (rows) { return (rows && rows[0] && rows[0].doc) || null; });
    }).catch(function () { return null; });
  }

  // ── REST helpers ────────────────────────────────────────────────────────────
  var REST = SUPABASE_URL + "/rest/v1";

  // A reviewer session is what allows WRITING. The shared phrase is a READ
  // credential and deliberately grants nothing here: anyone who can read the
  // register must not be able to rewrite another division's entries.
  function session() {
    try {
      if (window.CPL_SESSION && typeof window.CPL_SESSION.get === "function") {
        return window.CPL_SESSION.get() || null;
      }
      return JSON.parse(sessionStorage.getItem("cpl_sb") || "null");
    } catch (e) { return null; }
  }
  function canWrite() { var s = session(); return !!(s && s.access_token); }
  function whoami() { var s = session(); return (s && s.email) || "(reviewer)"; }

  function headers(write) {
    var s = session();
    var h = {
      apikey: SUPABASE_ANON,
      Authorization: "Bearer " + ((s && s.access_token) || SUPABASE_ANON)
    };
    var p = getPass();
    if (p) h["x-team-pass"] = p;          // read path for phrase holders
    if (write) {
      h["Content-Type"] = "application/json";
      h.Prefer = "return=representation";
    }
    return h;
  }

  // Every table URL is written out in full at each call site, in the shape
  // kb/_build_cobi_admin_surface.py scans for. Building them from a variable
  // would hide this tab's data surface from the Admin tab's RLS view, and an
  // inventory that misses a table renders as "nothing to protect" — a claim
  // about safety (the Sky160 lesson).
  //
  // That scanner reads COMMENTS as well as code: spelling the pattern out in
  // prose here once invented a table called "table" in the generated inventory.
  // A phantom row in a security view is the same defect as a missing one.
  function getJson(url) {
    return fetch(url, { headers: headers(false) }).then(function (r) {
      if (!r.ok) return null;
      return r.json();
    }).catch(function () { return null; });
  }

  // An RLS-filtered write answers 200 with an EMPTY body, never 403. An "ok"
  // that touched no row is a FAILURE — reporting it as success tells someone
  // their entry was recorded when nothing was. Same guarantee cr_reference.js
  // and map_users.js both needed.
  function wrote(r) {
    if (!r.ok) throw new Error("save " + r.status);
    return r.json().then(function (rows) {
      if (!Array.isArray(rows) || rows.length === 0) {
        throw new Error("not saved — your sign-in does not allow writing to the register");
      }
      return rows[0];
    });
  }
  function addArea(rec) {
    return fetch(REST + "/gr_areas", { method: "POST", headers: headers(true), body: JSON.stringify([rec]) }).then(wrote);
  }
  function addRevision(rec) {
    return fetch(REST + "/gr_revisions", { method: "POST", headers: headers(true), body: JSON.stringify([rec]) }).then(wrote);
  }
  function addArtifact(rec) {
    return fetch(REST + "/gr_artifacts", { method: "POST", headers: headers(true), body: JSON.stringify([rec]) }).then(wrote);
  }
  var WRITERS = { gr_areas: addArea, gr_revisions: addRevision, gr_artifacts: addArtifact };
  function post(table, rec) { return WRITERS[table](rec); }

  // ── citations ───────────────────────────────────────────────────────────────
  // Canonical stored form: "T5 §55050" | "EC §76004" | "GC §11342.2".
  var CODES = { T5: "Title 5", EC: "Ed. Code", GC: "Gov. Code" };
  function citeCode(c) { return String(c || "").split(" ")[0]; }
  function citeLabel(c) {
    var code = citeCode(c), rest = String(c || "").slice(code.length).trim();
    return (CODES[code] || code) + " " + rest;
  }
  // Parse whatever a human typed into canonical entries. Anything we cannot
  // place under a KNOWN code is returned as a reject rather than guessed — the
  // form shows rejects back instead of silently dropping or mis-filing them.
  function parseCites(s) {
    var out = [], bad = [];
    String(s || "").split(/[,;\n]+/).forEach(function (raw) {
      var t = raw.trim();
      if (!t) return;
      var m = /^(T5|EC|GC|title\s*5|ed\.?\s*code|gov\.?\s*code)?\s*§?\s*([0-9]{4,6}(?:\.[0-9]+)?[a-z]?)$/i.exec(t);
      if (!m) { bad.push(t); return; }
      var code = (m[1] || "").toLowerCase().replace(/[\s.]/g, "");
      code = code === "t5" || code === "title5" ? "T5"
           : code === "ec" || code === "edcode" ? "EC"
           : code === "gc" || code === "govcode" ? "GC" : "";
      if (!code) {                      // infer ONLY from unambiguous ranges
        var n = m[2];
        code = /^5[358]/.test(n) ? "T5" : /^(66|70|76)/.test(n) ? "EC" : /^11/.test(n) ? "GC" : "";
      }
      if (!code) { bad.push(t); return; }
      out.push(code + " §" + m[2]);
    });
    return { ok: out, bad: bad };
  }

  // ── scoped styles (.grx) ────────────────────────────────────────────────────
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var st = document.createElement("style");
    st.id = CSS_ID;
    st.textContent = [
      ".grx{--gx-ink:var(--text-strong,#1C1C1A);--gx-muted:var(--text-muted,#5C5C55);",
      "--gx-border:var(--border,rgba(28,28,26,.14));--gx-bstrong:var(--border-strong,rgba(28,28,26,.30));",
      "--gx-surface:var(--surface-opaque,#fff);--gx-card:var(--surface-subtle,#faf9f6);",
      "--gx-accent:var(--seal-blue,#002F6D);--gx-g:var(--hunter,#2C601A);--gx-y:var(--mustard-text,#8B6800);",
      "--gx-r:var(--crimson,#920000);font-family:'Source Sans 3',Arial,sans-serif;color:var(--gx-ink);}",
      ".grx h2,.grx h3,.grx h4{font-family:Georgia,'Playfair Display',serif;margin:0;}",
      // head
      ".grx .gx-head{border-bottom:2px solid var(--gx-accent);padding-bottom:12px;margin-bottom:16px;}",
      ".grx .gx-eyebrow{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:var(--gx-muted);font-weight:700;}",
      ".grx .gx-title{font-size:23px;margin:4px 0 2px;}",
      ".grx .gx-sub{color:var(--gx-muted);font-size:13px;margin:0 0 6px;}",
      ".grx .gx-thesis{font-size:13.2px;line-height:1.55;margin:8px 0 0;max-width:74ch;}",
      ".grx .gx-samp{display:inline-block;margin-left:8px;padding:1px 7px;border-radius:3px;font-size:10.5px;",
      "font-weight:800;letter-spacing:.08em;text-transform:uppercase;background:var(--mustard-fill,#E3B341);color:var(--gx-accent);}",
      // area bar
      ".grx .gx-areabar{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin-bottom:14px;}",
      ".grx .gx-areabar label{font-size:12px;font-weight:700;color:var(--gx-muted);}",
      ".grx select,.grx input[type=text],.grx input[type=date],.grx textarea{padding:6px 9px;border:1px solid var(--gx-bstrong);",
      "border-radius:5px;font:13px inherit;background:var(--gx-surface);color:var(--gx-ink);}",
      ".grx textarea{width:100%;min-height:64px;resize:vertical;}",
      // toolbar
      ".grx .gx-tools{display:flex;flex-wrap:wrap;gap:8px;align-items:center;padding:10px 12px;border:1px solid var(--gx-border);",
      "border-radius:7px;background:var(--gx-card);margin-bottom:14px;}",
      ".grx .gx-tools .sp{flex:1 1 auto;}",
      ".grx .gx-search{min-width:210px;}",
      ".grx .gx-chip{border:1px solid var(--gx-bstrong);background:var(--gx-surface);color:var(--gx-muted);",
      "border-radius:20px;padding:4px 11px;font:600 11.7px inherit;cursor:pointer;display:inline-flex;align-items:center;gap:5px;}",
      ".grx .gx-chip[aria-pressed=true]{background:var(--gx-accent);border-color:var(--gx-accent);color:#fff;}",
      ".grx .gx-chip .sw{width:8px;height:8px;border-radius:50%;display:inline-block;}",
      ".grx .gx-chip.fg .sw{background:var(--gx-g);}.grx .gx-chip.fy .sw{background:var(--gx-y);}",
      ".grx .gx-chip.fr .sw{background:var(--gx-r);}",
      ".grx .gx-count{font-size:12px;color:var(--gx-muted);}",
      ".grx .gx-btn{border:1px solid var(--gx-accent);background:var(--gx-accent);color:#fff;border-radius:5px;",
      "padding:6px 12px;font:600 12.4px inherit;cursor:pointer;}",
      ".grx .gx-btn.ghost{background:var(--gx-surface);color:var(--gx-accent);}",
      ".grx .gx-btn:disabled{opacity:.55;cursor:default;}",
      // rows
      ".grx .gx-grp{margin:16px 0 4px;}",
      ".grx .gx-grph{display:flex;align-items:baseline;gap:8px;border-bottom:1px solid var(--gx-border);padding-bottom:5px;margin-bottom:6px;}",
      ".grx .gx-grph h3{font-size:13.5px;}",
      ".grx .gx-item{border:1px solid var(--gx-border);border-left:3px solid var(--bd,var(--gx-accent));border-radius:6px;",
      "background:var(--gx-surface);margin:6px 0;padding:0;}",
      ".grx .gx-item[hidden]{display:none;}",
      ".grx .gx-item>summary{list-style:none;cursor:pointer;padding:9px 12px;display:flex;flex-wrap:wrap;gap:8px;align-items:baseline;}",
      ".grx .gx-item>summary::-webkit-details-marker{display:none;}",
      ".grx .gx-num{font-size:11px;color:var(--gx-muted);font-weight:700;min-width:1.6em;}",
      ".grx .gx-ttl{font-weight:600;font-size:13.3px;flex:1 1 260px;}",
      ".grx .gx-sm{display:inline-flex;gap:6px;align-items:center;flex-wrap:wrap;}",
      ".grx .gx-p{font-size:9.6px;font-weight:800;letter-spacing:.06em;padding:1px 5px;border-radius:3px;border:1px solid currentColor;}",
      ".grx .gx-p.g{color:var(--gx-g);}.grx .gx-p.y{color:var(--gx-y);}.grx .gx-p.r{color:var(--gx-r);}",
      ".grx .gx-cite{font-size:10.4px;font-weight:700;color:var(--gx-accent);background:var(--gx-card);",
      "border:1px solid var(--gx-border);border-radius:3px;padding:1px 5px;white-space:nowrap;}",
      ".grx .gx-cite.derived{border-style:dashed;color:var(--gx-muted);}",
      ".grx .gx-st{font-size:10px;font-weight:800;letter-spacing:.05em;text-transform:uppercase;color:var(--gx-muted);}",
      ".grx .gx-desc{padding:0 12px 11px 12px;font-size:12.6px;line-height:1.5;color:var(--gx-muted);}",
      ".grx .gx-desc p{margin:0 0 6px;}",
      ".grx .gx-meta{font-size:10.8px;color:var(--gx-muted);border-top:1px dotted var(--gx-border);padding-top:5px;margin-top:6px;}",
      // artifacts
      ".grx .gx-arts{margin-top:26px;border-top:1px solid var(--gx-border);padding-top:14px;}",
      ".grx .gx-art{border:1px solid var(--gx-border);border-radius:6px;background:var(--gx-surface);padding:9px 12px;margin:6px 0;}",
      ".grx .gx-art .t{font-weight:600;font-size:13px;}",
      ".grx .gx-art .m{font-size:11px;color:var(--gx-muted);margin-top:2px;}",
      ".grx .gx-art .w{font-size:12.3px;color:var(--gx-muted);margin-top:5px;line-height:1.45;}",
      ".grx .gx-kind{font-size:9.6px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;",
      "color:var(--gx-accent);border:1px solid var(--gx-border);border-radius:3px;padding:1px 5px;margin-right:6px;}",
      // forms
      ".grx .gx-form{border:1px solid var(--gx-bstrong);border-radius:7px;background:var(--gx-card);padding:14px 16px;margin:10px 0 18px;}",
      ".grx .gx-form h4{font-size:14px;margin-bottom:9px;}",
      ".grx .gx-fld{margin-bottom:9px;}",
      ".grx .gx-fld label{display:block;font-size:11.4px;font-weight:700;color:var(--gx-muted);margin-bottom:3px;}",
      ".grx .gx-fld input[type=text],.grx .gx-fld select{width:100%;max-width:520px;}",
      ".grx .gx-frow{display:flex;flex-wrap:wrap;gap:12px;}",
      ".grx .gx-frow>div{flex:1 1 200px;}",
      ".grx .gx-err{color:var(--gx-r);font-size:11.6px;margin-top:7px;min-height:1em;}",
      ".grx .gx-ok{color:var(--gx-g);font-size:11.6px;margin-top:7px;}",
      ".grx .gx-note{font-size:11.4px;color:var(--gx-muted);margin:6px 0 0;}",
      ".grx .gx-empty{padding:22px;text-align:center;color:var(--gx-muted);font-size:13px;",
      "border:1px dashed var(--gx-bstrong);border-radius:7px;}",
      // lock card
      ".grx .gx-lock{max-width:460px;margin:36px auto;border:1px solid var(--gx-border);border-radius:8px;background:var(--gx-surface);padding:24px 26px;text-align:left;}",
      ".grx .gx-lock .lk{font-family:Georgia,serif;font-size:17px;font-weight:600;margin:0 0 6px;}",
      ".grx .gx-lock p{color:var(--gx-muted);font-size:12.8px;line-height:1.5;margin:0 0 14px;}",
      ".grx .gx-lock .row{display:flex;flex-wrap:wrap;gap:8px;align-items:center;}",
      ".grx .gx-lock input{padding:7px 10px;border:1px solid var(--gx-bstrong);border-radius:5px;font:13px inherit;",
      "background:var(--gx-card);color:var(--gx-ink);min-width:180px;}",
      ".grx .gx-lock button{padding:7px 14px;border:1px solid var(--gx-accent);border-radius:5px;background:var(--gx-accent);",
      "color:#fff;font:600 12.5px inherit;cursor:pointer;}",
      ".grx .gx-lock button:disabled{opacity:.6;cursor:default;}",
      ".grx .gx-lock .err{color:var(--gx-r);font-size:11.5px;margin:9px 0 0;min-height:1em;}"
    ].join("");
    document.head.appendChild(st);
  }

  // ── small builders ──────────────────────────────────────────────────────────
  var TLBL = { g: "GUIDANCE", y: "TITLE 5", r: "ED CODE" };
  var TTITLE = { g: "Chancellor's Office guidance memo", y: "Board of Governors rulemaking (Title 5)", r: "Education Code amendment" };
  var STATUSES = ["proposed", "under_review", "adopted", "withdrawn", "parked"];
  function stLabel(s) { return String(s || "").replace(/_/g, " "); }

  function pathChips(path) {
    var wrap = el("span", { class: "gx-sm" });
    (path || []).forEach(function (p) {
      wrap.appendChild(el("span", { class: "gx-p " + p, title: TTITLE[p] || "", text: TLBL[p] || p }));
    });
    return wrap;
  }
  function citeChips(cites, derived) {
    var wrap = el("span", { class: "gx-sm" });
    (cites || []).forEach(function (c) {
      wrap.appendChild(el("span", {
        class: "gx-cite" + (derived ? " derived" : ""),
        title: derived ? "Extracted from the text at migration — not yet curator-confirmed" : "",
        text: citeLabel(c)
      }));
    });
    return wrap;
  }
  function field(labelText, control) {
    return el("div", { class: "gx-fld" }, [el("label", { text: labelText }), control]);
  }
  function textInput(ph) { return el("input", { type: "text", placeholder: ph || "" }); }
  function selectOf(values, labels) {
    var s = el("select");
    values.forEach(function (v, i) { s.appendChild(el("option", { value: v, text: (labels && labels[i]) || v })); });
    return s;
  }

  // ── state ───────────────────────────────────────────────────────────────────
  var state = { areas: [], areaId: null, revisions: [], artifacts: [], filters: null };

  function loadAreas() {
    return getJson(REST + "/gr_areas?select=*&status=eq.active&order=sort.asc,title.asc");
  }
  function loadArea(id) {
    return Promise.all([
      getJson(REST + "/gr_revisions?select=*&area_id=eq." + encodeURIComponent(id) + "&order=n.asc"),
      getJson(REST + "/gr_artifacts?select=*&area_id=eq." + encodeURIComponent(id) + "&order=created_at.desc")
    ]);
  }

  // ── THE CROSS-AREA SECTION INDEX ────────────────────────────────────────────
  // The reason a General Counsel wants a register rather than a folder of Word
  // docs: once citations are DATA across every priority area, a section that two
  // areas both propose to touch becomes visible BEFORE rulemaking, not during
  // it. Dual enrollment, CPL, SCFF and baccalaureate teams all edit overlapping
  // parts of Title 5, and today nobody sees the collision until OAL. This is
  // computed from what is stored — it invents nothing.
  function collisions(rows) {
    var by = {};
    (rows || []).forEach(function (r) {
      (r.citations || []).forEach(function (c) {
        (by[c] = by[c] || {})[r.area_id] = true;
      });
    });
    return Object.keys(by).map(function (c) {
      return { cite: c, areas: Object.keys(by[c]).sort() };
    }).filter(function (x) { return x.areas.length > 1; })
      .sort(function (a, b) { return b.areas.length - a.areas.length || a.cite.localeCompare(b.cite); });
  }

  function renderCollisions(host, all, areaTitles) {
    var hits = collisions(all);
    var sec = el("div", { class: "gx-arts" });
    sec.appendChild(el("h3", { text: "Sections touched by more than one priority area" }));
    if (!hits.length) {
      sec.appendChild(el("p", { class: "gx-note",
        text: "No section is currently cited by two areas. This list fills in as more areas are added — it is what surfaces a conflict before rulemaking rather than during it." }));
    } else {
      hits.forEach(function (h) {
        var d = el("div", { class: "gx-art" });
        d.appendChild(el("div", { class: "t" }, [
          el("span", { class: "gx-cite", text: citeLabel(h.cite) }),
          document.createTextNode("  " + h.areas.length + " areas")
        ]));
        d.appendChild(el("div", { class: "m",
          text: h.areas.map(function (a) { return areaTitles[a] || a; }).join("  ·  ") }));
        sec.appendChild(d);
      });
    }
    host.appendChild(sec);
  }

  // ── revisions list + filtering ──────────────────────────────────────────────
  function matches(r, f) {
    if (f.path !== "all" && (r.pathway || []).indexOf(f.path) === -1) return false;
    if (f.status !== "all" && r.status !== f.status) return false;
    if (f.cite !== "all" && (r.citations || []).indexOf(f.cite) === -1) return false;
    if (f.q) {
      var hay = [r.title, r.summary, r.consideration, r.instrument, r.grp]
        .concat(r.citations || []).join(" ").toLowerCase();
      if (hay.indexOf(f.q) === -1) return false;
    }
    return true;
  }

  function revisionRow(r) {
    var prim = (r.pathway && r.pathway[0]) || "y";
    var d = el("details", { class: "gx-item" });
    d.style.setProperty("--bd", "var(--gx-" + prim + ")");
    d._rev = r;
    var sm = el("span", { class: "gx-sm" }, [
      pathChips(r.pathway),
      citeChips(r.citations, r.citations_derived),
      el("span", { class: "gx-st", text: stLabel(r.status) })
    ]);
    d.appendChild(el("summary", null, [
      el("span", { class: "gx-num", text: r.n == null ? "" : String(r.n) }),
      el("span", { class: "gx-ttl", text: r.title || "" }),
      sm
    ]));
    var desc = el("div", { class: "gx-desc" });
    if (r.summary) appendRich(desc, r.summary);
    if (r.consideration) {
      var c = el("p");
      c.appendChild(el("b", { text: "Consideration: " }));
      appendRich(c, r.consideration);
      desc.appendChild(c);
    }
    var bits = [];
    if (r.instrument) bits.push(r.instrument);
    if (r.ed_first) bits.push("Ed. Code change first? " + r.ed_first);
    if (r.updated_by) bits.push("entered by " + r.updated_by);
    if (r.citations_derived && (r.citations || []).length) {
      bits.push("citations extracted from the text — not curator-confirmed");
    }
    if (bits.length) desc.appendChild(el("p", { class: "gx-meta", text: bits.join("  ·  ") }));
    d.appendChild(desc);
    return d;
  }

  // ── add-forms (reviewer only) ───────────────────────────────────────────────
  function formShell(title, note) {
    var f = el("div", { class: "gx-form" });
    f.appendChild(el("h4", { text: title }));
    if (note) f.appendChild(el("p", { class: "gx-note", text: note }));
    return f;
  }
  function wireSubmit(form, btn, build, table, after) {
    var err = el("p", { class: "gx-err", text: "" });
    form.appendChild(err);
    btn.addEventListener("click", function () {
      var rec;
      try { rec = build(); } catch (e) { err.className = "gx-err"; err.textContent = e.message; return; }
      if (!rec) return;
      btn.disabled = true; err.className = "gx-err"; err.textContent = "";
      post(table, rec).then(function (row) {
        btn.disabled = false;
        err.className = "gx-ok"; err.textContent = "Saved.";
        after(row);
      }).catch(function (e) {
        btn.disabled = false; err.className = "gx-err"; err.textContent = e.message;
      });
    });
  }

  function newAreaForm(onSaved) {
    var f = formShell("Add a priority area",
      "One row per Chancellor's Office priority area. Until the authoritative list is loaded, type the title you want.");
    var title = textInput("e.g. CCC Baccalaureate");
    var division = textInput("Chancellor's Office division (optional)");
    var summary = textInput("One line on what this area covers (optional)");
    f.appendChild(field("Priority area title", title));
    var row = el("div", { class: "gx-frow" }, [field("CO division", division), field("Summary", summary)]);
    f.appendChild(row);
    var btn = el("button", { class: "gx-btn", type: "button", text: "Add area" });
    f.appendChild(btn);
    wireSubmit(f, btn, function () {
      var t = title.value.trim();
      if (!t) throw new Error("Give the area a title.");
      var slug = t.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48);
      if (!slug) throw new Error("That title has no letters or numbers in it.");
      return {
        id: slug, title: t, division: division.value.trim() || null,
        summary: summary.value.trim() || null, sort: 99,
        created_by: whoami(), updated_by: whoami()
      };
    }, "gr_areas", function (row) { title.value = division.value = summary.value = ""; onSaved(row); });
    return f;
  }

  function newRevisionForm(areaId, nextN, onSaved) {
    var f = formShell("Add a revision under consideration",
      "Citations become filterable the moment they are entered — type them as 55050, T5 §55050 or EC §76004.");
    var title = textInput("What is under consideration");
    var grp = textInput("Grouping label (optional)");
    var summary = el("textarea", { placeholder: "Why it matters / what the review would ask" });
    var consid = textInput("Consideration (optional)");
    var cites = textInput("55050, EC §76004");
    var status = selectOf(STATUSES, STATUSES.map(stLabel));
    var edf = selectOf(["", "Yes", "Split", "No"], ["Ed. Code first? —", "Yes", "Split", "No"]);
    var paths = ["g", "y", "r"].map(function (p) {
      return el("button", { class: "gx-chip f" + p, type: "button", "data-p": p, "aria-pressed": "false" },
        [el("span", { class: "sw" }), TLBL[p]]);
    });
    paths.forEach(function (b) {
      b.addEventListener("click", function () {
        b.setAttribute("aria-pressed", b.getAttribute("aria-pressed") === "true" ? "false" : "true");
      });
    });
    f.appendChild(field("Title", title));
    f.appendChild(field("Summary", summary));
    f.appendChild(el("div", { class: "gx-frow" }, [field("Grouping", grp), field("Consideration", consid)]));
    f.appendChild(el("div", { class: "gx-frow" }, [
      field("Citations", cites), field("Status", status), field("Ed. Code first?", edf)]));
    f.appendChild(field("Pathway", el("div", { class: "gx-sm" }, paths)));
    var btn = el("button", { class: "gx-btn", type: "button", text: "Add revision" });
    f.appendChild(btn);
    wireSubmit(f, btn, function () {
      var t = title.value.trim();
      if (!t) throw new Error("Give the revision a title.");
      var parsed = parseCites(cites.value);
      if (parsed.bad.length) {
        throw new Error("Could not place these under a known code — write them as T5 §55050 or EC §76004: " + parsed.bad.join(", "));
      }
      var chosen = paths.filter(function (b) { return b.getAttribute("aria-pressed") === "true"; })
                        .map(function (b) { return b.getAttribute("data-p"); });
      return {
        area_id: areaId, n: nextN, title: t, grp: grp.value.trim() || null,
        summary: summary.value.trim() || null, consideration: consid.value.trim() || null,
        pathway: chosen, citations: parsed.ok, citations_derived: false,
        ed_first: edf.value || null, status: status.value,
        created_by: whoami(), updated_by: whoami()
      };
    }, "gr_revisions", function (row) {
      title.value = grp.value = consid.value = cites.value = ""; summary.value = "";
      paths.forEach(function (b) { b.setAttribute("aria-pressed", "false"); });
      onSaved(row);
    });
    return f;
  }

  function newArtifactForm(areaId, onSaved) {
    var f = formShell("Add an artifact to the knowledge base",
      "A source document that informs these revisions — a guidance memo, a regulation, a legal opinion, a comment letter. The register records WHAT it is and WHY it matters; nothing is analysed automatically.");
    var title = textInput("Document title");
    var url = textInput("https://…");
    var kind = selectOf(["memo", "regulation", "statute", "opinion", "letter", "report", "other"]);
    var source = textInput("Issuing body");
    var division = textInput("CO division (optional)");
    var cites = textInput("Sections it governs, e.g. T5 §55050");
    var why = el("textarea", { placeholder: "Why this matters to the revisions under consideration" });
    f.appendChild(field("Title", title));
    f.appendChild(el("div", { class: "gx-frow" }, [field("Link", url), field("Kind", kind)]));
    f.appendChild(el("div", { class: "gx-frow" }, [
      field("Source", source), field("CO division", division), field("Citations", cites)]));
    f.appendChild(field("Why it matters", why));
    var btn = el("button", { class: "gx-btn", type: "button", text: "Add artifact" });
    f.appendChild(btn);
    wireSubmit(f, btn, function () {
      var t = title.value.trim();
      if (!t) throw new Error("Give the artifact a title.");
      var u = url.value.trim();
      if (u && !/^https:\/\//i.test(u)) throw new Error("Links must start with https://");
      var parsed = parseCites(cites.value);
      if (parsed.bad.length) throw new Error("Could not place these citations: " + parsed.bad.join(", "));
      return {
        area_id: areaId, title: t, url: u || null, kind: kind.value,
        source: source.value.trim() || null, division: division.value.trim() || null,
        citations: parsed.ok, why: why.value.trim() || null, added_by: whoami()
      };
    }, "gr_artifacts", function (row) {
      title.value = url.value = source.value = division.value = cites.value = ""; why.value = "";
      onSaved(row);
    });
    return f;
  }

  // ── main render ─────────────────────────────────────────────────────────────
  function renderRegister(root, allRevisions) {
    clear(root);
    var area = null;
    state.areas.forEach(function (a) { if (a.id === state.areaId) area = a; });
    var wrap = el("div", { class: "grx" });
    var nar = (area && area.narrative) || {};
    var isSample = /^SAMPLE AREA/i.test((area && area.summary) || "");

    // masthead
    var head = el("div", { class: "gx-head" });
    head.appendChild(el("div", { class: "gx-eyebrow", text: nar.eyebrow || "Government Relations · policy & regulation review" }));
    var h2 = el("h2", { class: "gx-title" }, [document.createTextNode((area && area.title) || "GR register")]);
    if (isSample) h2.appendChild(el("span", { class: "gx-samp", text: "Sample" }));
    head.appendChild(h2);
    if (area && area.division) head.appendChild(el("p", { class: "gx-sub", text: area.division }));
    if (area && area.summary) head.appendChild(el("p", { class: "gx-sub", text: area.summary }));
    if (nar.thesis) head.appendChild(richP(nar.thesis, "gx-thesis"));
    wrap.appendChild(head);

    // area picker
    var bar = el("div", { class: "gx-areabar" });
    bar.appendChild(el("label", { for: "gx-area", text: "Priority area" }));
    var sel = el("select", { id: "gx-area" });
    state.areas.forEach(function (a) {
      var o = el("option", { value: a.id, text: a.title });
      if (a.id === state.areaId) o.setAttribute("selected", "selected");
      sel.appendChild(o);
    });
    sel.addEventListener("change", function () { state.areaId = sel.value; load(root); });
    bar.appendChild(sel);
    var addAreaBtn = null;
    if (canWrite()) {
      addAreaBtn = el("button", { class: "gx-btn ghost", type: "button", text: "New area" });
      bar.appendChild(addAreaBtn);
    } else {
      bar.appendChild(el("span", { class: "gx-note", text: "Sign in to add areas, revisions or artifacts." }));
    }
    wrap.appendChild(bar);
    var areaFormHost = el("div");
    wrap.appendChild(areaFormHost);
    if (addAreaBtn) {
      addAreaBtn.addEventListener("click", function () {
        if (areaFormHost.firstChild) { clear(areaFormHost); return; }
        areaFormHost.appendChild(newAreaForm(function (row) {
          state.areas.push(row); state.areaId = row.id; load(root);
        }));
      });
    }

    // toolbar
    var f = { q: "", path: "all", status: "all", cite: "all" };
    state.filters = f;
    var tools = el("div", { class: "gx-tools" });
    var search = el("input", { type: "text", class: "gx-search", placeholder: "Search titles, text, citations…", "aria-label": "Search revisions" });
    tools.appendChild(search);
    var chips = [
      el("button", { class: "gx-chip", "data-f": "all", "aria-pressed": "true", text: "All" }),
      el("button", { class: "gx-chip fg", "data-f": "g", "aria-pressed": "false" }, [el("span", { class: "sw" }), "Guidance"]),
      el("button", { class: "gx-chip fy", "data-f": "y", "aria-pressed": "false" }, [el("span", { class: "sw" }), "Title 5"]),
      el("button", { class: "gx-chip fr", "data-f": "r", "aria-pressed": "false" }, [el("span", { class: "sw" }), "Ed. Code"])
    ];
    chips.forEach(function (c) { tools.appendChild(c); });

    // Section dropdowns are built from what is ACTUALLY cited in this area, so a
    // section nobody has cited never appears as an empty option.
    var present = {};
    state.revisions.forEach(function (r) { (r.citations || []).forEach(function (c) { present[c] = true; }); });
    var allCites = Object.keys(present).sort();
    ["T5", "EC", "GC"].forEach(function (code) {
      var mine = allCites.filter(function (c) { return citeCode(c) === code; });
      if (!mine.length) return;
      var s = selectOf(["all"].concat(mine),
        [CODES[code] + " — any"].concat(mine.map(function (c) { return "§" + c.split("§")[1]; })));
      s.setAttribute("aria-label", CODES[code] + " section");
      s.addEventListener("change", function () {
        f.cite = s.value;
        // one section filter at a time — the other dropdowns reset to "any"
        secSelects.forEach(function (o) { if (o !== s) o.value = "all"; });
        apply();
      });
      tools.appendChild(s);
      secSelects.push(s);
    });
    var stSel = selectOf(["all"].concat(STATUSES), ["Any status"].concat(STATUSES.map(stLabel)));
    stSel.setAttribute("aria-label", "Status");
    tools.appendChild(stSel);
    tools.appendChild(el("span", { class: "sp" }));
    var count = el("span", { class: "gx-count", text: "" });
    tools.appendChild(count);
    var clearBtn = el("button", { class: "gx-chip", type: "button", text: "Clear" });
    tools.appendChild(clearBtn);
    var wordBtn = el("button", { class: "gx-btn ghost", type: "button", text: "⬇ Word" });
    tools.appendChild(wordBtn);
    wrap.appendChild(tools);

    // rows
    var listHost = el("div");
    wrap.appendChild(listHost);
    var rowEls = state.revisions.map(revisionRow);
    var groups = {};
    rowEls.forEach(function (d) {
      var g = d._rev.grp || "";
      if (!groups[g]) {
        var gd = el("div", { class: "gx-grp" });
        if (g) gd.appendChild(el("div", { class: "gx-grph" }, [el("h3", { text: g })]));
        groups[g] = gd;
        listHost.appendChild(gd);
      }
      groups[g].appendChild(d);
    });
    var empty = el("div", { class: "gx-empty", text: "No revision matches these filters." });
    empty.hidden = true;
    listHost.appendChild(empty);

    function apply() {
      var shown = 0;
      rowEls.forEach(function (d) {
        var ok = matches(d._rev, f);
        d.hidden = !ok;
        if (ok) shown++;
      });
      Object.keys(groups).forEach(function (g) {
        var any = Array.prototype.some.call(groups[g].querySelectorAll(".gx-item"), function (r) { return !r.hidden; });
        groups[g].style.display = any ? "" : "none";
      });
      empty.hidden = shown !== 0;
      count.textContent = shown === state.revisions.length
        ? shown + (shown === 1 ? " revision" : " revisions")
        : "showing " + shown + " of " + state.revisions.length;
    }
    search.addEventListener("input", function () { f.q = search.value.trim().toLowerCase(); apply(); });
    chips.forEach(function (c) {
      c.addEventListener("click", function () {
        f.path = c.getAttribute("data-f");
        chips.forEach(function (o) { o.setAttribute("aria-pressed", o === c ? "true" : "false"); });
        apply();
      });
    });
    stSel.addEventListener("change", function () { f.status = stSel.value; apply(); });
    clearBtn.addEventListener("click", function () {
      f.q = ""; f.path = "all"; f.status = "all"; f.cite = "all";
      search.value = ""; stSel.value = "all";
      secSelects.forEach(function (s) { s.value = "all"; });
      chips.forEach(function (o) { o.setAttribute("aria-pressed", o.getAttribute("data-f") === "all" ? "true" : "false"); });
      apply();
    });
    // The export reads the RENDERED, FILTERED rows — never a second list that
    // could drift from the screen (the Sky167 lesson; the briefing this replaced
    // kept a separate 13-item array beside a 16-row screen, cross-linked by
    // hand-written "#7" strings that nothing validated).
    wordBtn.addEventListener("click", function () {
      draftWord(area, rowEls.filter(function (d) { return !d.hidden; }).map(function (d) { return d._rev; }));
    });

    // add-revision
    if (canWrite()) {
      var revHost = el("div");
      var addRev = el("button", { class: "gx-btn ghost", type: "button", text: "Add a revision" });
      addRev.addEventListener("click", function () {
        if (revHost.firstChild) { clear(revHost); return; }
        var nextN = state.revisions.reduce(function (m, r) { return Math.max(m, r.n || 0); }, 0) + 1;
        revHost.appendChild(newRevisionForm(state.areaId, nextN, function () { load(root); }));
      });
      wrap.appendChild(el("div", { class: "gx-areabar" }, [addRev]));
      wrap.appendChild(revHost);
    }

    // artifacts
    var arts = el("div", { class: "gx-arts" });
    arts.appendChild(el("h3", { text: "Knowledge base — artifacts informing this area" }));
    if (!state.artifacts.length) {
      arts.appendChild(el("p", { class: "gx-note", text: "No artifacts recorded for this area yet." }));
    }
    state.artifacts.forEach(function (a) {
      var d = el("div", { class: "gx-art" });
      var t = el("div", { class: "t" });
      if (a.kind) t.appendChild(el("span", { class: "gx-kind", text: a.kind }));
      if (a.url && /^https:\/\//i.test(a.url)) {
        t.appendChild(el("a", { href: a.url, target: "_blank", rel: "noopener", text: a.title }));
      } else {
        t.appendChild(document.createTextNode(a.title || ""));
      }
      d.appendChild(t);
      var m = [a.source, a.division, a.doc_date].filter(Boolean).join("  ·  ");
      if (m) d.appendChild(el("div", { class: "m", text: m }));
      if ((a.citations || []).length) d.appendChild(citeChips(a.citations, false));
      if (a.why) d.appendChild(el("div", { class: "w", text: a.why }));
      if (a.added_by) d.appendChild(el("div", { class: "m", text: "added by " + a.added_by }));
      arts.appendChild(d);
    });
    if (canWrite()) {
      var artHost = el("div");
      var addArt = el("button", { class: "gx-btn ghost", type: "button", text: "Add an artifact" });
      addArt.addEventListener("click", function () {
        if (artHost.firstChild) { clear(artHost); return; }
        artHost.appendChild(newArtifactForm(state.areaId, function () { load(root); }));
      });
      arts.appendChild(addArt);
      arts.appendChild(artHost);
    }
    wrap.appendChild(arts);

    // cross-area collisions
    var titles = {};
    state.areas.forEach(function (a) { titles[a.id] = a.title; });
    renderCollisions(wrap, allRevisions || state.revisions, titles);

    root.appendChild(wrap);
    apply();
  }
  var secSelects = [];

  // ── Word export — built from the rows on screen ─────────────────────────────
  function docBody(area, rows) {
    var tl = { g: ["#4c6b54", "Guidance"], y: ["#84692b", "Title 5"], r: ["#8b4a3d", "Ed. Code"] };
    function tag(t) {
      return (t || []).map(function (x) {
        var v = tl[x] || ["#666", x];
        return '<span style="color:' + v[0] + ';font-weight:bold;font-size:8.5pt">' + v[1].toUpperCase() + "</span>";
      }).join(' <span style="color:#aaa">&#8594;</span> ');
    }
    function esc(s) {
      return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    }
    var items = (rows || []).map(function (r) {
      var cites = (r.citations || []).map(citeLabel).join(", ");
      return '<div style="margin:0 0 12pt 0">' +
        '<p style="margin:0 0 2pt 0;font-family:Georgia,serif;font-size:13pt;color:#23252b"><b>' +
          (r.n == null ? "" : r.n + ". ") + esc(r.title) + "</b> &nbsp; " + tag(r.pathway) +
          (cites ? ' &nbsp; <span style="color:#99a;font-size:8.5pt">' + esc(cites) + "</span>" : "") + "</p>" +
        (r.summary ? '<p style="margin:0 0 2pt 0;font-size:10.5pt;line-height:1.35;color:#23252b">' + esc(r.summary) + "</p>" : "") +
        '<p style="margin:0;font-size:9.5pt;color:#555"><b>Status:</b> ' + esc(stLabel(r.status)) +
          (r.ed_first ? " &nbsp;&#183;&nbsp; <b>Ed. Code change first?</b> " + esc(r.ed_first) : "") +
          (r.consideration ? " &nbsp;&#183;&nbsp; " + esc(r.consideration) : "") + "</p></div>";
    }).join("");
    var nar = (area && area.narrative) || {};
    return '<p style="font-family:Georgia,serif;font-size:22pt;font-weight:bold;margin:0 0 2pt 0;color:#23252b">' +
        esc((area && area.title) || "GR register") + "</p>" +
      '<p style="font-size:11pt;color:#555;margin:0">Policy &amp; regulation review &#183; ' +
        (rows || []).length + " entr" + ((rows || []).length === 1 ? "y" : "ies") +
        " &#183; for the Chancellor&rsquo;s Office</p>" +
      '<hr style="border:none;border-top:2px solid #3d4a60;margin:8pt 0 12pt 0">' +
      (nar.thesis ? '<p style="font-size:11pt;line-height:1.4;color:#23252b;margin:0 0 10pt 0">' +
        String(nar.thesis).replace(/<[^>]*>/g, "") + "</p>" : "") +
      '<p style="font-size:9.5pt;color:#444;margin:0 0 14pt 0;padding:6pt 10pt;background:#eeeee9;border-left:3px solid #3d4a60">' +
        "<b>Guidance</b> = a Chancellor&rsquo;s Office memo &#183; <b>Title 5</b> = Board of Governors rulemaking &#183; " +
        "<b>Ed. Code</b> = statutory amendment.</p>" +
      items +
      '<p style="font-size:9pt;color:#777;margin:12pt 0 0"><i>Exported from the COBI GR register. ' +
        "This file reflects the rows and filters shown on screen at export time.</i></p>";
  }
  function draftWord(area, rows) {
    var html = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>GR register</title></head><body style="font-family:Calibri,Arial,sans-serif;color:#23252b;margin:0.6in">' + docBody(area, rows) + "</body></html>";
    var slug = String((area && area.id) || "gr").replace(/[^a-z0-9]+/gi, "_");
    var fn = "GR_Register_" + slug + ".doc";
    try {
      var blob = new Blob(["﻿" + html], { type: "application/msword" });
      var url = URL.createObjectURL(blob);
      var a = el("a", { href: url, download: fn });
      document.body.appendChild(a); a.click();
      setTimeout(function () { URL.revokeObjectURL(url); if (a.parentNode) a.parentNode.removeChild(a); }, 1500);
    } catch (e) {
      var a2 = el("a", { href: "data:application/msword;charset=utf-8," + encodeURIComponent("﻿" + html), download: fn });
      document.body.appendChild(a2); a2.click(); if (a2.parentNode) a2.parentNode.removeChild(a2);
    }
  }

  // ── lock screen ─────────────────────────────────────────────────────────────
  function renderLock(root, errMsg) {
    clear(root);
    var wrap = el("div", { class: "grx" });
    var card = el("div", { class: "gx-lock" });
    card.appendChild(el("div", { class: "lk", text: "MAP Government Relations — internal" }));
    card.appendChild(el("p", { text: "Pre-decisional policy and regulation material for the MAP team. Enter the MAP-team phrase to view. Content is served only after the phrase is verified — it is not present on this page otherwise." }));
    var input = el("input", { type: "password", placeholder: "MAP-team phrase…", autocomplete: "off", "aria-label": "MAP team phrase" });
    var btn = el("button", { type: "button", text: "View register" });
    var err = el("p", { class: "err", text: errMsg || "" });
    function go() {
      err.textContent = ""; btn.disabled = true;
      verify(input.value.trim()).then(function (ok) {
        btn.disabled = false;
        if (ok === true) { setPass(input.value.trim()); input.value = ""; load(root); }
        else if (ok === null) { err.textContent = "Couldn't reach the server — try again in a moment."; }
        else { err.textContent = "That phrase doesn't match — check with the MAP team."; }
      });
    }
    btn.addEventListener("click", go);
    input.addEventListener("keydown", function (e) { if (e.key === "Enter") { e.preventDefault(); go(); } });
    card.appendChild(el("div", { class: "row" }, [input, btn]));
    card.appendChild(err);
    wrap.appendChild(card);
    root.appendChild(wrap);
    if (input.focus) try { input.focus(); } catch (e) { /* ignore */ }
  }

  // ── load ────────────────────────────────────────────────────────────────────
  function load(root) {
    if (!getPass() && !canWrite()) { renderLock(root); return Promise.resolve(); }
    secSelects = [];
    return loadAreas().then(function (areas) {
      // An RLS-filtered read answers 200 with an EMPTY array, never 403 — so a
      // null (transport failure) and an empty list are DIFFERENT states and must
      // not render the same way.
      if (areas === null) { clearPass(); renderLock(root, "Couldn't read the register — the phrase may have been rotated."); return; }
      state.areas = areas;
      if (!areas.length) {
        clear(root);
        var w = el("div", { class: "grx" });
        w.appendChild(el("div", { class: "gx-empty", text: "No priority areas are visible to you yet." }));
        root.appendChild(w);
        return;
      }
      if (!state.areaId || !areas.some(function (a) { return a.id === state.areaId; })) {
        state.areaId = areas[0].id;
      }
      return Promise.all([
        loadArea(state.areaId),
        getJson(REST + "/gr_revisions?select=area_id,citations")   // for the cross-area index
      ]).then(function (res) {
        state.revisions = (res[0] && res[0][0]) || [];
        state.artifacts = (res[0] && res[0][1]) || [];
        renderRegister(root, res[1] || []);
      });
    });
  }

  function activate() {
    ensureCss();
    var root = document.getElementById(ROOT_ID);
    if (!root) return;
    load(root);
  }

  var api = {
    activate: activate,
    _appendRich: appendRich,
    _parseCites: parseCites,
    _citeLabel: citeLabel,
    _collisions: collisions,
    _matches: matches,
    _renderRegister: renderRegister,
    _draftDocBody: docBody,
    _state: state
  };
  if (typeof window !== "undefined") window.CPL_GR = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})();
