/* KPI card reorder — login-free drag-to-rearrange for the headline KPI grid.
 *
 * Built for grabbing audience-tailored screenshots: drag cards into the order
 * a presentation needs, screenshot, done. The order persists per-browser in
 * localStorage until someone reorders again (or clicks "Reset card order").
 * No auth, no backend, no shared state — each viewer's browser keeps its own
 * arrangement; the curated default order (generator kpi_display_order) is
 * untouched for everyone else.
 *
 * Static asset: NOT regenerated by excel_to_dashboard.py. The KPI section
 * markup IS regenerated daily, so cards are re-matched by their .kpi-label
 * text on every load — a renamed or removed card simply falls back to its
 * default spot, and a brand-new card re-enters at its default position
 * (never buried at the end). Desktop-only (HTML5 drag and drop); touch
 * devices keep the default order.
 */
(function () {
  "use strict";

  var KEY = "cplKpiOrder.v1";
  var GRID_SEL = ".kpi-section";

  function norm(s) {
    return (s || "").replace(/\s+/g, " ").trim().toLowerCase();
  }

  // Stable identity for a card across daily regens: its label text.
  // Falls back to a heading, then to a positional key.
  function cardKey(card, i) {
    var el = card.querySelector(".kpi-label") || card.querySelector("h1,h2,h3,h4");
    return norm(el ? el.textContent : "") || "pos" + i;
  }

  function currentOrder(grid) {
    return Array.prototype.map.call(grid.children, cardKey);
  }

  function readSaved() {
    try {
      var v = JSON.parse(window.localStorage.getItem(KEY));
      return Array.isArray(v) && v.length ? v : null;
    } catch (e) { return null; }
  }

  function writeSaved(order) {
    try { window.localStorage.setItem(KEY, JSON.stringify(order)); } catch (e) {}
  }

  function clearSaved() {
    try { window.localStorage.removeItem(KEY); } catch (e) {}
  }

  // Reorder the grid's children to `order` (array of card keys). Cards not
  // named in `order` (e.g. a card added after the order was saved) re-enter
  // at their current default index so additions stay visible.
  function applyOrder(grid, order) {
    var nodes = Array.prototype.slice.call(grid.children);
    var byKey = {}, unknown = [];
    nodes.forEach(function (n, i) {
      var k = cardKey(n, i);
      if (order.indexOf(k) !== -1 && !byKey[k]) byKey[k] = n;
      else unknown.push({ node: n, idx: i });
    });
    var ordered = [];
    order.forEach(function (k) { if (byKey[k]) ordered.push(byKey[k]); });
    unknown.forEach(function (u) {
      ordered.splice(Math.min(u.idx, ordered.length), 0, u.node);
    });
    ordered.forEach(function (n) { grid.appendChild(n); });
  }

  function ensureCss() {
    if (document.getElementById("kpi-reorder-css")) return;
    var st = document.createElement("style");
    st.id = "kpi-reorder-css";
    st.textContent =
      GRID_SEL + " > [draggable=true] { cursor: grab; }\n" +
      GRID_SEL + " > .kpi-drag-src { opacity: 0.45; }\n" +
      ".kpi-reorder-reset { text-align: right; padding: 0.2rem 2rem 0.6rem; " +
      "background: #ffffff; margin-top: -1px; }\n" +
      ".kpi-reorder-reset button { background: none; border: none; cursor: pointer; " +
      "font-size: 0.72rem; color: var(--navy-primary, #1C1C1A); opacity: 0.65; " +
      "text-decoration: underline; padding: 0; }\n" +
      ".kpi-reorder-reset button:hover { opacity: 1; }";
    document.head.appendChild(st);
  }

  // Reading-order insertion point for a pointer position in a wrapped grid:
  // the first non-dragged card that is on a later row, or on the pointer's
  // row with its midpoint right of the pointer. null = append at end.
  function insertionPoint(grid, x, y, dragging) {
    var els = Array.prototype.filter.call(grid.children, function (c) {
      return c !== dragging;
    });
    for (var i = 0; i < els.length; i++) {
      var r = els[i].getBoundingClientRect();
      var sameRow = y >= r.top && y <= r.bottom;
      if (y < r.top || (sameRow && x < r.left + r.width / 2)) return els[i];
    }
    return null;
  }

  function init() {
    var grid = document.querySelector(GRID_SEL);
    if (!grid || !grid.children.length) return;
    if (document.querySelector(".kpi-reorder-reset")) return; // already wired
    ensureCss();

    var defaultOrder = currentOrder(grid);
    var saved = readSaved();
    if (saved) applyOrder(grid, saved);

    // Reset affordance — only visible while a custom order is saved.
    var reset = document.createElement("div");
    reset.className = "kpi-reorder-reset";
    reset.innerHTML = "<button type=\"button\" title=\"Restore the default card order\">↺ Reset card order</button>";
    reset.style.display = saved ? "" : "none";
    grid.insertAdjacentElement("afterend", reset);
    reset.firstChild.addEventListener("click", function () {
      clearSaved();
      applyOrder(grid, defaultOrder);
      reset.style.display = "none";
    });

    var dragging = null;
    Array.prototype.forEach.call(grid.children, function (card) {
      card.setAttribute("draggable", "true");
      if (!card.title) card.title = "Drag to reorder · the order is saved in this browser";
    });
    grid.addEventListener("dragstart", function (e) {
      var card = e.target;
      while (card && card.parentNode !== grid) card = card.parentNode;
      if (!card || card === grid) return;
      dragging = card;
      card.classList.add("kpi-drag-src");
      try {
        e.dataTransfer.setData("text/plain", "");
        e.dataTransfer.effectAllowed = "move";
      } catch (err) {}
    });
    grid.addEventListener("dragover", function (e) {
      if (!dragging) return;
      e.preventDefault();
      try { e.dataTransfer.dropEffect = "move"; } catch (err) {}
      var before = insertionPoint(grid, e.clientX, e.clientY, dragging);
      if (before !== dragging && before !== dragging.nextSibling) {
        grid.insertBefore(dragging, before);
      }
    });
    grid.addEventListener("drop", function (e) { e.preventDefault(); });
    grid.addEventListener("dragend", function () {
      if (!dragging) return;
      dragging.classList.remove("kpi-drag-src");
      dragging = null;
      writeSaved(currentOrder(grid));
      reset.style.display = "";
    });
  }

  // Exposed for tests (jsdom can't simulate layout-dependent drag geometry,
  // so the persistence/apply/reset core is testable directly).
  window.CPL_KPI_REORDER = {
    KEY: KEY,
    cardKey: cardKey,
    currentOrder: currentOrder,
    applyOrder: applyOrder,
    readSaved: readSaved,
    writeSaved: writeSaved,
    clearSaved: clearSaved,
    init: init
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
