/* KPI card shelf — per-browser HIDE + centered title row + per-card COLLAPSE
 * for the headline KPI grid (.kpi-section). Three login-free presentation aids,
 * built on the same regen-safe pattern as kpi_reorder.js:
 *
 *   1. HIDE  — an × on each card removes it from the grid (per-browser). A
 *              "Hidden (N)" tray on the toolbar restores any/all of them.
 *   2. CENTER — the big metric (.kpi-number) + label (.kpi-label) become a
 *              centered "title row" (the always-visible head of the card).
 *   3. COLLAPSE — everything below the title row (breakdowns, footnote, "How
 *              this is calculated") is the collapsible body. Cards open
 *              COLLAPSED so only the title row (the top half) shows by default;
 *              click a card's head to expand it, or use the "Expand all /
 *              Collapse all" toolbar button to flip every card at once.
 *
 * STATIC asset — NOT regenerated by excel_to_dashboard.py. The KPI section
 * markup IS regenerated daily, so on every load we (re-)wrap each card's
 * head/body and re-apply saved state, re-matching cards by their .kpi-label
 * text (a renamed or brand-new card simply starts visible + collapsed at its
 * default spot). State lives per-browser in localStorage — no auth, no backend,
 * no shared state; the curated layout is untouched for everyone else.
 *
 * Operates ONLY on `.kpi-section > .kpi-card` (the headline KPIs). The
 * full-width KPI-Trends and College-Activity panels share the same grid but are
 * NOT .kpi-card, so they are left alone.
 *
 * Coexists with kpi_reorder.js: all controls live INSIDE each card so they ride
 * along on a drag-reorder; their clicks stopPropagation so a press never starts
 * a drag, and clicking a card's head toggles collapse (a drag suppresses the
 * click, so reorder still works).
 */
(function () {
  "use strict";

  var GRID_SEL = ".kpi-section";
  var CARD_SEL = ".kpi-card";
  var KEY = "cplKpiCards.v1"; // { hidden: [labelKey...], expanded: [labelKey...] }

  function norm(s) { return (s || "").replace(/\s+/g, " ").trim().toLowerCase(); }

  // Stable identity across daily regens: the card's .kpi-label text.
  function cardKey(card) {
    var el = card.querySelector(".kpi-label");
    return norm(el ? el.textContent : "");
  }

  function readState() {
    try {
      var v = JSON.parse(localStorage.getItem(KEY));
      if (v && typeof v === "object") {
        return {
          hidden: Array.isArray(v.hidden) ? v.hidden : [],
          expanded: Array.isArray(v.expanded) ? v.expanded : []
        };
      }
    } catch (e) {}
    return { hidden: [], expanded: [] };
  }
  function writeState(s) {
    try { localStorage.setItem(KEY, JSON.stringify(s)); } catch (e) {}
  }
  function without(arr, v) { return arr.filter(function (x) { return x !== v; }); }
  function withVal(arr, v) { return arr.indexOf(v) === -1 ? arr.concat([v]) : arr; }

  function ensureCss() {
    if (document.getElementById("kpi-cards-css")) return;
    var st = document.createElement("style");
    st.id = "kpi-cards-css";
    st.textContent = [
      CARD_SEL + ".kc-managed { position: relative; }",
      // Centered title row (head) — the metric + label, always visible.
      CARD_SEL + " .kc-head { text-align: center; cursor: pointer; padding: 0 1.1rem; }",
      CARD_SEL + " .kc-head .kpi-number { text-align: center; margin-bottom: 0.35rem; }",
      CARD_SEL + " .kc-head .kpi-label { text-align: center; }",
      CARD_SEL + " .kc-head:hover .kc-caret { opacity: 0.85; }",
      // The collapsible body (everything below the title row).
      CARD_SEL + " .kc-body { margin-top: 0.5rem; text-align: left; }",
      CARD_SEL + ".kc-collapsed > .kc-body { display: none; }",
      // Caret indicator (left corner) — rotates when collapsed.
      CARD_SEL + " .kc-caret { position: absolute; top: 0.55rem; left: 0.6rem; font-size: 0.6rem; "
        + "color: var(--text-muted, #5C5C55); opacity: 0; transition: opacity 0.15s ease, transform 0.2s ease; "
        + "pointer-events: none; }",
      CARD_SEL + ":hover .kc-caret { opacity: 0.6; }",
      CARD_SEL + ".kc-collapsed .kc-caret { transform: rotate(-90deg); }",
      // Hide × (right corner).
      CARD_SEL + " .kc-hide { position: absolute; top: 0.4rem; right: 0.5rem; background: none; border: none; "
        + "cursor: pointer; font-size: 0.95rem; line-height: 1; color: var(--text-muted, #5C5C55); "
        + "opacity: 0; transition: opacity 0.15s ease; padding: 2px 4px; border-radius: 4px; }",
      CARD_SEL + ":hover .kc-hide { opacity: 0.5; }",
      CARD_SEL + " .kc-hide:hover { opacity: 1; background: rgba(28,28,26,0.06); }",
      // Hidden card — removed from the grid.
      CARD_SEL + ".kc-hidden { display: none !important; }",
      // Toolbar (a thin bar above the grid).
      ".kc-bar { display: flex; gap: 0.5rem; align-items: center; justify-content: flex-end; "
        + "padding: 0 2rem 0.1rem; position: relative; flex-wrap: wrap; }",
      ".kpi-section-wrapper.collapsed .kc-bar { display: none; }",
      ".kc-bar button { background: var(--surface-opaque, #fff); border: 1px solid var(--border, rgba(28,28,26,.14)); "
        + "border-radius: 6px; cursor: pointer; font-size: 0.68rem; color: var(--navy-primary, #1C1C1A); "
        + "padding: 3px 9px; opacity: 0.85; }",
      ".kc-bar button:hover { opacity: 1; background: rgba(28,28,26,0.04); }",
      // Hidden-cards restore tray.
      ".kc-tray { position: absolute; top: 100%; right: 2rem; z-index: 50; margin-top: 4px; "
        + "background: var(--surface-opaque, #fff); border: 1px solid var(--border, rgba(28,28,26,.14)); "
        + "border-radius: 8px; box-shadow: 0 8px 30px rgba(20,20,30,0.12); padding: 0.5rem; "
        + "min-width: 220px; max-height: 50vh; overflow: auto; }",
      ".kc-tray-h { font-size: 0.66rem; text-transform: uppercase; letter-spacing: 0.05em; "
        + "color: var(--text-muted, #5C5C55); padding: 0.1rem 0.4rem 0.35rem; }",
      ".kc-tray-row { display: flex; align-items: center; justify-content: space-between; gap: 0.6rem; "
        + "padding: 0.25rem 0.4rem; border-radius: 5px; font-size: 0.78rem; color: var(--text-body, #2b2b27); }",
      ".kc-tray-row:hover { background: rgba(28,28,26,0.04); }",
      ".kc-tray-row button { font-size: 0.66rem; padding: 1px 7px; }",
      ".kc-tray-all { width: 100%; margin-top: 0.35rem; }"
    ].join("\n");
    document.head.appendChild(st);
  }

  // Wrap a card's children into a centered head (.kpi-number + .kpi-label) and a
  // collapsible body (everything else). Idempotent: skips an already-managed card.
  function manageCard(card) {
    if (card.classList.contains("kc-managed")) return;
    var num = card.querySelector(":scope > .kpi-number");
    var label = card.querySelector(":scope > .kpi-label");
    if (!num || !label) return; // not a standard KPI card — leave it alone

    var head = document.createElement("div");
    head.className = "kc-head";
    var body = document.createElement("div");
    body.className = "kc-body";

    // Snapshot the original direct children, then partition into head/body.
    var kids = Array.prototype.slice.call(card.children);
    kids.forEach(function (kid) {
      if (kid === num || kid === label) head.appendChild(kid);
      else body.appendChild(kid);
    });
    card.appendChild(head);
    card.appendChild(body);

    var caret = document.createElement("span");
    caret.className = "kc-caret";
    caret.setAttribute("aria-hidden", "true");
    caret.textContent = "▼"; // ▼
    card.appendChild(caret);

    var hide = document.createElement("button");
    hide.type = "button";
    hide.className = "kc-hide";
    hide.title = "Hide this card (this browser only — restore from “Hidden” above)";
    hide.setAttribute("aria-label", "Hide this card");
    hide.textContent = "×"; // ×
    card.appendChild(hide);

    card.classList.add("kc-managed");

    // Click the head → toggle collapse. (A drag-reorder suppresses the click, so
    // kpi_reorder.js keeps working.) Don't toggle when text is being selected.
    head.addEventListener("click", function () {
      if (window.getSelection && String(window.getSelection())) return;
      toggleCard(card);
    });
    hide.addEventListener("mousedown", function (e) { e.stopPropagation(); });
    hide.addEventListener("click", function (e) {
      e.stopPropagation();
      hideCard(card);
    });
  }

  function applyCardState(card, state) {
    var k = cardKey(card);
    card.classList.toggle("kc-hidden", state.hidden.indexOf(k) !== -1);
    // Default = collapsed (only the title row shows). Expanded only if saved so.
    card.classList.toggle("kc-collapsed", state.expanded.indexOf(k) === -1);
  }

  function toggleCard(card) {
    var k = cardKey(card);
    var state = readState();
    if (card.classList.contains("kc-collapsed")) {
      state.expanded = withVal(state.expanded, k);
      card.classList.remove("kc-collapsed");
    } else {
      state.expanded = without(state.expanded, k);
      card.classList.add("kc-collapsed");
    }
    writeState(state);
  }

  function hideCard(card) {
    var k = cardKey(card);
    var state = readState();
    state.hidden = withVal(state.hidden, k);
    writeState(state);
    card.classList.add("kc-hidden");
    refreshBar();
  }

  function cards(grid) {
    return Array.prototype.filter.call(
      grid.querySelectorAll(":scope > " + CARD_SEL),
      function () { return true; }
    );
  }

  // ── Toolbar: Expand all / Collapse all + Hidden (N) tray ──────────────────
  var grid = null, bar = null, tray = null;

  function allKeys() { return cards(grid).map(cardKey); }

  function setAll(expand) {
    var state = readState();
    state.expanded = expand ? allKeys().slice() : [];
    writeState(state);
    cards(grid).forEach(function (c) { c.classList.toggle("kc-collapsed", !expand); });
    refreshBar();
  }

  function restore(k) {
    var state = readState();
    state.hidden = without(state.hidden, k);
    writeState(state);
    cards(grid).forEach(function (c) {
      if (cardKey(c) === k) c.classList.remove("kc-hidden");
    });
    refreshBar();
  }

  function restoreAll() {
    var state = readState();
    state.hidden = [];
    writeState(state);
    cards(grid).forEach(function (c) { c.classList.remove("kc-hidden"); });
    refreshBar();
  }

  function cardLabelText(k) {
    var found = "";
    cards(grid).forEach(function (c) {
      if (cardKey(c) === k) {
        var el = c.querySelector(".kpi-label");
        found = el ? el.textContent.trim() : k;
      }
    });
    return found || k;
  }

  function closeTray() { if (tray) { tray.remove(); tray = null; } }

  function openTray() {
    closeTray();
    var state = readState();
    tray = document.createElement("div");
    tray.className = "kc-tray";
    var h = document.createElement("div");
    h.className = "kc-tray-h";
    h.textContent = "Hidden cards";
    tray.appendChild(h);
    state.hidden.forEach(function (k) {
      var row = document.createElement("div");
      row.className = "kc-tray-row";
      var name = document.createElement("span");
      name.textContent = cardLabelText(k);
      var b = document.createElement("button");
      b.type = "button"; b.textContent = "Restore";
      b.addEventListener("click", function () { restore(k); if (readState().hidden.length) openTray(); else closeTray(); });
      row.appendChild(name); row.appendChild(b);
      tray.appendChild(row);
    });
    var all = document.createElement("button");
    all.type = "button"; all.className = "kc-tray-all"; all.textContent = "Restore all";
    all.addEventListener("click", function () { restoreAll(); closeTray(); });
    tray.appendChild(all);
    bar.appendChild(tray);
  }

  function refreshBar() {
    if (!bar) return;
    var state = readState();
    var anyExpanded = cards(grid).some(function (c) {
      return !c.classList.contains("kc-hidden") && !c.classList.contains("kc-collapsed");
    });
    bar.innerHTML = "";
    var toggle = document.createElement("button");
    toggle.type = "button";
    toggle.textContent = anyExpanded ? "⊟ Collapse all" : "⊞ Expand all";
    toggle.title = anyExpanded ? "Collapse every KPI card to its title row" : "Expand every KPI card";
    toggle.addEventListener("click", function () { setAll(!anyExpanded); });
    bar.appendChild(toggle);

    if (state.hidden.length) {
      var hidBtn = document.createElement("button");
      hidBtn.type = "button";
      hidBtn.textContent = "▦ Hidden (" + state.hidden.length + ")";
      hidBtn.title = "Restore hidden KPI cards";
      hidBtn.addEventListener("click", function (e) {
        e.stopPropagation();
        if (tray) closeTray(); else openTray();
      });
      bar.appendChild(hidBtn);
    } else {
      closeTray();
    }
  }

  function init() {
    grid = document.querySelector(GRID_SEL);
    if (!grid) return;
    ensureCss();

    var state = readState();
    cards(grid).forEach(function (card) {
      manageCard(card);
      applyCardState(card, state);
    });

    // Toolbar above the grid (regen-safe: rebuilt each load).
    if (!grid.previousElementSibling || !grid.previousElementSibling.classList.contains("kc-bar")) {
      bar = document.createElement("div");
      bar.className = "kc-bar";
      grid.insertAdjacentElement("beforebegin", bar);
    } else {
      bar = grid.previousElementSibling;
    }
    refreshBar();

    // Close the tray on an outside click.
    document.addEventListener("click", function (e) {
      if (tray && bar && !bar.contains(e.target)) closeTray();
    });
  }

  // Exposed for tests (jsdom can run the core; drag geometry is kpi_reorder's).
  window.CPL_KPI_CARDS = {
    KEY: KEY,
    cardKey: cardKey,
    readState: readState,
    writeState: writeState,
    manageCard: manageCard,
    applyCardState: applyCardState,
    toggleCard: toggleCard,
    hideCard: hideCard,
    setAll: function (x) { return setAll(x); },
    restore: function (k) { return restore(k); },
    restoreAll: function () { return restoreAll(); },
    init: init
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
