// MAP Export tab — renderer.
//
// STATIC consumer asset (NOT regenerated by excel_to_dashboard.py), lazy-loaded
// by the inline boot in the tab shell on first activation of #tab-map-export.
//
// Purpose: Sam's colleague Malone is integrating the CER (Credential Reference)
// canonical credential layer into the new MAP Exhibit Module — MAP lacks a
// canonical layer under which all locally-determined exhibit titles hang. This
// tab renders EVERY canonical credential from the CER dataset
// (credential_reference_data.js ⊕ the live kb_curation curation overlay, so
// curated display titles / issuers are reflected) shaped to Malone's required
// "FullExhibitJSON" (sample committed verbatim for provenance at
// kb/reference/map_full_exhibit_sample.json) — viewable + downloadable, one
// record per unified_title, honest nulls where we hold no data.
//
// COBI EXTENSIONS (documented in the export's top-level _meta): `localVariants`
// (the raw college-entered exhibit-title variants collapsed under the canonical
// title — the whole point of the canonical layer) and `trainingAgency` are
// ADDITIVE fields not present in the MAP schema.
//
// Self-contained behind the CONFIG block (the cpl_news.js / map_users.js
// pattern). Scoped CSS injected from JS so both HTMLs are covered without a
// Rule-4 mirror. All DOM is built via createElement/textContent — no innerHTML
// with data (XSS safety; CodeQL js/xss).
(function () {
  "use strict";

  // ── Config (anon key is public + RLS-gated; mirrors credential_reference.js) ──
  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var REST = SUPABASE_URL + "/rest/v1";
  // The CER's curation namespace in kb_curation (credential_reference.js).
  var KEY_PREFIX = "_CREDENTIAL_REVIEW::";
  var SAMPLE_PATH = "kb/reference/map_full_exhibit_sample.json";

  // ── Scoped CSS (var(--token) only — no raw hex) ──
  var CSS_ID = "cpl-map-export-css";
  var CSS = [
    ".cplmx { color: var(--text-body); }",
    ".cplmx-head { display:flex; flex-wrap:wrap; gap:8px; align-items:baseline; margin:0 0 10px; }",
    ".cplmx-head .h { font-weight:700; color: var(--navy-primary); font-size:1.05rem; }",
    ".cplmx-head .sub { color: var(--text-muted); font-size:.8rem; }",
    ".cplmx-note { color: var(--text-muted); font-size:.76rem; font-style:italic; }",
    ".cplmx-toolbar { display:flex; flex-wrap:wrap; gap:8px; align-items:center; margin:0 0 10px; }",
    ".cplmx-toolbar input.q { flex:1 1 240px; min-width:180px; padding:7px 11px; border:1px solid var(--border-strong); border-radius:6px; font-size:.86rem; background: var(--surface-opaque); color: var(--text-body); }",
    ".cplmx-toolbar input.q:focus { outline:none; border-color: var(--seal-blue); }",
    ".cplmx-btn { background: var(--seal-blue); color: var(--surface-opaque); border:none; border-radius:6px; padding:7px 14px; font-weight:600; font-size:.8rem; cursor:pointer; }",
    ".cplmx-btn:hover { opacity:.92; }",
    ".cplmx-btn.ghost { background: var(--surface-subtle); color: var(--text-body); border:1px solid var(--border-strong); }",
    ".cplmx-count { font-size:.78rem; color: var(--text-muted); margin-left:auto; }",
    ".cplmx-main { display:flex; gap:12px; align-items:stretch; }",
    ".cplmx-list { flex:0 0 360px; max-width:42%; border:1px solid var(--border); border-radius:8px; background: var(--surface-opaque); overflow-y:auto; max-height:72vh; }",
    ".cplmx-row { padding:7px 12px; border-bottom:1px solid var(--border); cursor:pointer; }",
    ".cplmx-row:hover { background: var(--surface-subtle); }",
    ".cplmx-row.on { background: var(--surface-muted); box-shadow: inset 3px 0 0 var(--seal-blue); }",
    ".cplmx-row .t { font-weight:600; color: var(--navy-primary); font-size:.85rem; }",
    ".cplmx-row .s { font-size:.72rem; color: var(--text-muted); }",
    ".cplmx-detail { flex:1 1 auto; min-width:0; border:1px solid var(--border); border-radius:8px; background: var(--surface-opaque); display:flex; flex-direction:column; max-height:72vh; }",
    ".cplmx-detail-head { display:flex; gap:8px; align-items:center; padding:8px 12px; border-bottom:1px solid var(--border); }",
    ".cplmx-detail-head .t { font-weight:600; color: var(--navy-primary); font-size:.88rem; flex:1 1 auto; min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }",
    ".cplmx-detail-head button { flex:0 0 auto; }",
    ".cplmx-pre { margin:0; padding:12px 14px; overflow:auto; font-size:.75rem; line-height:1.45; flex:1 1 auto; color: var(--text-body); font-family: ui-monospace, Menlo, monospace; }",
    ".cplmx-empty { padding:26px; color: var(--text-muted); text-align:center; }",
    "@media (max-width: 900px) { .cplmx-main { flex-direction:column; } .cplmx-list { max-width:100%; flex-basis:auto; max-height:40vh; } }",
  ].join("\n");

  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var s = document.createElement("style");
    s.id = CSS_ID;
    s.textContent = CSS;
    document.head.appendChild(s);
  }

  // ── DOM helper — createElement/textContent only (no innerHTML with data) ──
  function el(tag, cls, kids) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (kids != null) {
      if (!Array.isArray(kids)) kids = [kids];
      kids.forEach(function (c) {
        if (c == null) return;
        if (typeof c === "string") n.appendChild(document.createTextNode(c));
        else n.appendChild(c);
      });
    }
    return n;
  }
  function clearNode(n) { while (n.firstChild) n.removeChild(n.firstChild); }

  // ── Live curation overlay (the CER's kb_curation namespace) ──────────────
  // Paginated with Range headers over a stable order (the Session-105 lesson:
  // PostgREST caps a single response at 1,000 rows in ARBITRARY order, so a
  // one-shot GET silently drops a different tail once the namespace outgrows
  // the cap). Fields of interest: unified_title_override /
  // issuing_agency_override / issuing_agency_additional_override /
  // training_agency_override. Fail-soft: {ok:false} → render from the baked
  // payload with an "overlay unavailable" note.
  function fetchOverlay() {
    var PAGE = 1000;
    var url = REST + "/kb_curation?select=course_id,field,value"
      + "&course_id=like." + encodeURIComponent(KEY_PREFIX) + "%25"
      + "&order=course_id.asc,field.asc";
    var out = [];
    function page(from) {
      return fetch(url, { headers: {
        "apikey": SUPABASE_ANON,
        "Range-Unit": "items",
        "Range": from + "-" + (from + PAGE - 1)
      } }).then(function (r) {
        if (!r.ok) throw new Error("overlay " + r.status);
        return r.json();
      }).then(function (arr) {
        out = out.concat(arr || []);
        return (arr && arr.length === PAGE) ? page(from + PAGE) : out;
      });
    }
    return page(0).then(function (rows) {
      var m = {};
      rows.forEach(function (row) {
        var t = (row.course_id || "").slice(KEY_PREFIX.length);
        if (!t) return;
        var rec = m[t] = m[t] || {};
        if (row.field === "unified_title_override") rec.utitle = row.value || "";
        else if (row.field === "issuing_agency_override") rec.issuer = row.value || "";
        else if (row.field === "issuing_agency_additional_override") rec.issuer2 = row.value || "";
        else if (row.field === "training_agency_override") rec.trainer = row.value || "";
      });
      return { ok: true, map: m };
    }).catch(function () { return { ok: false, map: {} }; });
  }

  // ── Mapping — one FullExhibitJSON record per unified_title ───────────────
  function topName(payload, top) {
    if (!top || !payload || !payload.top_categories) return null;
    return payload.top_categories[String(top).slice(0, 2)] || null;
  }

  // Resolved issuing agencies: primary (override wins; "" = curator-cleared →
  // none) + additional (the " | "-joined additional-issuers override, else the
  // baked multi-issuer list), deduped case-insensitively, in order.
  function agencyParts(b, ov) {
    var parts = [];
    var primary = (ov && ov.issuer !== undefined) ? (ov.issuer || null) : (b.issuer || null);
    if (primary) parts.push(primary);
    var additional = [];
    if (ov && ov.issuer2 !== undefined) {
      if (ov.issuer2) additional = ov.issuer2.split(" | ");
    } else if (Array.isArray(b.issuers)) {
      additional = b.issuers;
    }
    additional.forEach(function (x) {
      x = (x == null ? "" : String(x)).replace(/^\s+|\s+$/g, "");
      if (!x) return;
      var dup = parts.some(function (p) { return p.toLowerCase() === x.toLowerCase(); });
      if (!dup) parts.push(x);
    });
    return parts;
  }

  function buildRecord(b, ov, payload) {
    ov = ov || {};
    // Title: a non-empty curated rename wins over the baked canonical title.
    var title = (ov.utitle) ? ov.utitle : b.ut;
    var parts = agencyParts(b, ov);
    var agency = parts.length ? parts.join(" | ") : null;
    var trainer = (ov.trainer !== undefined) ? (ov.trainer || null) : (b.trainer || null);

    var arts = Array.isArray(b.articulations) ? b.articulations : [];
    var criteria = arts.map(function (a) {
      var locals = Array.isArray(a.local) ? a.local : [];
      var units = [];
      locals.forEach(function (lc) { if (typeof lc.u === "number") units.push(lc.u); });
      // Criteria text: the generated credit-rec line when it unambiguously
      // describes this single articulation line; otherwise the articulation's
      // own course title (gen_rec is per-credential, so with >1 lines it would
      // mislabel every line).
      var text = a.title || null;
      if (arts.length === 1 && b.gen_rec) text = b.gen_rec;
      if (!text) text = b.gen_rec || null;
      var first = locals.length ? locals[0] : null;
      return {
        criteria: text,
        criteriaNormalized: text,
        minUnits: units.length ? Math.min.apply(null, units) : null,
        maxUnits: units.length ? Math.max.apply(null, units) : null,
        course: {
          courseNumber: first ? (((first.subj || "") + " " + (first.num || "")).replace(/^\s+|\s+$/g, "") || null) : null,
          title: a.title || null,
          cidDisplayText: (a.sys === "C-ID") ? (a.cid || "") : ""
        },
        isArticulated: true
      };
    });

    // Adoptions: union of colleges across every articulation line's locals.
    var seen = {}, colleges = [];
    arts.forEach(function (a) {
      (a.local || []).forEach(function (lc) {
        (lc.colleges || []).forEach(function (cn) {
          if (cn && !seen[cn]) { seen[cn] = 1; colleges.push(cn); }
        });
      });
    });
    colleges.sort();

    // COBI extension — the raw college-entered title variants (r/c/q keys).
    var variants = Array.isArray(b.raw_variants) ? b.raw_variants.map(function (v) {
      return {
        rawTitle: v.r || "",
        confidence: (typeof v.c === "number") ? v.c : null,
        qualityFlag: v.q || null
      };
    }) : [];

    return {
      exhibitId: null,           // MAP assigns
      aceId: null,
      title: title,
      description: null,
      sourceId: null,
      status: { combinedStatusName: "Active" },
      classification: {
        cplTypeId: null,
        cplTypeDescription: (b.cpl_types && b.cpl_types.length) ? b.cpl_types.join(" | ") : null,
        learningModeId: null,
        learningModeDescription: null,
        estimatedUnits: null,
        agency: agency,
        cipCodeID: null,
        cipCodeName: null,
        socCodeID: null,
        socCodeName: null,
        topCodeID: b.top_modal || null,
        topCodeName: topName(payload, b.top_modal),
        industrySectorID: null,
        industrySectorName: null
      },
      notes: null,
      adoptions: {
        adoptedByColleges: colleges.map(function (cn) {
          return { collegeId: null, collegeName: cn };
        })
      },
      criteria: criteria,
      evidence: agency ? [{
        evidenceTypeName: "Certificate",
        issuer: agency,
        description: null,
        submissionGuidelines: null
      }] : [],
      // ── COBI extensions (NOT in the MAP FullExhibitJSON schema — see _meta) ──
      localVariants: variants,
      trainingAgency: trainer
    };
  }

  // Entry wrapper: the Malone-shaped record + the flat fields the list / CSV /
  // search need without re-walking the record.
  function buildEntries(payload, overlayMap) {
    overlayMap = overlayMap || {};
    var rows = (payload && Array.isArray(payload.unified_titles)) ? payload.unified_titles : [];
    return rows.map(function (b) {
      var ov = overlayMap[b.ut] || {};
      var rec = buildRecord(b, ov, payload);
      var parts = agencyParts(b, ov);
      var variantText = Array.isArray(b.raw_variants)
        ? b.raw_variants.map(function (v) { return v.r || ""; }).join(" ") : "";
      return {
        rec: rec,
        title: rec.title,
        issuer: parts.length ? parts[0] : null,
        issuers2: parts.slice(1).join(" | "),
        trainer: rec.trainingAgency,
        cplType: rec.classification.cplTypeDescription || "",
        top: rec.classification.topCodeID || "",
        nCriteria: rec.criteria.length,
        nColleges: rec.adoptions.adoptedByColleges.length,
        nVariants: rec.localVariants.length,
        search: (rec.title + " " + parts.join(" ") + " " + variantText).toLowerCase()
      };
    });
  }

  function buildMeta(payload, entries, overlayOk) {
    return {
      generated_at: new Date().toISOString(),
      source: "COBI Credential Reference (canonical layer)",
      source_generated_at: (payload && payload._generated_at) || null,
      curation_overlay_applied: !!overlayOk,
      record_count: entries.length,
      map_schema_sample: SAMPLE_PATH,
      extensions: "localVariants (the raw college-entered exhibit-title variants collapsed under this canonical credential, with confidence + quality flag) and trainingAgency are ADDITIVE fields not present in the MAP FullExhibitJSON schema. All other fields follow the sample; nulls mean COBI holds no data (e.g. exhibitId — MAP assigns)."
    };
  }

  function exportJson(entries, payload, overlayOk) {
    return JSON.stringify({
      _meta: buildMeta(payload, entries, overlayOk),
      exhibits: entries.map(function (e) { return e.rec; })
    }, null, 2);
  }

  // ── CSV (flat) ──
  function csvEsc(v) {
    v = (v == null) ? "" : String(v);
    return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
  }
  function csvText(entries) {
    var lines = ["title,issuer,additional_issuers,trainer,cpl_type,top_code,n_criteria,n_colleges,n_variants"];
    entries.forEach(function (e) {
      lines.push([e.title, e.issuer, e.issuers2, e.trainer, e.cplType, e.top,
        e.nCriteria, e.nColleges, e.nVariants].map(csvEsc).join(","));
    });
    return lines.join("\n");
  }

  // ── Downloads (Blob + createObjectURL — the cpl_funding.js precedent) ──
  function download(name, text, mime) {
    var blob = new Blob([text], { type: mime || "application/json;charset=utf-8" });
    var a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(function () { try { URL.revokeObjectURL(a.href); } catch (e) {} }, 500);
  }
  function today() {
    var d = new Date();
    return d.getFullYear() + "-" + ("0" + (d.getMonth() + 1)).slice(-2) + "-" + ("0" + d.getDate()).slice(-2);
  }
  function slug(s) {
    return String(s || "record").replace(/[^A-Za-z0-9_-]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 60) || "record";
  }

  // ── State + render ──
  var STATE = { entries: [], payload: null, overlayOk: null, q: "", selected: -1 };

  function filteredEntries() {
    if (!STATE.q) return STATE.entries;
    var q = STATE.q.toLowerCase();
    return STATE.entries.filter(function (e) { return e.search.indexOf(q) !== -1; });
  }

  function render(mount) {
    ensureCss();
    clearNode(mount);
    mount.removeAttribute("style"); // drop the shell's dashed placeholder styling
    var root = el("div", "cplmx");

    // Slim header line.
    root.appendChild(el("div", "cplmx-head", [
      el("span", "h", "MAP Export"),
      el("span", "sub", "— " + STATE.entries.length
        + " canonical credentials · shaped to the MAP Exhibit Module FullExhibitJSON (sample: " + SAMPLE_PATH + ")"),
      STATE.overlayOk === false
        ? el("span", "cplmx-note", "⚠ live curation overlay unavailable — baked titles/issuers shown")
        : null
    ]));

    // Toolbar: search + downloads.
    var qIn = el("input", "q");
    qIn.type = "search";
    qIn.placeholder = "Search title, issuer, raw variant…";
    qIn.value = STATE.q;
    var count = el("span", "cplmx-count");
    var allBtn = el("button", "cplmx-btn", "⬇ Download all (JSON)");
    allBtn.type = "button";
    allBtn.addEventListener("click", function () {
      download("map_exhibit_export_" + today() + ".json",
        exportJson(STATE.entries, STATE.payload, STATE.overlayOk), "application/json;charset=utf-8");
    });
    var csvBtn = el("button", "cplmx-btn ghost", "⬇ CSV");
    csvBtn.type = "button";
    csvBtn.addEventListener("click", function () {
      download("map_exhibit_export_" + today() + ".csv", csvText(STATE.entries), "text/csv;charset=utf-8");
    });
    root.appendChild(el("div", "cplmx-toolbar", [qIn, allBtn, csvBtn, count]));

    // Master-detail split.
    var list = el("div", "cplmx-list");
    var detail = el("div", "cplmx-detail");
    root.appendChild(el("div", "cplmx-main", [list, detail]));
    mount.appendChild(root);

    function renderDetail(entry) {
      clearNode(detail);
      if (!entry) {
        detail.appendChild(el("div", "cplmx-empty", "Select a credential to preview its FullExhibitJSON record."));
        return;
      }
      var text = JSON.stringify(entry.rec, null, 2);
      var dlBtn = el("button", "cplmx-btn ghost", "⬇");
      dlBtn.type = "button";
      dlBtn.title = "Download this record (JSON)";
      dlBtn.addEventListener("click", function () {
        download("map_exhibit_" + slug(entry.title) + ".json", text, "application/json;charset=utf-8");
      });
      var cpBtn = el("button", "cplmx-btn ghost", "⧉");
      cpBtn.type = "button";
      cpBtn.title = "Copy this record to the clipboard";
      cpBtn.addEventListener("click", function () {
        try {
          if (navigator.clipboard && navigator.clipboard.writeText) {
            navigator.clipboard.writeText(text).then(function () {
              cpBtn.textContent = "✓"; setTimeout(function () { cpBtn.textContent = "⧉"; }, 1200);
            });
          }
        } catch (e) { /* clipboard unavailable — no-op */ }
      });
      detail.appendChild(el("div", "cplmx-detail-head", [
        el("span", "t", entry.title || "(untitled)"),
        dlBtn, cpBtn
      ]));
      var pre = el("pre", "cplmx-pre");
      pre.textContent = text;
      detail.appendChild(pre);
    }

    function renderList() {
      var rows = filteredEntries();
      clearNode(list);
      count.textContent = rows.length + " of " + STATE.entries.length;
      if (!rows.length) {
        list.appendChild(el("div", "cplmx-empty",
          STATE.entries.length ? "No credentials match this search." : "No canonical credentials in the dataset."));
        renderDetail(null);
        return;
      }
      var selectedEntry = null;
      rows.forEach(function (e, i) {
        var idx = STATE.entries.indexOf(e);
        var on = (STATE.selected === idx);
        if (on) selectedEntry = e;
        var row = el("div", "cplmx-row" + (on ? " on" : ""), [
          el("div", "t", e.title || "(untitled)"),
          el("div", "s", (e.issuer || "no issuer") + " · " + e.nVariants + " variant" + (e.nVariants === 1 ? "" : "s"))
        ]);
        row.addEventListener("click", function () {
          STATE.selected = idx;
          renderList();
        });
        list.appendChild(row);
      });
      if (!selectedEntry) {
        // Selection fell out of the filter (or nothing picked yet) → first row.
        STATE.selected = STATE.entries.indexOf(rows[0]);
        selectedEntry = rows[0];
        if (list.firstChild && list.firstChild.classList) list.firstChild.classList.add("on");
      }
      renderDetail(selectedEntry);
    }

    qIn.addEventListener("input", function () {
      STATE.q = qIn.value;
      renderList();
    });

    renderList();
    return { renderList: renderList };
  }

  // ── Boot ──
  function boot() {
    var mount = document.getElementById("map-export-root");
    if (!mount) return;
    if (STATE.entries.length && STATE.payload) { render(mount); return; }
    ensureCss();
    clearNode(mount);
    mount.appendChild(document.createTextNode("Loading canonical credentials…"));
    function withData(cb) {
      if (window.CPL_CREDENTIAL_REFERENCE) { cb(); return; }
      if (window.CPL_TABS && window.CPL_TABS.loadScript) {
        window.CPL_TABS.loadScript("credential_reference_data.js", "CPL_CREDENTIAL_REFERENCE", cb);
      } else { cb(); }
    }
    withData(function () {
      var payload = window.CPL_CREDENTIAL_REFERENCE;
      if (!payload || !Array.isArray(payload.unified_titles)) {
        clearNode(mount);
        mount.appendChild(document.createTextNode(
          "Credential Reference dataset unavailable (credential_reference_data.js did not load)."));
        return;
      }
      fetchOverlay().then(function (ov) {
        STATE.payload = payload;
        STATE.overlayOk = ov.ok;
        STATE.entries = buildEntries(payload, ov.map);
        render(mount);
      });
    });
  }

  window.CPL_MAP_EXPORT_TAB = {
    boot: boot,
    // exposed for tests:
    _buildEntries: buildEntries,
    _buildRecord: buildRecord,
    _buildMeta: buildMeta,
    _agencyParts: agencyParts,
    _topName: topName,
    _csv: csvText,
    _exportJson: exportJson,
    _fetchOverlay: fetchOverlay,
    _filteredEntries: filteredEntries,
    _render: render,
    _state: STATE
  };
})();
