// MAP Users tab — renderer (StarMax, Session 87).
//
// STATIC consumer asset (NOT regenerated by excel_to_dashboard.py), lazy-loaded
// by the inline boot in the tab shell on first activation of #tab-map-users.
//
// Manages the MAP platform's per-college user roster (MAP "College Users &
// Roles", category #9) so the team can keep it current + nudge colleges. The
// data is STAFF PII, so it lives only in the gated Supabase table
// public.map_college_users (synced by map/sync_map_users.py). This tab shows:
//   • DEFAULT (public, anon): per-college user COUNTS + the 7-way RoleName mix +
//     "data as of", via the SECURITY DEFINER map_users_summary() RPC. No PII.
//   • SIGNED-IN (magic-link reviewer OR shared team phrase — the same cpl_sb /
//     cpl_team_pass session as the Team & RACI tab): a per-college ROSTER drawer
//     with names + emails, gated server-side by is_allowed_reviewer() OR
//     team_pass_ok() (RLS on map_college_users — anon reads return nothing).
//
// Self-contained behind the CONFIG block (the cpl_news.js / cpl_chat.js
// pattern). Scoped CSS injected from JS so both HTMLs are covered without a
// Rule-4 mirror.
(function () {
  "use strict";

  // ── Config (anon key is public + RLS-gated; mirrors cpl_news.js) ──
  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var REST = SUPABASE_URL + "/rest/v1";
  var TEAM_PASS_KEY = "cpl_team_pass";

  var state = { summary: null, loading: false, error: null, q: "", sort: "users", rosterOpen: {} };

  // ── Auth (shared cpl_sb magic-link session + cpl_team_pass phrase) ──
  // Reads-only here; the roster RLS validates the access token / x-team-pass
  // header server-side, so a logged-out visitor simply gets no rows.
  function isValidJwt(t) {
    return typeof t === "string" && t.split(".").length === 3 && t.length > 40;
  }
  function getSession() {
    try {
      var s = JSON.parse(sessionStorage.getItem("cpl_sb") || "null");
      if (s && isValidJwt(s.access_token)) return { access_token: s.access_token, email: s.email || "(reviewer)" };
    } catch (e) {}
    try {
      var p = localStorage.getItem(TEAM_PASS_KEY);
      if (p) return { teamPass: p, email: "(team)" };
    } catch (e) {}
    return null;
  }
  function authHeaders() {
    var s = getSession();
    // PostgREST rejects an empty/garbled Bearer with 401, so fall back to the
    // anon key when there's no reviewer token (then the team-pass header, if any,
    // is what unlocks the roster).
    var token = (s && s.access_token) || SUPABASE_ANON;
    var h = { apikey: SUPABASE_ANON, Authorization: "Bearer " + token };
    if (s && s.teamPass) h["x-team-pass"] = s.teamPass;
    return h;
  }
  function signedIn() { return !!getSession(); }

  // ── Scoped CSS (var(--token) only — no raw hex) ──
  var CSS_ID = "map-users-css";
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var css = [
      ".mapu { max-width: 1100px; margin: 0 auto; color: var(--text-body); }",
      ".mapu h2 { color: var(--navy-primary); margin: 16px 0 4px; }",
      ".mapu-intro { color: var(--text-muted); max-width: 860px; margin: 0 0 12px; font-size: .92rem; }",
      ".mapu-stat { display:flex; flex-wrap:wrap; gap:10px; margin:0 0 14px; }",
      ".mapu-stat .box { flex:1 1 150px; border:1px solid var(--border); border-radius:8px; background: var(--surface-subtle); padding:10px 12px; }",
      ".mapu-stat .box .n { font-size:1.5rem; font-weight:700; color: var(--navy-primary); }",
      ".mapu-stat .box .l { font-size:.74rem; color: var(--text-muted); text-transform:uppercase; letter-spacing:.05em; }",
      ".mapu-toolbar { display:flex; flex-wrap:wrap; gap:8px; align-items:center; margin:0 0 12px; }",
      ".mapu-toolbar input.q { flex:1 1 220px; min-width:180px; padding:8px 12px; border:1px solid var(--border-strong); border-radius:6px; font-size:.9rem; }",
      ".mapu-toolbar input.q:focus { outline:none; border-color: var(--navy-secondary); }",
      ".mapu-select { padding:7px 10px; border:1px solid var(--border-strong); border-radius:6px; font-size:.82rem; background: var(--surface-opaque); color: var(--text-body); }",
      ".mapu-count { font-size:.82rem; color: var(--text-muted); margin-left:auto; }",
      ".mapu-auth { font-size:.78rem; color: var(--text-muted); }",
      ".mapu-auth b { color: var(--hunter, #2c601a); }",
      ".mapu-table { width:100%; border-collapse:collapse; font-size:.88rem; }",
      ".mapu-table th { text-align:left; background: var(--navy-primary); color:#fff; padding:7px 10px; font-size:.74rem; text-transform:uppercase; letter-spacing:.04em; position:sticky; top:0; }",
      ".mapu-table th.num, .mapu-table td.num { text-align:right; }",
      ".mapu-table td { padding:7px 10px; border-bottom:1px solid var(--border); vertical-align:top; }",
      ".mapu-table tr:hover { background: var(--surface-subtle); }",
      ".mapu-roles { display:flex; flex-wrap:wrap; gap:4px; }",
      ".mapu-chip { font-size:.68rem; background: var(--surface-muted); color: var(--text-muted); border-radius:10px; padding:1px 8px; white-space:nowrap; }",
      ".mapu-rosterbtn { background: var(--surface-subtle); border:1px solid var(--border-strong); border-radius:5px; padding:2px 9px; cursor:pointer; color: var(--text-body); font-size:.76rem; }",
      ".mapu-rosterbtn:hover { background: var(--surface-muted); }",
      ".mapu-roster { background: var(--surface-subtle); }",
      ".mapu-roster table { width:100%; border-collapse:collapse; font-size:.82rem; }",
      ".mapu-roster td, .mapu-roster th { padding:4px 8px; border-bottom:1px solid var(--border); }",
      ".mapu-roster th { color: var(--text-muted); text-transform:uppercase; font-size:.66rem; letter-spacing:.04em; text-align:left; }",
      ".mapu-gate { color: var(--text-muted); font-size:.82rem; padding:8px 4px; }",
      ".mapu-gate a { color: var(--navy-secondary); cursor:pointer; text-decoration:underline; }",
      ".mapu-empty { border:1px dashed var(--border-strong); border-radius:8px; background: var(--surface-subtle); color: var(--text-muted); padding:26px; text-align:center; }",
      ".mapu-draftchip { display:inline-block; margin-left:8px; background: var(--mustard-fill, #f2dca0); color: var(--text-strong, #4a3a00); font-size:.62rem; font-weight:700; letter-spacing:.08em; padding:2px 8px; border-radius:10px; text-transform:uppercase; vertical-align:middle; }",
    ].join("\n");
    var el = document.createElement("style");
    el.id = CSS_ID; el.textContent = css;
    document.head.appendChild(el);
  }

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  // ── Data ──
  function loadSummary() {
    return fetch(REST + "/rpc/map_users_summary", {
      method: "POST",
      headers: { apikey: SUPABASE_ANON, Authorization: "Bearer " + SUPABASE_ANON, "Content-Type": "application/json" },
      body: "{}",
    }).then(function (r) {
      if (!r.ok) throw new Error("summary " + r.status);
      return r.json();
    });
  }
  function loadRoster(college) {
    var url = REST + "/map_college_users?select=first_name,last_name,email,role_name,username"
      + "&college=eq." + encodeURIComponent(college) + "&order=role_name.asc,last_name.asc";
    return fetch(url, { headers: authHeaders() }).then(function (r) {
      if (!r.ok) throw new Error("roster " + r.status);
      return r.json();
    });
  }
  function loadContacts(college) {
    // The gated contacts (Primary Contact / VPAA = VP Instruction / VPSS = VP
    // Student Services) for the refresh nudge. Reviewer/team-phrase only.
    var url = REST + "/map_college_contacts?college=eq." + encodeURIComponent(college) + "&limit=1";
    return fetch(url, { headers: authHeaders() }).then(function (r) {
      if (!r.ok) throw new Error("contacts " + r.status);
      return r.json();
    }).then(function (rows) { return (rows && rows[0]) || null; });
  }

  // ── Nudge (a pre-filled mailto: — like the RACI nudge, nothing auto-sent) ──
  function nudgeRecipients(c) {
    if (!c) return [];
    return [c.primary_contact_email, c.vpaa_email, c.vpss_email]
      .filter(function (e) { return e && String(e).indexOf("@") > 0; });
  }
  function buildNudgeMailto(college, c) {
    var to = nudgeRecipients(c).join(",");
    var subject = "Action requested: refresh your MAP college users — " + college;
    var who = c ? [
      c.primary_contact ? "Primary Contact: " + c.primary_contact : "",
      c.vpaa ? "VP of Instruction (VPAA): " + c.vpaa : "",
      c.vpss ? "VP of Student Services (VPSS): " + c.vpss : "",
    ].filter(Boolean).join("\n") : "";
    var body = "Hello " + college + " team,\n\n"
      + "As part of the statewide CPL (Credit for Prior Learning) effort, please take a few "
      + "minutes to review and update your institution's user list in the MAP platform so the "
      + "right staff have access and the roster stays current.\n\n"
      + (who ? who + "\n\n" : "")
      + "You can manage users in the MAP CPL Dashboard. Thank you for keeping your college's "
      + "CPL team up to date.\n\n— The CPL Initiative team";
    return "mailto:" + encodeURIComponent(to)
      + "?subject=" + encodeURIComponent(subject)
      + "&body=" + encodeURIComponent(body);
  }
  function openNudge(college) {
    return loadContacts(college).then(function (c) {
      var recips = nudgeRecipients(c);
      var href = buildNudgeMailto(college, c);
      // Open the user's mail client (nothing is auto-sent — mirrors RACI).
      try { window.location.href = href; } catch (e) {}
      if (!recips.length) {
        alert("No contact emails are on file for " + college
          + ". A blank draft was opened — add the College Contact / VP of Instruction / "
          + "VP of Student Services manually.");
      }
      return recips;
    }).catch(function () {
      alert("Could not load this college's contacts. Sign in on the Team & RACI tab "
        + "(reviewer or team phrase) and try again.");
    });
  }

  // ── Render ──
  function roleChips(mix) {
    if (!mix || typeof mix !== "object") return "";
    return Object.keys(mix).sort(function (a, b) { return mix[b] - mix[a]; })
      .map(function (role) {
        return '<span class="mapu-chip">' + esc(role) + " " + mix[role] + "</span>";
      }).join("");
  }

  function filteredSorted() {
    var rows = (state.summary || []).slice();
    var q = state.q.trim().toLowerCase();
    if (q) rows = rows.filter(function (r) { return (r.college || "").toLowerCase().indexOf(q) >= 0; });
    rows.sort(function (a, b) {
      if (state.sort === "college") return (a.college || "").localeCompare(b.college || "");
      return (b.user_count || 0) - (a.user_count || 0); // default: most users first
    });
    return rows;
  }

  function fmtDate(s) {
    if (!s) return "—";
    var d = new Date(s);
    if (isNaN(d.getTime())) return esc(String(s).slice(0, 10));
    return d.toISOString().slice(0, 10);
  }

  function render(root) {
    ensureCss();
    if (state.loading) { root.innerHTML = '<div class="mapu"><p class="mapu-gate">Loading MAP users…</p></div>'; return; }
    if (state.error) {
      root.innerHTML = '<div class="mapu"><div class="mapu-empty">Could not load MAP users ('
        + esc(state.error) + ").</div></div>";
      return;
    }
    var rows = filteredSorted();
    var totalUsers = (state.summary || []).reduce(function (s, r) { return s + (r.user_count || 0); }, 0);
    var totalColleges = (state.summary || []).length;
    var lastSynced = (state.summary || []).reduce(function (m, r) {
      return (!m || (r.last_synced && r.last_synced > m)) ? r.last_synced : m;
    }, null);

    var html = '<div class="mapu">';
    html += '<h2>MAP Users <span class="mapu-draftchip">Gated</span></h2>';
    html += '<p class="mapu-intro">The MAP platform’s per-college user roster (names + roles). '
      + "Counts and the role mix are shown to everyone; the staff <b>names &amp; emails</b> are visible "
      + "only to a signed-in reviewer or team-phrase user. Source: MAP “College Users &amp; Roles”, "
      + "synced into a gated store.</p>";

    html += '<div class="mapu-stat">'
      + '<div class="box"><div class="n">' + totalUsers.toLocaleString() + '</div><div class="l">MAP users</div></div>'
      + '<div class="box"><div class="n">' + totalColleges + '</div><div class="l">Colleges</div></div>'
      + '<div class="box"><div class="n">' + fmtDate(lastSynced) + '</div><div class="l">Data as of</div></div>'
      + "</div>";

    html += '<div class="mapu-toolbar">'
      + '<input class="q" type="text" placeholder="Filter colleges…" value="' + esc(state.q) + '">'
      + '<select class="mapu-select" data-sort>'
      + '<option value="users"' + (state.sort === "users" ? " selected" : "") + ">Most users</option>"
      + '<option value="college"' + (state.sort === "college" ? " selected" : "") + ">College A–Z</option>"
      + "</select>"
      + '<span class="mapu-auth">' + (signedIn()
        ? "Signed in <b>✓</b> — roster visible"
        : "Sign in on the <b>Team &amp; RACI</b> tab to see names &amp; emails") + "</span>"
      + '<span class="mapu-count">' + rows.length + " college" + (rows.length === 1 ? "" : "s") + "</span>"
      + "</div>";

    if (!rows.length) {
      html += '<div class="mapu-empty">No colleges match “' + esc(state.q) + "”.</div></div>";
      root.innerHTML = html;
      wire(root);
      return;
    }

    var canNudge = signedIn();
    html += '<table class="mapu-table"><thead><tr>'
      + "<th>College</th><th class=\"num\">Users</th><th>Role mix</th><th>Actions</th>"
      + "</tr></thead><tbody>";
    rows.forEach(function (r) {
      var open = !!state.rosterOpen[r.college];
      var nudgeBtn = canNudge
        ? ' <button class="mapu-rosterbtn" data-nudge="' + esc(r.college)
          + '" title="Email this college’s Primary Contact + VP of Instruction + VP of Student Services to refresh their MAP users (opens your mail app — nothing is auto-sent)">\u{1F4E3} nudge</button>'
        : "";
      html += "<tr>"
        + "<td>" + esc(r.college) + "</td>"
        + '<td class="num">' + (r.user_count || 0) + "</td>"
        + '<td><div class="mapu-roles">' + roleChips(r.role_mix) + "</div></td>"
        + '<td><button class="mapu-rosterbtn" data-roster="' + esc(r.college) + '">'
        + (open ? "✕ hide" : "\u{1F465} roster") + "</button>" + nudgeBtn + "</td>"
        + "</tr>";
      if (open) {
        html += '<tr class="mapu-roster"><td colspan="4" data-roster-cell="' + esc(r.college) + '">'
          + '<div class="mapu-gate">Loading roster…</div></td></tr>';
      }
    });
    html += "</tbody></table></div>";
    root.innerHTML = html;
    wire(root);
    // Fill any open roster cells.
    rows.forEach(function (r) { if (state.rosterOpen[r.college]) fillRoster(root, r.college); });
  }

  function rosterHtml(rows) {
    if (!rows || !rows.length) {
      return '<div class="mapu-gate">No roster rows returned. '
        + (signedIn() ? "This college has no users on record." :
          "Sign in on the <b>Team &amp; RACI</b> tab to view names &amp; emails.") + "</div>";
    }
    var h = "<table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Username</th></tr></thead><tbody>";
    rows.forEach(function (u) {
      var name = ((u.first_name || "") + " " + (u.last_name || "")).trim() || "—";
      h += "<tr><td>" + esc(name) + "</td><td>" + esc(u.email || "—") + "</td><td>"
        + esc(u.role_name || "—") + "</td><td>" + esc(u.username || "—") + "</td></tr>";
    });
    return h + "</tbody></table>";
  }

  function fillRoster(root, college) {
    var cell = root.querySelector('[data-roster-cell="' + cssEscape(college) + '"]');
    if (!cell) return;
    loadRoster(college).then(function (rows) {
      cell.innerHTML = rosterHtml(rows);
    }).catch(function () {
      cell.innerHTML = '<div class="mapu-gate">Could not load the roster. '
        + "Sign in on the <b>Team &amp; RACI</b> tab (reviewer or team phrase) and try again.</div>";
    });
  }

  function cssEscape(s) {
    if (window.CSS && window.CSS.escape) return window.CSS.escape(s);
    return String(s).replace(/["\\\]]/g, "\\$&");
  }

  function wire(root) {
    var q = root.querySelector("input.q");
    if (q) q.addEventListener("input", function () { state.q = q.value; renderInto(root, true); });
    var sel = root.querySelector("[data-sort]");
    if (sel) sel.addEventListener("change", function () { state.sort = sel.value; renderInto(root, true); });
    root.querySelectorAll("[data-roster]").forEach(function (btn) {
      btn.addEventListener("click", function () {
        var c = btn.getAttribute("data-roster");
        state.rosterOpen[c] = !state.rosterOpen[c];
        renderInto(root, true);
      });
    });
    root.querySelectorAll("[data-nudge]").forEach(function (btn) {
      btn.addEventListener("click", function () { openNudge(btn.getAttribute("data-nudge")); });
    });
  }

  // Re-render preserving scroll/focus is overkill here; a full re-render is fine
  // (the dataset is ~128 rows). `keepData` avoids a refetch on filter/sort.
  function renderInto(root, keepData) {
    if (keepData && state.summary) { render(root); return; }
    state.loading = true; state.error = null; render(root);
    loadSummary().then(function (data) {
      state.summary = Array.isArray(data) ? data : [];
      state.loading = false; render(root);
    }).catch(function (e) {
      state.loading = false; state.error = (e && e.message) || "error"; render(root);
    });
  }

  function activate() {
    var root = document.getElementById("map-users-root");
    if (!root) return;
    renderInto(root, !!state.summary);
  }

  window.CPL_MAP_USERS_TAB = {
    activate: activate,
    render: render,
    // exposed for tests
    _state: state,
    _roleChips: roleChips,
    _rosterHtml: rosterHtml,
    _authHeaders: authHeaders,
    _filteredSorted: filteredSorted,
    _fmtDate: fmtDate,
    _buildNudgeMailto: buildNudgeMailto,
    _nudgeRecipients: nudgeRecipients,
  };

  document.addEventListener("cpl-tab-activated", function (e) {
    if (e && e.detail && e.detail.tab === "map-users") activate();
  });
})();
