/*
 * COBI — Project lifecycle overlay  (window.CPL_PROJECT_LIFECYCLE)
 *
 * Soft-delete for the Activities & Projects cards. A reviewer (magic-link) or a
 * team-phrase user can **Table** (pause) or **Archive** (close) a project; it
 * leaves the active grid + every CPL_DATA consumer (RACI matrix, Annual Report,
 * custom reports) and moves to a collapsed "Tabled & Archived" section with its
 * reason + date. Reversible — ♻ Restore deletes the overlay row and the project
 * returns to the grid (live, or on the next daily regen). Never a hard delete.
 *
 * SCOPE — real work-item projects ONLY (Session 95, Sam 2026-07-02). Ids that
 * render Activity-metrics KPI cards (CPL_DATA.activity_kpis — the official
 * workplan sub-activities) are IMMUNE: the generator ignores overlay rows on
 * them, no longer renders duplicate Projects-Grid cards for them, and this
 * module skips them in reconcile()/mountControls(). Tabling/archiving a
 * project can never remove an Activity card, its RACI rows, or its Workplan
 * Goals ladder.
 *
 * Storage: the Supabase `public.project_lifecycle` overlay (project_id pk →
 * {state, reason, updated_by, updated_at}; absence of a row = active). Anon read;
 * writes gated by is_allowed_reviewer() OR team_pass_ok() (the RACI / Mission
 * Control gate). The committed kb/project_lifecycle.json ledger (written by the
 * daily cron) is the "noted in the KB" record + the generator's bake-in source.
 *
 * Two layers, like card_updates.js + projects_editor.js:
 *   • the generator bakes the last-known overlay (tabled cards rendered HIDDEN
 *     with data-lifecycle + the collapsed section);
 *   • this module reconciles any DRIFT since that regen (a just-tabled card is
 *     hidden + added to the section; a just-restored one is un-hidden + removed),
 *     and provides the 🗄 Table/Archive + ♻ Restore controls.
 *
 * STATIC asset — NOT regenerated by excel_to_dashboard.py; injects its own CSS.
 */
(function () {
  "use strict";

  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var TEAM_PASS_KEY = "cpl_team_pass";

  // ── Pure helpers (exported for tests) ───────────────────────────────────────
  function escapeHtml(s) {
    return (s == null ? "" : String(s)).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  // overlay rows -> { pid: {state, reason, updated_by, updated_at} }, dropping
  // malformed rows (no project_id, or a state outside the allowed pair).
  function indexOverlay(rows) {
    var out = {};
    (rows || []).forEach(function (r) {
      if (!r || r.project_id == null) return;
      if (r.state !== "tabled" && r.state !== "archived") return;
      out[String(r.project_id)] = {
        state: r.state,
        reason: r.reason || "",
        updated_by: r.updated_by || "",
        updated_at: r.updated_at || ""
      };
    });
    return out;
  }

  function fmtDate(iso) {
    if (!iso) return "";
    var d = new Date(iso);
    if (isNaN(d.getTime())) return String(iso).slice(0, 10);
    try { return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" }); }
    catch (e) { return d.toISOString().slice(0, 10); }
  }

  function badgeHtml(state) {
    if (state === "archived") {
      return '<span class="tabled-badge" data-state="archived" style="background:#6b7280;color:#fff;' +
        'font-size:0.6rem;font-weight:700;padding:0.1rem 0.4rem;border-radius:3px;text-transform:uppercase;letter-spacing:0.03em;">Archived</span>';
    }
    return '<span class="tabled-badge" data-state="tabled" style="background:var(--gold-accent,#E3B341);color:#3a2e00;' +
      'font-size:0.6rem;font-weight:700;padding:0.1rem 0.4rem;border-radius:3px;text-transform:uppercase;letter-spacing:0.03em;">Tabled</span>';
  }

  // Inner HTML for one collapsed "Tabled & Archived" card. Matches the server's
  // render_tabled_archived_section so a live-tabled entry looks identical to a
  // baked one. `name`/`reason`/`by` are escaped (overlay text is reviewer-written
  // but treated as untrusted).
  function entryHtml(pid, name, meta) {
    meta = meta || {};
    var reason = (meta.reason || "").trim();
    var by = (meta.updated_by || "").trim();
    var when = fmtDate(meta.updated_at);
    var metaBits = [];
    if (when) metaBits.push("Since " + when);
    if (by) metaBits.push(escapeHtml(by));
    var reasonHtml = reason
      ? '<div class="tabled-reason" style="font-size:0.78rem;color:#444;margin:0.3rem 0;line-height:1.4;">' + escapeHtml(reason) + '</div>'
      : "";
    return (
      '<div class="tabled-card-head" style="display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap;">' +
        badgeHtml(meta.state) +
        '<span class="tabled-name" style="font-weight:600;color:var(--navy-primary,#16324f);">' +
          escapeHtml(name) +
          ' <span style="color:#999;font-weight:400;font-size:0.75rem;">' + escapeHtml(pid) + '</span>' +
        '</span>' +
      '</div>' +
      reasonHtml +
      '<div class="tabled-meta" style="font-size:0.68rem;color:#888;font-style:italic;">' + metaBits.join(" · ") + '</div>' +
      '<button type="button" class="tabled-restore" data-pid="' + escapeHtml(pid) + '" ' +
        'style="margin-top:0.5rem;font-size:0.72rem;background:transparent;border:1px solid #ccc;border-radius:4px;' +
        'padding:0.25rem 0.6rem;cursor:pointer;color:var(--text-strong,#1a1a1a);">♻ Restore to active</button>'
    );
  }

  // ── Auth (mirrors raci.js: magic-link session OR shared team phrase) ─────────
  function isValidJwt(t) { return typeof t === "string" && /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(t); }
  function getSession() {
    try {
      var s = JSON.parse(sessionStorage.getItem("cpl_sb") || "null");
      if (s && isValidJwt(s.access_token) && (s.refresh_token || !s.exp || s.exp > Date.now())) return s;
    } catch (e) {}
    try {
      var p = localStorage.getItem(TEAM_PASS_KEY);
      if (p) return { teamPass: p, email: "(team)" };
    } catch (e) {}
    return null;
  }
  function refreshToken(rt) {
    return fetch(SUPABASE_URL + "/auth/v1/token?grant_type=refresh_token", {
      method: "POST", headers: { apikey: SUPABASE_ANON, "Content-Type": "application/json" },
      body: JSON.stringify({ refresh_token: rt })
    }).then(function (r) { return r.ok ? r.json() : Promise.reject(new Error("refresh " + r.status)); });
  }
  function ensureFresh(s) {
    // Prefer the STORED session over the one handed in: refresh tokens rotate,
    // and a caller's copy can hold a CONSUMED one after a sibling module (or
    // the cpl_session.js keeper) renewed. Re-spending it reads to Supabase as
    // token reuse. See credential_reference.js — same line, same reason.
    s = getSession() || s;
    if (!s) return Promise.resolve(null);
    if (s.access_token && s.exp && s.exp <= Date.now() + 60000 && s.refresh_token) {
      return refreshToken(s.refresh_token).then(function (tok) {
        if (!isValidJwt(tok.access_token)) throw new Error("bad refresh");
        var ns = { access_token: tok.access_token, refresh_token: tok.refresh_token || s.refresh_token,
          email: s.email, exp: Date.now() + (parseInt(tok.expires_in || "3600", 10) * 1000) };
        try { sessionStorage.setItem("cpl_sb", JSON.stringify(ns)); } catch (e) {}
        return ns;
      }).catch(function () { return s; });
    }
    return Promise.resolve(s);
  }
  // Anon-RPC validate so a wrong team phrase is never stored (the raci.js pattern).
  function verifyPhrase(p) {
    return fetch(SUPABASE_URL + "/rest/v1/rpc/team_pass_ok", {
      method: "POST",
      headers: { apikey: SUPABASE_ANON, Authorization: "Bearer " + SUPABASE_ANON,
        "Content-Type": "application/json", "x-team-pass": p },
      body: "{}"
    }).then(function (r) { return r.ok ? r.json() : false; })
      .then(function (v) { return v === true; }).catch(function () { return false; });
  }

  // ── Supabase REST ────────────────────────────────────────────────────────────
  // Bearer = the user JWT for a real session, else the ANON key (NEVER an empty
  // "Bearer " — PostgREST 401s that at the auth layer before RLS; the team phrase
  // rides the x-team-pass header which team_pass_ok() validates).  (Session 83.)
  function headersFor(s, prefer) {
    var token = (s && s.access_token) || SUPABASE_ANON;
    var h = { apikey: SUPABASE_ANON, "Content-Type": "application/json", Authorization: "Bearer " + token };
    if (s && s.teamPass) h["x-team-pass"] = s.teamPass;
    if (prefer) h.Prefer = prefer;
    return h;
  }
  function sbGet(path) {
    return fetch(SUPABASE_URL + "/rest/v1/" + path, { headers: { apikey: SUPABASE_ANON } })
      .then(function (r) { return r.ok ? r.json() : []; }).catch(function () { return []; });
  }
  function upsertLifecycle(pid, state, reason, s) {
    var who = s ? (s.teamPass ? "(team)" : (s.email || "(reviewer)")) : "";
    var body = { project_id: pid, state: state, reason: reason || null,
      updated_by: who, updated_at: new Date().toISOString() };
    return ensureFresh(s).then(function (fs) {
      return fetch(SUPABASE_URL + "/rest/v1/project_lifecycle", {
        method: "POST", headers: headersFor(fs, "resolution=merge-duplicates"), body: JSON.stringify(body)
      });
    });
  }
  function deleteLifecycle(pid, s) {
    return ensureFresh(s).then(function (fs) {
      return fetch(SUPABASE_URL + "/rest/v1/project_lifecycle?project_id=eq." + encodeURIComponent(pid), {
        method: "DELETE", headers: headersFor(fs) });
    });
  }

  // ── DOM ──────────────────────────────────────────────────────────────────────
  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) Object.keys(attrs).forEach(function (k) {
      if (k === "class") n.className = attrs[k];
      else if (k === "html") n.innerHTML = attrs[k];
      else if (k === "style") n.setAttribute("style", attrs[k]);
      else n.setAttribute(k, attrs[k]);
    });
    (kids || []).forEach(function (c) { n.appendChild(typeof c === "string" ? document.createTextNode(c) : c); });
    return n;
  }
  function gridEl() { return document.getElementById("projectsGrid"); }
  function cardFor(pid) {
    var q = (window.CSS && CSS.escape ? CSS.escape(pid) : pid);
    // Post-reorg every project renders as a nested .activity-kpi-card[data-pid]
    // under its Activity (CPL_DATA.activity_kpis); the old separate #projectsGrid
    // .project-card is dissolved. Resolve the nested card first, then fall back to
    // the legacy grid card so pre-regen HTML still resolves during the transition.
    return document.querySelector('.activity-kpi-card[data-pid="' + q + '"]') ||
      (gridEl() ? gridEl().querySelector('.project-card[data-pid="' + q + '"]') : null);
  }
  function cardName(card) {
    // The nested card names its project in .akpi-name; the legacy grid card used
    // .project-name. Read the new shape first, fall back to the old.
    var n = card && (card.querySelector(".akpi-name") || card.querySelector(".project-name"));
    return n ? (n.textContent || "").trim() : "";
  }

  // The collapsed "Tabled & Archived" section — find the server-baked one or
  // build it as a sibling right after #projectsGrid.
  function ensureSection() {
    var existing = document.querySelector(".tabled-archived-wrap");
    if (existing) return existing;
    var grid = gridEl();
    if (!grid) return null;
    var wrap = el("details", { "class": "tabled-archived-wrap",
      "style": "margin-top:1.5rem;border:1px solid #e3e3e3;border-radius:10px;padding:0.5rem 1rem;background:#fff;" });
    wrap.innerHTML =
      '<summary class="tabled-archived-summary" style="cursor:pointer;font-weight:700;color:var(--navy-primary,#16324f);font-size:0.95rem;list-style:none;">' +
        '🗄 Tabled &amp; Archived <span class="tabled-archived-count" style="color:#888;font-weight:400;font-size:0.85rem;">(0)</span></summary>' +
      '<div class="tabled-archived-note" style="font-size:0.76rem;color:#666;margin:0.5rem 0 0.8rem 0;line-height:1.4;">' +
        'Paused or closed projects — kept for the record but excluded from active priorities, reports, and the RACI matrix. ' +
        'Sign in (or unlock with the team phrase) to Restore one.</div>' +
      '<div class="tabled-archived-grid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:0.7rem;"></div>';
    grid.parentNode.insertBefore(wrap, grid.nextSibling);
    return wrap;
  }
  function sectionGrid() { var s = ensureSection(); return s ? s.querySelector(".tabled-archived-grid") : null; }
  function entryFor(pid) {
    return document.querySelector('.tabled-card[data-pid="' + (window.CSS && CSS.escape ? CSS.escape(pid) : pid) + '"]');
  }
  function refreshCount() {
    var s = document.querySelector(".tabled-archived-wrap");
    if (!s) return;
    var n = s.querySelectorAll(".tabled-card").length;
    var c = s.querySelector(".tabled-archived-count");
    if (c) c.textContent = "(" + n + ")";
    // An emptied section is hidden so it never lingers as an empty disclosure.
    s.style.display = n ? "" : "none";
  }
  function addEntry(pid, name, meta) {
    var grid = sectionGrid();
    if (!grid) return;
    if (entryFor(pid)) { entryFor(pid).innerHTML = entryHtml(pid, name, meta); refreshCount(); return; }
    var card = el("div", { "class": "tabled-card", "data-pid": pid, "data-lifecycle": meta.state || "tabled",
      "style": "border:1px solid #e3e3e3;border-radius:8px;padding:0.7rem 0.9rem;background:#fafafa;" });
    card.innerHTML = entryHtml(pid, name, meta);
    grid.appendChild(card);
    refreshCount();
  }
  function removeEntry(pid) { var e = entryFor(pid); if (e) e.remove(); refreshCount(); }

  function hideCard(pid, state) {
    var card = cardFor(pid);
    if (card) { card.setAttribute("data-lifecycle", state || "tabled"); card.style.display = "none"; }
  }
  function showCard(pid) {
    var card = cardFor(pid);
    if (card) { card.removeAttribute("data-lifecycle"); card.style.display = ""; }
  }

  // The Annual Workplan Goals table (a SEPARATE tab/surface from the grid) also
  // lists each project. The generator drops a tabled project's rows on the next
  // regen, but until then this hides them live so a tabled project doesn't linger
  // there (Sam, Session 84 follow-up). In render_annual_goals_table_html the
  // sub-activity name cell carries data-pid on its .wpg-assoc-cell and spans 3
  // rows (Goal/Current/Stretch); the grouped render uses data-aid on the ladder
  // cells. Hide both shapes. `table ...` scoping avoids the grid's own data-pid.
  function esc4q(s) { return (window.CSS && CSS.escape) ? CSS.escape(s) : String(s); }
  function nextTr(row) { var n = row.nextElementSibling; while (n && n.tagName !== "TR") n = n.nextElementSibling; return n; }
  function setGoalsRowsHidden(pid, hidden) {
    var q = esc4q(pid);
    Array.prototype.forEach.call(document.querySelectorAll('table [data-pid="' + q + '"]'), function (a) {
      var nameCell = a.closest && a.closest("td[rowspan]");
      if (!nameCell) return;                                  // not a goals-table name cell
      var span = parseInt(nameCell.getAttribute("rowspan"), 10) || 1;
      var row = a.closest("tr");
      for (var i = 0; i < span && row; i++) { row.style.display = hidden ? "none" : ""; row = nextTr(row); }
    });
    Array.prototype.forEach.call(document.querySelectorAll('[data-aid="' + q + '"]'), function (c) {
      var tr = c.closest && c.closest("tr"); if (tr) tr.style.display = hidden ? "none" : "";
    });
  }

  // The OFFICIAL WORKPLAN layer — the sub-activity ids that render
  // Activity-metrics KPI cards (read from CPL_DATA.activity_kpis); mirrors the
  // generator's activity_layer_ids.
  //
  // RETAINED FOR REFERENCE ONLY — it NO LONGER GATES TABLING. Pre-Session-95
  // this marked Activity-layer ids IMMUNE so a stale overlay row couldn't hide
  // an Activity card (the 2026-07-02 mixup where tabling "redundant" duplicate
  // project cards erased 22 Activity cards). The Activities-tab reorg folded
  // EVERY project into activity_kpis — each now renders as a nested
  // .activity-kpi-card[data-pid] and is itself tableable — so using this as a
  // gate would mark *everything* immune and nothing would be tableable. Tabling
  // a sub-activity card hides only that one card, never an Activity group header
  // (.activity-group-header is not .activity-kpi-card). mountControls() and
  // reconcile() therefore no longer consult it. Kept because it documents the
  // generator mirror and its shape is asserted by tests. The `indexOf("5.")`
  // guard is left intact (the single held-out `5.1` stays out of the map).
  // Empty map when CPL_DATA is absent (e.g. tests).
  function activityLayerIds() {
    var out = {};
    try {
      var groups = (window.CPL_DATA && window.CPL_DATA.activity_kpis) || [];
      groups.forEach(function (g) {
        (g.kpis || []).forEach(function (k) {
          if (k && k.id != null && String(k.id).indexOf("5.") !== 0) out[String(k.id)] = true;
        });
      });
    } catch (e) {}
    return out;
  }

  // ── Reconcile drift between the baked HTML and the live overlay ───────────────
  var _overlay = {};
  function reconcile() {
    // The `immune` gate (activityLayerIds()) is intentionally GONE here: the
    // Activities-tab reorg folded every project into activity_kpis, so it would
    // now mark *everything* immune and no overlay-tabled project would ever hide.
    // All sub-activity cards are tableable (see activityLayerIds()'s doc comment).
    // 1. Anything in the overlay but visible → hide + add an entry.
    Object.keys(_overlay).forEach(function (pid) {
      var meta = _overlay[pid];
      var card = cardFor(pid);
      var name = (card && cardName(card)) || (entryFor(pid) && entryNameOf(entryFor(pid))) || pid;
      if (card && !card.getAttribute("data-lifecycle")) hideCard(pid, meta.state);
      else if (card) card.setAttribute("data-lifecycle", meta.state); // keep state in sync
      if (!entryFor(pid)) addEntry(pid, name, meta);
      else entryFor(pid).innerHTML = entryHtml(pid, name, meta); // keep reason/date fresh
      setGoalsRowsHidden(pid, true);                  // also drop it from the Annual Goals table
    });
    // 2. Anything baked as tabled but NO LONGER in the overlay → restore it.
    //    gridEl() may be null post-reorg → [] (already handled); harmless because
    //    the generator excludes tabled projects from activity_kpis, so none
    //    render as baked-tabled cards.
    var baked = gridEl() ? gridEl().querySelectorAll(".project-card[data-lifecycle]") : [];
    Array.prototype.forEach.call(baked, function (card) {
      var pid = card.getAttribute("data-pid");
      if (pid && !_overlay[pid]) { showCard(pid); setGoalsRowsHidden(pid, false); }
    });
    Array.prototype.forEach.call(document.querySelectorAll(".tabled-card[data-pid]"), function (e) {
      var pid = e.getAttribute("data-pid");
      if (pid && !_overlay[pid]) e.remove();
    });
    refreshCount();
    mountControls();
  }
  function entryNameOf(entry) {
    var n = entry.querySelector(".tabled-name");
    if (!n) return "";
    // strip the trailing " <pid>" span
    return (n.firstChild && n.firstChild.textContent || "").trim();
  }

  // ── Controls (shown only to a signed-in reviewer / team-phrase user) ─────────
  function mountControls() {
    var authed = !!getSession();
    // Restore buttons on the collapsed entries.
    Array.prototype.forEach.call(document.querySelectorAll(".tabled-restore"), function (b) {
      b.style.display = authed ? "" : "none";
    });
    // A 🗄 control on each ACTIVE (visible) sub-activity card. Post-reorg every
    // project renders as a nested .activity-kpi-card[data-pid] under its Activity
    // (the old separate #projectsGrid .project-card is dissolved), and EACH one
    // is tableable. The Session-95 `immune` gate is intentionally DROPPED: it
    // existed to stop duplicate grid cards from hiding an Activity card, but the
    // reorg folded every project into activity_kpis, so activityLayerIds() would
    // now mark *everything* immune — keeping the gate would make nothing
    // tableable. Tabling a sub-activity card only hides that one card, never an
    // Activity group header (.activity-group-header is not .activity-kpi-card, so
    // the selector below never matches a header). The legacy `#projectsGrid
    // .project-card` selector is retained for pre-regen HTML during the
    // transition; there is no gridEl()-null early-out (there may be no grid now).
    Array.prototype.forEach.call(
      document.querySelectorAll('.activity-kpi-card[data-pid], #projectsGrid .project-card[data-pid]'),
      function (card) {
        var has = card.querySelector(".plc-ctl-row");
        if (card.getAttribute("data-lifecycle")) { if (has) has.remove(); return; }
        // The 🗄 control shows for EVERYONE (affordance-visibility vs action-
        // eligibility) so the team-phrase / reviewer unlock is reachable from the
        // card — a not-signed-in click opens the unlock in the popup. (Fixes the
        // chicken-and-egg where the unlock was buried behind an authed-only button.)
        if (has) return;
        var row = el("div", { "class": "plc-ctl-row" });
        var btn = el("button", { "class": "plc-table-btn", "type": "button",
          "data-pid": card.getAttribute("data-pid"),
          "title": "Table or archive this project — moves it out of active priorities (reversible)" },
          ["🗄 Table / Archive"]);
        row.appendChild(btn);
        card.appendChild(row);
      });
  }

  // ── Modal: Table / Archive ───────────────────────────────────────────────────
  function closeModal() {
    var ov = document.querySelector(".plc-modal-overlay");
    if (ov) ov.remove();
  }
  function openTableModal(pid) {
    closeModal();
    var card = cardFor(pid);
    var name = (card && cardName(card)) || pid;
    var sess = getSession();

    var overlay = el("div", { "class": "plc-modal-overlay" });
    var modal = el("div", { "class": "plc-modal" });
    overlay.appendChild(modal);
    modal.appendChild(el("h3", {}, ["Table or archive: " + name + " (" + pid + ")"]));
    modal.appendChild(el("div", { "class": "plc-modal-sub" }, [
      "It moves to the Tabled & Archived section and leaves active priorities, reports, and the RACI matrix. Reversible." ]));

    var statusEl = el("div", { "class": "plc-modal-status" }, []);

    if (!sess) {
      // Not authed → offer the team-phrase unlock in place (or sign in elsewhere).
      var inp = el("input", { "type": "password", "placeholder": "team phrase", "class": "plc-in" });
      var unlockBtn = el("button", { "class": "plc-btn plc-btn-go", "type": "button" }, ["🔓 Unlock"]);
      unlockBtn.addEventListener("click", function () {
        var p = (inp.value || "").trim();
        if (!p) { statusEl.textContent = "Enter the team phrase."; return; }
        statusEl.textContent = "Checking…"; unlockBtn.disabled = true;
        verifyPhrase(p).then(function (ok) {
          unlockBtn.disabled = false;
          if (!ok) { statusEl.textContent = "That phrase doesn't match — try again, or sign in as a reviewer."; return; }
          try { localStorage.setItem(TEAM_PASS_KEY, p); } catch (e) {}
          openTableModal(pid); // re-open in edit mode
        });
      });
      inp.addEventListener("keydown", function (e) { if (e.key === "Enter") unlockBtn.click(); });
      modal.appendChild(el("div", { "class": "plc-unlock" }, [
        el("div", { "class": "plc-modal-sub" }, ["Unlock editing with the team phrase — no sign-in needed:"]),
        inp, unlockBtn ]));
      modal.appendChild(statusEl);
      var closeRow0 = el("div", { "class": "plc-modal-actions" }, []);
      var cancel0 = el("button", { "class": "plc-btn-cancel", "type": "button" }, ["Close"]);
      cancel0.addEventListener("click", closeModal);
      closeRow0.appendChild(cancel0);
      modal.appendChild(closeRow0);
      document.body.appendChild(overlay);
      inp.focus();
      return;
    }

    // Authed → state choice + reason.
    var choice = el("div", { "class": "plc-choice" }, []);
    var rTable = el("label", {}, []);
    var rTableIn = el("input", { "type": "radio", "name": "plc-state", "value": "tabled" });
    rTableIn.checked = true;
    rTable.appendChild(rTableIn);
    rTable.appendChild(document.createTextNode(" Table — paused, may resume"));
    var rArch = el("label", {}, []);
    var rArchIn = el("input", { "type": "radio", "name": "plc-state", "value": "archived" });
    rArch.appendChild(rArchIn);
    rArch.appendChild(document.createTextNode(" Archive — done / cancelled"));
    choice.appendChild(rTable);
    choice.appendChild(rArch);
    modal.appendChild(choice);

    var ta = el("textarea", { "class": "plc-reason", "placeholder": "Reason (e.g. contingent on funding not secured) — shown in the Tabled & Archived record." });
    modal.appendChild(ta);
    modal.appendChild(statusEl);

    var actions = el("div", { "class": "plc-modal-actions" }, []);
    var cancel = el("button", { "class": "plc-btn-cancel", "type": "button" }, ["Cancel"]);
    var confirm = el("button", { "class": "plc-btn-submit", "type": "button" }, ["Confirm"]);
    cancel.addEventListener("click", closeModal);
    actions.appendChild(cancel);
    actions.appendChild(confirm);
    modal.appendChild(actions);

    confirm.addEventListener("click", function () {
      var state = (modal.querySelector('input[name="plc-state"]:checked') || {}).value || "tabled";
      var reason = (ta.value || "").trim();
      confirm.disabled = true;
      statusEl.className = "plc-modal-status";
      statusEl.textContent = "Saving…";
      var meta = { state: state, reason: reason, updated_by: sess.teamPass ? "(team)" : (sess.email || "(reviewer)"),
        updated_at: new Date().toISOString() };
      // Optimistic: hide the card + add the entry.
      hideCard(pid, state);
      addEntry(pid, name, meta);
      mountControls();
      upsertLifecycle(pid, state, reason, sess).then(function (r) {
        if (r.ok) {
          _overlay[pid] = meta;
          closeModal();
        } else {
          // rollback
          showCard(pid); removeEntry(pid); mountControls();
          confirm.disabled = false;
          statusEl.className = "plc-modal-status err";
          return r.text().then(function (t) {
            statusEl.textContent = "Save failed (HTTP " + r.status + "). " +
              (r.status === 401 || r.status === 403 ? "Your sign-in/phrase may have expired." : (t || "").slice(0, 120));
          });
        }
      }).catch(function (e) {
        showCard(pid); removeEntry(pid); mountControls();
        confirm.disabled = false;
        statusEl.className = "plc-modal-status err";
        statusEl.textContent = "Network error: " + (e && e.message || "unknown");
      });
    });

    document.body.appendChild(overlay);
    ta.focus();
  }

  function doRestore(pid, btn) {
    var sess = getSession();
    if (!sess) { return; }
    var entry = entryFor(pid);
    var name = entry ? entryNameOf(entry) : pid;
    var prevMeta = _overlay[pid];
    if (btn) { btn.disabled = true; btn.textContent = "Restoring…"; }
    // Optimistic: un-hide the grid card (if present) + remove the entry.
    showCard(pid);
    removeEntry(pid);
    mountControls();
    deleteLifecycle(pid, sess).then(function (r) {
      if (r.ok) { delete _overlay[pid]; }
      else {
        // rollback
        if (prevMeta) { hideCard(pid, prevMeta.state); addEntry(pid, name, prevMeta); mountControls(); }
        alert("Restore failed (HTTP " + r.status + "). " +
          (r.status === 401 || r.status === 403 ? "Your sign-in/phrase may have expired." : ""));
      }
    }).catch(function (e) {
      if (prevMeta) { hideCard(pid, prevMeta.state); addEntry(pid, name, prevMeta); mountControls(); }
      alert("Restore failed: " + (e && e.message || "network error"));
    });
  }

  // ── Delegated clicks (controls are injected dynamically) ─────────────────────
  function onClick(e) {
    var t = e.target;
    while (t && t !== document) {
      if (t.classList && t.classList.contains("plc-table-btn")) { e.preventDefault(); openTableModal(t.getAttribute("data-pid")); return; }
      if (t.classList && t.classList.contains("tabled-restore")) { e.preventDefault(); doRestore(t.getAttribute("data-pid"), t); return; }
      if (t.classList && t.classList.contains("plc-modal-overlay")) {
        // Close ONLY on a true backdrop click. (Session-95 fix: this capture-
        // phase walk reaches the overlay from ANY click inside the modal, so
        // picking the Archive radio — or clicking the reason box — dismissed
        // the modal instantly; only the pre-selected "Tabled" with an empty
        // reason could ever be confirmed. That's why every 2026-07-02 row
        // landed as tabled/no-reason.)
        if (t === e.target) closeModal();
        return;
      }
      t = t.parentNode;
    }
  }

  // ── CSS (var(--token); covers the injected controls + modal only) ────────────
  function injectCss() {
    if (document.getElementById("plc-css")) return;
    var css =
      ".plc-ctl-row{margin-top:0.5rem;text-align:right;}" +
      ".plc-table-btn{font-size:0.7rem;background:transparent;border:1px solid #ddd;border-radius:4px;padding:0.2rem 0.55rem;" +
        "cursor:pointer;color:#777;transition:background .15s,color .15s;}" +
      ".plc-table-btn:hover{background:#faf3e0;border-color:var(--gold-accent,#E3B341);color:var(--text-strong,#1a1a1a);}" +
      ".plc-modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,0.45);z-index:9000;display:flex;align-items:center;justify-content:center;padding:1rem;}" +
      ".plc-modal{background:#fff;border-radius:12px;padding:1.2rem 1.4rem;max-width:460px;width:100%;box-shadow:0 12px 40px rgba(0,0,0,0.3);}" +
      ".plc-modal h3{margin:0 0 0.4rem 0;font-size:1.05rem;color:var(--navy-primary,#16324f);}" +
      ".plc-modal-sub{font-size:0.8rem;color:#666;margin-bottom:0.7rem;line-height:1.4;}" +
      ".plc-choice{display:flex;flex-direction:column;gap:0.4rem;margin:0.4rem 0 0.7rem 0;font-size:0.85rem;color:#333;}" +
      ".plc-reason{width:100%;min-height:70px;font-family:inherit;font-size:0.85rem;padding:0.5rem;border:1px solid #ccc;border-radius:6px;box-sizing:border-box;}" +
      ".plc-in{font-family:inherit;font-size:0.85rem;padding:0.4rem 0.5rem;border:1px solid #ccc;border-radius:6px;margin:0.3rem 0.4rem 0.3rem 0;}" +
      ".plc-unlock{margin:0.4rem 0;}" +
      ".plc-modal-status{font-size:0.78rem;color:#666;min-height:1.1em;margin-top:0.4rem;}" +
      ".plc-modal-status.err{color:var(--crimson,#a33);}" +
      ".plc-modal-actions{display:flex;justify-content:flex-end;gap:0.5rem;margin-top:0.8rem;}" +
      ".plc-btn,.plc-btn-go,.plc-btn-cancel,.plc-btn-submit{font-size:0.85rem;padding:0.4rem 0.9rem;border-radius:6px;cursor:pointer;border:1px solid #ccc;background:#f3f3f3;}" +
      ".plc-btn-submit,.plc-btn-go{background:var(--navy-primary,#16324f);color:#fff;border-color:var(--navy-primary,#16324f);}" +
      ".tabled-archived-summary::-webkit-details-marker{display:none;}";
    var st = el("style", { "id": "plc-css" });
    st.textContent = css;
    document.head.appendChild(st);
  }

  // ── Load + boot ──────────────────────────────────────────────────────────────
  // Is the Activities surface present in the DOM? Pre-reorg the marker was
  // #projectsGrid; the Activities-tab reorg dissolved that grid (the generator
  // now emits ONLY the "Tabled & Archived" ledger between the Projects-Grid
  // markers), so gridEl() is null on the live dashboard. Treat a nested
  // .activity-kpi-card[data-pid] or the baked ledger as "on the Activities view"
  // too — without this, run() would early-out on the real page and the overlay
  // would never load, so a card tabled since the last daily regen would never
  // reconcile (hide) on load. Still early-outs on other pages/tabs that render
  // none of these.
  function activitiesSurfacePresent() {
    return !!(gridEl() ||
      document.querySelector('.activity-kpi-card[data-pid]') ||
      document.querySelector('.tabled-archived-wrap'));
  }
  var _loading = false, _again = false;
  function run() {
    if (!activitiesSurfacePresent()) { mountControls(); return; }  // not on the Activities view yet
    if (_loading) { _again = true; return; }
    _loading = true; _again = false;
    sbGet("project_lifecycle?select=project_id,state,reason,updated_by,updated_at").then(function (rows) {
      _overlay = indexOverlay(rows);
      reconcile();
    }).then(null, function () {}).then(function () {
      _loading = false;
      if (_again) run();
    });
  }

  if (typeof document !== "undefined" && document.addEventListener) {
    function boot() { injectCss(); document.addEventListener("click", onClick, true); run(); }
    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
    else boot();
    if (typeof window !== "undefined" && window.addEventListener) {
      window.addEventListener("cpl-tab-activated", function (e) {
        var tab = e && e.detail && e.detail.tab;
        if (tab === "activities-projects" || tab == null) run();
      });
      // Re-light controls when auth changes (sign-in completes on another tab).
      window.addEventListener("hashchange", mountControls);
      window.addEventListener("storage", function (e) {
        if (!e || e.key === "cpl_sb" || e.key === TEAM_PASS_KEY) mountControls();
      });
    }
  }

  var api = {
    escapeHtml: escapeHtml,
    indexOverlay: indexOverlay,
    entryHtml: entryHtml,
    badgeHtml: badgeHtml,
    fmtDate: fmtDate,
    activityLayerIds: activityLayerIds,
    reconcile: reconcile,
    mountControls: mountControls,
    run: run,
    _setOverlay: function (m) { _overlay = m || {}; }  // test hook
  };
  if (typeof window !== "undefined") window.CPL_PROJECT_LIFECYCLE = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})();
