// Sierra Training tab — renderer (SkyReach, Session 93; Phase 2 SkySierra,
// Session 94). Phases 1 + 2 of docs/sierra_training_tab_scope.md: the review
// queue + gap miner, and the GUIDANCE layer (sierra_guidance — short response
// directives cpl-chat v25 appends to every system prompt; the same-minute
// tuning knob that needs no redeploy).
//
// STATIC consumer asset (NOT regenerated by excel_to_dashboard.py), lazy-loaded
// by the inline boot in the tab shell on first activation of #tab-sierra-training.
//
// The improvement loop's working surface: every Sierra turn is logged
// (chat_interactions) and every answer is rateable (sierra_feedback) — this tab
// is where a TEAM MEMBER (not a Claude session) sees the gaps and drains the
// queue. Two panes, both server-gated by the reviewer/team-phrase RLS SELECT
// policies (the map_users.js pattern — a logged-out visitor simply gets no
// rows and sees the sign-in gate):
//   • FEEDBACK QUEUE — sierra_feedback newest-first; filters rating / audience /
//     page / status / has-note; rows expand to the full Q + A + note; a triage
//     status (new → triaged → addressed) advances via the SECURITY DEFINER RPC
//     sierra_feedback_set_status (reviewer/team-phrase gated server-side).
//   • GAP MINER — chat_interactions classified client-side: LOW-SIMILARITY
//     turns (top_similarity < 0.55 or null — the RAG corpus had nothing close:
//     the single best "what artifact is missing" signal), PUNTS (Sierra
//     explicitly said she didn't have it), recurring THEMES (keyword counts
//     over the gap rows), and an audience slice so student-facing gaps rank
//     first.
//
// GOVERNANCE (from the scope doc): this tab reads logs and triages feedback.
// It must NEVER write to the public cpl-knowledge-base repo — Sierra-corpus
// ingestion is Phase 3, and public-KB publishing stays behind its human-gated
// CURATION.md pipeline regardless.
//
// Self-contained behind the CONFIG block; scoped CSS injected from JS so both
// HTMLs are covered without a Rule-4 mirror.
(function () {
  "use strict";

  // ── Config (anon key is public + RLS-gated; mirrors map_users.js) ──
  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var REST = SUPABASE_URL + "/rest/v1";
  var TEAM_PASS_KEY = "cpl_team_pass";

  // Gap thresholds/signatures (Phase 1 of the scope doc). LOW_SIM matches the
  // function's MATCH_THRESHOLD=0.5 neighborhood — below ~0.55 the RAG corpus
  // had nothing close. PUNT_RES are the honest fallback signatures measured in
  // the live logs (2026-07-01: "don't have" 24 · "doesn't appear" 8 · "don't
  // see" 6 · "not certain" 1 — NOT a bare "MAP@rccd.edu", which appears in 174
  // of 298 answers as routine routing).
  var LOW_SIM = 0.55;
  // NOTE the [’'] classes: the model writes CURLY apostrophes ("don’t"),
  // so a straight-quote-only regex silently misses most punts (caught by the
  // committed test).
  var PUNT_RES = [
    /\bdon['’]?t (?:currently )?have\b/i,
    /\bdo not (?:currently )?have\b/i,
    /\bdoes ?n[o'’]t appear\b/i,
    /\bdon['’]?t see\b/i,
    /\bnot certain\b/i,
    /\bi['’]?m not sure\b/i,
    /\bsources don['’]?t\b/i,
    /\bdon['’]?t contain\b/i,
    /\bcould ?n[o'’]t find\b/i,
    /\bunable to find\b/i,
  ];
  var TURN_LIMIT = 500;   // newest N turns analyzed (surfaced in the UI)
  var FEEDBACK_LIMIT = 200;

  var STATUSES = ["new", "triaged", "addressed"];

  var state = {
    loading: false, error: null, gated: false,
    feedback: null, turns: null,
    // feedback-queue filters
    fRating: "", fAudience: "", fPage: "", fStatus: "open", fNote: false, fDays: "",
    open: {},          // turn_id → expanded
    // gap-miner filters
    gKind: "all", gAudience: "", gDays: "",
    gOpen: {},         // interaction id → expanded
    busy: {},          // turn_id → status write in flight
    bulkStatus: "triaged", bulkBusy: false,
    // guidance layer (Phase 2)
    guidance: null,    // rows newest-first; null = load failed
    guidBusy: {},      // id → toggle write in flight
    addBusy: false,
    draftRule: "", draftNote: "",   // composer drafts survive re-renders
  };

  // cpl-chat v25 sends the newest N active rules — mirror the function's cap
  // so the tab can honestly mark which rules are actually reaching Sierra.
  var GUIDANCE_SENT_CAP = 10;

  // "Test in Sierra" handoff — same-origin sessionStorage key the CPL Assistant
  // tab (cpl_chat.js) consumes on #chatbot activation: it prefills the input
  // (never auto-sends) so a reviewer can replay a logged question against the
  // live function after a fix.
  var TEST_Q_KEY = "cplSierraTestQ.v1";
  function testInSierra(q) {
    try { sessionStorage.setItem(TEST_Q_KEY, String(q || "").slice(0, 1000)); } catch (e) {}
    location.hash = "#chatbot";
  }

  // ── Auth (shared cpl_sb magic-link session + cpl_team_pass phrase) ──
  function isValidJwt(t) {
    return typeof t === "string" && t.split(".").length === 3 && t.length > 40;
  }
  function getSession() {
    try {
      var s = JSON.parse(sessionStorage.getItem("cpl_sb") || "null");
      if (s && isValidJwt(s.access_token)) return { access_token: s.access_token, email: s.email || "(reviewer)" };
    } catch (e) {}
    try {
      var p = localStorage.getItem(TEAM_PASS_KEY);
      if (p) return { teamPass: p, email: "(team)" };
    } catch (e) {}
    return null;
  }
  function authHeaders() {
    var s = getSession();
    var token = (s && s.access_token) || SUPABASE_ANON;
    var h = { apikey: SUPABASE_ANON, Authorization: "Bearer " + token };
    if (s && s.teamPass) h["x-team-pass"] = s.teamPass;
    return h;
  }
  function signedIn() { return !!getSession(); }

  // ── Scoped CSS (var(--token) only — no raw hex) ──
  var CSS_ID = "sierra-training-css";
  function ensureCss() {
    if (document.getElementById(CSS_ID)) return;
    var css = [
      ".sit { max-width: 1150px; margin: 0 auto; color: var(--text-body); }",
      ".sit h2 { color: var(--navy-primary); margin: 16px 0 4px; }",
      ".sit h3 { color: var(--navy-primary); margin: 20px 0 8px; font-size: 1.02rem; }",
      ".sit-intro { color: var(--text-muted); max-width: 900px; margin: 0 0 12px; font-size: .92rem; }",
      ".sit-gatechip { display:inline-block; margin-left:8px; background: var(--mustard-fill, #f2dca0); color: var(--text-strong, #4a3a00); font-size:.62rem; font-weight:700; letter-spacing:.08em; padding:2px 8px; border-radius:10px; text-transform:uppercase; vertical-align:middle; }",
      ".sit-stat { display:flex; flex-wrap:wrap; gap:10px; margin:0 0 14px; }",
      ".sit-stat .box { flex:1 1 140px; border:1px solid var(--border); border-radius:8px; background: var(--surface-subtle); padding:10px 12px; }",
      ".sit-stat .box .n { font-size:1.5rem; font-weight:700; color: var(--navy-primary); }",
      ".sit-stat .box .l { font-size:.72rem; color: var(--text-muted); text-transform:uppercase; letter-spacing:.05em; }",
      ".sit-toolbar { display:flex; flex-wrap:wrap; gap:8px; align-items:center; margin:0 0 10px; }",
      ".sit-select { padding:6px 10px; border:1px solid var(--border-strong); border-radius:6px; font-size:.82rem; background: var(--surface-opaque); color: var(--text-body); }",
      ".sit-check { font-size:.82rem; color: var(--text-body); display:flex; align-items:center; gap:5px; }",
      ".sit-count { font-size:.8rem; color: var(--text-muted); margin-left:auto; }",
      ".sit-auth { font-size:.78rem; color: var(--text-muted); }",
      ".sit-auth b { color: var(--hunter, #2c601a); }",
      ".sit-empty { border:1px dashed var(--border-strong); border-radius:8px; background: var(--surface-subtle); color: var(--text-muted); padding:26px; text-align:center; }",
      ".sit-gate { color: var(--text-muted); font-size:.85rem; padding:8px 4px; }",
      ".sit-row { border:1px solid var(--border); border-radius:8px; margin:0 0 8px; background: var(--surface-opaque); }",
      ".sit-row-head { display:flex; flex-wrap:wrap; gap:6px 10px; align-items:baseline; padding:8px 12px; cursor:pointer; }",
      ".sit-row-head:hover { background: var(--surface-subtle); }",
      ".sit-q { flex:1 1 340px; font-size:.88rem; font-weight:600; color: var(--text-strong); min-width:220px; }",
      ".sit-meta { font-size:.72rem; color: var(--text-muted); white-space:nowrap; }",
      ".sit-chip { font-size:.68rem; border-radius:10px; padding:1px 8px; white-space:nowrap; background: var(--surface-muted); color: var(--text-muted); }",
      ".sit-chip-down { color: var(--brick, #8c2f22); background: rgba(140,47,34,.10); font-weight:700; }",
      ".sit-chip-up { color: var(--hunter, #2c601a); background: rgba(44,96,26,.10); font-weight:700; }",
      ".sit-chip-new { color: var(--brick, #8c2f22); background: rgba(140,47,34,.10); }",
      ".sit-chip-triaged { color: var(--text-strong, #4a3a00); background: var(--mustard-fill, #f2dca0); }",
      ".sit-chip-addressed { color: var(--hunter, #2c601a); background: rgba(44,96,26,.10); }",
      ".sit-chip-gap { color: var(--navy-secondary); background: var(--surface-muted); }",
      ".sit-row-body { border-top:1px solid var(--border); padding:10px 14px; font-size:.85rem; }",
      ".sit-row-body .lbl { font-size:.68rem; text-transform:uppercase; letter-spacing:.05em; color: var(--text-muted); margin:8px 0 2px; }",
      ".sit-row-body .txt { white-space:pre-wrap; word-break:break-word; max-height:340px; overflow:auto; background: var(--surface-subtle); border-radius:6px; padding:8px 10px; }",
      ".sit-note { border-left:3px solid var(--mustard, #d9a800); }",
      ".sit-actions { display:flex; gap:6px; margin-top:10px; align-items:center; flex-wrap:wrap; }",
      ".sit-btn { background: var(--surface-subtle); border:1px solid var(--border-strong); border-radius:5px; padding:3px 10px; cursor:pointer; color: var(--text-body); font-size:.76rem; }",
      ".sit-btn:hover { background: var(--surface-muted); }",
      ".sit-btn[disabled] { opacity:.5; cursor:default; }",
      ".sit-btn.on { background: var(--seal-blue); color:#fff; border-color: var(--seal-blue); }",
      ".sit-themes { display:flex; flex-wrap:wrap; gap:6px; margin:0 0 12px; }",
      ".sit-theme { font-size:.76rem; background: var(--surface-muted); color: var(--text-body); border:1px solid var(--border); border-radius:12px; padding:2px 10px; }",
      ".sit-theme b { color: var(--navy-primary); }",
      ".sit-cap { font-size:.74rem; color: var(--text-muted); margin:4px 0 14px; }",
      ".sit-gov { font-size:.76rem; color: var(--text-muted); border-left:3px solid var(--border-strong); padding:4px 10px; margin:16px 0 0; }",
      ".sit-bulk { display:inline-flex; align-items:center; gap:5px; font-size:.76rem; color: var(--text-muted); }",
      ".sit-logmatch { font-size:.78rem; color: var(--text-body); background: var(--surface-subtle); border-radius:6px; padding:6px 10px; }",
      ".sit-logmatch b { color: var(--navy-primary); }",
      ".sit-logmatch.sit-dim { color: var(--text-muted); }",
      ".sit-guid-warn { font-size:.8rem; color: var(--text-body); background: var(--mustard-fill, #f2dca0); border-radius:8px; padding:8px 12px; max-width:900px; }",
      ".sit-guid-composer { display:flex; flex-direction:column; gap:6px; margin:0 0 12px; }",
      ".sit-guid-composer textarea { resize:vertical; padding:8px 11px; border:1px solid var(--border-strong); border-radius:8px; font: .86rem inherit; font-family:inherit; background: var(--surface-opaque); color: var(--text-body); }",
      ".sit-guid-row { display:flex; gap:6px; }",
      ".sit-guid-note { flex:1; padding:6px 11px; border:1px solid var(--border); border-radius:8px; font-size:.8rem; background: var(--surface-opaque); color: var(--text-body); }",
      ".sit-rule-off .sit-q { color: var(--text-muted); text-decoration: line-through; }",
    ].join("\n");
    var el = document.createElement("style");
    el.id = CSS_ID; el.textContent = css;
    document.head.appendChild(el);
  }

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function fmtWhen(s) {
    if (!s) return "—";
    var d = new Date(s);
    if (isNaN(d.getTime())) return esc(String(s).slice(0, 16));
    return d.toISOString().slice(0, 16).replace("T", " ") + " UTC";
  }
  function truncate(s, n) {
    s = String(s == null ? "" : s);
    return s.length > n ? s.slice(0, n - 1) + "…" : s;
  }
  function withinDays(iso, days) {
    if (!days) return true;
    var d = new Date(iso);
    if (isNaN(d.getTime())) return false;
    return Date.now() - d.getTime() <= days * 86400000;
  }
  function dayOptions(current) {
    var h = "";
    [["", "Any time"], ["1", "Last 24h"], ["7", "Last 7 days"], ["30", "Last 30 days"]]
      .forEach(function (o) {
        h += '<option value="' + o[0] + '"' + (current === o[0] ? " selected" : "") + ">" + o[1] + "</option>";
      });
    return h;
  }
  // Link a feedback row back to its chat_interactions turn: same normalized
  // question, nearest in time. Gives the triager the retrieval telemetry
  // (similarity / topic-match) the feedback snapshot itself doesn't carry.
  function normQ(s) { return String(s || "").trim().toLowerCase().replace(/\s+/g, " "); }
  function logMatch(f) {
    var q = normQ(f && f.question);
    if (!q || !state.turns) return null;
    var best = null;
    var fT = new Date((f && f.created_at) || 0).getTime();
    state.turns.forEach(function (t) {
      if (normQ(t.question) !== q) return;
      var dt = Math.abs(new Date(t.created_at || 0).getTime() - fT);
      if (!best || dt < best.dt) best = { t: t, dt: dt };
    });
    return best && best.t;
  }

  // ── Gap classification (exposed for tests) ──
  function isLowSim(turn) {
    var v = turn && turn.top_similarity;
    return v == null || v < LOW_SIM;
  }
  function isPunt(turn) {
    var r = (turn && turn.response) || "";
    for (var i = 0; i < PUNT_RES.length; i++) if (PUNT_RES[i].test(r)) return true;
    return false;
  }
  function gapKinds(turn) {
    var k = [];
    if (isLowSim(turn)) k.push("low-sim");
    if (isPunt(turn)) k.push("punt");
    return k;
  }
  // Recurring THEMES over the gap rows' QUESTIONS — a tight stopworded keyword
  // count so "what artifact is missing" reads at a glance. Not clever, just a
  // frequency strip; the rows themselves are right below.
  var THEME_STOP = {};
  ("what where which when how does do have has about their they credit college colleges community many much " +
   "with from that this there here could would should will been being your some more most other than then " +
   "prior learning can get for the and are was were had not but all any who its you into also just very " +
   "offer offers give gives provide provides opportunities opportunity available tell cpl map i is it of in on to a an my me we our can't don't")
    .split(/\s+/).forEach(function (w) { THEME_STOP[w] = 1; });
  function themeCounts(rows) {
    var counts = {};
    (rows || []).forEach(function (t) {
      var seen = {};
      String((t && t.question) || "").toLowerCase().replace(/[^a-z0-9\s]/g, " ")
        .split(/\s+/).forEach(function (w) {
          if (w.length < 3 || THEME_STOP[w] || seen[w]) return;
          seen[w] = 1;
          counts[w] = (counts[w] || 0) + 1;
        });
    });
    return Object.keys(counts)
      .filter(function (w) { return counts[w] >= 2; })
      .sort(function (a, b) { return counts[b] - counts[a] || (a < b ? -1 : 1); })
      .slice(0, 14)
      .map(function (w) { return { word: w, n: counts[w] }; });
  }
  function audienceCounts(rows) {
    var by = {};
    (rows || []).forEach(function (t) {
      var a = (t && t.audience) || "(not set)";
      by[a] = (by[a] || 0) + 1;
    });
    return by;
  }

  // ── Data ──
  function loadFeedback() {
    var url = REST + "/sierra_feedback?select=turn_id,created_at,updated_at,page,audience,rating,note,question,response,status"
      + "&order=created_at.desc&limit=" + FEEDBACK_LIMIT;
    return fetch(url, { headers: authHeaders() }).then(function (r) {
      if (!r.ok) throw new Error("feedback " + r.status);
      return r.json();
    });
  }
  function loadTurns() {
    var url = REST + "/chat_interactions?select=id,created_at,question,response,top_similarity,topic_match,audience"
      + "&order=created_at.desc&limit=" + TURN_LIMIT;
    return fetch(url, { headers: authHeaders() }).then(function (r) {
      if (!r.ok) throw new Error("turns " + r.status);
      return r.json();
    });
  }
  // Guidance rows (Phase 2). Soft-fails to null so a guidance hiccup never
  // takes down the queue/miner panes.
  function loadGuidance() {
    var url = REST + "/sierra_guidance?select=id,rule,active,note,created_by,created_at,updated_by,updated_at"
      + "&order=created_at.desc&limit=100";
    return fetch(url, { headers: authHeaders() }).then(function (r) {
      if (!r.ok) throw new Error("guidance " + r.status);
      return r.json();
    }).catch(function () { return null; });
  }
  function whoAmI() {
    var s = getSession();
    return (s && s.email) || null;
  }
  function addGuidance(rule, note, root) {
    if (state.addBusy || !rule) return Promise.resolve();
    state.addBusy = true; render(root);
    var h = authHeaders();
    h["Content-Type"] = "application/json";
    h["Prefer"] = "return=representation";
    return fetch(REST + "/sierra_guidance", {
      method: "POST", headers: h,
      body: JSON.stringify({ rule: rule, note: note || null, created_by: whoAmI(), updated_by: whoAmI() }),
    }).then(function (r) {
      if (!r.ok) throw new Error("add " + r.status);
      return r.json();
    }).then(function (rows) {
      var row = Array.isArray(rows) ? rows[0] : rows;
      if (row) (state.guidance = state.guidance || []).unshift(row);
      state.draftRule = ""; state.draftNote = "";
    }).catch(function () {
      alert("Could not add the rule — renew your session on the Team & RACI tab (reviewer or team phrase) and try again.");
    }).then(function () { state.addBusy = false; render(root); });
  }
  function toggleGuidance(id, root) {
    if (state.guidBusy[id]) return Promise.resolve();
    var row = (state.guidance || []).filter(function (r) { return String(r.id) === String(id); })[0];
    if (!row) return Promise.resolve();
    state.guidBusy[id] = true; render(root);
    var h = authHeaders();
    h["Content-Type"] = "application/json";
    return fetch(REST + "/sierra_guidance?id=eq." + encodeURIComponent(id), {
      method: "PATCH", headers: h,
      body: JSON.stringify({ active: !row.active, updated_by: whoAmI() }),
    }).then(function (r) {
      if (!r.ok) throw new Error("toggle " + r.status);
      row.active = !row.active;
    }).catch(function () {
      alert("Could not update the rule — renew your session on the Team & RACI tab and try again.");
    }).then(function () { delete state.guidBusy[id]; render(root); });
  }
  function setStatus(turnId, status, root) {
    if (state.busy[turnId]) return Promise.resolve();
    state.busy[turnId] = true; render(root);
    var h = authHeaders();
    h["Content-Type"] = "application/json";
    return fetch(REST + "/rpc/sierra_feedback_set_status", {
      method: "POST", headers: h,
      body: JSON.stringify({ p_turn_id: turnId, p_status: status }),
    }).then(function (r) {
      if (!r.ok) throw new Error("status " + r.status);
      (state.feedback || []).forEach(function (f) { if (f.turn_id === turnId) f.status = status; });
    }).catch(function () {
      alert("Could not save the status — sign in on the Team & RACI tab (reviewer or team phrase) and try again.");
    }).then(function () {
      delete state.busy[turnId]; render(root);
    });
  }
  // Bulk triage: advance EVERY currently-filtered row to the picked status in
  // one go (sequential RPC calls — the queue caps at 200 rows and the RPC is
  // the only public write path, so no batch endpoint to lean on).
  function bulkTriage(root) {
    if (state.bulkBusy) return Promise.resolve();
    var target = state.bulkStatus;
    var rows = filteredFeedback().filter(function (f) { return (f.status || "new") !== target; });
    if (!rows.length) { alert('Every filtered row is already "' + target + '".'); return Promise.resolve(); }
    if (!confirm('Mark ' + rows.length + ' filtered feedback row(s) as "' + target + '"?')) return Promise.resolve();
    state.bulkBusy = true; render(root);
    var h = authHeaders();
    h["Content-Type"] = "application/json";
    var failed = 0;
    var chain = Promise.resolve();
    rows.forEach(function (f) {
      chain = chain.then(function () {
        return fetch(REST + "/rpc/sierra_feedback_set_status", {
          method: "POST", headers: h,
          body: JSON.stringify({ p_turn_id: f.turn_id, p_status: target }),
        }).then(function (r) {
          if (!r.ok) { failed++; return; }
          (state.feedback || []).forEach(function (x) { if (x.turn_id === f.turn_id) x.status = target; });
        }).catch(function () { failed++; });
      });
    });
    return chain.then(function () {
      state.bulkBusy = false;
      if (failed) alert(failed + " of " + rows.length + " rows failed to save — renew your session on the Team & RACI tab and retry.");
      render(root);
    });
  }

  // ── Feedback queue ──
  function filteredFeedback() {
    var rows = (state.feedback || []).slice();
    if (state.fRating) rows = rows.filter(function (f) { return f.rating === state.fRating; });
    if (state.fAudience) rows = rows.filter(function (f) { return (f.audience || "(not set)") === state.fAudience; });
    if (state.fPage) rows = rows.filter(function (f) { return (f.page || "(unknown)") === state.fPage; });
    if (state.fStatus === "open") rows = rows.filter(function (f) { return (f.status || "new") !== "addressed"; });
    else if (state.fStatus) rows = rows.filter(function (f) { return (f.status || "new") === state.fStatus; });
    if (state.fNote) rows = rows.filter(function (f) { return !!(f.note && String(f.note).trim()); });
    if (state.fDays) rows = rows.filter(function (f) { return withinDays(f.created_at, +state.fDays); });
    return rows;
  }
  function options(values, current, anyLabel) {
    var h = '<option value="">' + esc(anyLabel) + "</option>";
    values.forEach(function (v) {
      h += '<option value="' + esc(v) + '"' + (current === v ? " selected" : "") + ">" + esc(v) + "</option>";
    });
    return h;
  }
  function distinct(rows, key, fallback) {
    var seen = {};
    (rows || []).forEach(function (r) { seen[(r && r[key]) || fallback] = 1; });
    return Object.keys(seen).sort();
  }
  function statusChip(s) {
    s = s || "new";
    return '<span class="sit-chip sit-chip-' + esc(s) + '">' + esc(s) + "</span>";
  }
  function feedbackRow(f) {
    var open = !!state.open[f.turn_id];
    var ratingChip = '<span class="sit-chip sit-chip-' + (f.rating === "down" ? "down" : "up") + '">'
      + (f.rating === "down" ? "\u{1F44E} down" : "\u{1F44D} up") + "</span>";
    var h = '<div class="sit-row">'
      + '<div class="sit-row-head" data-open="' + esc(f.turn_id) + '">'
      + ratingChip + statusChip(f.status)
      + '<span class="sit-q">' + esc(truncate(f.question || "(no question captured)", 150)) + "</span>"
      + (f.note ? '<span class="sit-chip">\u{1F4DD} note</span>' : "")
      + '<span class="sit-meta">' + esc(f.audience || "—") + " · " + esc(f.page || "—") + " · " + fmtWhen(f.created_at) + "</span>"
      + "</div>";
    if (open) {
      h += '<div class="sit-row-body">';
      if (f.note) h += '<div class="lbl">Note from the rater</div><div class="txt sit-note">' + esc(f.note) + "</div>";
      h += '<div class="lbl">Question</div><div class="txt">' + esc(f.question || "—") + "</div>"
        + '<div class="lbl">Sierra’s answer</div><div class="txt">' + esc(f.response || "—") + "</div>";
      // Retrieval telemetry from the matching chat_interactions turn — was
      // this a knowledge gap (low similarity / punt) or a wording problem?
      var m = logMatch(f);
      h += '<div class="lbl">Chat-log turn</div>';
      if (m) {
        var sim = m.top_similarity == null ? "none" : Number(m.top_similarity).toFixed(2);
        h += '<div class="sit-logmatch">KB similarity <b>' + sim + "</b>"
          + (m.topic_match ? " · exhibit topic-match ✓" : " · no exhibit topic-match")
          + gapKinds(m).map(function (k) {
            return ' · <span class="sit-chip sit-chip-gap">' + (k === "low-sim" ? "⚠ low similarity" : "\u{1F6A7} punt") + "</span>";
          }).join("")
          + " · logged " + fmtWhen(m.created_at) + "</div>";
      } else {
        h += '<div class="sit-logmatch sit-dim">No matching turn in the newest ' + TURN_LIMIT
          + " loaded — likely older than the analysis window.</div>";
      }
      h += '<div class="sit-actions"><span class="lbl" style="margin:0">Triage:</span>';
      STATUSES.forEach(function (s) {
        var on = (f.status || "new") === s;
        h += '<button class="sit-btn' + (on ? " on" : "") + '" data-status="' + esc(s) + '" data-turn="' + esc(f.turn_id) + '"'
          + (on || state.busy[f.turn_id] ? " disabled" : "") + ">" + esc(s) + "</button>";
      });
      h += '<button class="sit-btn" data-qact="test" data-qsrc="fb:' + esc(f.turn_id) + '">🧪 Test in Sierra</button>'
        + '<button class="sit-btn" data-qact="copy" data-qsrc="fb:' + esc(f.turn_id) + '">⧉ Copy question</button>';
      h += "</div></div>";
    }
    return h + "</div>";
  }

  // ── Gap miner ──
  function gapRows() {
    var rows = (state.turns || []).filter(function (t) { return gapKinds(t).length > 0; });
    if (state.gKind === "low-sim") rows = rows.filter(isLowSim);
    else if (state.gKind === "punt") rows = rows.filter(isPunt);
    if (state.gAudience) rows = rows.filter(function (t) { return ((t.audience || "(not set)")) === state.gAudience; });
    if (state.gDays) rows = rows.filter(function (t) { return withinDays(t.created_at, +state.gDays); });
    return rows;
  }
  function gapRow(t) {
    var open = !!state.gOpen[t.id];
    var kinds = gapKinds(t).map(function (k) {
      var label = k === "low-sim"
        ? "⚠ low similarity" + (t.top_similarity == null ? " (none)" : " (" + Number(t.top_similarity).toFixed(2) + ")")
        : "\u{1F6A7} punt";
      return '<span class="sit-chip sit-chip-gap">' + label + "</span>";
    }).join("");
    var h = '<div class="sit-row">'
      + '<div class="sit-row-head" data-gopen="' + esc(t.id) + '">'
      + kinds
      + '<span class="sit-q">' + esc(truncate(t.question || "(empty)", 150)) + "</span>"
      + '<span class="sit-meta">' + esc(t.audience || "—") + " · " + fmtWhen(t.created_at) + "</span>"
      + "</div>";
    if (open) {
      h += '<div class="sit-row-body">'
        + '<div class="lbl">Question</div><div class="txt">' + esc(t.question || "—") + "</div>"
        + '<div class="lbl">Sierra’s answer</div><div class="txt">' + esc(t.response || "—") + "</div>"
        + '<div class="sit-actions">'
        + '<button class="sit-btn" data-qact="test" data-qsrc="gap:' + esc(t.id) + '">🧪 Test in Sierra</button>'
        + '<button class="sit-btn" data-qact="copy" data-qsrc="gap:' + esc(t.id) + '">⧉ Copy question</button>'
        + "</div></div>";
    }
    return h + "</div>";
  }

  // ── Guidance pane (Phase 2) ──
  function guidanceRow(r, sent) {
    var chip = r.active
      ? (sent
        ? '<span class="sit-chip sit-chip-addressed" title="Within the newest ' + GUIDANCE_SENT_CAP + ' active rules — sent to Sierra on every question">active · sent</span>'
        : '<span class="sit-chip sit-chip-triaged" title="More than ' + GUIDANCE_SENT_CAP + ' newer active rules exist — this one is NOT currently sent">active · beyond top-' + GUIDANCE_SENT_CAP + ", not sent</span>")
      : '<span class="sit-chip">inactive</span>';
    var h = '<div class="sit-row' + (r.active ? "" : " sit-rule-off") + '">'
      + '<div class="sit-row-head" style="cursor:default">'
      + chip
      + '<span class="sit-q">' + esc(r.rule) + "</span>"
      + '<span class="sit-meta">' + esc(r.created_by || "—") + " · " + fmtWhen(r.created_at) + "</span>"
      + '<button class="sit-btn" data-guid-toggle="' + esc(r.id) + '"' + (state.guidBusy[r.id] ? " disabled" : "") + ">"
      + (r.active ? "Deactivate" : "Reactivate") + "</button>"
      + "</div>";
    if (r.note) {
      h += '<div class="sit-row-body" style="padding:6px 14px;border-top:none"><span class="lbl" style="margin:0;display:inline">Note:</span> ' + esc(r.note) + "</div>";
    }
    return h + "</div>";
  }

  // ── Render ──
  function render(root) {
    ensureCss();
    if (state.loading) { root.innerHTML = '<div class="sit"><p class="sit-gate">Loading Sierra logs…</p></div>'; return; }

    var html = '<div class="sit">';
    html += '<h2>Sierra Training <span class="sit-gatechip">Team only</span></h2>';
    html += '<p class="sit-intro">The improvement loop for <b>Sierra</b>, the CPL assistant: the '
      + "\u{1F44D}/\u{1F44E} <b>feedback queue</b> from both chat surfaces, and a <b>gap miner</b> over the "
      + "chat logs — turns where the knowledge base had nothing close (low similarity) or Sierra "
      + "explicitly punted. Triage the queue; the recurring themes point at the artifacts and "
      + "guidance Sierra is missing.</p>";

    if (!signedIn()) {
      html += '<div class="sit-empty">This surface reads the gated Sierra logs. '
        + 'Sign in on the <b>Team &amp; RACI</b> tab (magic-link reviewer or the shared team phrase), '
        + "then come back — the queue loads automatically.</div></div>";
      root.innerHTML = html;
      return;
    }
    if (state.error) {
      html += '<div class="sit-empty">Could not load the Sierra logs (' + esc(state.error)
        + "). If you just signed in, re-open this tab; otherwise your session may have expired — "
        + 'renew it on the <b>Team &amp; RACI</b> tab.</div></div>';
      root.innerHTML = html;
      return;
    }
    if (state.gated) {
      html += '<div class="sit-empty">The server returned no rows — your sign-in doesn’t appear to '
        + "unlock the gated logs. Renew your session on the <b>Team &amp; RACI</b> tab and try again.</div></div>";
      root.innerHTML = html;
      return;
    }

    var fb = state.feedback || [];
    var turns = state.turns || [];
    var gaps = turns.filter(function (t) { return gapKinds(t).length > 0; });
    var openCount = fb.filter(function (f) { return (f.status || "new") !== "addressed"; }).length;
    var downCount = fb.filter(function (f) { return f.rating === "down"; }).length;
    var activeGuidance = (state.guidance || []).filter(function (r) { return r.active; }).length;

    html += '<div class="sit-stat">'
      + '<div class="box"><div class="n">' + openCount + '</div><div class="l">Open feedback</div></div>'
      + '<div class="box"><div class="n">' + downCount + '</div><div class="l">\u{1F44E} total</div></div>'
      + '<div class="box"><div class="n">' + gaps.length + '</div><div class="l">Gap turns</div></div>'
      + '<div class="box"><div class="n">' + turns.length + '</div><div class="l">Turns analyzed</div></div>'
      + '<div class="box"><div class="n">' + activeGuidance + '</div><div class="l">🧭 Active guidance</div></div>'
      + "</div>";

    // ── Pane 1: feedback queue ──
    var rows = filteredFeedback();
    html += "<h3>\u{1F4EC} Feedback queue</h3>";
    html += '<div class="sit-toolbar">'
      + '<select class="sit-select" data-f="fRating">' + options(["down", "up"], state.fRating, "Any rating") + "</select>"
      + '<select class="sit-select" data-f="fAudience">' + options(distinct(fb, "audience", "(not set)"), state.fAudience, "Any audience") + "</select>"
      + '<select class="sit-select" data-f="fPage">' + options(distinct(fb, "page", "(unknown)"), state.fPage, "Any page") + "</select>"
      + '<select class="sit-select" data-f="fStatus">'
      + '<option value="open"' + (state.fStatus === "open" ? " selected" : "") + ">Open (new + triaged)</option>"
      + '<option value=""' + (state.fStatus === "" ? " selected" : "") + ">Any status</option>"
      + STATUSES.map(function (s) { return '<option value="' + s + '"' + (state.fStatus === s ? " selected" : "") + ">" + s + "</option>"; }).join("")
      + "</select>"
      + '<label class="sit-check"><input type="checkbox" data-f-note' + (state.fNote ? " checked" : "") + "> has note</label>"
      + '<select class="sit-select" data-f="fDays" aria-label="Feedback date range">' + dayOptions(state.fDays) + "</select>"
      + '<span class="sit-bulk">Mark all ' + rows.length + " filtered → "
      + '<select class="sit-select" data-bulk-status aria-label="Bulk triage status">'
      + ["triaged", "addressed"].map(function (s) {
        return '<option value="' + s + '"' + (state.bulkStatus === s ? " selected" : "") + ">" + s + "</option>";
      }).join("")
      + "</select>"
      + '<button class="sit-btn" data-bulk-apply' + (state.bulkBusy || !rows.length ? " disabled" : "") + ">"
      + (state.bulkBusy ? "Working…" : "Apply") + "</button></span>"
      + '<span class="sit-count">' + rows.length + " of " + fb.length + "</span>"
      + "</div>";
    if (!rows.length) {
      html += '<div class="sit-empty">' + (fb.length ? "No feedback matches these filters." : "No feedback yet — the \u{1F44D}/\u{1F44E} bar on the Sierra surfaces feeds this queue.") + "</div>";
    } else {
      rows.forEach(function (f) { html += feedbackRow(f); });
    }

    // ── Pane 2: gap miner ──
    var g = gapRows();
    var themes = themeCounts(gaps);
    var byAud = audienceCounts(gaps);
    html += "<h3>⛏️ Gap miner <span class=\"sit-meta\">(newest " + turns.length + " turns; low similarity &lt; " + LOW_SIM + " or Sierra punted)</span></h3>";
    if (themes.length) {
      html += '<div class="sit-themes">' + themes.map(function (t) {
        return '<span class="sit-theme">' + esc(t.word) + " <b>×" + t.n + "</b></span>";
      }).join("") + "</div>";
    }
    html += '<div class="sit-toolbar">'
      + '<select class="sit-select" data-g="gKind">'
      + '<option value="all"' + (state.gKind === "all" ? " selected" : "") + ">All gaps</option>"
      + '<option value="low-sim"' + (state.gKind === "low-sim" ? " selected" : "") + ">Low similarity</option>"
      + '<option value="punt"' + (state.gKind === "punt" ? " selected" : "") + ">Punts</option>"
      + "</select>"
      + '<select class="sit-select" data-g="gAudience">' + options(Object.keys(byAud).sort(), state.gAudience, "Any audience") + "</select>"
      + '<select class="sit-select" data-g="gDays" aria-label="Gap date range">' + dayOptions(state.gDays) + "</select>"
      + '<span class="sit-meta">' + Object.keys(byAud).sort().map(function (a) { return esc(a) + " " + byAud[a]; }).join(" · ") + "</span>"
      + '<span class="sit-count">' + g.length + " of " + gaps.length + "</span>"
      + "</div>";
    if (!g.length) {
      html += '<div class="sit-empty">No gap turns match — nice.</div>';
    } else {
      g.forEach(function (t) { html += gapRow(t); });
    }

    // ── Pane 3: guidance layer (Phase 2) ──
    html += "<h3>🧭 Guidance <span class=\"sit-meta\">(response directives Sierra follows — live within a minute, no redeploy)</span></h3>";
    html += '<p class="sit-guid-warn">⚠ Guidance steers <b>every</b> Sierra surface, including the production '
      + "map.rccd.edu widget. Sierra receives the newest <b>" + GUIDANCE_SENT_CAP + " active</b> rules on every "
      + "question (each ≤500 characters). Deactivate instead of deleting — the list is its own audit trail.</p>";
    if (state.guidance === null) {
      html += '<div class="sit-empty">Could not load the guidance rules — renew your session on the '
        + "<b>Team &amp; RACI</b> tab and re-open this tab.</div>";
    } else {
      html += '<div class="sit-guid-composer">'
        + '<textarea class="sit-guid-input" maxlength="500" rows="2" '
        + 'placeholder="e.g. When a visitor asks about CPR or First Aid credit, always mention the statewide EMS pathway alongside local exhibits.">'
        + esc(state.draftRule) + "</textarea>"
        + '<div class="sit-guid-row">'
        + '<input class="sit-guid-note" maxlength="300" value="' + esc(state.draftNote) + '" '
        + 'placeholder="Optional note — why this rule exists (e.g. which feedback it answers)">'
        + '<button class="sit-btn" data-guid-add' + (state.addBusy ? " disabled" : "") + ">"
        + (state.addBusy ? "Adding…" : "➕ Add rule") + "</button>"
        + "</div></div>";
      if (!state.guidance.length) {
        html += '<div class="sit-empty">No guidance rules yet — add the first one above. '
          + "It reaches Sierra on her next answer.</div>";
      } else {
        var activeRank = 0;
        state.guidance.forEach(function (r) {
          if (r.active) activeRank++;
          html += guidanceRow(r, r.active && activeRank <= GUIDANCE_SENT_CAP);
        });
      }
    }

    html += '<p class="sit-gov">Phases 1 + 2 of the Sierra Training scope (review queue + gap miner + the '
      + "guidance layer). Ingesting artifacts into Sierra’s knowledge (Phase 3) comes next, and nothing here "
      + "ever writes to the public CPL Knowledge Base (that stays behind its human-reviewed curation "
      + "pipeline).</p>";
    html += "</div>";
    root.innerHTML = html;
    wire(root);
  }

  function wire(root) {
    root.querySelectorAll("[data-f]").forEach(function (sel) {
      sel.addEventListener("change", function () { state[sel.getAttribute("data-f")] = sel.value; render(root); });
    });
    var note = root.querySelector("[data-f-note]");
    if (note) note.addEventListener("change", function () { state.fNote = note.checked; render(root); });
    root.querySelectorAll("[data-g]").forEach(function (sel) {
      sel.addEventListener("change", function () { state[sel.getAttribute("data-g")] = sel.value; render(root); });
    });
    root.querySelectorAll("[data-open]").forEach(function (el) {
      el.addEventListener("click", function () {
        var id = el.getAttribute("data-open");
        state.open[id] = !state.open[id];
        render(root);
      });
    });
    root.querySelectorAll("[data-gopen]").forEach(function (el) {
      el.addEventListener("click", function () {
        var id = el.getAttribute("data-gopen");
        state.gOpen[id] = !state.gOpen[id];
        render(root);
      });
    });
    root.querySelectorAll("[data-status]").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.stopPropagation();
        setStatus(btn.getAttribute("data-turn"), btn.getAttribute("data-status"), root);
      });
    });
    var bulkSel = root.querySelector("[data-bulk-status]");
    if (bulkSel) bulkSel.addEventListener("change", function () { state.bulkStatus = bulkSel.value; });
    var bulkBtn = root.querySelector("[data-bulk-apply]");
    if (bulkBtn) bulkBtn.addEventListener("click", function () { bulkTriage(root); });
    // guidance composer (drafts live in state so re-renders don't eat typing)
    var gi = root.querySelector(".sit-guid-input");
    if (gi) gi.addEventListener("input", function () { state.draftRule = gi.value; });
    var gn = root.querySelector(".sit-guid-note");
    if (gn) gn.addEventListener("input", function () { state.draftNote = gn.value; });
    var ga = root.querySelector("[data-guid-add]");
    if (ga) ga.addEventListener("click", function () {
      var rule = (state.draftRule || "").trim();
      if (rule.length < 3) { alert("Rule text is required (3–500 characters)."); return; }
      addGuidance(rule, (state.draftNote || "").trim(), root);
    });
    root.querySelectorAll("[data-guid-toggle]").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.stopPropagation();
        toggleGuidance(btn.getAttribute("data-guid-toggle"), root);
      });
    });
    root.querySelectorAll("[data-qact]").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.stopPropagation();
        var q = lookupQuestion(btn.getAttribute("data-qsrc"));
        if (!q) return;
        if (btn.getAttribute("data-qact") === "copy") copyText(q, btn);
        else testInSierra(q);
      });
    });
  }

  // Resolve a row's question from the id-typed data-qsrc handle ("fb:<turn_id>"
  // / "gap:<interaction id>") — ids are attribute-safe where full question text
  // is not.
  function lookupQuestion(src) {
    var m = /^(fb|gap):([\s\S]+)$/.exec(src || "");
    if (!m) return null;
    var rows = m[1] === "fb" ? state.feedback : state.turns;
    var key = m[1] === "fb" ? "turn_id" : "id";
    var hit = (rows || []).filter(function (r) { return String(r[key]) === m[2]; })[0];
    return (hit && hit.question) || null;
  }
  function copyText(q, btn) {
    function flash() {
      var o = btn.textContent;
      btn.textContent = "✓ copied";
      setTimeout(function () { btn.textContent = o; }, 1200);
    }
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(q).then(flash, function () {});
        return;
      }
    } catch (e) { /* fall through */ }
    try {
      var ta = document.createElement("textarea");
      ta.value = q;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      flash();
    } catch (e2) { /* clipboard unavailable */ }
  }

  function renderInto(root, keepData) {
    if (keepData && (state.feedback || state.turns)) { render(root); return; }
    if (!signedIn()) { state.loading = false; render(root); return; }
    state.loading = true; state.error = null; state.gated = false; render(root);
    Promise.all([loadFeedback(), loadTurns(), loadGuidance()]).then(function (res) {
      state.feedback = Array.isArray(res[0]) ? res[0] : [];
      state.turns = Array.isArray(res[1]) ? res[1] : [];
      state.guidance = Array.isArray(res[2]) ? res[2] : null;  // null = load failed (soft)
      // RLS returns 200 + [] to a non-unlocking session — surface that honestly
      // instead of rendering a confusing all-zeros dashboard.
      state.gated = state.feedback.length === 0 && state.turns.length === 0;
      state.loading = false; render(root);
    }).catch(function (e) {
      state.loading = false; state.error = (e && e.message) || "error"; render(root);
    });
  }

  function activate() {
    var root = document.getElementById("sierra-training-root");
    if (!root) return;
    renderInto(root, !!(state.feedback || state.turns));
  }

  window.CPL_SIERRA_TRAINING_TAB = {
    activate: activate,
    render: render,
    // exposed for tests
    _state: state,
    _isLowSim: isLowSim,
    _isPunt: isPunt,
    _gapKinds: gapKinds,
    _themeCounts: themeCounts,
    _audienceCounts: audienceCounts,
    _filteredFeedback: filteredFeedback,
    _gapRows: gapRows,
    _feedbackRow: feedbackRow,
    _gapRow: gapRow,
    _authHeaders: authHeaders,
    _statusChip: statusChip,
    _LOW_SIM: LOW_SIM,
    _PUNT_RES: PUNT_RES,
    _withinDays: withinDays,
    _logMatch: logMatch,
    _lookupQuestion: lookupQuestion,
    _bulkTriage: bulkTriage,
    _testInSierra: testInSierra,
    TEST_Q_KEY: TEST_Q_KEY,
    _guidanceRow: guidanceRow,
    _addGuidance: addGuidance,
    _toggleGuidance: toggleGuidance,
    _loadGuidance: loadGuidance,
    GUIDANCE_SENT_CAP: GUIDANCE_SENT_CAP,
  };

  // NOTE: tabs.js dispatches cpl-tab-activated on WINDOW (not document) — a
  // document listener never fires, which silently broke "sign in on Team &
  // RACI, then come back — the queue loads automatically" (fixed Session 94).
  window.addEventListener("cpl-tab-activated", function (e) {
    if (e && e.detail && e.detail.tab === "sierra-training") activate();
  });
})();
