/* TMC Builder — interactive Transfer Model Curriculum (ADT) submission helper.
 *
 * STATIC asset (NOT regenerated by excel_to_dashboard.py). Lazy-loaded by the
 * tab shell on first #tmc-builder open. Injects its own var(--token) CSS, so it
 * needs no Rule-4 HTML <style> mirror — only the nav button + pane are mirrored.
 *
 * Model: pick a submitting College + a TMC at the top. The LEFT column is the
 * fixed, ASCCC-defined C-ID course list (window.CPL_TMC_TEMPLATES — draft seed).
 * The RIGHT column is a searchable picker of that college's own COCI offerings
 * (window.CPL_TMC_COLLEGE_COURSES, lazy), auto-matching the local course that
 * already carries each slot's C-ID. Output: export (print / .docx / JSON) and an
 * optional Save/Resume to Supabase public.tmc_submissions (anon, no PII).
 */
(function () {
  "use strict";

  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";

  var CC_GLOBAL = "CPL_TMC_COLLEGE_COURSES";
  var booted = false;
  var state = {
    college: "",
    collegeIdx: -1,
    tmc: null,            // selected template object
    courses: [],          // [[subj,num,title,units,cid], ...] for the college
    byCid: null,          // Map cid -> [courseObj,...]
    choice: {},           // slotKey -> courseObj | null
    loadedCourses: false
  };

  /* ----------------------------------------------------------------- utils */
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function el(tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html != null) n.innerHTML = html;
    return n;
  }
  function normCid(s) { return String(s == null ? "" : s).trim().toUpperCase().replace(/\s+/g, " "); }

  // parse a units string like "3", "3–4", "4-5", "8–10" -> [min,max]
  function unitRange(u) {
    if (u == null) return null;
    var m = String(u).replace(/[–—]/g, "-").match(/(\d+(?:\.\d+)?)\s*(?:-\s*(\d+(?:\.\d+)?))?/);
    if (!m) return null;
    var lo = parseFloat(m[1]);
    var hi = m[2] != null ? parseFloat(m[2]) : lo;
    return [lo, hi];
  }
  function unitsInRange(courseUnits, slotUnits) {
    if (courseUnits == null) return null;
    var r = unitRange(slotUnits);
    if (!r) return null;
    var cu = parseFloat(courseUnits);
    if (isNaN(cu)) return null;
    // allow a tiny tolerance for half-unit lab rounding
    return cu >= r[0] - 0.01 && cu <= r[1] + 0.01;
  }
  function slotCids(slot) {
    var arr = [];
    if (slot.cid) arr.push(normCid(slot.cid));
    (slot.alts || []).forEach(function (a) { arr.push(normCid(a)); });
    return arr;
  }

  // Per-TMC status: 'official' (encoded from the authoritative template) /
  // 'draft' (seed sections present, faculty-verify) / 'planned' (catalog only).
  var STATUS_META = {
    official: { label: "✓ Official", cls: "ok" },
    draft:    { label: "⚠ Draft", cls: "warn" },
    planned:  { label: "◷ Coming soon", cls: "muted" }
  };
  function tmcStatus(t) { return (t && t.status) || (t && t.sections && t.sections.length ? "draft" : "planned"); }
  function statusMeta(t) { return STATUS_META[tmcStatus(t)] || STATUS_META.planned; }
  function tmcSource(t) {
    if (t && t.source) return t.source;
    var m = (window.CPL_TMC_TEMPLATES && window.CPL_TMC_TEMPLATES._meta && window.CPL_TMC_TEMPLATES._meta.sources) || {};
    return (t && m[t.id]) || "";
  }

  /* --------------------------------------------------------------- styling */
  function ensureCss() {
    if (document.getElementById("tmc-builder-css")) return;
    var css = "" +
      "#tab-tmc-builder .tmc-wrap{max-width:1100px;}" +
      "#tab-tmc-builder .tmc-draft{background:#FFF6E0;border:1px solid var(--gold-accent);color:#7a5c00;padding:10px 14px;border-radius:8px;font-size:.85rem;margin-bottom:14px;}" +
      "#tab-tmc-builder h2{margin:0 0 4px;}" +
      "#tab-tmc-builder .tmc-sub{font-weight:400;color:var(--text-muted);font-size:1rem;}" +
      "#tab-tmc-builder .tmc-intro{color:#4b5563;margin:0 0 16px;max-width:880px;}" +
      "#tab-tmc-builder .tmc-pickers{display:flex;flex-wrap:wrap;gap:16px;align-items:flex-end;background:var(--surface-subtle,#f8fafc);border:1px solid var(--border-strong,#cbd5e1);border-radius:10px;padding:14px 16px;margin-bottom:18px;}" +
      "#tab-tmc-builder .tmc-pick label{display:block;font-size:.72rem;text-transform:uppercase;letter-spacing:.04em;color:var(--text-muted);font-weight:700;margin-bottom:4px;}" +
      "#tab-tmc-builder .tmc-pick select{padding:8px 10px;border:1px solid var(--border-strong,#cbd5e1);border-radius:7px;font-size:.95rem;background:#fff;min-width:260px;max-width:100%;}" +
      "#tab-tmc-builder .tmc-empty{color:var(--text-muted);text-align:center;border:1px dashed var(--border-strong,#cbd5e1);border-radius:10px;padding:36px 18px;background:var(--surface-subtle,#f8fafc);}" +
      "#tab-tmc-builder .tmc-formhead{display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center;gap:12px;background:var(--navy-primary);color:#fff;border-radius:10px 10px 0 0;padding:14px 18px;}" +
      "#tab-tmc-builder .tmc-formhead h3{margin:0;font-size:1.18rem;color:#fff;}" +
      "#tab-tmc-builder .tmc-formhead .tmc-deg{display:inline-block;background:var(--gold-accent);color:var(--navy-primary);font-weight:700;font-size:.72rem;padding:2px 9px;border-radius:20px;margin-left:8px;vertical-align:middle;}" +
      "#tab-tmc-builder .tmc-formhead .tmc-collegelbl{font-size:.84rem;color:var(--light-blue,#bcd);}" +
      "#tab-tmc-builder .tmc-meter{font-size:.82rem;color:#fff;text-align:right;}" +
      "#tab-tmc-builder .tmc-meter b{font-size:1.05rem;}" +
      "#tab-tmc-builder .tmc-body{border:1px solid var(--border-strong,#cbd5e1);border-top:none;border-radius:0 0 10px 10px;background:#fff;}" +
      "#tab-tmc-builder .tmc-section{border-top:1px solid #eef2f7;}" +
      "#tab-tmc-builder .tmc-section:first-child{border-top:none;}" +
      "#tab-tmc-builder .tmc-sechead{display:flex;justify-content:space-between;align-items:baseline;gap:10px;padding:10px 16px;background:var(--surface-subtle,#f5f7fa);font-weight:700;color:var(--navy-primary);font-size:.92rem;}" +
      "#tab-tmc-builder .tmc-secmeta{font-weight:500;color:var(--text-muted);font-size:.78rem;}" +
      "#tab-tmc-builder .tmc-secnote{padding:0 16px 8px;font-size:.78rem;color:var(--text-muted);font-style:italic;background:var(--surface-subtle,#f5f7fa);}" +
      "#tab-tmc-builder .tmc-colhead{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:6px 16px;font-size:.7rem;text-transform:uppercase;letter-spacing:.04em;color:var(--text-muted);font-weight:700;}" +
      "#tab-tmc-builder .tmc-slot{display:grid;grid-template-columns:1fr 1fr;gap:14px;padding:10px 16px;border-top:1px dashed #eef2f7;align-items:start;}" +
      "#tab-tmc-builder .tmc-left .tmc-cid{display:inline-block;font-family:ui-monospace,Menlo,monospace;font-size:.74rem;font-weight:700;color:var(--navy-primary);background:#eef2fb;border:1px solid #d6e0f5;border-radius:5px;padding:1px 7px;margin-right:6px;}" +
      "#tab-tmc-builder .tmc-left .tmc-cid.noncid{color:#7a5c00;background:#FFF6E0;border-color:var(--gold-accent);}" +
      "#tab-tmc-builder .tmc-left .tmc-ctitle{font-weight:600;color:#1f2937;}" +
      "#tab-tmc-builder .tmc-left .tmc-units{display:block;font-size:.76rem;color:var(--text-muted);margin-top:2px;}" +
      "#tab-tmc-builder .tmc-right{position:relative;}" +
      "#tab-tmc-builder .tmc-picker-btn{width:100%;text-align:left;background:#fff;border:1px solid var(--border-strong,#cbd5e1);border-radius:7px;padding:8px 10px;font-size:.85rem;cursor:pointer;color:#1f2937;line-height:1.3;}" +
      "#tab-tmc-builder .tmc-picker-btn:hover{border-color:var(--navy-primary);}" +
      "#tab-tmc-builder .tmc-picker-btn.empty{color:var(--text-muted);}" +
      "#tab-tmc-builder .tmc-picker-btn .tmc-pc-code{font-family:ui-monospace,Menlo,monospace;font-weight:700;color:var(--navy-primary);}" +
      "#tab-tmc-builder .tmc-status{display:inline-block;font-size:.72rem;font-weight:700;margin-top:5px;padding:1px 8px;border-radius:20px;}" +
      "#tab-tmc-builder .tmc-status.ok{color:#065f46;background:#ecfdf5;border:1px solid #34d399;}" +
      "#tab-tmc-builder .tmc-status.warn{color:#92400e;background:#fffbeb;border:1px solid #fcd34d;}" +
      "#tab-tmc-builder .tmc-status.none{color:#475569;background:#f1f5f9;border:1px solid #cbd5e1;}" +
      "#tab-tmc-builder .tmc-status.empty{color:#9ca3af;background:transparent;border:1px dashed #cbd5e1;}" +
      "#tab-tmc-builder .tmc-clear{margin-left:8px;color:#9ca3af;cursor:pointer;font-size:.72rem;text-decoration:underline;}" +
      "#tab-tmc-builder .tmc-pop{position:absolute;z-index:50;left:0;right:0;top:calc(100% + 4px);background:#fff;border:1px solid var(--navy-primary);border-radius:8px;box-shadow:0 12px 32px rgba(0,0,0,.18);overflow:hidden;}" +
      "#tab-tmc-builder .tmc-pop input{width:100%;border:none;border-bottom:1px solid #e5e7eb;padding:9px 11px;font-size:.85rem;outline:none;box-sizing:border-box;}" +
      "#tab-tmc-builder .tmc-pop-list{max-height:240px;overflow:auto;}" +
      "#tab-tmc-builder .tmc-opt{padding:7px 11px;font-size:.82rem;cursor:pointer;border-top:1px solid #f1f5f9;line-height:1.3;}" +
      "#tab-tmc-builder .tmc-opt:hover{background:#eef6ff;}" +
      "#tab-tmc-builder .tmc-opt .tmc-pc-code{font-family:ui-monospace,Menlo,monospace;font-weight:700;color:var(--navy-primary);}" +
      "#tab-tmc-builder .tmc-opt .tmc-pc-u{color:var(--text-muted);}" +
      "#tab-tmc-builder .tmc-opt .tmc-pc-cid{display:inline-block;font-size:.68rem;font-weight:700;color:#065f46;background:#ecfdf5;border:1px solid #34d399;border-radius:4px;padding:0 5px;margin-left:6px;}" +
      "#tab-tmc-builder .tmc-opt-none{padding:10px 11px;color:var(--text-muted);font-size:.8rem;}" +
      "#tab-tmc-builder .tmc-opt-group{padding:5px 11px;font-size:.68rem;text-transform:uppercase;letter-spacing:.04em;color:var(--text-muted);font-weight:700;background:var(--surface-subtle,#f8fafc);}" +
      "#tab-tmc-builder .tmc-actions{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin-top:16px;}" +
      "#tab-tmc-builder .tmc-btn{border:1px solid var(--navy-primary);background:#fff;color:var(--navy-primary);font-weight:600;font-size:.85rem;padding:8px 14px;border-radius:7px;cursor:pointer;}" +
      "#tab-tmc-builder .tmc-btn:hover{background:var(--navy-primary);color:#fff;}" +
      "#tab-tmc-builder .tmc-btn.primary{background:var(--navy-primary);color:var(--gold-accent);}" +
      "#tab-tmc-builder .tmc-btn.primary:hover{background:#0d2c52;}" +
      "#tab-tmc-builder .tmc-btn[disabled]{opacity:.5;cursor:not-allowed;}" +
      "#tab-tmc-builder .tmc-msg{font-size:.82rem;margin-left:6px;}" +
      "#tab-tmc-builder .tmc-msg.ok{color:#065f46;}" +
      "#tab-tmc-builder .tmc-msg.err{color:#991b1b;}" +
      "#tab-tmc-builder .tmc-legend{font-size:.74rem;color:var(--text-muted);margin:8px 0 0;}" +
      "#tab-tmc-builder .tmc-legend span{margin-right:14px;white-space:nowrap;}" +
      "#tab-tmc-builder .tmc-loading{color:var(--text-muted);font-size:.85rem;padding:8px 0;}" +
      "#tab-tmc-builder .tmc-totals{display:flex;flex-wrap:wrap;justify-content:space-between;gap:10px;align-items:center;padding:12px 18px;background:#eef2fb;border-top:2px solid var(--navy-primary);font-size:.9rem;color:var(--navy-primary);}" +
      "#tab-tmc-builder .tmc-totals b{font-size:1.15rem;}" +
      "#tab-tmc-builder .tmc-totals .tmc-totals-target{color:var(--text-muted);font-size:.82rem;}" +
      "#tab-tmc-builder .tmc-sechead .tmc-secsel{color:#065f46;}" +
      "#tab-tmc-builder .tmc-stchip{display:inline-block;font-size:.66rem;font-weight:700;padding:2px 8px;border-radius:20px;margin-left:8px;vertical-align:middle;}" +
      "#tab-tmc-builder .tmc-stchip.ok{background:#ecfdf5;color:#065f46;border:1px solid #34d399;}" +
      "#tab-tmc-builder .tmc-stchip.warn{background:#fffbeb;color:#92400e;border:1px solid #fcd34d;}" +
      "#tab-tmc-builder .tmc-stchip.muted{background:#eef2f7;color:#475569;border:1px solid #cbd5e1;}" +
      "#tab-tmc-builder .tmc-statuslegend{font-size:.76rem;color:var(--text-muted);margin:-8px 0 16px;}" +
      "#tab-tmc-builder .tmc-srclink{color:var(--navy-primary);font-weight:600;text-decoration:underline;}" +
      "#tab-tmc-builder .tmc-formhead .tmc-srclink{color:#cfe3ff;}" +
      "#tab-tmc-builder .tmc-soon-badge{display:inline-block;font-size:.74rem;font-weight:700;color:#475569;background:#eef2f7;border:1px solid #cbd5e1;border-radius:20px;padding:3px 12px;margin-bottom:6px;}" +
      "@media (max-width:720px){#tab-tmc-builder .tmc-slot,#tab-tmc-builder .tmc-colhead{grid-template-columns:1fr;}}" +
      "@media print{body *{visibility:hidden;}#tab-tmc-builder,#tab-tmc-builder *{visibility:visible;}#tab-tmc-builder .tmc-pickers,#tab-tmc-builder .tmc-actions,#tab-tmc-builder .tmc-pop{display:none!important;}#tab-tmc-builder{position:absolute;left:0;top:0;width:100%;}}";
    var st = el("style");
    st.id = "tmc-builder-css";
    st.textContent = css;
    document.head.appendChild(st);
  }

  /* --------------------------------------------------------------- supabase */
  function sbHeaders(extra) {
    var h = { apikey: SUPABASE_ANON, "Content-Type": "application/json" };
    if (extra) Object.keys(extra).forEach(function (k) { h[k] = extra[k]; });
    return h;
  }
  function sbLoad(college, tmcId) {
    var q = "/rest/v1/tmc_submissions?college=eq." + encodeURIComponent(college) +
            "&tmc_id=eq." + encodeURIComponent(tmcId) + "&select=*";
    return fetch(SUPABASE_URL + q, { headers: sbHeaders() }).then(function (r) {
      return r.ok ? r.json() : [];
    }).then(function (rows) { return (rows && rows[0]) || null; }).catch(function () { return null; });
  }
  function sbSave(payload) {
    return fetch(SUPABASE_URL + "/rest/v1/tmc_submissions?on_conflict=college,tmc_id", {
      method: "POST",
      headers: sbHeaders({ Prefer: "resolution=merge-duplicates,return=representation" }),
      body: JSON.stringify(payload)
    });
  }

  /* ---------------------------------------------------------- data loading */
  function ensureScript(src, global, cb) {
    if (window[global]) { cb(true); return; }
    if (window.CPL_TABS && window.CPL_TABS.loadScript) {
      window.CPL_TABS.loadScript(src, global, function () { cb(!!window[global]); });
      return;
    }
    var s = el("script");
    s.src = src;
    s.onload = function () { cb(!!window[global]); };
    s.onerror = function () { cb(false); };
    document.head.appendChild(s);
  }
  function loadCollegeCourses(cb) { ensureScript("tmc_college_courses.js", CC_GLOBAL, cb); }

  function setCollege(name) {
    state.college = name;
    state.choice = {};
    var data = window[CC_GLOBAL];
    if (!data || !name) { state.collegeIdx = -1; state.courses = []; state.byCid = null; return; }
    state.collegeIdx = data.colleges.indexOf(name);
    var recs = (state.collegeIdx >= 0 && data.courses[String(state.collegeIdx)]) || [];
    state.courses = recs.map(function (r) { return { subj: r[0] || "", num: r[1] || "", title: r[2] || "", units: r[3], cid: r[4] || null }; });
    var m = new Map();
    state.courses.forEach(function (c) {
      if (c.cid) {
        var k = normCid(c.cid);
        if (!m.has(k)) m.set(k, []);
        m.get(k).push(c);
      }
    });
    state.byCid = m;
  }

  // candidate courses for a slot's picker, scored: C-ID match first, then
  // subject-prefix / title-token overlap, then everything (search filters).
  function candidatesFor(slot, query) {
    var q = (query || "").trim().toLowerCase();
    var cids = slotCids(slot);
    var subjHint = (slot.cid || "").split(" ")[0].toLowerCase();
    var titleToks = String(slot.title || "").toLowerCase().split(/[^a-z0-9]+/).filter(function (t) { return t.length > 3; });
    var out = [];
    state.courses.forEach(function (c) {
      var hay = (c.subj + " " + c.num + " " + c.title + " " + (c.cid || "")).toLowerCase();
      if (q && hay.indexOf(q) === -1) return;
      var score = 0;
      if (c.cid && cids.indexOf(normCid(c.cid)) !== -1) score += 100;
      if (subjHint && c.subj.toLowerCase().indexOf(subjHint.slice(0, 3)) === 0) score += 8;
      titleToks.forEach(function (t) { if (c.title.toLowerCase().indexOf(t) !== -1) score += 2; });
      out.push({ c: c, score: score });
    });
    out.sort(function (a, b) {
      if (b.score !== a.score) return b.score - a.score;
      if (a.c.subj !== b.c.subj) return a.c.subj < b.c.subj ? -1 : 1;
      return String(a.c.num) < String(b.c.num) ? -1 : 1;
    });
    return out;
  }

  /* ----------------------------------------------------------- slot status */
  function statusFor(slot, course) {
    if (!course) return { cls: "empty", label: "— not selected" };
    var cids = slotCids(slot);
    var hasCid = course.cid && cids.indexOf(normCid(course.cid)) !== -1;
    var ur = unitsInRange(course.units, slot.units);
    if (slot.noncid && !slot.cid) {
      if (ur === false) return { cls: "warn", label: "⚠ units differ (" + fmtU(course.units) + " vs " + slot.units + ")" };
      return { cls: "ok", label: "✓ selected" };
    }
    if (hasCid) {
      if (ur === false) return { cls: "warn", label: "⚠ C-ID match · units differ (" + fmtU(course.units) + " vs " + slot.units + ")" };
      return { cls: "ok", label: "✓ C-ID aligned" };
    }
    return { cls: "none", label: "○ no C-ID on file — align or pursue C-ID" };
  }
  function fmtU(u) { return u == null ? "?" : (u % 1 === 0 ? String(u) : String(u)); }

  /* -------------------------------------------------------------- counters */
  function sectionUnits(si) {
    var sec = state.tmc.sections[si], sum = 0;
    sec.slots.forEach(function (slot, sj) {
      var c = state.choice[si + ":" + sj];
      if (c && c.units != null && !isNaN(parseFloat(c.units))) sum += parseFloat(c.units);
    });
    return Math.round(sum * 10) / 10;
  }
  function tally() {
    var filled = 0, required = 0, units = 0, aligned = 0;
    if (!state.tmc || !state.tmc.sections) return { filled: filled, required: required, units: units, aligned: aligned };
    state.tmc.sections.forEach(function (sec, si) {
      var need = sec.select === "all" ? sec.slots.length : sec.select;
      required += need;
      sec.slots.forEach(function (slot, sj) {
        var c = state.choice[si + ":" + sj];
        if (c) {
          filled++;
          if (c.units != null && !isNaN(parseFloat(c.units))) units += parseFloat(c.units);
          var stt = statusFor(slot, c);
          if (stt.cls === "ok") aligned++;
        }
      });
    });
    return { filled: filled, required: required, units: Math.round(units * 10) / 10, aligned: aligned };
  }

  /* ----------------------------------------------------------------- views */
  var root;
  function render() {
    root.innerHTML = "";
    var wrap = el("div", "tmc-wrap");
    wrap.appendChild(el("div", "tmc-draft",
      "⚠️ <strong>Draft tool</strong> — the left-side C-ID course lists are seed data pending faculty/articulation-officer verification against the official template at " +
      "<a href='https://c-idsystem.org/transfer-efforts/' target='_blank' rel='noopener'>c-idsystem.org</a>. " +
      "Your local-course selections are saved to help you prepare the official ADT submission."));
    wrap.appendChild(el("h2", null, "TMC Builder <span class='tmc-sub'>— align your courses to a Transfer Model Curriculum (ADT)</span>"));
    wrap.appendChild(el("p", "tmc-intro",
      "Pick your <strong>college</strong> and a <strong>Transfer Model Curriculum</strong>. The left column is the fixed, ASCCC-defined C-ID course list; " +
      "for each row, choose the matching course from <strong>your college's COCI offerings</strong> on the right. Courses that already carry the slot's C-ID are matched automatically."));

    // pickers
    var pk = el("div", "tmc-pickers");
    var colPick = el("div", "tmc-pick");
    colPick.appendChild(el("label", null, "Submitting College"));
    var colSel = el("select");
    colSel.id = "tmc-college-sel";
    colSel.appendChild(new Option("Select your college…", ""));
    var data = window[CC_GLOBAL];
    (data ? data.colleges : []).forEach(function (n) {
      var o = new Option(n, n);
      if (n === state.college) o.selected = true;
      colSel.appendChild(o);
    });
    colSel.onchange = function () { onCollege(colSel.value); };
    colPick.appendChild(colSel);
    pk.appendChild(colPick);

    var tmcPick = el("div", "tmc-pick");
    tmcPick.appendChild(el("label", null, "Program / Discipline (TMC)"));
    var tmcSel = el("select");
    tmcSel.id = "tmc-tmc-sel";
    tmcSel.appendChild(new Option("Select a TMC…", ""));
    var tlist = (window.CPL_TMC_TEMPLATES ? window.CPL_TMC_TEMPLATES.templates : []).slice().sort(function (a, b) {
      return a.discipline < b.discipline ? -1 : 1;
    });
    var avail = tlist.filter(function (t) { return tmcStatus(t) !== "planned"; });
    var soon = tlist.filter(function (t) { return tmcStatus(t) === "planned"; });
    function addOptGroup(label, arr) {
      if (!arr.length) return;
      var og = document.createElement("optgroup");
      og.label = label;
      arr.forEach(function (t) {
        var deg = t.degree ? " (" + t.degree + ")" : "";
        var stext = statusMeta(t).label.replace(/^[^A-Za-z]+\s*/, ""); // strip the emoji
        var o = new Option(t.discipline + deg + " — " + stext, t.id);
        if (state.tmc && state.tmc.id === t.id) o.selected = true;
        og.appendChild(o);
      });
      tmcSel.appendChild(og);
    }
    addOptGroup("Available now (" + avail.length + ")", avail);
    addOptGroup("Coming soon (" + soon.length + ")", soon);
    tmcSel.onchange = function () { onTmc(tmcSel.value); };
    tmcPick.appendChild(tmcSel);
    pk.appendChild(tmcPick);
    wrap.appendChild(pk);

    if (tlist.length) {
      var legend = el("div", "tmc-statuslegend");
      legend.innerHTML = "<strong>" + avail.length + " of " + tlist.length + "</strong> TMCs built so far · status: " +
        "<b class='tmc-stchip warn'>⚠ Draft</b> seed (verify) · " +
        "<b class='tmc-stchip muted'>◷ Coming soon</b> (official template linked) · " +
        "<b class='tmc-stchip ok'>✓ Official</b> once encoded";
      wrap.appendChild(legend);
    }

    var mount = el("div");
    mount.id = "tmc-form-mount";
    wrap.appendChild(mount);
    root.appendChild(wrap);
    renderForm(mount);
  }

  function renderForm(mount) {
    mount.innerHTML = "";
    // A planned / not-yet-encoded TMC: show a catalog panel + official-template
    // link (no college needed). This is the "status indicator" payoff for the
    // 37 TMCs we haven't encoded yet — they're visible and link out.
    if (state.tmc && tmcStatus(state.tmc) === "planned") {
      var pt = state.tmc, psrc = tmcSource(pt);
      var panel = el("div", "tmc-empty");
      panel.innerHTML =
        "<div class='tmc-soon-badge'>◷ Coming soon</div>" +
        "<h3 style='margin:8px 0 4px'>" + esc(pt.discipline) + " TMC</h3>" +
        "<p style='max-width:580px;margin:0 auto 12px'>This Transfer Model Curriculum is in our catalog — we're encoding its fixed C-ID course list from the official ASCCC template. Pick an <strong>Available now</strong> TMC to build today, or open the official template:</p>" +
        (psrc ? "<a class='tmc-srclink' href='" + esc(psrc) + "' target='_blank' rel='noopener'>📄 View the official " + esc(pt.discipline) + " TMC ↗</a>" : "");
      mount.appendChild(panel);
      return;
    }
    if (!state.college || !state.tmc) {
      mount.appendChild(el("div", "tmc-empty",
        !window[CC_GLOBAL]
          ? "<div class='tmc-loading'>Loading college course catalog…</div>"
          : "Select a college and a TMC above to begin building the submission."));
      return;
    }
    var t = state.tmc;
    var st = statusMeta(t);
    var src = tmcSource(t);
    var card = el("div");
    // header
    var head = el("div", "tmc-formhead");
    var left = el("div");
    left.innerHTML = "<h3>" + esc(t.discipline) +
      (t.degree ? "<span class='tmc-deg'>" + esc(t.degree) + "</span>" : "") +
      "<span class='tmc-stchip " + st.cls + "'>" + esc(st.label) + "</span></h3>" +
      "<div class='tmc-collegelbl'>" + esc(state.college) + " · " + esc(t.version || "draft") +
      (src ? " · <a class='tmc-srclink' href='" + esc(src) + "' target='_blank' rel='noopener'>official template ↗</a>" : "") + "</div>";
    head.appendChild(left);
    var meterBox = el("div", "tmc-meter");
    meterBox.id = "tmc-meter";
    head.appendChild(meterBox);
    card.appendChild(head);

    var body = el("div", "tmc-body");
    t.sections.forEach(function (sec, si) {
      var sed = el("div", "tmc-section");
      var need = sec.select === "all" ? "all required" : ("select " + sec.select);
      var secU = sectionUnits(si);
      var sh = el("div", "tmc-sechead");
      sh.innerHTML = "<span>" + esc(sec.name) + "</span><span class='tmc-secmeta'>" + esc(need) +
        (sec.units ? " · req " + esc(sec.units) + " u" : "") +
        " · <b class='tmc-secsel'>your courses: " + secU + " u</b></span>";
      sed.appendChild(sh);
      if (sec.note) sed.appendChild(el("div", "tmc-secnote", esc(sec.note)));
      var ch = el("div", "tmc-colhead");
      ch.innerHTML = "<div>C-ID Course (ASCCC-defined)</div><div>Your College's Course (from COCI)</div>";
      sed.appendChild(ch);
      sec.slots.forEach(function (slot, sj) {
        sed.appendChild(renderSlot(si, sj, slot));
      });
      body.appendChild(sed);
    });
    card.appendChild(body);

    // grand-total footer — Total Units of the college's selected (right-side) courses
    var gt = tally();
    var totals = el("div", "tmc-totals");
    totals.id = "tmc-totals";
    totals.innerHTML =
      "<span>Total Units — your selected courses: <b id='tmc-total-units'>" + gt.units + "</b> u</span>" +
      "<span class='tmc-totals-target'>" + gt.filled + " of " + gt.required + " required courses selected" +
      (t.total_units ? " · TMC major-units target ≈ " + esc(String(t.total_units)) + " u (draft)" : "") + "</span>";
    card.appendChild(totals);
    mount.appendChild(card);

    // legend + actions
    var legend = el("div", "tmc-legend");
    legend.innerHTML =
      "<span><b style='color:#065f46'>✓ C-ID aligned</b> — your course carries this C-ID</span>" +
      "<span><b style='color:#92400e'>⚠ units differ</b> — review unit/contact-hour match</span>" +
      "<span><b style='color:#475569'>○ no C-ID</b> — align content or pursue C-ID approval</span>";
    mount.appendChild(legend);

    var act = el("div", "tmc-actions");
    act.appendChild(mkBtn("💾 Save to Supabase", "primary", doSave));
    act.appendChild(mkBtn("📄 Export Word (.docx)", "", doDocx));
    act.appendChild(mkBtn("🖨 Print / PDF", "", function () { window.print(); }));
    act.appendChild(mkBtn("{ } Export JSON", "", doJson));
    var msg = el("span", "tmc-msg");
    msg.id = "tmc-msg";
    act.appendChild(msg);
    mount.appendChild(act);

    updateMeter();
  }

  function mkBtn(label, cls, fn) {
    var b = el("button", "tmc-btn" + (cls ? " " + cls : ""), label);
    b.type = "button";
    b.onclick = fn;
    return b;
  }

  function renderSlot(si, sj, slot) {
    var key = si + ":" + sj;
    var row = el("div", "tmc-slot");
    var leftc = el("div", "tmc-left");
    var cidHtml = slot.cid
      ? "<span class='tmc-cid'>" + esc(slot.cid) + "</span>"
      : "<span class='tmc-cid noncid'>non-C-ID</span>";
    var altHtml = slot.alts && slot.alts.length ? " <span class='tmc-units'>or " + slot.alts.map(esc).join(", ") + "</span>" : "";
    leftc.innerHTML = cidHtml + "<span class='tmc-ctitle'>" + esc(slot.title) + "</span>" +
      "<span class='tmc-units'>Required units: " + esc(slot.units || "—") + altHtml + "</span>";
    row.appendChild(leftc);

    var rightc = el("div", "tmc-right");
    rightc.appendChild(renderPicker(key, slot));
    var chosen = state.choice[key];
    var stt = statusFor(slot, chosen);
    var pill = el("span", "tmc-status " + stt.cls, esc(stt.label));
    pill.id = "tmc-st-" + key.replace(":", "-");
    rightc.appendChild(pill);
    if (chosen) {
      var clr = el("span", "tmc-clear", "clear");
      clr.onclick = function () { setChoice(key, null); };
      rightc.appendChild(clr);
    }
    row.appendChild(rightc);
    return row;
  }

  function renderPicker(key, slot) {
    var chosen = state.choice[key];
    var btn = el("button", "tmc-picker-btn" + (chosen ? "" : " empty"));
    btn.type = "button";
    btn.innerHTML = chosen
      ? "<span class='tmc-pc-code'>" + esc(chosen.subj + " " + chosen.num) + "</span> — " + esc(chosen.title) +
        " <span class='tmc-pc-u'>(" + fmtU(chosen.units) + " u)</span>"
      : "Select your " + esc((slot.cid || "").split(" ")[0] || "local") + " course…";
    btn.onclick = function (e) {
      e.stopPropagation();
      openPicker(btn.parentNode, key, slot);
    };
    return btn;
  }

  var openPop = null;
  function closePicker() {
    if (openPop && openPop.parentNode) openPop.parentNode.removeChild(openPop);
    openPop = null;
    document.removeEventListener("click", closePicker);
  }
  function openPicker(container, key, slot) {
    closePicker();
    var pop = el("div", "tmc-pop");
    var search = el("input");
    search.type = "text";
    search.placeholder = "Search " + state.courses.length + " courses at " + state.college + "…";
    pop.appendChild(search);
    var list = el("div", "tmc-pop-list");
    pop.appendChild(list);
    container.appendChild(pop);
    openPop = pop;
    setTimeout(function () { document.addEventListener("click", closePicker); }, 0);
    pop.onclick = function (e) { e.stopPropagation(); };

    function fill() {
      var cand = candidatesFor(slot, search.value);
      list.innerHTML = "";
      if (!cand.length) { list.appendChild(el("div", "tmc-opt-none", "No matching course in this college's COCI list.")); return; }
      var shownMatch = false, shownOther = false;
      cand.slice(0, 60).forEach(function (x) {
        var isMatch = x.score >= 100;
        if (isMatch && !shownMatch) { list.appendChild(el("div", "tmc-opt-group", "✓ Already carries this C-ID")); shownMatch = true; }
        if (!isMatch && !shownOther && shownMatch) { list.appendChild(el("div", "tmc-opt-group", "Other courses")); shownOther = true; }
        var o = el("div", "tmc-opt");
        o.innerHTML = "<span class='tmc-pc-code'>" + esc(x.c.subj + " " + x.c.num) + "</span> " + esc(x.c.title) +
          " <span class='tmc-pc-u'>(" + fmtU(x.c.units) + " u)</span>" +
          (isMatch ? "<span class='tmc-pc-cid'>" + esc(x.c.cid) + "</span>" : "");
        o.onclick = function () { setChoice(key, x.c); closePicker(); };
        list.appendChild(o);
      });
    }
    search.oninput = fill;
    fill();
    search.focus();
  }

  function setChoice(key, course) {
    state.choice[key] = course;
    // re-render just the affected slot + meter (cheap full re-render of the form mount)
    renderForm(document.getElementById("tmc-form-mount"));
  }

  function updateMeter() {
    var m = document.getElementById("tmc-meter");
    if (!m) return;
    var t = tally();
    m.innerHTML = "Total Units: <b>" + t.units + "</b> · <b>" + t.aligned + "</b> C-ID aligned · <b>" + t.filled + "/" + t.required + "</b> slots";
  }

  /* --------------------------------------------------------------- actions */
  function collectPayload(status) {
    var alignments = {};
    state.tmc.sections.forEach(function (sec, si) {
      sec.slots.forEach(function (slot, sj) {
        var c = state.choice[si + ":" + sj];
        if (c) {
          alignments[si + ":" + sj] = {
            cid: slot.cid || "", slot_title: slot.title, slot_units: slot.units || "",
            subj: c.subj, num: c.num, title: c.title, units: c.units, course_cid: c.cid || "",
            status: statusFor(slot, c).cls
          };
        }
      });
    });
    var t = tally();
    return {
      college: state.college, tmc_id: state.tmc.id, tmc_discipline: state.tmc.discipline,
      degree_type: state.tmc.degree, alignments: alignments, status: status || "draft",
      total_major_units: t.units, filled_slots: t.filled, total_slots: t.required
    };
  }

  function setMsg(text, cls) {
    var m = document.getElementById("tmc-msg");
    if (m) { m.textContent = text; m.className = "tmc-msg " + (cls || ""); }
  }

  function doSave() {
    setMsg("Saving…", "");
    sbSave(collectPayload("draft")).then(function (r) {
      if (r.ok) setMsg("✓ Saved — resume any time by re-selecting this college + TMC.", "ok");
      else r.text().then(function (tx) { setMsg("Save failed: " + (tx || r.status), "err"); });
    }).catch(function (e) { setMsg("Save failed: " + e.message, "err"); });
  }

  function doJson() {
    var blob = new Blob([JSON.stringify(collectPayload("draft"), null, 2)], { type: "application/json" });
    downloadBlob(blob, slug() + ".json");
  }

  function slug() {
    return (state.college + "_" + state.tmc.discipline).replace(/[^A-Za-z0-9]+/g, "_") + "_TMC";
  }
  function downloadBlob(blob, name) {
    var a = el("a");
    a.href = URL.createObjectURL(blob);
    a.download = name;
    document.body.appendChild(a); a.click();
    setTimeout(function () { URL.revokeObjectURL(a.href); document.body.removeChild(a); }, 100);
  }

  function doDocx() {
    if (!window.docx) { setMsg("Word export unavailable (docx library not loaded) — use Print/PDF.", "err"); return; }
    var d = window.docx;
    var rows = [headerRow(d)];
    state.tmc.sections.forEach(function (sec, si) {
      rows.push(sectionRow(d, sec));
      sec.slots.forEach(function (slot, sj) {
        var c = state.choice[si + ":" + sj];
        rows.push(slotRow(d, slot, c));
      });
    });
    var t = tally();
    var doc = new d.Document({
      sections: [{
        children: [
          new d.Paragraph({ text: state.tmc.discipline + " — " + state.tmc.degree, heading: d.HeadingLevel.HEADING_1 }),
          new d.Paragraph({ text: state.college + "   ·   TMC alignment (DRAFT — verify against official template)" }),
          new d.Paragraph({ text: t.aligned + " C-ID aligned · " + t.filled + "/" + t.required + " slots filled · " + t.units + " units mapped" }),
          new d.Paragraph({ text: "" }),
          new d.Table({ width: { size: 100, type: d.WidthType.PERCENTAGE }, rows: rows })
        ]
      }]
    });
    d.Packer.toBlob(doc).then(function (blob) { downloadBlob(blob, slug() + ".docx"); });
  }
  function cell(d, text, opts) {
    opts = opts || {};
    return new d.TableCell({
      shading: opts.shade ? { fill: opts.shade } : undefined,
      columnSpan: opts.span,
      children: [new d.Paragraph({ children: [new d.TextRun({ text: text || "", bold: !!opts.bold, color: opts.color })] })]
    });
  }
  function headerRow(d) {
    return new d.TableRow({ children: [
      cell(d, "C-ID", { bold: true, shade: "0B2A4A", color: "FFFFFF" }),
      cell(d, "TMC Course", { bold: true, shade: "0B2A4A", color: "FFFFFF" }),
      cell(d, "Units", { bold: true, shade: "0B2A4A", color: "FFFFFF" }),
      cell(d, "Your College Course", { bold: true, shade: "0B2A4A", color: "FFFFFF" }),
      cell(d, "Units", { bold: true, shade: "0B2A4A", color: "FFFFFF" }),
      cell(d, "Status", { bold: true, shade: "0B2A4A", color: "FFFFFF" })
    ] });
  }
  function sectionRow(d, sec) {
    var need = sec.select === "all" ? "all required" : ("select " + sec.select);
    return new d.TableRow({ children: [cell(d, sec.name + "  (" + need + (sec.units ? ", " + sec.units + " units" : "") + ")", { bold: true, shade: "EEF2FB", span: 6 })] });
  }
  function slotRow(d, slot, c) {
    var stt = statusFor(slot, c);
    return new d.TableRow({ children: [
      cell(d, slot.cid || "non-C-ID"),
      cell(d, slot.title),
      cell(d, slot.units || ""),
      cell(d, c ? (c.subj + " " + c.num + " — " + c.title) : "—"),
      cell(d, c && c.units != null ? String(c.units) : ""),
      cell(d, stt.label.replace(/^[^A-Za-z]+/, ""))
    ] });
  }

  /* ------------------------------------------------------------- selection */
  function onCollege(name) {
    setCollege(name);
    if (state.college && state.tmc) autoMatch();   // auto-populate the C-ID matches
    maybeResume();
    renderForm(document.getElementById("tmc-form-mount"));
  }
  function onTmc(id) {
    state.tmc = (window.CPL_TMC_TEMPLATES.templates || []).filter(function (t) { return t.id === id; })[0] || null;
    state.choice = {};
    if (state.college && state.tmc) autoMatch();
    maybeResume();
    renderForm(document.getElementById("tmc-form-mount"));
  }

  // pre-select the college's course that already carries each slot's C-ID
  function autoMatch() {
    if (!state.tmc || !state.tmc.sections || !state.byCid) return;
    state.tmc.sections.forEach(function (sec, si) {
      sec.slots.forEach(function (slot, sj) {
        var key = si + ":" + sj;
        if (state.choice[key]) return;
        var cids = slotCids(slot);
        for (var i = 0; i < cids.length; i++) {
          var hit = state.byCid.get(cids[i]);
          if (hit && hit.length) { state.choice[key] = hit[0]; break; }
        }
      });
    });
  }

  // if a saved submission exists for (college, tmc), load its alignments
  function maybeResume() {
    if (!state.college || !state.tmc) return;
    sbLoad(state.college, state.tmc.id).then(function (row) {
      if (!row || !row.alignments) return;
      // only adopt saved rows the curator hadn't already auto/hand-matched away from
      Object.keys(row.alignments).forEach(function (k) {
        var a = row.alignments[k];
        state.choice[k] = { subj: a.subj, num: a.num, title: a.title, units: a.units, cid: a.course_cid || null };
      });
      renderForm(document.getElementById("tmc-form-mount"));
      setMsg("Resumed your saved alignment from " + (row.updated_at || "Supabase").slice(0, 10) + ".", "ok");
    });
  }

  /* ------------------------------------------------------------------ boot */
  function boot() {
    if (booted) return;
    booted = true;
    ensureCss();
    root = document.getElementById("tmc-builder-root");
    if (!root) return;
    render(); // shell + (empty) selectors immediately
    // lazy-load the TMC templates (small) then the per-college COCI index (big)
    ensureScript("tmc_templates.js", "CPL_TMC_TEMPLATES", function () {
      render(); // TMC dropdown now populated
      loadCollegeCourses(function (ok) {
        state.loadedCourses = ok;
        render(); // college dropdown now populated
      });
    });
  }

  window.CPL_TMC_BUILDER = { boot: boot, _state: state };
})();
