/*
 * unified_courses.js — UI for the "Unified Courses" dashboard tab.
 * Renders / filters / sorts the COCI course-identity layer from
 * window.CPL_UNIFIED_COURSES (generated by excel_to_dashboard.py), and adds
 * lightweight curation: allowed reviewers sign in (Supabase magic link) and
 * assign a discipline where blank. Edits are written to Supabase (kb_curation)
 * and shown immediately via a live overlay; a sync script folds them into
 * git (kb/coci_curation.json) so the daily regen is regen-safe.
 *
 * The anon key below is the PUBLIC Supabase key (safe to embed) — Row-Level
 * Security is what restricts writes to authenticated allowed reviewers.
 */
(function () {
  "use strict";

  var SUPABASE_URL = "https://hvuwhnbuahrtptokpqfh.supabase.co";
  var SUPABASE_ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dXdobmJ1YWhydHB0b2twcWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NzI0ODEsImV4cCI6MjA5MTE0ODQ4MX0.p0q-93iTM0GkF2z8_q7Vvl1tsX9SFGMM-W7Wdx7WfmM";
  var MAX_VISIBLE = 500;

  function el(tag, attrs, kids) {
    var n = document.createElement(tag);
    if (attrs) Object.keys(attrs).forEach(function (k) {
      if (k === "class") n.className = attrs[k];
      else if (k === "html") n.innerHTML = attrs[k];
      else if (k === "title") n.title = attrs[k];
      else n.setAttribute(k, attrs[k]);
    });
    (kids || []).forEach(function (c) { n.appendChild(typeof c === "string" ? document.createTextNode(c) : c); });
    return n;
  }
  function uniqSorted(arr) { return Array.from(new Set(arr.filter(Boolean))).sort(); }

  // ---- Supabase auth (magic-link implicit flow, no library) ----------------
  function jwtEmail(t) {
    try { return JSON.parse(atob(t.split(".")[1].replace(/-/g, "+").replace(/_/g, "/"))).email || ""; }
    catch (e) { return ""; }
  }
  // A Supabase access token is a JWT: three base64url segments, ASCII only.
  // Reject anything else so a truncated/garbled token (e.g. a stray "…") can
  // never reach a request header and throw the cryptic non-Latin-1 fetch error.
  function isValidJwt(t) {
    return typeof t === "string" &&
      /^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(t);
  }
  function getSession() {
    try {
      var s = JSON.parse(sessionStorage.getItem("cpl_sb") || "null");
      if (s && isValidJwt(s.access_token) && s.exp > Date.now()) return s;
    } catch (e) {}
    // No valid session — drop any stale/garbled value so the UI shows "Sign
    // in" again instead of pretending to be signed in and breaking writes.
    sessionStorage.removeItem("cpl_sb");
    return null;
  }
  function consumeAuthHash() {
    var h = location.hash || "";
    if (h.indexOf("access_token=") < 0) return false;
    var p = {};
    h.replace(/^#/, "").split("&").forEach(function (kv) {
      var a = kv.split("="); p[decodeURIComponent(a[0])] = decodeURIComponent(a[1] || "");
    });
    if (!isValidJwt(p.access_token)) return false;
    sessionStorage.setItem("cpl_sb", JSON.stringify({
      access_token: p.access_token, email: jwtEmail(p.access_token),
      exp: Date.now() + (parseInt(p.expires_in || "3600", 10) * 1000)
    }));
    history.replaceState(null, "", location.pathname + location.search);
    location.hash = "unified-courses";
    return true;
  }
  function signIn(email) {
    // GoTrue's REST endpoint takes the redirect as a ?redirect_to= query param
    // (it ignores a body "options" object — that's the JS client's shape). The
    // URL must be in the project's allowed Redirect URLs.
    var redirect = encodeURIComponent(location.origin + location.pathname);
    return fetch(SUPABASE_URL + "/auth/v1/otp?redirect_to=" + redirect, {
      method: "POST",
      headers: { "apikey": SUPABASE_ANON, "Content-Type": "application/json" },
      body: JSON.stringify({ email: email, create_user: true })
    });
  }
  function signOut() { sessionStorage.removeItem("cpl_sb"); }
  function fetchOverlay() {
    return fetch(SUPABASE_URL + "/rest/v1/kb_curation?select=course_id,value&field=eq.discipline",
      { headers: { "apikey": SUPABASE_ANON } })
      .then(function (r) { return r.ok ? r.json() : []; })
      .then(function (arr) { var m = {}; arr.forEach(function (x) { m[x.course_id] = x.value; }); return m; })
      .catch(function () { return {}; });
  }
  function saveDiscipline(courseId, value, sess) {
    return fetch(SUPABASE_URL + "/rest/v1/kb_curation", {
      method: "POST",
      headers: {
        "apikey": SUPABASE_ANON, "Authorization": "Bearer " + sess.access_token,
        "Content-Type": "application/json", "Prefer": "resolution=merge-duplicates,return=minimal"
      },
      body: JSON.stringify({ course_id: courseId, field: "discipline", value: value, reviewer_email: sess.email })
    });
  }

  function init() {
    var data = window.CPL_UNIFIED_COURSES;
    var pane = document.getElementById("tab-unified-courses");
    if (!pane) return;
    var wrap = pane.querySelector("#uc-table-wrap");
    var toolbar = pane.querySelector("#uc-toolbar");
    var summary = pane.querySelector("#uc-summary");
    if (!data || !data.rows || !data.rows.length) {
      if (wrap) wrap.innerHTML = '<p style="padding:1rem;color:#666;">Unified course data is not available in this build.</p>';
      return;
    }
    var colleges = data.colleges || [];
    var mqList = data.mq_disciplines || [];
    var rows = data.rows;
    var session = getSession();

    var state = { kind: "", disc: "", credit: "", conf: "", artic: "", flagged: false, q: "", sort: "title", dir: 1 };

    // ---- toolbar ----
    function sel(id, label, opts) {
      var s = el("select", { id: id, class: "uc-filter" });
      s.appendChild(el("option", { value: "" }, [label]));
      opts.forEach(function (o) { s.appendChild(el("option", { value: o }, [o])); });
      return s;
    }
    var fKind = sel("uc-kind", "All kinds", ["Course", "Cluster"]);
    var fDisc = sel("uc-disc", "All disciplines", uniqSorted(rows.map(function (r) { return r.disc; })));
    var fCredit = sel("uc-credit", "All credit statuses", uniqSorted(rows.map(function (r) { return r.credit; })));
    var fConf = sel("uc-conf", "Any confidence", ["high (≥0.85)", "medium (0.7–0.84)", "low (<0.7)"]);
    var fArtic = sel("uc-artic", "Adoption: any", ["Has earned articulation", "No articulation yet"]);
    var search = el("input", { id: "uc-search", type: "search", placeholder: "Search title or ID…", class: "uc-filter" });
    var flagged = el("label", { class: "uc-flag-toggle" }, []);
    var flaggedCb = el("input", { type: "checkbox", id: "uc-flagged" });
    flagged.appendChild(flaggedCb); flagged.appendChild(document.createTextNode(" Flagged only"));
    var blanksBtn = el("label", { class: "uc-flag-toggle" }, []);
    var blanksCb = el("input", { type: "checkbox", id: "uc-blanks" });
    blanksBtn.appendChild(blanksCb); blanksBtn.appendChild(document.createTextNode(" Blank discipline only"));
    var exportBtn = el("a", { class: "uc-export", href: data.export_path || "exports/unified_courses.xlsx",
      title: "Download the full set (incl. singletons) as Excel" }, ["↓ Export all to .xlsx"]);
    var auth = el("span", { id: "uc-auth", class: "uc-auth" });

    [fKind, fDisc, fCredit, fConf, fArtic, search, flagged, blanksBtn, auth, exportBtn]
      .forEach(function (c) { toolbar.appendChild(c); });

    function renderAuth() {
      auth.innerHTML = "";
      if (session) {
        auth.appendChild(el("span", { class: "uc-auth-on" }, ["✎ Curating as " + session.email + " "]));
        var out = el("a", { href: "#", class: "uc-auth-link" }, ["Sign out"]);
        out.onclick = function (e) { e.preventDefault(); signOut(); session = null; renderAuth(); render(); };
        auth.appendChild(out);
      } else {
        var link = el("a", { href: "#", class: "uc-auth-link" }, ["Sign in to curate"]);
        link.onclick = function (e) {
          e.preventDefault();
          var email = prompt("Reviewer email — we'll send a magic sign-in link:");
          if (!email) return;
          signIn(email.trim()).then(function (r) {
            if (r.ok) { alert("Check your email for the sign-in link, then return here. (Request it once — repeated tries hit a send limit.)"); return; }
            if (r.status === 429) { alert("Too many sign-in emails just now — please wait a few minutes, then request one link."); return; }
            r.json().then(function (b) {
              alert("Sign-in request failed (HTTP " + r.status + (b && b.msg ? "): " + b.msg : ")") +
                    ".\nIf this persists, confirm your email is in allowed_reviewers and that this URL is in the Supabase Redirect URLs.");
            }).catch(function () { alert("Sign-in request failed (HTTP " + r.status + ")."); });
          }).catch(function () { alert("Network error sending the sign-in link."); });
        };
        auth.appendChild(link);
      }
    }

    function confTier(c) { if (c == null) return ""; if (c >= 0.85) return "high"; if (c >= 0.7) return "medium"; return "low"; }
    function rowFlagged(r) { var f = r.flags || {}; return !!(f.over_merged || f.credit_mixed || f.top_mixed || f.ncc_mixed); }
    function passes(r) {
      if (state.kind && r.kind !== state.kind) return false;
      if (state.disc && r.disc !== state.disc) return false;
      if (state.credit && r.credit !== state.credit) return false;
      if (state.conf && confTier(r.conf) !== state.conf) return false;
      var hasArt = (r.adopted && r.adopted.length) || (r.potential && r.potential.length);
      if (state.artic === "Has earned articulation" && !hasArt) return false;
      if (state.artic === "No articulation yet" && hasArt) return false;
      if (state.flagged && !rowFlagged(r)) return false;
      if (blanksCb.checked && r.disc) return false;
      if (state.q) {
        var q = state.q.toLowerCase();
        if ((r.title || "").toLowerCase().indexOf(q) < 0 && (r.id || "").toLowerCase().indexOf(q) < 0) return false;
      }
      return true;
    }
    function names(idxList) { return (idxList || []).map(function (i) { return colleges[i]; }).filter(Boolean).sort(); }
    function adoptionCell(idxList, kind) {
      var n = (idxList || []).length;
      var span = el("span", { class: "uc-adopt " + kind }, [String(n)]);
      if (n) span.title = names(idxList).join("\n");
      return span;
    }
    function flagBadges(r) {
      var f = r.flags || {}, out = el("span", {});
      function b(on, txt, cls, tip) { if (on) out.appendChild(el("span", { class: "uc-badge " + cls, title: tip }, [txt])); }
      b(f.over_merged, "over-merge", "warn", "subject_spread ≥ 8 — possible over-merge; review");
      b(f.credit_mixed, "credit", "mix", "members disagree on credit status");
      b(f.top_mixed, "TOP", "mix", "members disagree on TOP code");
      b(f.ncc_mixed, "noncredit", "mix", "members disagree on noncredit category");
      b(r._curated, "curated ✓", "ok", "discipline set by a reviewer (pending git sync)");
      if (!f.reviewed && !r._curated) b(true, "unreviewed", "muted", "AI draft — not human-reviewed");
      return out;
    }

    // discipline cell: click-to-edit when signed in
    function disciplineCell(r) {
      var td = el("td", {});
      function showValue() {
        td.innerHTML = "";
        var v = r.disc || "—";
        if (session) {
          var span = el("span", { class: "uc-disc-edit", title: "Click to set discipline" }, [v]);
          span.onclick = function () { showEditor(); };
          td.appendChild(span);
        } else { td.appendChild(document.createTextNode(v)); }
      }
      function showEditor() {
        td.innerHTML = "";
        var s = el("select", { class: "uc-filter" });
        s.appendChild(el("option", { value: "" }, ["— choose —"]));
        mqList.forEach(function (d) {
          var o = el("option", { value: d }, [d]);
          if (d === r.disc) o.setAttribute("selected", "selected");
          s.appendChild(o);
        });
        td.appendChild(s);
        s.focus();
        s.onchange = function () {
          var val = s.value;
          if (!val) { showValue(); return; }
          if (!session || !isValidJwt(session.access_token)) {
            signOut(); session = null; renderAuth(); render();
            alert("Your sign-in session is no longer valid — please sign in again.");
            return;
          }
          s.disabled = true;
          saveDiscipline(r.id, val, session).then(function (resp) {
            if (resp.ok) { r.disc = val; r.flags.reviewed = true; r._curated = true; showValue(); }
            else { alert("Save failed (status " + resp.status + "). Are you an allowed reviewer?"); showValue(); }
          }).catch(function (err) {
            var m = (err && err.message) || "network error";
            // A corrupted token throws a synchronous header error before the
            // request leaves the browser — clear it and prompt re-sign-in.
            if (/ISO-8859-1|headers/i.test(m)) {
              signOut(); session = null; renderAuth(); render();
              alert("Your sign-in session looks corrupted — you've been signed out. Please sign in again.");
            } else {
              alert("Could not save: " + m);
              showValue();
            }
          });
        };
        s.onblur = function () { setTimeout(function () { if (td.contains(s)) showValue(); }, 150); };
      }
      showValue();
      return td;
    }

    var COLS = [
      { key: "kind", label: "Kind" }, { key: "id", label: "ID" }, { key: "title", label: "Title" },
      { key: "disc", label: "Discipline" }, { key: "credit", label: "Credit" },
      { key: "units", label: "Units" }, { key: "top", label: "TOP" }, { key: "subj", label: "Subject(s)" },
      { key: "members", label: "Members" }, { key: "adopted", label: "Adopted" },
      { key: "potential", label: "Potential Adoption" }, { key: "conf", label: "Conf." }, { key: "flags", label: "Flags" }
    ];

    function render() {
      var matched = rows.filter(passes);
      matched.sort(function (a, b) {
        var k = state.sort, av, bv;
        if (k === "adopted" || k === "potential") { av = (a[k] || []).length; bv = (b[k] || []).length; }
        else if (k === "members" || k === "units" || k === "conf") { av = a[k] || 0; bv = b[k] || 0; }
        else { av = (a[k] == null ? "" : String(a[k])).toLowerCase(); bv = (b[k] == null ? "" : String(b[k])).toLowerCase(); }
        return (av < bv ? -1 : av > bv ? 1 : 0) * state.dir;
      });
      summary.textContent = matched.length.toLocaleString() + " of " + rows.length.toLocaleString() +
        " in-browser identities" + (data.count_total ? " (· " + data.count_total.toLocaleString() + " total incl. singletons in the export)" : "") +
        (matched.length > MAX_VISIBLE ? " — showing first " + MAX_VISIBLE + "; refine filters or use the export" : "") +
        (session ? " · click a Discipline cell to curate" : "");

      var table = el("table", { class: "uc-table" });
      var thead = el("thead"), htr = el("tr");
      COLS.forEach(function (c) {
        var th = el("th", { "data-key": c.key }, [c.label + (state.sort === c.key ? (state.dir > 0 ? " ▲" : " ▼") : "")]);
        th.style.cursor = "pointer";
        th.onclick = function () { if (state.sort === c.key) state.dir = -state.dir; else { state.sort = c.key; state.dir = 1; } render(); };
        htr.appendChild(th);
      });
      thead.appendChild(htr); table.appendChild(thead);
      var tb = el("tbody");
      matched.slice(0, MAX_VISIBLE).forEach(function (r) {
        var tr = el("tr");
        tr.appendChild(el("td", {}, [r.kind || ""]));
        tr.appendChild(el("td", { class: "uc-id" }, [r.id || ""]));
        tr.appendChild(el("td", {}, [r.title || ""]));
        tr.appendChild(disciplineCell(r));
        tr.appendChild(el("td", {}, [r.credit || "—"]));
        tr.appendChild(el("td", {}, [r.units == null ? "—" : String(r.units)]));
        tr.appendChild(el("td", {}, [r.top || "—"]));
        tr.appendChild(el("td", {}, [(r.subj || []).join(", ")]));
        tr.appendChild(el("td", {}, [String(r.members == null ? "" : r.members)]));
        tr.appendChild(el("td", {}, [adoptionCell(r.adopted, "adopted")]));
        tr.appendChild(el("td", {}, [adoptionCell(r.potential, "potential")]));
        tr.appendChild(el("td", {}, [r.conf == null ? "—" : r.conf.toFixed(2)]));
        tr.appendChild(el("td", {}, [flagBadges(r)]));
        tb.appendChild(tr);
      });
      table.appendChild(tb);
      wrap.innerHTML = ""; wrap.appendChild(table);
    }

    fKind.onchange = function () { state.kind = this.value; render(); };
    fDisc.onchange = function () { state.disc = this.value; render(); };
    fCredit.onchange = function () { state.credit = this.value; render(); };
    fConf.onchange = function () { state.conf = this.value.split(" ")[0]; render(); };
    fArtic.onchange = function () { state.artic = this.value; render(); };
    flaggedCb.onchange = function () { state.flagged = this.checked; render(); };
    blanksCb.onchange = function () { render(); };
    var t; search.oninput = function () { clearTimeout(t); var v = this.value; t = setTimeout(function () { state.q = v; render(); }, 180); };

    renderAuth();
    render();
    // Merge any live Supabase curation overlay (so curated values show before git sync)
    fetchOverlay().then(function (m) {
      var changed = false;
      rows.forEach(function (r) {
        if (m[r.id] != null) { r.disc = m[r.id]; r.flags.reviewed = true; r._curated = true; changed = true; }
      });
      if (changed) render();
    });
  }

  // Process an auth redirect hash as early as possible, then init.
  consumeAuthHash();
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
