insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at)
values
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 001', 'unified_title_override', 'The Acoustical Apprentice, Safety, and the Trade', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 004', 'unified_title_override', 'Foundations and Floors', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 006', 'unified_title_override', 'Structural Framing', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 007', 'unified_title_override', 'Form Detailing, Construction & Erection', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 008', 'unified_title_override', 'Exterior Finish', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 009', 'unified_title_override', 'Blueprint Reading-Commercial', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 010', 'unified_title_override', 'Concrete - Precast and Prestressed', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 011', 'unified_title_override', 'Interior Finish', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 012', 'unified_title_override', 'Layout/Leveling Construction Site Practice', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 013', 'unified_title_override', 'Engineered Structural Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 014', 'unified_title_override', 'Interior Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 015', 'unified_title_override', 'Stair Building', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 016', 'unified_title_override', 'Roof Framing', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 018', 'unified_title_override', 'Commercial Concrete', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 020', 'unified_title_override', 'Commercial Door Hardware', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 102', 'unified_title_override', 'Basic Applications', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 103', 'unified_title_override', 'Mathematics for Drywall/Lathers', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 104', 'unified_title_override', 'Exterior/Advanced Fire Control System and Partitions', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 105', 'unified_title_override', 'Doors, Windows, Exterior Systems/Building Documents', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 106', 'unified_title_override', 'Blueprint Reading 1', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 107', 'unified_title_override', 'Blueprint Reading 2', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 108', 'unified_title_override', 'Blueprint Reading 3', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 110', 'unified_title_override', 'Welding 1', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 111', 'unified_title_override', 'Residential Metal Framing', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 112', 'unified_title_override', 'Exterior Systems and Trims', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 113', 'unified_title_override', 'Interior Metal Lathing System, Sound Control', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 114', 'unified_title_override', 'Ceilings, Shaft Protection and Demountable Partitions', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 115', 'unified_title_override', 'Arches, Furring and Advanced Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 116', 'unified_title_override', 'Advanced Construction Techniques', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 117', 'unified_title_override', 'Drywall Lathing Trade Safety', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1201', 'unified_title_override', 'Modular System Installer Safety', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1202', 'unified_title_override', 'Introduction to Office Modular Systems Installation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1204', 'unified_title_override', 'Print Reading Measurement and Layout', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1205', 'unified_title_override', 'Modular Systems Construction and Quality Control 1', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1206', 'unified_title_override', 'Modular System Construction and Quality Control 2', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1207', 'unified_title_override', 'Drapery, Window Coverings, and Fine Furnishings', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1208', 'unified_title_override', 'Floor to Ceiling Wall System Construction', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 278', 'unified_title_override', 'Worker Safety and Tool Skills for Pile Drivers', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 279', 'unified_title_override', 'Pile Driver Math Applications', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 280', 'unified_title_override', 'Pile Driver Rigging', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 281', 'unified_title_override', 'Form Detailing, Construction, and Erection for Pile Drivers', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 282', 'unified_title_override', 'Welding 1: Introduction to SMAW', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 283', 'unified_title_override', 'Introduction to Land and Water Pile Driving', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 285', 'unified_title_override', 'Advanced Pile Driving Land and Water', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 286', 'unified_title_override', 'Wharfage and Marine Structures', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 287', 'unified_title_override', 'Welding 3: Advanced SMAW', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 288', 'unified_title_override', 'Introduction to Structural Blueprints and Layout Instruments', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 289', 'unified_title_override', 'Advanced Structural Blueprints and Bridge Building', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 290', 'unified_title_override', 'Falsework, Shoring, and Heavy Timber Framing', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 291', 'unified_title_override', 'Advanced Formwork', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 292', 'unified_title_override', 'Welding 3 FCAW', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 293', 'unified_title_override', 'Welding 4 FCAW Pipe', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 294', 'unified_title_override', 'Welding 6: FCAW 4G Certification', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 302', 'unified_title_override', 'Introduction to Scaffolds and Confined Space', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 305', 'unified_title_override', 'Welded Frame and Mobile Tower Scaffold', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 306', 'unified_title_override', 'Blueprint Reading-Residential', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 307', 'unified_title_override', 'System Scaffold', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 308', 'unified_title_override', 'Suspended Scaffolds and Shoring Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 309', 'unified_title_override', 'Tube and Clamp Scaffold', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 311', 'unified_title_override', 'Blueprint Reading for Scaffold Erectors', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 313', 'unified_title_override', 'Introduction to Welding and Cutting', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 314', 'unified_title_override', 'Welding 2', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 316', 'unified_title_override', 'Hazard Awareness for Scaffold Erectors', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 404', 'unified_title_override', 'Tools of the Trade and Installation of Hardwood Floors', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 405', 'unified_title_override', 'Finishing and Repairing Floors', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 503', 'unified_title_override', 'Introduction to Working Drawings, Construction Math and Fire Stop Installation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 504', 'unified_title_override', 'Residential Blueprint Reading and Forklift Safety', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 505', 'unified_title_override', 'Residential Insulation and Weatherization', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 506', 'unified_title_override', 'Commercial Blueprint Reading and Mobile Tower Scaffolds', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 507', 'unified_title_override', 'Commercial and Industrial Insulation and Aerial Lift', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 508', 'unified_title_override', 'Energy Conservation Codes and Standards', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 703', 'unified_title_override', 'Introduction to Grid Ceiling Installation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 705', 'unified_title_override', 'Specialty Ceiling Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 706', 'unified_title_override', 'Access Floor Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 708', 'unified_title_override', 'Suspended Framing Ceiling Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 709', 'unified_title_override', 'Infection Control Risk Assessment and Hospital Code for Acoustical Installers', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 711', 'unified_title_override', 'Integrated Ceilings and Special Techniques', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 712', 'unified_title_override', 'Advanced Grid Ceilings', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 714', 'unified_title_override', 'Acoustical Blueprint Reading', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 715', 'unified_title_override', 'Specialty Systems', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 856', 'unified_title_override', 'Millwright Safety and Tool Skills', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 857', 'unified_title_override', 'The Millwright Apprentice, the Trade, and 16 Hour Safety', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 858', 'unified_title_override', 'Millwright Math Applications', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 859', 'unified_title_override', 'Millwright Rigging', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 860', 'unified_title_override', 'Materials of Construction', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 861', 'unified_title_override', 'Layout Procedures for Millwrights', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 862', 'unified_title_override', 'Precision Optical Instruments', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 863', 'unified_title_override', 'Blueprint Reading and Aerial Lift', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 864', 'unified_title_override', 'Cutting and Welding 1', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 865', 'unified_title_override', 'Welding 2 SMAW', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 866', 'unified_title_override', 'Monorails', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 867', 'unified_title_override', 'Conveyors for Millwrights', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 868', 'unified_title_override', 'Machinery Installation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 869', 'unified_title_override', 'Machinery Maintenance for Millwrights', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 870', 'unified_title_override', 'Precision Tools for Millwrights', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 871', 'unified_title_override', 'Turbines', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 872', 'unified_title_override', 'Cutting and Welding 3', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 901', 'unified_title_override', 'Mill Cabinet Safety and Tool Skills', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 902', 'unified_title_override', 'The Mill Cabinet Apprentice and the Trade', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 903', 'unified_title_override', 'Math for the Mill Cabinet Trade', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 904', 'unified_title_override', 'Basic Cabinet Making', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 905', 'unified_title_override', 'Basic Blueprint Reading Mill Cabinet', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 906', 'unified_title_override', 'Machinery Maintenance for Mill Cabinet', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 907', 'unified_title_override', 'Cabinet Hardware Installation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 908', 'unified_title_override', 'Sanding, Stains, and Finish Preparation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 909', 'unified_title_override', 'Advanced Machinery Operation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 910', 'unified_title_override', 'Advanced Blueprint Reading for Mill Cabinet', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 911', 'unified_title_override', 'Advanced Cabinet Making', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 912', 'unified_title_override', 'Veneers, Laminate, and Finishing', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 913', 'unified_title_override', 'CAD Basics for Mill Cabinetry', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 914', 'unified_title_override', 'Introduction to CNC', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 915', 'unified_title_override', 'Solid Surface Material, Fabrication, and Installation', 'carp-title-s109@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 916', 'unified_title_override', 'Advanced Project for Mill Cabinet', 'carp-title-s109@bot', now())
on conflict (course_id, field) do nothing;
