// Regression tests for the CER triage worklist's 💡 identity-anchored
// suggestion chips (2026-07-07, Rule 5c integration Phase 1).
//
// kb/unclassified_suggestions.json is OPTIONAL (generated by the daily cron's
// kb/_suggest_unclassified.py). Guards:
//   1. file absent → worklist renders normally, no chips, no crash;
//   2. file present → chips render per kind (CCN/C-ID/COS/course) with the
//      right labels; clicking a chip FILLS the title input (and, for COS, the
//      issuer input) and re-arms the Save button — never auto-saves;
//   3. rows without suggestions get no chips; signed-out chips are disabled.
//
// Run from repo root: `npm test` (or `node tests/cer_wl_suggestions.test.js`).
const fs = require("fs");
const { JSDOM } = require("jsdom");

const src = fs.readFileSync("credential_reference.js", "utf8");
const results = [];
function check(name, cond) { results.push([name, !!cond]); }
function txt(el) { return (el && el.textContent || "").trim(); }

const fixtureRows = [
  { ut: "Existing Credential", raw_count: 1, articulations: [], audit_tags: {}, audit_tag_total: 0 },
];
const auditStub = {
  title_cards: [
    { raw_title: "ADM JUS 003 - Legal Aspects of Evidence", unified_title: null, tags: ["unclassified_in_map"], band: "<0.40" },
    { raw_title: "Weird Cert Nobody Suggested", unified_title: null, tags: ["unclassified_in_map"], band: "<0.40" },
    { raw_title: "CompTIA Cert Prep Thing", unified_title: null, tags: ["unclassified_in_map"], band: "<0.40" },
  ],
  stats: {},
};
const suggStub = {
  suggestions: {
    "ADM JUS 003 - Legal Aspects of Evidence": [
      { kind: "cid", id: "AJ 124", title: "Legal Aspects of Evidence", code: "ADM JUS 003" },
      { kind: "course", title: "Legal Aspects of Evidence II", code: "ADM JUS 003", share: 0.8, colleges: 5 },
    ],
    "CompTIA Cert Prep Thing": [
      { kind: "cos", id: "1234-A", title: "CompTIA A+", org: "Computing Technology Industry Association (CompTIA)" },
    ],
  },
};

function makeDom(opts) {
  const html = `<!DOCTYPE html><html><body>
  <div id="tab-credential-reference">
    <div id="cr-toolbar"></div><div id="cr-summary"></div><div id="cr-table-wrap"></div>
  </div></body></html>`;
  const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.org/" });
  const { window } = dom;
  window.CPL_CREDENTIAL_REFERENCE = { _generated_at: "t", top_categories: {}, unified_titles: fixtureRows };
  if (opts.signedIn) {
    window.sessionStorage.setItem("cpl_sb", JSON.stringify({
      access_token: "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1hcEByY2NkLmVkdSJ9.c2ln",
      refresh_token: "rt", email: "map@rccd.edu", exp: Date.now() + 3600e3,
    }));
  }
  window.fetch = function (url, o) {
    url = String(url); const method = (o && o.method) || "GET";
    const ok = (b) => Promise.resolve({ ok: true, status: 200, json: () => Promise.resolve(b) });
    if (url.indexOf("unclassified_suggestions.json") >= 0)
      return opts.withSuggs ? ok(suggStub)
        : Promise.resolve({ ok: false, status: 404, json: () => Promise.reject(new Error("404")) });
    if (url.indexOf("exhibit_audit/latest.json") >= 0) return ok(auditStub);
    if (url.indexOf("kb_curation") >= 0 && method === "GET") return ok([]);
    if (url.indexOf("cos_matches.json") >= 0)
      return Promise.resolve({ ok: false, status: 404, json: () => Promise.reject(new Error("404")) });
    return ok([]);
  };
  window.eval(src);
  return window;
}
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

(async () => {
  // A — no suggestions file.
  const wa = makeDom({ signedIn: true, withSuggs: false });
  await sleep(100);
  wa.document.querySelector(".cr-triage-btn").click();
  await sleep(100);
  check("absent: worklist rows render", wa.document.querySelectorAll(".cr-wl-table tbody tr").length === 3);
  check("absent: no chips, no crash", wa.document.querySelectorAll(".cr-wl-sugg").length === 0);

  // B — suggestions present, signed in.
  const wb = makeDom({ signedIn: true, withSuggs: true });
  await sleep(100);
  wb.document.querySelector(".cr-triage-btn").click();
  await sleep(100);
  const db = wb.document;
  const rows = Array.from(db.querySelectorAll(".cr-wl-table tbody tr"));
  const rowOf = (t) => rows.find((tr) => txt(tr.querySelector(".cr-wl-rawt")) === t);
  const aj = rowOf("ADM JUS 003 - Legal Aspects of Evidence");
  const ajChips = Array.from(aj.querySelectorAll(".cr-wl-sugg"));
  check("present: two chips on the C-ID row", ajChips.length === 2);
  check("present: C-ID chip label", /💡 C-ID AJ 124: Legal Aspects of Evidence/.test(txt(ajChips[0])));
  check("present: course chip label", /💡 course title:/.test(txt(ajChips[1])));
  const titleInp = aj.querySelector(".cr-wl-title-input");
  const saveBtn = aj.querySelector(".cr-wl-save");
  ajChips[0].click();
  check("click: fills the title input", titleInp.value === "Legal Aspects of Evidence");
  check("click: does NOT auto-save", txt(saveBtn) === "Save");
  const cos = rowOf("CompTIA Cert Prep Thing");
  const cosChip = cos.querySelector(".cr-wl-sugg");
  check("present: COS chip label carries org", /COS: CompTIA A\+ — Computing Technology/.test(txt(cosChip)));
  cosChip.click();
  check("click: COS fills title", cos.querySelector(".cr-wl-title-input").value === "CompTIA A+");
  check("click: COS fills issuer", /CompTIA/.test(cos.querySelector(".cr-wl-iss-input").value));
  check("present: unsuggested row has no chips",
    rowOf("Weird Cert Nobody Suggested").querySelectorAll(".cr-wl-sugg").length === 0);

  // C — signed out: chips visible but disabled.
  const wc = makeDom({ signedIn: false, withSuggs: true });
  await sleep(100);
  wc.document.querySelector(".cr-triage-btn").click();
  await sleep(100);
  const chip = wc.document.querySelector(".cr-wl-sugg");
  check("signed-out: chip rendered but disabled", chip && chip.disabled === true);

  let pass = 0;
  for (const [n, ok] of results) { console.log((ok ? "PASS" : "FAIL") + "  " + n); if (ok) pass++; }
  console.log(`\n${pass}/${results.length} assertions passed`);
  process.exit(pass === results.length ? 0 : 1);
})();
