// Guards the CCR filter-bar cleanup (Session 69, Sam's asks 1–3):
//   #1 the Search box LEADS the toolbar (top-left) and is widened.
//   #2 the "Generated by" provenance FILTER is removed — but the per-row ⚙
//      discipline-provenance BADGE is KEPT (the filter was low-value once the
//      inference backlog cleared; the badge still conveys provenance per row).
//   #3 the Subjects <select> is narrowed (maxWidth) so it stops eating the row.
// Plus a regression guard that moving search to first didn't break its wiring.
//
// Run from repo root: `npm test` (or `node tests/uc_filter_bar_cleanup.test.js`).
const fs = require("fs");
const { JSDOM } = require("jsdom");

const results = [];
function check(name, cond) { results.push([name, !!cond]); }
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const src = fs.readFileSync("unified_courses.js", "utf8");

const html = `<!DOCTYPE html><html><head></head><body>
<div id="tab-unified-courses">
  <div id="uc-toolbar"></div><div id="uc-summary"></div><div id="uc-table-wrap"></div>
</div>
<script>
  window.CPL_UNIFIED_COURSES = ${JSON.stringify({
    generated_at: "2026-06-22 15:00",
    rows: [{
      // a Generated M-ID carrying a discipline-provenance source → must keep its ⚙ badge
      kind: "Course", id: "ARTS M1341", title: "Digital Imaging with Drones",
      id_system: "M-ID", disc: "Art", credit: "Credit", units: 3.0, top: "0699.00",
      subj: ["ARTS"], members: 3, adopted: [], potential: [], conf: 0.85, locked: false,
      dsrc: "title_keyword", dconf: 0.55,
      flags: { over_merged: false, credit_mixed: false, top_mixed: false, ncc_mixed: false },
    }],
    colleges: ["A"], mq_disciplines: ["Art"], topmap: {},
  })};
  window.CPL_UC_MEMBERS = { generated_at: "2026-06-22 15:02", colleges: ["A"], members: {}, topmap: {} };
</script>
</body></html>`;

(async function main() {
  const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.org/" });
  dom.window.fetch = () => Promise.resolve({ ok: true, status: 200, json: () => Promise.resolve([]) });
  dom.window.eval(src);
  await sleep(150);
  const d = dom.window.document;

  const toolbar = d.getElementById("uc-toolbar");
  const search = d.getElementById("uc-search");

  // #1 — search leads the toolbar, top-left, widened
  check("#uc-search exists", !!search);
  check("#1 search is the FIRST child of the toolbar (top-left)",
    toolbar && toolbar.firstElementChild === search);
  check("#1 search is widened (explicit width in its inline style)",
    search && /width:\s*300px/.test(search.getAttribute("style") || ""));

  // #2 — the "Generated by" provenance filter is gone…
  check("#2 the 'Generated by' filter (#uc-prov) is removed", !d.getElementById("uc-prov"));
  // …but the per-row ⚙ provenance badge is KEPT
  const badges = Array.from(d.querySelectorAll(".uc-badge")).map((b) => b.textContent);
  check("#2 the per-row ⚙ provenance badge is KEPT (title-keyword row → '⚙ title-kw')",
    badges.some((t) => /⚙\s*title-kw/.test(t)));

  // #3 — the Subjects select is narrowed
  const subj = d.getElementById("uc-subj");
  check("#3 the Subjects select is narrowed (maxWidth set)",
    subj && subj.style.maxWidth === "150px");

  // regression — search still filters after being moved to first position
  const rowCountBefore = d.querySelectorAll(".uc-table tbody tr").length;
  check("baseline: the one data row renders", rowCountBefore >= 1);
  search.value = "zzznomatchxyz";
  search.dispatchEvent(new dom.window.Event("input"));
  await sleep(240); // past the 180ms search debounce
  const matchAfter = Array.from(d.querySelectorAll(".uc-table tbody tr"))
    .some((tr) => /Digital Imaging with Drones/.test(tr.textContent));
  check("regression: typing a non-matching term filters the row out (search wiring intact)",
    !matchAfter);

  let pass = 0;
  for (const [n, ok] of results) { console.log((ok ? "PASS" : "FAIL") + "  " + n); if (ok) pass++; }
  console.log(`\n${pass}/${results.length} assertions passed`);
  process.exit(pass === results.length && results.length > 0 ? 0 : 1);
})();
