#!/usr/bin/env python3
"""Build fact-sheet/statewide_recs.js from statewide_data.js.

For every CCC-Collaborative ("statewide") exhibit, emit its distinct credit
recommendations so the public Fact Sheet can show them in a collapsible wedge
under each exhibit. Each rec carries the recommendation text (title + units, as
published) and the C-ID when the source row has one (per Sam: many recs have no
C-ID; when they do, it shows up as the CR on the PDF — so we surface all recs and
badge the C-ID when present).

Source of truth = our daily MAP dataset (View_ArticulatedMAPExhibits: Credit
Recommendation + CID Number + Course), already aggregated into statewide_data.js
by excel_to_dashboard.py's _build_statewide_adoption(). No scraping.

Output: window.CPL_STATEWIDE_RECS = { "<exhibit unified_title>": [ {t,u,cid}, ... ] }
  t = course/title text, u = units (e.g. "3.0"), cid = C-ID or "".

Run: python3 fact-sheet/_build_statewide_recs.py  (reads ./statewide_data.js)
"""
import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)


def load_statewide(path):
    s = open(path, encoding="utf-8").read()
    i = s.find("{")
    return json.loads(s[i:].strip().rstrip(";"))


# "3.0 hours in Introduction to the Administration of Justice" -> ("3.0", "Introduction…")
_UNIT_RE = re.compile(r"^\s*([\d.]+)\s*(?:hours?|units?|semester\s+units?)\s+(?:in|of|for)?\s*", re.I)


def split_units(credit):
    m = _UNIT_RE.match(credit or "")
    if m:
        return m.group(1), credit[m.end():].strip()
    return "", (credit or "").strip()


def norm_title(t):
    """Collapse phrasing variants of the same course to one key."""
    t = re.sub(r"[^a-z0-9]+", " ", (t or "").lower()).strip()
    # common abbreviation expansions so "intro" == "introduction" etc.
    t = re.sub(r"\bintro\b", "introduction", t)
    t = re.sub(r"\badmin\b", "administration", t)
    return t


def build(sw):
    out = {}
    no_ccc = []  # statewide credentials with no CCC-tagged authoritative exhibit (MAP fix list)
    for e in sw.get("exhibits", []):
        if e.get("collaborative_type") != "CCC Collaborative":
            continue
        title = e.get("unified_title") or e.get("title") or ""
        if not title:
            continue
        # Authoritative recs come ONLY from the CCC-tagged (MAP-published) exhibit
        # rows (producer's authoritative_recs); fall back to nothing if there were
        # none (caveat (a): show recs only where a true CCC exhibit exists).
        src = e.get("authoritative_recs")
        if not src:
            no_ccc.append(title)
            continue
        seen = {}  # norm_title -> rec dict (first wins; backfill cid/units)
        order = []
        for r in src:
            credit = (r.get("credit") or "").strip()
            if not credit:
                continue
            units, body = split_units(credit)
            key = norm_title(body) or norm_title(credit)
            cid = (r.get("cid") or "").strip()
            if key not in seen:
                seen[key] = {"t": body or credit, "u": units, "cid": cid}
                order.append(key)
            else:
                cur = seen[key]
                if cid and not cur["cid"]:
                    cur["cid"] = cid
                if units and not cur["u"]:
                    cur["u"] = units
        if order:
            # Stable, readable order: by title.
            recs = [seen[k] for k in order]
            recs.sort(key=lambda x: x["t"].lower())
            out[title] = recs
    return out, no_ccc


def main():
    sw_path = os.path.join(ROOT, "statewide_data.js")
    if not os.path.exists(sw_path):
        print("statewide_data.js not found at", sw_path, "— skipping (graceful).")
        return 0
    sw = load_statewide(sw_path)
    recs, no_ccc = build(sw)
    out_path = os.path.join(SCRIPT_DIR, "statewide_recs.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* Statewide CPL Credit Recommendations — auto-generated by "
                "fact-sheet/_build_statewide_recs.py from statewide_data.js. */\n")
        f.write("window.CPL_STATEWIDE_RECS = " + json.dumps(recs, ensure_ascii=False, separators=(",", ":")) + ";\n")
    n_ex = len(recs)
    n_rec = sum(len(v) for v in recs.values())
    print(f"wrote {out_path}: {n_ex} CCC exhibits, {n_rec} distinct recs")
    # Caveat (a): statewide credentials with NO CCC-tagged authoritative exhibit —
    # they show no recs. Logged here so MAP can add/fix the CCC exhibit.
    if no_ccc:
        print(f"\n⚠ {len(no_ccc)} statewide credential(s) have NO CCC-tagged authoritative "
              f"exhibit (no recs shown — fix in MAP):")
        for t in sorted(no_ccc):
            print("   -", t)
    # Spot-check
    for t in ("POST Basic Academy", "EMT Certification", "California Real Estate Salesperson License"):
        if t in recs:
            print(f"\n{t}: {len(recs[t])} recs")
            for r in recs[t][:12]:
                print(f"   [{r['cid'] or '—':<10}] {r['u'] or '?':>4}u  {r['t']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
