#!/usr/bin/env python3
"""Extract the CPL Implementation Funding model workbook into cpl_funding_data.js.

One-shot, re-runnable extractor: reads funding/CPL_Funding_Model_2026.xlsx
(sheet "CPL IMPLEMENTATION MODEL 2026") and emits ../cpl_funding_data.js
carrying `window.CPL_FUNDING` for the Implementation Funding tab
(cpl_funding.js). The output is a STATIC committed asset — it is NOT
regenerated by the daily cron. When Sam ships a new model workbook, drop it
at funding/CPL_Funding_Model_2026.xlsx (or pass a path) and re-run:

    python3 funding/_build_funding_data.py [path/to/model.xlsx]

Workbook shape (2026-06-11 rev2 — shares-first, applied by
funding/_revise_workbook_2026_06_11.py):
  row 2-3   funding-pool inputs: remaining C3, one-time D3, admin E3,
            scaling F3 (typed values); H3/I3/J3 derive the per-year tranche
  row 5-6   college-table headers; row 6 = PRIORITY SHARE / PROJECTED
            HEADCOUNT (TARGET) sub-heads
  row 7     the model inputs per priority: SHARE (E7/G7/I7) + projection
            TARGET %% (F7/H7/J7)
  row 8     ORDER 0 "SYSTEM" — statewide totals (formulas)
  rows 9-126 one row per college: typed headcount C + county data N; the
            dollar/projection columns are formulas
  row 127+  AVERAGE row + footnotes

THE BUILDER COMPUTES, IT DOES NOT READ DERIVED CELLS. openpyxl edits
invalidate Excel's cached formula values (and openpyxl cannot evaluate
formulas), so every derived number is recomputed here from the typed inputs
through the workbook's own chain — which also makes the artifact
deterministic:

  tranche      = (remaining + one_time - admin - scaling) / 3
  per_student  = tranche / Σ(college headcounts)          [informational]
  dollars_k    = (headcount / Σ headcounts) × share_k × tranche
  heads_k      = headcount × target_k                      [target, no $ effect]
  BALANCE      = tranche − SYSTEM total  (0 by construction when Σshares = 1)

PII: institutional + U.S. Census aggregates only (college/district/county
names, headcounts, dollars). No person-level data anywhere in the workbook.
"""
import json
import os
import sys

from openpyxl import load_workbook

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_XLSX = os.path.join(HERE, "CPL_Funding_Model_2026.xlsx")
OUT_JS = os.path.join(HERE, "..", "cpl_funding_data.js")
SHEET = "CPL IMPLEMENTATION MODEL 2026"
FIRST_COLLEGE_ROW = 9   # the college extent is detected by the numeric ORDER
                        # column (col A) — never a fixed last-row constant, so
                        # an inserted row can't silently fall outside the scan
YEARS = ["2026-27", "2027-28", "2028-29"]

PRIORITY_KEYS = ("p1", "p2", "p3")
PRIORITY_COLS = ("E", "G", "I")   # share input col; target input is the next col


def _num(v):
    if v is None or v == "":
        return None
    f = float(v)
    if f == int(f) and abs(f) < 1e15:
        return int(f)
    return round(f, 6)


def _money(v):
    return round(float(v), 2)


def _parse_priority_header(cell):
    """Row-5 priority cells: 'PRIORITY n\\n<description>\\n…\\nMETRIC: <metric>'."""
    lines = [ln.strip() for ln in str(cell).splitlines() if ln.strip()]
    label = lines[0].title() if lines else ""
    desc, metric = "", ""
    for ln in lines[1:]:
        if ln.upper().startswith("METRIC"):
            metric = ln.split(":", 1)[1].strip() if ":" in ln else ln
        elif not desc:
            desc = ln
    if metric:
        idx = [i for i, ln in enumerate(lines) if ln.upper().startswith("METRIC")]
        if idx and idx[0] + 1 < len(lines):
            metric = " ".join([metric] + lines[idx[0] + 1:])
    return label, desc, " ".join(metric.split())


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_XLSX
    wb = load_workbook(src, data_only=False)  # typed inputs read fine; derived cells are computed
    ws = wb[SHEET]

    # --- typed pool inputs ----------------------------------------------
    remaining = _money(ws["C3"].value)
    one_time = _money(ws["D3"].value)
    admin = _money(ws["E3"].value)
    scaling = _money(ws["F3"].value)
    net = _money(remaining + one_time - admin - scaling)
    per_year = net / len(YEARS)

    # --- priorities: share + projection target (typed, row 7) -----------
    priorities = []
    for key, col in zip(PRIORITY_KEYS, PRIORITY_COLS):
        label, desc, metric = _parse_priority_header(ws[f"{col}5"].value)
        share = float(ws[f"{col}7"].value)
        target = float(ws[chr(ord(col) + 1) + "7"].value)
        priorities.append({
            "key": key,
            "label": label,
            "description": desc,
            "metric": metric,
            "share": round(share, 6),
            "target_rate": round(target, 9),
        })
    share_sum = sum(p["share"] for p in priorities)
    if abs(share_sum - 1.0) > 1e-9:
        print(f"WARNING: priority shares sum to {share_sum} (not 1.0) — the model "
              "will not allocate the tranche exactly; the tab will surface this.")

    # --- college rows (typed: order/location/headcount/district/county/wa) --
    # Extent detection: college rows are exactly the rows whose ORDER (col A)
    # is numeric; the AVERAGE/footnote rows below carry no ORDER.
    wa_state = _num(ws["N8"].value)
    colleges = []
    last_row = FIRST_COLLEGE_ROW - 1
    r = FIRST_COLLEGE_ROW
    while isinstance(ws[f"A{r}"].value, (int, float)):
        last_row = r
        loc = ws[f"B{r}"].value
        r += 1
        if loc is None or not str(loc).strip():
            continue
        row_n = last_row
        wa = ws[f"N{row_n}"].value
        colleges.append({
            "order": _num(ws[f"A{row_n}"].value),
            "college": str(loc).strip(),
            "headcount": _num(ws[f"C{row_n}"].value) or 0,
            "district": (str(ws[f"L{row_n}"].value).strip() if ws[f"L{row_n}"].value is not None else None),
            "county": (str(ws[f"M{row_n}"].value).strip() if ws[f"M{row_n}"].value is not None else None),
            "working_adults": _num(wa) if not isinstance(wa, str) else None,
        })
    assert len(colleges) > 100, f"expected ~118 college rows, got {len(colleges)}"
    pending = [c["college"] for c in colleges if not c["headcount"]]
    if pending:
        print(f"NOTE: {len(pending)} college row(s) carry headcount 0 (allocation $0, "
              f"pending data): {', '.join(pending)}")

    # --- compute the chain (mirrors the workbook formulas exactly) -------
    total_heads = sum(c["headcount"] for c in colleges)
    per_student = per_year / total_heads

    def alloc(row, headcount):
        total = 0.0
        for p in priorities:
            heads = headcount * p["target_rate"]
            dollars = (headcount / total_heads) * p["share"] * per_year
            row[p["key"]] = _money(dollars)
            row[p["key"] + "_heads"] = round(heads, 6)
            total += dollars
        row["total"] = _money(total)

    for c in colleges:
        alloc(c, c["headcount"])
        c["headcount_pct"] = round(c["headcount"] / total_heads, 9)
        c["county_pop_pct"] = (round(c["working_adults"] / wa_state, 9)
                               if c["working_adults"] is not None and wa_state else None)

    system = {
        "order": 0, "college": "SYSTEM", "headcount": total_heads,
        "headcount_pct": 1,
        "district": (str(ws["L8"].value).strip() if ws["L8"].value is not None else None),
        "county": (str(ws["M8"].value).strip() if ws["M8"].value is not None else None),
        "working_adults": wa_state, "county_pop_pct": 1,
    }
    alloc(system, total_heads)

    projected = system["total"]
    balance = round(per_year - projected, 4)
    average_allocation = _money(sum(c["total"] for c in colleges) / len(colleges))

    # Conservation guard: the college rows must redistribute the SYSTEM row
    # exactly (the rev2 SUM-range fix makes this structural; a future edition
    # that re-breaks it gets caught here and in tests/cpl_funding.test.js).
    drift = abs(sum(c["total"] for c in colleges) - system["total"])
    assert drift < 0.5, f"college totals drift from SYSTEM by ${drift:.2f}"

    # --- footnotes (rows below the table) ---------------------------------
    footnotes = []
    for row in ws.iter_rows(min_row=last_row + 1, max_row=last_row + 6,
                            min_col=2, max_col=2, values_only=True):
        v = row[0]
        if v and (str(v).startswith("*") or str(v).lower().startswith("source:")):
            footnotes.append(str(v).strip())

    pool = {
        "remaining_2025_26": remaining,
        "one_time_2026_27": one_time,
        "admin_cost": admin,
        "admin_cost_label": str(ws["E2"].value).strip(),
        "scaling_projects_tech": scaling,
        "total_college_funding_label": str(ws["G2"].value).strip(),
        "total_college_funding": net,
        "available_per_year": _money(per_year),
        "years": YEARS,
        "ccc_headcount": total_heads,
        "per_student": per_student,
        "projected": projected,
        "balance": balance,
    }

    data = {
        "model_version": "2026-06-11.2",
        "source": "funding/CPL_Funding_Model_2026.xlsx",
        "sheet": SHEET,
        # College-headcount provenance (Sam, 2026-06-11): the workbook's
        # headcount column is pulled from the CCCCO MIS DataMart Annual/Term
        # Student Count report, Collegewide Search. headcount_label carries
        # the vintage from the workbook's own column header, so a refreshed
        # edition re-labels the tab automatically. A DataMart refresh is a
        # MODELING decision, not a drop-in swap (status filter + partial
        # years shift counts materially).
        "headcount_label": str(ws["C5"].value).strip(),
        "headcount_source": {
            "name": "CCCCO MIS DataMart — Annual/Term Student Count",
            "url": "https://datamart.cccco.edu/Students/Student_Headcount_Term_Annual.aspx",
            "selection": "Collegewide Search",
        },
        "pool": pool,
        "priorities": priorities,
        "system": system,
        "colleges": colleges,
        "average_allocation": average_allocation,
        "footnotes": footnotes,
    }

    payload = json.dumps(data, indent=1, ensure_ascii=False)
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(
            "// CPL Implementation Funding model data — generated by\n"
            "// funding/_build_funding_data.py from " + data["source"] + "\n"
            "// (model version " + data["model_version"] + ", shares-first). STATIC asset:\n"
            "// committed, not part of the daily cron. Do not hand-edit; re-run the builder.\n"
            "window.CPL_FUNDING = " + payload + ";\n"
        )
    print(f"wrote {os.path.normpath(OUT_JS)}: {len(colleges)} colleges + SYSTEM "
          f"(Σ headcount {total_heads:,}), shares {'/'.join(str(round(p['share']*100)) + '%' for p in priorities)}, "
          f"tranche ${per_year:,.2f}, balance ${balance:,.4f}")


if __name__ == "__main__":
    main()
