#!/usr/bin/env python3
"""Emit the browser copy of the Strong Workforce consortium roster.

Reads `kb/reference/swp_region_roster.json` — the resolved roster, read out of
`map_colleges.swp_region` — and writes `swp_region_data.js`
(`window.CPL_SWP_REGIONS`), so COBI can offer the Strong Workforce scope without
a Supabase round trip.

    python3 kb/_emit_swp_region_data.py

⚠️ THE ROSTER EXISTING IS NOT THE SAME AS A SURFACE OFFERING IT. It was derived
and committed on 2026-09-17 and the generator was wired to it the same day,
while `college_briefing.js` went on shipping the Strong Workforce scope disabled
with the reason "not yet in an export we hold" — which the roster had just made
false. A consumer does not notice that its prerequisite arrived. When this file
moves, check every surface that reads it, and every surface that says it cannot.

⚠️ ONE SOURCE. The JSON is the source and this file is derived; nothing here
adds a college. Re-run after refreshing the roster, in the same commit, or COBI
and the generators disagree about who is in a consortium — and they disagree
silently, because both lists look complete.

⚠️ `git add` THE OUTPUT BEFORE REBUILDING THE DEPENDENCY MAP. That builder
enumerates TRACKED files, so an untracked data file lands in the generic file
table with no `global` and no producer — it looks mapped, and the one fact a
future session needs (which script regenerates it) is the fact that is missing.
Measured here on the first run.
"""
import datetime
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "kb/reference/swp_region_roster.json")
OUT = os.path.join(ROOT, "swp_region_data.js")


def main():
    with open(SRC, encoding="utf-8") as fh:
        roster = json.load(fh)

    regions = roster.get("regions") or {}
    if not regions:
        sys.exit("ERROR: %s carries no regions." % SRC)

    payload = {
        "meta": {
            "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
            "generated_by": "kb/_emit_swp_region_data.py",
            "source": os.path.relpath(SRC, ROOT),
            "read_on": roster.get("_read_on"),
            # Carried so a surface can say WHY a college is absent rather than
            # implying it belongs to no consortium by accident.
            "caveat": roster.get("_caveat"),
        },
        # code -> {name, colleges[]}. Codes are the consortium's own (Bay, CVML,
        # IE/D …), so they stay as keys rather than being slugged.
        "regions": {
            code: {"name": blk["name"], "colleges": sorted(blk["colleges"])}
            for code, blk in sorted(regions.items())
        },
    }

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by kb/_emit_swp_region_data.py — do not hand-edit.\n")
        fh.write("// Source: %s (resolved from map_colleges.swp_region).\n" % payload["meta"]["source"])
        fh.write("window.CPL_SWP_REGIONS = ")
        json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")

    n = sum(len(b["colleges"]) for b in payload["regions"].values())
    print("regions %d | colleges %d | %s (%.1f KB)"
          % (len(payload["regions"]), n, OUT, os.path.getsize(OUT) / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
