insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at)
values
('_CREDENTIAL_REVIEW::Access Floor Systems', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Acoustical Blueprint Reading', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Blueprint Reading for Mill Cabinet', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Cabinet Making', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Formwork', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Grid Ceilings', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Machinery Operation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Pile Driving Land and Water', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Project for Mill Cabinet', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Structural Blueprints and Bridge Building', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Basic Blueprint Reading Mill Cabinet', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Basic Cabinet Making', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading and Aerial Lift', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading for Scaffold Erectors', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading-Commercial', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading-Residential', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::CAD Basics for Mill Cabinetry', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Cabinet Hardware Installation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 019', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California (CTCNC) — OSHA Training', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1203', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 312', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 608', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 707', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 710', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 713', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — FA/C', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Blueprint Reading and Mobile Tower Scaffolds', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Concrete', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Door Hardware', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial and Industrial Insulation and Aerial Lift', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Concrete - Precast and Prestressed', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Conveyors for Millwrights', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Cutting and Welding 1', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Cutting and Welding 3', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Drapery, Window Coverings, and Fine Furnishings', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Energy Conservation Codes and Standards', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Engineered Structural Systems', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Exterior Finish', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Falsework, Shoring, and Heavy Timber Framing', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Finishing and Repairing Floors', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Floor to Ceiling Wall System Construction', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Form Detailing, Construction & Erection', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Form Detailing, Construction, and Erection for Pile Drivers', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Foundations and Floors', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Hazard Awareness for Scaffold Erectors', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Infection Control Risk Assessment and Hospital Code for Acoustical Installers', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Integrated Ceilings and Special Techniques', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Interior Finish', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Interior Systems', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to CNC', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Grid Ceiling Installation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Land and Water Pile Driving', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Office Modular Systems Installation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Scaffolds and Confined Space', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Structural Blueprints and Layout Instruments', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Welding and Cutting', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Working Drawings, Construction Math and Fire Stop Installation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Layout Procedures for Millwrights', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Layout/Leveling Construction Site Practice', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Machinery Installation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Machinery Maintenance for Mill Cabinet', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Machinery Maintenance for Millwrights', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Math for the Mill Cabinet Trade', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Mill Cabinet Safety and Tool Skills', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Millwright Math Applications', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Millwright Rigging', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Millwright Safety and Tool Skills', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Modular System Construction and Quality Control 2', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Modular System Installer Safety', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Modular Systems Construction and Quality Control 1', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Monorails', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Pile Driver Math Applications', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Pile Driver Rigging', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Precision Optical Instruments', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Precision Tools for Millwrights', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Print Reading Measurement and Layout', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Residential Blueprint Reading and Forklift Safety', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Residential Insulation and Weatherization', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Roof Framing', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Sanding, Stains, and Finish Preparation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Solid Surface Material, Fabrication, and Installation', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Specialty Ceiling Systems', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Stair Building', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Structural Framing', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Suspended Framing Ceiling Systems', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Suspended Scaffolds and Shoring Systems', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::System Scaffold', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::The Acoustical Apprentice, Safety, and the Trade', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::The Mill Cabinet Apprentice and the Trade', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::The Millwright Apprentice, the Trade, and 16 Hour Safety', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Tools of the Trade and Installation of Hardwood Floors', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Tube and Clamp Scaffold', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Turbines', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Veneers, Laminate, and Finishing', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welded Frame and Mobile Tower Scaffold', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 1: Introduction to SMAW', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 2 SMAW', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 3 FCAW', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 3: Advanced SMAW', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 4 FCAW Pipe', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 6: FCAW 4G Certification', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Wharfage and Marine Structures', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Worker Safety and Tool Skills for Pile Drivers', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Cabinetmaker', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Carpenter', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Drywall Applicator', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Hardwood Floor Layer', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Insulator', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Modular Installer', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Pile Driver', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Scaffold Erector', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Shingler', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California (CTCNC) — Work Experience', 'subj_override', 'CARP', 'carp-subj-s110@bot', now()),
('_CREDENTIAL_REVIEW::Access Floor Systems', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Acoustical Blueprint Reading', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Blueprint Reading for Mill Cabinet', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Cabinet Making', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Formwork', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Grid Ceilings', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Machinery Operation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Pile Driving Land and Water', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Project for Mill Cabinet', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Advanced Structural Blueprints and Bridge Building', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Basic Blueprint Reading Mill Cabinet', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Basic Cabinet Making', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading and Aerial Lift', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading for Scaffold Erectors', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading-Commercial', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Blueprint Reading-Residential', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::CAD Basics for Mill Cabinetry', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Cabinet Hardware Installation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — CARP 019', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California (CTCNC) — OSHA Training', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 1203', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 312', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 608', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 707', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 710', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — CARP 713', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California Apprenticeship — FA/C', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Blueprint Reading and Mobile Tower Scaffolds', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Concrete', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial Door Hardware', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Commercial and Industrial Insulation and Aerial Lift', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Concrete - Precast and Prestressed', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Conveyors for Millwrights', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Cutting and Welding 1', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Cutting and Welding 3', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Drapery, Window Coverings, and Fine Furnishings', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Energy Conservation Codes and Standards', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Engineered Structural Systems', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Exterior Finish', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Falsework, Shoring, and Heavy Timber Framing', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Finishing and Repairing Floors', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Floor to Ceiling Wall System Construction', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Form Detailing, Construction & Erection', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Form Detailing, Construction, and Erection for Pile Drivers', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Foundations and Floors', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Hazard Awareness for Scaffold Erectors', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Infection Control Risk Assessment and Hospital Code for Acoustical Installers', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Integrated Ceilings and Special Techniques', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Interior Finish', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Interior Systems', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to CNC', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Grid Ceiling Installation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Land and Water Pile Driving', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Office Modular Systems Installation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Scaffolds and Confined Space', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Structural Blueprints and Layout Instruments', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Welding and Cutting', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Introduction to Working Drawings, Construction Math and Fire Stop Installation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Layout Procedures for Millwrights', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Layout/Leveling Construction Site Practice', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Machinery Installation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Machinery Maintenance for Mill Cabinet', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Machinery Maintenance for Millwrights', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Math for the Mill Cabinet Trade', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Mill Cabinet Safety and Tool Skills', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Millwright Math Applications', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Millwright Rigging', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Millwright Safety and Tool Skills', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Modular System Construction and Quality Control 2', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Modular System Installer Safety', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Modular Systems Construction and Quality Control 1', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Monorails', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Pile Driver Math Applications', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Pile Driver Rigging', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Precision Optical Instruments', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Precision Tools for Millwrights', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Print Reading Measurement and Layout', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Residential Blueprint Reading and Forklift Safety', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Residential Insulation and Weatherization', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Roof Framing', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Sanding, Stains, and Finish Preparation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Solid Surface Material, Fabrication, and Installation', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Specialty Ceiling Systems', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Stair Building', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Structural Framing', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Suspended Framing Ceiling Systems', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Suspended Scaffolds and Shoring Systems', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::System Scaffold', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::The Acoustical Apprentice, Safety, and the Trade', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::The Mill Cabinet Apprentice and the Trade', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::The Millwright Apprentice, the Trade, and 16 Hour Safety', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Tools of the Trade and Installation of Hardwood Floors', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Tube and Clamp Scaffold', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Turbines', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Veneers, Laminate, and Finishing', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welded Frame and Mobile Tower Scaffold', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 1: Introduction to SMAW', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 2 SMAW', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 3 FCAW', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 3: Advanced SMAW', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 4 FCAW Pipe', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Welding 6: FCAW 4G Certification', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Wharfage and Marine Structures', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Worker Safety and Tool Skills for Pile Drivers', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Cabinetmaker', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Carpenter', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Drywall Applicator', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Hardwood Floor Layer', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Insulator', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Modular Installer', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Pile Driver', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Scaffold Erector', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Apprenticeship — Shingler', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now()),
('_CREDENTIAL_REVIEW::Carpenters Training Committee for Northern California (CTCNC) — Work Experience', 'discipline_override', 'Carpentry', 'carp-disc-s110@bot', now())
on conflict (course_id, field) do nothing;
