-- ESL merging sheet, 2026-09-26: the data changes Sam's verdicts allow. Built 2026-09-26T19:40:32Z.
-- Guarded: an UPDATE touches a row only while it still holds the value and cohort read at build
-- time, so a row a curator moved since is left alone. Run once; a second run changes nothing.
begin;
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M10PD' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M90BQ' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M90EP' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M90LN' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M90YC' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M90YD' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M90YE' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M90YS' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M9171' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M91BE' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M91BF' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M91BG' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M91GF' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M91GN' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M91GT' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M9222' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M9223' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M91IL', reviewer_email = 'esl-health-s294@bot', reviewed_at = now() where course_id = 'ESOL M9240' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 3
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESLN M9002' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESLN M9013' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESLN M9015' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESLN M9018' and field = 'merge_into' and value = 'ESOL M1141' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1019' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1021' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M1141', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1043' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1062' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1085' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1086' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1302' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M1141', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1303' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M1333' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9043' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9046' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9048' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9049' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9054' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9056' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9057' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9058' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9065' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'relevel-esl-s188@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9068' and field = 'merge_into' and value = 'ESOL M1141' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9069' and field = 'merge_into' and value = 'ESOL M1141' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9070' and field = 'merge_into' and value = 'ESOL M1141' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9072' and field = 'merge_into' and value = 'ESOL M1141' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9080' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9081' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9184' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M9168', reviewer_email = 'esl-ladder-s294@bot', reviewed_at = now() where course_id = 'ESOL M9200' and field = 'merge_into' and value = 'ESOL M9256' and reviewer_email = 'package-esl-s187@bot';  -- item 6
update kb_curation set value = 'ESOL M1141', reviewer_email = 'esl-catalog-s294@bot', reviewed_at = now() where course_id = 'ESOL M1061' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 2
update kb_curation set value = 'ESOL M1141', reviewer_email = 'esl-catalog-s294@bot', reviewed_at = now() where course_id = 'ESOL M1094' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 2
update kb_curation set value = 'ESOL M1141', reviewer_email = 'esl-catalog-s294@bot', reviewed_at = now() where course_id = 'ESOL M1191' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 2
update kb_curation set value = 'ESOL M9256', reviewer_email = 'esl-catalog-s294@bot', reviewed_at = now() where course_id = 'ESOL M1240' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 2
update kb_curation set value = 'ESOL M1141', reviewer_email = 'esl-catalog-s294@bot', reviewed_at = now() where course_id = 'ESOL M1251' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 2
update kb_curation set value = 'ESOL M1141', reviewer_email = 'esl-catalog-s294@bot', reviewed_at = now() where course_id = 'ESOL M9082' and field = 'merge_into' and value = 'ESOL M9168' and reviewer_email = 'package-esl-s187@bot';  -- item 2
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10AD', 'merge_into', 'ESOL M1141', 'esl-transfer-s294@bot', now()) on conflict do nothing;  -- item 4
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9192', 'merge_into', 'ESOL M1141', 'esl-transfer-s294@bot', now()) on conflict do nothing;  -- item 4
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M91BQ', 'merge_into', 'ESOL M1141', 'esl-transfer-s294@bot', now()) on conflict do nothing;  -- item 4
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESLN M9025', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESLN M9026', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESLN M9027', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESLN M9028', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESLN M9274', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10XV', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10XW', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10XX', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10XY', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10XZ', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10YA', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10YB', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10YC', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M10YD', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1362', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1363', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1364', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1365', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1366', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1367', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1368', 'merge_into', 'ESOL M1141', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1369', 'merge_into', 'ESOL M1141', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1370', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1371', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1372', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1373', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1374', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1375', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1376', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1377', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1378', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M1379', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9265', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9266', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9268', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9269', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9270', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9271', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9273', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9275', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9276', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9277', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9278', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9279', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9280', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9281', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9282', 'merge_into', 'ESOL M1141', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9283', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9284', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9285', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9286', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9287', 'merge_into', 'ESOL M1141', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9288', 'merge_into', 'ESOL M1141', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9289', 'merge_into', 'ESOL M1141', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9290', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9291', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9292', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9293', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9294', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9295', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9296', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9297', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9298', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9299', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9300', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9301', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9302', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9303', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9304', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9305', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9306', 'merge_into', 'ESOL M9177', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9307', 'merge_into', 'ESOL M9177', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9308', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9310', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9311', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9312', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9313', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9314', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9315', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9316', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9317', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9318', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9319', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9320', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9321', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9322', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9323', 'merge_into', 'ESOL M9256', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9325', 'merge_into', 'ESOL M9023', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
insert into kb_curation (course_id, field, value, reviewer_email, reviewed_at) values ('ESOL M9326', 'merge_into', 'ESOL M9168', 'esl-newfold-s294@bot', now()) on conflict do nothing;  -- item 5
delete from kb_curation where course_id = 'FTVE M1018' and field = 'merge_into' and value = 'ESOL M1152' and reviewer_email = 'automerge-v1@bot';  -- item 9
commit;
select reviewer_email, count(*) from kb_curation where reviewer_email like 'esl-%-s294@bot' group by 1 order by 1;
